### ISSUE TITLE
Terraform select the less used datastore

### ISSUE THREAD

**Issue by vkmellon** [terraform-providers/terraform-provider-vsphere#1003]
Hi!

Is there possibility to select less used datasore with Terraform?

Looks like if datastore_id was not provided then it is selecting the same datastore as in template.

**Comment by bill-rich** [comment]
Hey @vkmellon! I definitely see understand how this could be a useful feature, however there are a few problems given the immutable infrastructure approach of Terraform. If we have an option to use the less utilized datastore, that can change over time, and it can be unclear from the configuration where the VM currently resides. 

Instead, I'd recommend using datastore clusters with SDRS. Then you can allow vSphere to place (and migrate) the VM based on the rules you have set.

**Comment by sofixa** [comment]
The problem with that is that SDRS only works on Enterprise Plus license level, and there are plenty of people without it. 

It would be pretty cool if there was a data source that provided that information ( least used datastore" ), which can then be added to lifecycle ignore_change on the VM level.
