### ISSUE TITLE
Default gateway not route correctly

### ISSUE THREAD

**Issue by mkennedy85** [terraform-providers/terraform-provider-vsphere#1030]
I am trying to configure a guest OS using the customize block below, but the gateway is not configured in a way that I would expect and is not able to reach outside it's subnet.

```hcl

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "test-terraform"
        domain    = "example.com"
      }

      dns_server_list = ["12.124.10.2", "12.124.10.4"]
      dns_suffix_list = ["example.com"]

      network_interface {
        ipv4_address = "12.179.177.151"
        ipv4_netmask = 22
      }

      ipv4_gateway = "12.179.176.1"
    }
  }
}
```

Once completed it just says network is unreachable and is resolved if I place the gateway in the `/etc/sysconfig/network` file `GATEWAY=12.179.176.1`. It seems to create a `route-interface` file that contains `ADDRESS0=12.179.176.0` and `GATEWAY0=12.179.176.1` and no `GATEWAY` entry in the `ifcfg-interface` file.

+ Terraform v0.12.24
+ provider.vsphere v1.17.1
+ CentOS 7.7
+ vSphere 6.7

Am I missing something?

**Comment by bill-rich** [comment]
Hi @mkennedy85!
Unfortunately there is not very much we can do on the Terraform provider side for this issue. It is more of an issue with how vSphere interacts with the guest OS. I would recommend opening a ticket with VMware to see about getting this addressed. 

The guest OS customization compatibility matrix shows that CentOS 7 is supported, but it is possible there are caveats to what will work.
