### ISSUE TITLE
Deploying vm from OVF 

### ISSUE THREAD

**Issue by sumitAgrawal007** [terraform-providers/terraform-provider-vsphere#1043]
i was interested in writing a workflow to clone a VM from a OVF Template, either uploading locally or from a URL. However in the vsphere terraform documentation I found this mentioned

NOTE: Neither the vsphere_virtual_machine resource nor the vSphere provider supports importing of OVA or OVF files as this is a workflow that is fundamentally not the domain of Terraform. The supported path for deployment in Terraform is to first import the virtual machine into a template that has not been powered on, and then clone from that template. This can be accomplished with Packer, govc's import.ovf and import.ova subcommands, or ovftool.

Deploying a VM from OVF is a useful feature and has been requested by our VMware customers and product management. It is also very much in domain of terraform to create a resource from local file in my opinion. My query here is If I submit a pull request for this feature, will it be accepted?

I can see there is already a feature request for this
https://github.com/terraform-providers/terraform-provider-vsphere/issues/961

**Comment by jcpowermac** [comment]
@sumitAgrawal007 we created a custom provider and resource to accomplish this.  It is very limited since we don't need something complex for our use-case but maybe it would help.

https://github.com/openshift/installer/tree/master/pkg/terraform/exec/plugins/vsphereprivate
