### ISSUE TITLE
Make disk online, format and change the names in OS after VM provisioned

### ISSUE THREAD

**Issue by msharma111** [terraform-providers/terraform-provider-vsphere#1047]
I am using Terraform to create new Vsphere VM and I could not find anything where I can make my disks online and change the format or label in windows after VM is created. Do we have something for this in terraform ?

**Comment by bill-rich** [comment]
Hi @msharma111! Unfortunately all disk related changed through Terraform currently require a reboot to take effect, and format changes are not supported at all. Format changes are a feature that is currently on our backlog, but has not been focused on yet.
