### ISSUE TITLE
CI/CD tests failing with undefined: os.UserHomeDir, needs go 1.12 version in test machine

### ISSUE THREAD

**Issue by sumitAgrawal007** [terraform-providers/terraform-provider-vsphere#1053]
The CI/CD test for pull request https://github.com/terraform-providers/terraform-provider-vsphere/pull/1052 are failing with 
vendor/github.com/vmware/govmomi/session/cache/session.go:70:15: undefined: os.UserHomeDir

This code that was recently added in commit https://github.com/terraform-providers/terraform-provider-vsphere/commit/101150c43b6e0e00c9099cfae7c6a04e16bdd185 
has use of os.UserHomeDir which needs go 1.12+ version 

The current test machine has lower version so CI/CD is failing.

**Comment by bill-rich** [comment]
Fixed in #1054. Thanks for catching this!
