### ISSUE TITLE
Crash when cloning from template

### ISSUE THREAD

**Issue by fsedano** [terraform-providers/terraform-provider-vsphere#1059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### vSphere Provider Version

v1.17.3_x4
### Affected Resource(s)

- 'vsphere_network'

### Terraform Configuration Files

```hcl

variable "vcenter_host" {}
variable "vcenter_user" {}
variable "vcenter_password" {}
variable "vcenter_dc" {}
variable "ds_name" {}
variable "routable_pg" {}
variable "trunk_pg" {}
variable "template" {}
variable "datastore_name" {}
variable "resource_pool" {}

provider "vsphere" {

  # If you have a self-signed cert
  allow_unverified_ssl = true
  user = var.vcenter_user
  password = var.vcenter_password
  vsphere_server = var.vcenter_host

}

data "vsphere_datacenter" "dc" {
  name = var.vcenter_dc
}

data "vsphere_datastore" "datastore" {
  name          = var.datastore_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = var.resource_pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.routable_pg
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "trunk" {
  name          = var.trunk_pg
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.template
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_distributed_virtual_switch" "dvs" {
  name          = var.ds_name
  datacenter_id = data.vsphere_datacenter.dc.id
}



resource "vsphere_virtual_machine" "vwlc-terraform" {
  name             = "vwlc-terraform"
  count = 1
  nested_hv_enabled = true
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder = "Lab infra testing VMs/Autodeployed vWLCs"
  num_cpus = 4
  memory   = 8192
  guest_id = "ubuntu64Guest"


clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    linked_clone = true
    customize {
      linux_options {
        host_name = "vwlc-terraform"
        domain    = "cisco.com"
      }

      network_interface {
      }

    }
}

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label = "disk0"
    size  = 160
  }
}

```

### Debug Output

https://gist.github.com/fsedano/c8048cf4f8a19ac4d4318353a12cdeb9

### Panic Output

https://gist.github.com/fsedano/08b4f0db638124bb24cc182f7bdb24c1

### Expected Behavior

Create the VM

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Not sure if it makes a difference, but I'm cloning a VM not a template, due to a VCenter issue.

### References

* #0000

**Comment by bill-rich** [comment]
A fix is in for this in #1067. It should be in the new release next week.
