### ISSUE TITLE
Can't import arbitrary VMs 

### ISSUE THREAD

**Issue by ianwinsemius** [terraform-providers/terraform-provider-vsphere#1068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### vSphere Provider Version

provider.vsphere v1.18.0

### Affected Resource(s)

vsphere_virtual_machine resources and modules

###Description 
I have a set of two hosts in a compute_cluster, each of these hosts has several VMs that I was able to import, and one or two that I was unable to import. 

I've tried importing based on the name in the UI in the datacenter: (where dc1 is the datcenter, machine-name is the display name of the vm, and vm is the name of the module)

terraform import module.machine-name.vsphere_virtual_machine.vm /dc1/vm/machine-name

I've tried importing based on the name in the UI in the datacenter: (where dc1 is the datcenter, machine-name is the display name of the vm)

terraform import vsphere_virtual_machine.machine-name /dc1/vm/machine-name

but I get the following error. 
`Error: error fetching virtual machine: vm '/dc1/vm/machine-name' not found
`
I've successfully imported vms on both of these hosts with the same esxi compatibility version, and vmware tools version, and I've tried removing my terraform config and reinitializing.

I've also tried importing based on the uid of the VM, and the vm id number, neither of which work for 'visible' or 'invisible' vms. (not surprised by this but it seemed like it was worth a shotI

### Expected Behavior

```
module.machine-name.vsphere_virtual_machine.vm: Importing from ID "/dc1/vm/machine-name"...
module.machine-name.vsphere_virtual_machine.vm: Import prepared!
  Prepared vsphere_virtual_machine for import
module.machine-name.vsphere_virtual_machine.vm: Refreshing state... [id=564dde42-bd9b-bcdb-9845-d28264e7a89c]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### Actual Behavior

For both resources and modules, I get the following:
Error: error fetching virtual machine: vm '/dc1/vm/machine-name' not found

### Steps to Reproduce

Attempt importing one of the VMs that seem to be invisible to terraform

**Comment by ianwinsemius** [comment]
Ah HA!

I realized that all the VMs I was importing were in folders. The TF documentation doesn't mention folders as part of the import. 

/dc/vm/machine-name != /dc/vm/folder/machine-name

This is not a bug, this is user error. It would very helpful to see that noted in the TF docs though.

**Comment by aareet** [comment]
Thanks for reporting the outcome back here @ianwinsemius, I'll add a note to improve the docs.
