### ISSUE TITLE
Cannot deploy OVF - VMDK tried to get uploaded the host, not to VCenter.

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-vsphere#1072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.12.24

### vSphere Provider Version
1.18

### Affected Resource(s)
vsphere_virtual_machine using ovf_deploy

### Terraform Configuration Files
```
resource "vsphere_virtual_machine" "vmFromLocalOvf" {
  name = "vm1"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id = data.vsphere_datastore.datastore.id
  host_system_id = data.vsphere_host.host.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout = 0
  datacenter_id = data.vsphere_datacenter.dc.id
  force_power_off = false
  ovf_deploy {
    local_ovf_path = "C:\\Users\\REDACTED\\Desktop\\vmware\\cucm_11.5_vmv8_v1.1.ovf"
  }
  vapp {
    properties = {
      "DeploymentOption.value" = "CUCM_2500"
    }
  }
}
```

### Debug Output
Error: error while importing OVF template error while uploading the file C:\Users\REDACTED\Desktop\vmware\cucm_11.5_vmv8_v1.1-disk2.vmdk Post "https://10.10.10.10/nfc/5243d2a5-89e1-d9db-c9b1-3c31bc331498/disk-0.vmdk": Service Unavailable
### Expected Behavior
vmdk uploaded and VM created

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I can deploy this OVF in VMWare www interface to VCenter.  Actually, with VCenter Im deploying an OVA - for Terraform, I have extracted the OVF and VMDK and am deploying it all per instructions at [https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#deploying-vm-from-an-ovf-template](url) )
Anyhow - So that 10.10.10.10 in the error message, that is the IP of the VMware host, not my vcenter.  The IP of the host comes from   `host_system_id = data.vsphere_host.host.id` as shown above.  So not sure why terraform is trying to upload my vmdk there.  I dont have any connectivity to that 10.x IP from my terraform PC.  I can do this in vcenters web interface, so I should be able to do it here as well.

### References
N/A

* #0000

**Comment by jcpowermac** [comment]
@tezzigator when deploying an OVA or OVF the operation always uses a ESXi not vCenter.
See: https://github.com/terraform-providers/terraform-provider-vsphere/blob/03bc355615f0860c03095bc1698bb067df51715e/vsphere/internal/helper/ovfdeploy/ovf_helper.go#L47

and:
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.ResourcePool.html#importVApp

You will need conntectivity to the host from where ever you are running terraform.  I had similar situation in VMwareOnAWS because the hosts are separated from virtual machine network.

**Comment by tezzigator** [comment]
I see yes thats what I suspected.  But what doesnt make sense is that I can deploy the OVA, with the vcenter web interface, from the same machine Im trying to get ansible to work it from.

**Comment by jcpowermac** [comment]
I think there are private APIs for what you are describing that we don't have access to use.  At least this was the case in the past not sure now.

**Comment by tezzigator** [comment]
I see.  Well I can get [this ](https://github.com/vmware/pyvmomi-community-samples/blob/master/samples/deploy_ova.py)to work directly with Python, and also the [Import-VApp](https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.powercli.cmdletref.doc%2FImport-VApp.html)  powershell works.

Hopefully they can get this added here at some point.

**Comment by bill-rich** [comment]
That is odd that pyvmomi is working, but govmomi is not. Last I knew, access to the ESXi host network was a requirement, but I have not followed up on that in a while. @sumitAgrawal007, do you know what the API supports?

**Comment by tezzigator** [comment]
> 
> 
> That is odd that pyvmomi is working, but govmomi is not. Last I knew, access to the ESXi host network was a requirement, but I have not followed up on that in a while. @sumitAgrawal007, do you know what the API supports?

I believe you are right after all - I have access to separate vcenters.  I believe the one I was able to get the ova to deploy for pyvmomi with was the vcenter that I had full routing for.
