### ISSUE TITLE
VM resource not getting correct network interface

### ISSUE THREAD

**Issue by tezzigator** [terraform-providers/terraform-provider-vsphere#1079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Teraform Version
0.12.24

### vSphere Provider Version
1.18.1

### Affected Resource(s)
vsphere_virtual_machine

### Terraform Configuration Files
```
terraform { # variables not allowed here
  required_version = "= 0.12.24"
}
provider "vsphere" {
  version              = "=1.18.1"
  vsphere_server       = "REDACTED"
  user                 = "REDACTED"     #var.vsphere_user
  password             = "REDACTED" #var.vsphere_pass
  allow_unverified_ssl = true                # need to be true if using self signed cert
}

data "vsphere_datacenter" "dc" {
  name = "DC6"
}
data "vsphere_datastore" "datastore" {
  name          = "EAR"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_compute_cluster" "compute_cluster" {
  name          = "DC6-C4"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_host" "host" {
  name          = "esxi-dc6-c4-b1.hcs.local"
  datacenter_id = data.vsphere_datacenter.dc.id
}
data "vsphere_distributed_virtual_switch" "dvs" {
  name          = "DC6-vDS"
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "net" {
  name          = "TST1-302"
  datacenter_id = data.vsphere_datacenter.dc.id
  distributed_virtual_switch_uuid = data.vsphere_distributed_virtual_switch.dvs.id
}

data "vsphere_folder" "parent" {
  path = "/${data.vsphere_datacenter.dc.name}/vm/CLIENTS"
}

resource "vsphere_folder" "folder" {
  path          = "${data.vsphere_folder.parent.path}/TST1-302"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vmFromLocalOvf" {
  name                       = "publisher"
  folder                     = vsphere_folder.folder.path
  host_system_id             = data.vsphere_host.host.id
  resource_pool_id           = data.vsphere_compute_cluster.compute_cluster.resource_pool_id
  datastore_id               = data.vsphere_datastore.datastore.id
  wait_for_guest_net_timeout = 0
  wait_for_guest_ip_timeout  = 0
  datacenter_id              = data.vsphere_datacenter.dc.id
  force_power_off            = false
  network_interface {
    network_id = data.vsphere_network.net.id
    adapter_type = "vmxnet3"
    ovf_mapping = "Network Adapter 1"
  }
  ovf_deploy {
    local_ovf_path = "cucm_11.5_vmv8_v1.1.ovf"
  }
  vapp {
    properties = {
      "DeploymentOption.value" = "CUCM_2500"
    }
  }
}
```

### Expected Behavior
In this case since my OVF indicated a vmxnet3 type of adapter on eth0, and that in the OVF is titled "Network Adapter 1"  (not the usual "VM Network" or "Network 1" or "Adapter 1" that we normally see in OVF ) Then I expect the VMWare portgroup called TST1-302 that is located on VDS called "HK-DC6-vDS" to then be attached to the new VM that was created

### Actual Behavior
After the VM is created, in VMware you can see that the network that was actually connected was some other network (not located on any VDS)

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
I am deploying via ovf_deploy, so this may have something to do with it.
Also, I notice the EXACT SAME BEHAVIOR when using Ansible to deploy an OVF, where the same wrong network gets connected.

Here is the network adapter config from my OVF:
```
  <NetworkSection>
    <Info>The list of logical networks</Info>
    <Network ovf:name="eth0">
      <Description>eth0 handles all management and call processing traffic</Description>
    </Network>
  </NetworkSection>
...
      <Item>
        <rasd:AddressOnParent>7</rasd:AddressOnParent>
        <rasd:AutomaticAllocation>true</rasd:AutomaticAllocation>
        <rasd:Connection>eth0</rasd:Connection>
        <rasd:Description>vmxnet3 ethernet adapter on &quot;eth0&quot;</rasd:Description>
        <rasd:ElementName>Network adapter 1</rasd:ElementName>
        <rasd:InstanceID>9</rasd:InstanceID>
        <rasd:ResourceSubType>vmxnet3</rasd:ResourceSubType>
        <rasd:ResourceType>10</rasd:ResourceType>
      </Item>
```

**Comment by sumitAgrawal007** [comment]
network_interface block is not supported while deploying from ovf.
Instead pass the network mapping in the deploy_ovf block.
https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#creating-vm-from-deploying-a-ovf-template
