### ISSUE TITLE
Create a VM with same UUID after destroy?

### ISSUE THREAD

**Issue by remoe** [terraform-providers/terraform-provider-vsphere#1097]
Our backup system (Veeam) needs an UUID from the VM. Is it possible to create a new VM with ```vsphere_virtual_machine``` after ```terraform destroy``` with the same UUID without write a static one? The backup-system need to register the VM every time after recreate of a VM. I want to avoid this.

**Comment by Redeux** [comment]
Hi Remo.  Short of statically defining the UUID, I'm not aware of a way to accomplish what you're asking for, without suggesting some practices that I couldn't endorse, using the Terraform provider.

**Comment by remoe** [comment]
Thanks, I found a solution for this issue. It's possible to use vSphere tags for this kind of tasks.

https://helpcenter.veeam.com/docs/backup/vsphere/vm_tags.html
