### ISSUE TITLE
Feature Request: Manage Custom Attributes for VMS (annotations)

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#120]
Recently added was an annotation capability https://github.com/terraform-providers/terraform-provider-vsphere/pull/111.  

It would be great if we can create Custom attributes.  Custom attributes apply to all machines in the inventory.  

I would think the proper behavior here is:
1. if the attribute doesn't exist create it.  (On VMs this seems to be global)
2. if the attribute exists (name), and it's value is different update it
3. if the attribute exists (name), and it's value is the same noop it.

Welcome thoughts.

**Comment by vancluever** [comment]
Hey @rismoney, this is a great suggestion! Will add it to the TODO.

Just did a bit of research on this one and I think that we could just implement most of the functionality that is in the [fields](https://github.com/vmware/govmomi/tree/master/govc/fields) module in the govc reference implementation. 

Your idea on how the CRUD would work for this pretty much matches what the normal expected operation of TF, so we are on the same page here.

**Comment by rismoney** [comment]
I think this can be safely closed, as there is solid attribute support in the provider at this time.

**Comment by vancluever** [comment]
Thanks @rismoney! This is definitely dated now that we have #229. Glad it's working for you now!
