### ISSUE TITLE
vpshere plugin returns the last defined ipadres from the IpStack instead of the first

### ISSUE THREAD

**Issue by mjrider** [terraform-providers/terraform-provider-vsphere#127]
### Terraform Version
Terraform v0.9.11
terraform-provider-vsphere - master

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```hcl
resource "vsphere_virtual_machine" "acceptance-test" {
        name          = "test"
        vcpu          = 1
        memory        = 1024
        datacenter    = "DC0"
        cluster       = "CL0"
        resource_pool = "CL0/RP0"
        network_interface {
                label              = "VM network"
                ipv4_address       = "10.5.8.8"
                ipv4_prefix_length = "24"
                ipv4_gateway       = "10.5.8.1"
		ipv6_address       = "2001:XXXX::8"
		ipv6_prefix_length = "56"
		ipv6_gateway       = "2001:XXXX::1"

        }
        disk { ... }
}
```

### Expected Behavior
no changes in the VM when i run plan/apply for an existing VM with no changes

### Actual Behavior
terraform plan

case where ipv6 returns link-local
~ vsphere_virtual_machine.test
    network_interface.0.ipv6_address:       "fe80::250:56ff:febf:7f29" => "2001:XXXX::8"
    network_interface.0.ipv6_prefix_length: "64" => "56"

case where the last ip is the floating ip between 2 keepalived instances
~ vsphere_virtual_machine.test
    network_interface.0.ipv4_address:       "10.5.8.100" => "10.5.8.8"
    network_interface.0.ipv4_prefix_length: "32" => "24"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by vancluever** [comment]
Hey @mjrider - thanks for the report and the PR! Will make sure it's reviewed this week. :+1:
