### ISSUE TITLE
Can't change vm ip

### ISSUE THREAD

**Issue by neoblackcap** [terraform-providers/terraform-provider-vsphere#130]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
- vsphere_virtual_machine

### Terraform Configuration Files
```json
  "resource": {
    "vsphere_virtual_machine": {
      "newvm": {
        "name": "newvm",
        "vcpu": 4,
        "memory": 4096,
        "domain": "192.168.163.60",
        "datacenter": "Datacenter",
        "cluster": "DCOS",
        "network_interface": {
          "label": "lab",
          "ipv4_address": "10.1.1.124",
          "ipv4_prefix_length": "24",
          "ipv4_gateway": "10.1.1.254"
        },
        "disk": {
          "template": "lab04",
          "type": "thin"
        }
      }
    }
  }
```

### Debug Output
https://gist.github.com/neoblackcap/3b5086e5d491197e4732a59da8ba98f7

### Panic Output
None

### Expected Behavior
change ip on fly

### Actual Behavior
vm ip doesn't be changed, but shutdown vm then rerun `terraform apply`, ip changed!

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Important Factoids
None

### References
None

**Comment by vancluever** [comment]
Hey @neoblackcap - sorry you are having issues with this!

The functionality you are looking for does not exist in Terraform currently. Unfortunately I don't think there is an easy route for this as there is no way to re-customize an already deployed virtual machine. See [this thread](https://communities.vmware.com/thread/468154). I am trying to see if this is up to date, but in the meantime, do you have any information? (Re-customization seems to be mainly a vCloud Director feature).

My best recommendation to you would be if you require this functionality right now or in the foreseeable future, move your IP assignment workflow to DHCP, and use manual MAC address assignment for your network interfaces.

Let me know if you have any info on this!

**Comment by neoblackcap** [comment]
@vancluever thank you. I use the way post in your link now but I just wonder terraform can be replace vm-tools.
It look like there is no better way to archive this.

**Comment by playniuniu** [comment]
Do you install vmware tools?

I installed vmware tools in vcenter template, and then can change ip on fly

**Comment by neoblackcap** [comment]
@playniuniu yes, I have installed open-vm-tools in my guest, but it doesn't work

**Comment by playniuniu** [comment]
@neoblackcap I use the official vmtools on vcenter 5.5 update 3, and it worked for me, may be you can have a try

**Comment by neoblackcap** [comment]
@playniuniu I have read the vmware's document and they recommend open-vmtools now, and my vcenter version is 6+, but thank you.

**Comment by vancluever** [comment]
Hey all,

I still have not been able to find any new information regarding being able to re-customize a virtual machine after creation, including the network info, within pure vSphere itself, so I am going to close this issue now.

This isn't a solid "wontfix" though - if anything becomes evident through new support in vSphere core itself, or if anyone has any existing documentation of how this can be done through other tools (especially OSS ones) - please open a new issue with the docs!

Thanks!
