### ISSUE TITLE
Support basic vMotion tasks in vsphere_virtual_machine

### ISSUE THREAD

**Issue by vancluever** [terraform-providers/terraform-provider-vsphere#133]
Just making a formal TODO for this:

Right now, it doesn't look like a basic `datastore` change on a simple `template` disk workflow gets picked up at all. I tried adding a small patch to fix this, but `terraform apply` broke.

I would assume that this is because we don't allow a host to be picked in `vsphere_virtual_machine` - vMotion is probably not a scenario that we have thought of supporting, let alone Storage vMotion.

I think the base feature set we need to support is the three basic vMotion scenarios:

 * Host/Cluster Move
 * Storage Move
 * Both

From there, if there are more complex scenarios we need to support, we can move forward from there.

Related: #17 - old support roadmap, and #131 which is a sort-of related issue with datastore not being handled completely in state.

**Comment by bill-rich** [comment]
This has been implemented.
