### ISSUE TITLE
ipv6 not correctly detected under specific circumstance

### ISSUE THREAD

**Issue by maxadamo** [terraform-providers/terraform-provider-vsphere#143]
### Terraform Version
Terraform v0.10.2

### VM Operating System
CentOS 7

### Affected Resource(s)
- ipv6_address
- ipv6_gateway

### Terraform Configuration Files (relevant part)
```hcl
    ipv6_address       = "${var.blahblah["ipv6_address"]}"
    ipv6_gateway       = "${var.blahblah["ipv6_gateway"]}"
```

### Debug Output
```
~ vsphere_virtual_machine.puppet03_blahblah_net
      network_interface.0.ipv6_address:       "fe80::250:56ff:fe92:a280" => "2001:798:3::4"
      network_interface.0.ipv6_prefix_length: "64" => "48"
Plan: 0 to add, 1 to change, 0 to destroy.
```
I haven't seen to code for this provider (which I'll do ASAP), but I believe that I guessed the nature of his issue. 

When a VM is deployed, for each network interface we get two IPv6 addresses: 
- ipv6 link-local (which derives from the mac address, and it has nothing to do with terraform)
- ipv6 global (which is set by terraform)

Most of the times, these addresses show up from the command `ifconfig` in the following order: 
- link-local first
- global second

but sometime, for a reason that I don't know, the order is inverted, and it's kept in that order even after a reboot. 
In that case, if I run `terraform plan` (or `terraform apply`), terraform sees the link-local as the main IPv6, and tries to change it. 
The attempt has no effect, since the IP is correctly set, and it will keep attempting forever. 

*My assumption is that you are matching the last IPv6 in the list, and not the IPv6 marked as global.*

### Panic Output
Nothing

### Expected Behavior
`terraform plan` or `terraform apply` should not apply any change

### Actual Behavior
`terraform plan` and `terraform apply` keeps applying the change. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` (or `terraform plan`)

### Important Factoids
ESX 6.0

### References
Nothing

**Comment by maxadamo** [comment]
perhaps this should be the correct order: 
`
govc vm.ip -a /PAR-PRD-DC01/vm/puppetserver/puppet02.geant.net 
83.97.92.3,fe80::250:56ff:fe92:2c2f,2001:798:3::3
`

**Comment by mjrider** [comment]
@maxadamo are you able to test with a self compiled terraform vsphere provider?
this should be fixed by #128 and will be part of the next release

**Comment by maxadamo** [comment]
thanks @mjrider I can give it a shot (but since I am doing testing now I can also wait)

**Comment by vancluever** [comment]
Hey @maxadamo - sorry you are having trouble with this! As mentioned @mjrider contributed #128 which will be available in the next release which should be soon! Stay tuned :+1:

I will keep this issue open though until we know it's fixed :)

**Comment by mjrider** [comment]
@maxadamo this fix is now released a while ago https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/CHANGELOG.md#021-august-31-2017
Could you tell is if this issue is indeed fixed

**Comment by maxadamo** [comment]
@mjrider yes, I confirm that it's fixed!
