### ISSUE TITLE
Folder not found error

### ISSUE THREAD

**Issue by m4r10k** [terraform-providers/terraform-provider-vsphere#156]
I think I have found a bug during my tests with the vsphere-provider, which I would like to explain here. We have a large ESXi virtual center that is holding up ESXi installations from multiple countries in multiple datacenters.

### Terraform Version
Terraform v0.10.4

### Affected Resource(s)

Here is an example configuration which won't work. If I remove the ```folder``` property from the ```vsphere_virtual_machine``` resource, Terraform works as Expected

#### Config

```
resource "vsphere_folder" "docker" {
  path = "Terraform/Gitlab"
  datacenter = "Dca"
}
```

```
resource "vsphere_virtual_machine" "cows" {
  name          = "docker-${random_id.server.hex}"
  folder        = "${vsphere_folder.docker.path}"
  vcpu          = 2
  memory        = 4096
  domain        = "aaa"
  datacenter    = "Dca"
  cluster       = "ccc"
  resource_pool = "_TEST"
...
```

#### Error 1

OK, that is something strange, because the folder is created correctly, see the output from ```./govc_linux_amd64```. It is also shown correctly in the virtual center.

```
./terraform apply
random_id.server: Refreshing state... (ID: CJgXpI7siAE)
vsphere_folder.docker: Creating...
  datacenter:    "" => "Dca"
  existing_path: "" => "<computed>"
  path:          "" => "Terraform/Gitlab"
vsphere_folder.docker: Creation complete after 0s
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.cows: Resource 'vsphere_folder.docker' does not have attribute 'path' for variable 'vsphere_folder.docker.path'
```

```
./govc_linux_amd64 find | grep Gitlab
/AA/Dca/vm/Terraform/Gitlab
```

#### Error 2

Since I can find the folder, I just use the path as plain input to ```folder```.
```
resource "vsphere_virtual_machine" "cows" {
  name          = "docker-${random_id.server.hex}"
  folder        = "/AA/Dca/vm/Terraform/Gitlab"
  vcpu          = 2
  memory        = 4096
  domain        = "aaa"
  datacenter    = "Dca"
  cluster       = "ccc"
  resource_pool = "_TEST"
...
```

Then I get the error that the folder cannot be found.

```
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.cows: 1 error(s) occurred:

* vsphere_virtual_machine.cows: Cannot find folder /AA/Dca/vm/Terraform/Gitlab
```

### Conclusion

The full path is for example working without a problem for the ```disk``` datastore parameter. The given path does not work in any case. I've tried to reduce the path by ```AA``` and ```Dca``` and so on, but I get always the folder not found error.

**Comment by kleinsasserm** [comment]
I will try to dig deeper in this because I think the problems is around at this [line](https://github.com/terraform-providers/terraform-provider-vsphere/blob/b865d00f4df1ce4c084963fbf71b24fe622bbec3/vsphere/resource_vsphere_virtual_machine.go#L1832), as there is ```FindByInventoryPath``` called. Maybe I can find the time to debug this.

**Comment by vancluever** [comment]
Hey @kleinsasserm - that would be huge if you can find it - thanks!

Also, sorry, this is not a breaking change, I just have misapplied the wrong label (bug and breaking-change are beside each other :stuck_out_tongue:)

If you do find it and want to take a stab at putting in a PR, note that we recently added a bunch of folder helpers [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/folder_helper.go) that might help. What I would _prefer_ is that relative paths function correctly, as this will be the behaviour after the resource is updated in a month's time or so. The root VM path should be calculated relative to the datacenter provided by `datacenter`.

**Comment by jospradlin** [comment]
"Foldering" was definitely broken in the v 0.4 update; looks like they added support for other types of folders (other than the 'vm' folders).   

In the past, I could provide a 'full folder path', and assume it'd get created.   Now, if folders previously exist in the path; the Terraform folder resource fails (since 'parent folders already exist').   Also, I've seen issues where the 'parent-to-sub folder' creation (as documented) fails, since a parent folder isn't created prior to the children being created.

If the 'Folder creation' is going to change; at least made a 'Data Source' to validate a folder before the folder is created.  OR, make the 'Folder creation' function take a 'fully qualified path' and auto-create ONLY the folders that the function determines as being necessary.

**Comment by vancluever** [comment]
@jospradlin - sorry you are having issues with the new folder resource. Can you post your config and I could help you maybe with getting it into a correct state?

We actually have a test for parent folder creation [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_folder_test.go#L557) so that story has been tested.

A `vsphere_folder` data source would be a good idea! However, nothing in the vSphere provider take a folder by ID, and I'm not too sure things will end up going that way, which is where a data source would really shine. Nothing has changed in how folders are referenced in the `vsphere_virutal_machine` resource as well and there is also a test [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L1254) demonstrating the creation of a VM in a folder using the path referenced in the new `vsphere_folder` resource.

Thanks!

**Comment by pryorda** [comment]
Having this issue as well.  Going from v0.3 to 0.4 breaks stuffs


Module
```
# Providers
# VSphere
provider "vsphere" {
  user                 = "${var.vsphere_username}"
  password             = "${var.vsphere_password}"
  vsphere_server       = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.vsphere_allow_unverified_ssl}"
}

resource "vsphere_folder" "instance" {
  path       = "${var.vsphere_folder_path}"
  datacenter = "${var.vsphere_datacenter}"
  count   = "${var.vsphere_network_ipv4_addresses != "" ? 1 : 0}"
}

# DNS for instances
data "aws_route53_zone" "private-domain" {
  name         = "${lower(var.provider)}.private.com."
  private_zone = true
}

resource "aws_route53_record" "instance-dns" {
  zone_id = "${data.aws_route53_zone.private-domain.id}"
  type    = "A"
  ttl     = "900"
  records = ["${element(split(",", var.vsphere_network_ipv4_addresses), count.index)}"]
  name    = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}"
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
}

# Instance Resource
resource "vsphere_virtual_machine" "instance" {
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
  name  = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}"

  detach_unknown_disks_on_delete = true

  folder     = "${vsphere_folder.instance.path}"
  datacenter = "${var.vsphere_datacenter}"
  cluster    = "${var.vsphere_cluster}"
  domain     = "${lower(var.region)}.${lower(var.provider)}.private.com"

  dns_servers  = ["${split(",",var.vsphere_network_domain_resolvers)}"]
  dns_suffixes = ["${lower(var.region)}.${lower(var.provider)}.private.com","${split(",",var.vsphere_network_domain_search)}"]
  vcpu         = "${var.vsphere_vcpu}"
  memory       = "${var.vsphere_memory}"
  time_zone    = "${var.vsphere_cluster_timezone}"

  network_interface {
    label              = "${var.vsphere_network_label}"
    ipv4_address       = "${element(split(",", var.vsphere_network_ipv4_addresses), count.index)}"
    ipv4_prefix_length = "${var.vsphere_network_ipv4_prefix_length}"
    ipv4_gateway       = "${var.vsphere_network_ipv4_gateway}"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    template  = "${var.vsphere_template}"
    type      = "thin"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    vmdk      = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}.data_disk.vmdk"
    keep_on_remove = true
  }

  lifecycle {
    ignore_changes = ["network_interface", "dns_suffixes"]
  }
}

resource "vsphere_virtual_disk" "data_disk" {
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
  size          = "${var.data_disk_size}"
  vmdk_path     = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}.data_disk.vmdk"
  datacenter    = "${var.vsphere_datacenter}"
  datastore     = "${var.vsphere_datastore}"
  type          = "thin"
  adapter_type  = "lsiLogic"
  lifecycle {
    prevent_destroy = true
  }
}

output "instance_ids" {
  value = ["${vsphere_virtual_machine.instance.*.id}"]
}

output "instances_dns" {
  value = ["${vsphere_virtual_machine.instance.*.name}"]
}

output "instance_private_ips" {
  value = ["${vsphere_virtual_machine.instance.*.network_interface.0.ipv4_address}"]
}
```

Example .tfvars
```
# Application Network
vsphere_network_label = "dvPortGroup_qa"
vsphere_network_ipv4_gateway = "172.16.123.1"
vsphere_network_ipv4_addresses = "172.16.123.65"

# VM Location
vsphere_cluster = "VMSAC02 Cluster"
vsphere_folder_path = "QA/Beta"
vsphere_datastore = "Nimble Datastores/beta"

# VM Specs
vsphere_vcpu = "2"
vsphere_memory = "2048"
data_disk_size = "50"

# Labels
product= "infrastructure"
environment = "beta"
application = "consul"
component = "server"
region = "sac"
provider = "op"

# Chef Details
run_list = [ "role[consul-standalone" ]

# Monitors
consul_frontend = "http://beta-consul-server1.sac.op.private.com:8500/ui/"
```

v0.4 attempt
```
# Providers
# VSphere
provider "vsphere" {
  user                 = "${var.vsphere_username}"
  password             = "${var.vsphere_password}"
  vsphere_server       = "${var.vsphere_server}"
  allow_unverified_ssl = "${var.vsphere_allow_unverified_ssl}"
}

data "vsphere_datacenter" "datacenter" {
  name = "${var.vsphere_datacenter}"
}
resource "vsphere_folder" "instance" {
  type           = "vm"
  path           = "${var.vsphere_folder_path}"
  datacenter_id  = "${data.vsphere_datacenter.datacenter.id}"
  count          = "${var.vsphere_network_ipv4_addresses != "" ? 1 : 0}"
}

# DNS for instances
data "aws_route53_zone" "private-domain" {
  name         = "${lower(var.provider)}.private.com."
  private_zone = true
}

resource "aws_route53_record" "instance-dns" {
  zone_id = "${data.aws_route53_zone.private-domain.id}"
  type    = "A"
  ttl     = "900"
  records = ["${element(split(",", var.vsphere_network_ipv4_addresses), count.index)}"]
  name    = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}"
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
}

# Instance Resource
resource "vsphere_virtual_machine" "instance" {
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
  name  = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}"

  detach_unknown_disks_on_delete = true

  folder     = "${vsphere_folder.instance.path}"
  datacenter = "${var.vsphere_datacenter}"
  cluster    = "${var.vsphere_cluster}"
  domain     = "${lower(var.region)}.${lower(var.provider)}.private.com"

  dns_servers  = ["${split(",",var.vsphere_network_domain_resolvers)}"]
  dns_suffixes = ["${lower(var.region)}.${lower(var.provider)}.private.com","${split(",",var.vsphere_network_domain_search)}"]
  vcpu         = "${var.vsphere_vcpu}"
  memory       = "${var.vsphere_memory}"
  time_zone    = "${var.vsphere_cluster_timezone}"

  network_interface {
    label              = "${var.vsphere_network_label}"
    ipv4_address       = "${element(split(",", var.vsphere_network_ipv4_addresses), count.index)}"
    ipv4_prefix_length = "${var.vsphere_network_ipv4_prefix_length}"
    ipv4_gateway       = "${var.vsphere_network_ipv4_gateway}"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    template  = "${var.vsphere_template}"
    type      = "thin"
  }

  disk {
    datastore = "${var.vsphere_datastore}"
    vmdk      = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}.data_disk.vmdk"
    keep_on_remove = true
  }

  lifecycle {
    ignore_changes = ["network_interface", "dns_suffixes"]
  }
}

resource "vsphere_virtual_disk" "data_disk" {
  count   = "${var.vsphere_network_ipv4_addresses != "" ? length(split(",", "${var.vsphere_network_ipv4_addresses}")) : 0}"
  size          = "${var.data_disk_size}"
  vmdk_path     = "${lower(data.null_data_source.hostname.outputs["name"])}${count.index + 1}.${lower(var.region)}.data_disk.vmdk"
  datacenter    = "${var.vsphere_datacenter}"
  datastore     = "${var.vsphere_datastore}"
  type          = "thin"
  adapter_type  = "lsiLogic"
  lifecycle {
    prevent_destroy = true
  }
}

output "instance_ids" {
  value = ["${vsphere_virtual_machine.instance.*.id}"]
}

output "instances_dns" {
  value = ["${vsphere_virtual_machine.instance.*.name}"]
}

output "instance_private_ips" {
  value = ["${vsphere_virtual_machine.instance.*.network_interface.0.ipv4_address}"]
}
```

**Comment by vancluever** [comment]
Hey @pryorda - thank you very much for your config here - I am going to triage this and try to reproduce right now. I have opened #186 to track this, if you can watch that issue for updates instead of this one that would be great as this is not a related issue.

Thanks!

**Comment by lynic** [comment]
I encounter this issue too!
`
data "vsphere_datacenter" "dc" {}

resource "vsphere_folder" "folder" {
    path          = "kubernetes"
    type          = "vm"
    datacenter_id = "${data.vsphere_datacenter.dc.id}"
  }

resource "vsphere_virtual_machine" "kube-master" {
    name   = "tf-kube-master"
    vcpu   = 2
    memory = 4096
    folder = "${vsphere_folder.folder.path}"`

`* vsphere_virtual_machine.kube-master: Cannot find folder kubernetes`

**Comment by lynic** [comment]
okay, just check the [code](https://github.com/terraform-providers/terraform-provider-vsphere/blob/f84f2e6024f99b4da4994b938c488c90a26e865f/vsphere/resource_vsphere_virtual_machine.go#L1938), and I found that I must specific "datacenter" in vsphere_virtual_machine, after doing that, it can find the folder.

**Comment by AranVinkItility** [comment]
@lynic Thanks for the "datacenter" tip, fixed my problem

**Comment by vanniszsu** [comment]
the "datacenter" is no longer in the schema of the resource "vsphere_virtual_machine"
according to the [code](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go) of #498 

now the folder should use directly the name of the folder ,  not the folder id.

**Comment by vancluever** [comment]
Hey all,

Indeed @vanniszsu this is an old issue and is really no longer relevant in the scheme of things.

As we test the `vsphere_folder` resource for functionality extensively, including the objects that use folders, I'm going to close this issue now. If anyone encounters any new issues with this I would encourage them to open a new issue with the details.

Thanks!
