### ISSUE TITLE
vsphere_virtual_machine - support for guest_id ?

### ISSUE THREAD

**Issue by ze42** [terraform-providers/terraform-provider-vsphere#172]
Hello,

### Terraform Version
Terraform, latest: v0.10.6
vpshere provider: latest, and master branch

### Affected Resource(s)
vsphere_virtual_machine

### Current Behavior

It does not seem to support setting/changing the GuestId.
From what I read in the code, unless based on a template, GuestId is set to `otherLinux64Guest`, and no other value can be specified.

### Expected Behavior

A way to specify guest_id and override default behaviour with specific value.

Did I miss anything, or is it a feature that could be added?

**Comment by sofixa** [comment]
There isn't a way to set it, for now.
At work we're currently working on that and a few other improvements(like the ability to modify VMs), and we'll submit a PR soon(end of week).

Cheers, 
Adrian

**Comment by ze42** [comment]
@sofixa Good to hear.

Was probably about to start working on it in the next days, but if you have a PR coming this way with much more features, I'm looking forward to see this PR :)

**Comment by vancluever** [comment]
Hey @ze42, just a FYI that I have just closed #174. At this point in time changing of the guest ID is not something that we are planning to support.

There is a rewrite of `vsphere_virtual_machine` planned in the next couple of months that will be addressing the current complications of the existing resource, with the objective of simplifying the resource overall and being very specific on what you can do in-band with the resource. Creating VMs from scratch will be reviewed, but more than likely, templates will be the major method of bringing VMs into Terraform, with the recommendation to use tools like [Packer](https://www.packer.io/) to configure the VM hardware the way you want it to look.

Thanks!

**Comment by ze42** [comment]
Ok... I'll consider Packer to build images once it will be able to deploy directly on a vSphere cluster using the API (did not find anything in its documentation so far).

Is there a way to currently build a VM from an existing template, reusing the hardware specs? Did not find any... so, if there isn't any, I'll have to use the #174 for now...

**Comment by ze42** [comment]
@sofixa Thanks for the tip. Will probably help at some point.

But I meant build directly on vsphere. (are there some base official ova file for debian9 available somewhere? like EC2 templates available directly on maketplace by Debian...)

**Comment by sofixa** [comment]
@ze42 build directly on vsphere as in do the building of the image on vSphere? You can use the [Packer vmware-iso builder](https://www.packer.io/docs/builders/vmware-iso.html), with the official Debian 9 iso (in this case, cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-9.1.0-amd64-netinst.iso), that's what we do.

**Comment by ze42** [comment]
Yeah, unfortunately, that seems to require ssh access, rather than API usage.

And it doesn't seem to support "upgrade" (like using a base image, and repacking it with more stuffs in it)

**Comment by sofixa** [comment]
I think the SSH usage is for the VM(so that Packer can connect to the VM and launch stuff to create your template), but could be mistaken. I don't think you can do upgrades, Packer re-creates everything every time, but it ensures consistency, so it's not a huge issue IMO.

**Comment by ze42** [comment]
From: https://www.packer.io/docs/builders/vmware-iso.html

```
It can also build machines directly on VMware vSphere Hypervisor using SSH as opposed to the vSphere API.
```

From what I understand, it requires ssh to the hypervisor (which I don't have access).

For upgrades, the way we use images on AWS:
  * Use Debian image to build our own base image
  * Use our base image to create more specific ones

That's what I meant by "upgrade". Which would be nice, especialy for not having to install from iso image each time.
