### ISSUE TITLE
vsphere_file - not a suitable vmdk for vsphere_virtual_machine

### ISSUE THREAD

**Issue by ze42** [terraform-providers/terraform-provider-vsphere#178]
Hi there,

### Terraform Version

Terraform v0.10.6

Latest master at the time. (c19246445f263d26e1a12797b9b2c89b93123802)

### Affected Resource(s)

`vsphere_file`
`vsphere_virtual_machine`

### Terraform Configuration Files
Revealant config:

```
resource "vsphere_file" "innovation-vpn-1_root" {
  create_directories = true
  datacenter = "${var.datacenter}"
  datastore = "${var.datastore}"
  destination_file = "innovation-vpn-1/innovation-vpn-1_root.vmdk"
  source_datacenter = "${var.vm_template_datacenter}"
  source_datastore = "${var.vm_template_root_datastore}"
  # Source_file: jessie-template-current_2/jessie-template-current.vmdk
  source_file = "${var.vm_template_root_file}"
  lifecycle {
    ignore_changes = [
        "source_datacenter",
        "source_datastore",
        "source_file"
    ]
  }
}

resource "vsphere_virtual_machine" "innovation-vpn-1" {
  cluster = "${var.cluster}"
  datacenter = "${var.datacenter}"
  disk = {
    bootable = true
    datastore = "${var.datastore}"
    vmdk = "${vsphere_file.innovation-vpn-1_root.destination_file}"
    keep_on_remove = "True"
  }
  folder = "${vsphere_folder.infra-vpn.path}"
  memory = 4000
  name = "innovation-vpn-1"
  network_interface = {
[...]
  }
  skip_customization = true
  wait_for_guest_net = false
  vcpu = 2
}
```

### Expected Behavior

I would expect to use `vsphere_file` as `vmdk` for a disk when creating a `vsphere_virtual_machine`.

### Actual Behavior

Crashes, no able to find the file (though it does exist)!

### Important Factoids

```
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.innovation-vpn-1: 1 error(s) occurred:

* vsphere_virtual_machine.innovation-vpn-1: File /vmfs/volumes/5721deab-180fb09a-5d66-0090fa9d06c1/innovation-vpn-1/innovation-vpn-1_root.vmdk was not found
```

Note:

* the VM exist, but is not referenced by `terraform`, and must be manualy deleted.

* Deleting the VM deletes the whole directory (including the copied file within), ensuring further plan to also fail (`No such directory`). The state must be removed (`state rm vsphere_file.xxx`)

Using some `VirtualDiskManager.CopyVirtualDisk` instead of `FileManager.CopyDatastoreFile` seems to resolv the issue. (see branch https://github.com/ze42/terraform-provider-vsphere/tree/file_copy )

https://github.com/ze42/terraform-provider-vsphere/commit/f195ac5ac26802c626b3a7d4dfcb7c8a59f9b307

Did I miss something? Are there some known limitations?

I'm trying to use file.copy because template does not seem to be a valid option when having a source with multiple disks, and wanting to manage them separately (ie: will need to resize one of those, idependantly from the other!)

**Comment by bill-rich** [comment]
The `vsphere_virtual_machine` resource has been refactored and the behavior has changed considerably. I'm going to close this issue as it likely no longer applies. If you're still experiencing this problem, please open a new issue with the current resource. Thanks!
