### ISSUE TITLE
Guest OS and vsphere_virtual_machine configuration is set incorrectly?

### ISSUE THREAD

**Issue by SurferL** [terraform-providers/terraform-provider-vsphere#192]
### Terraform Version
`Terraform v0.10.7`

### Issue
There seems to be an issue where I convert a Fusion VM to an ESXi as seen [here](https://apple.stackexchange.com/questions/99433/moving-fusion-vms-to-esxi), and then I upload the newly created vmdk and create a virtual machine using the existing vmdk as a disk.

Firstly, the Guest OS for some reason is set to `Other Linux (64-bit)` when it should be `Microsoft Windows 7 (64-bit)`. Is there some way of manually setting it?

And secondly, when running the VM after `terraform apply`, the VM crashes and brings up Windows startup repair. However, when creating the VM manually and adding the vmdk as a disk seems to work. 

I'm not sure what I'm doing wrong with my configuration of the `vsphere_virtual_machine` such that it breaks, and also having the wrong Guest OS assigned to it. 

The error found after doing the startup repair is something along the lines of: 
```
Root cause found:
------------------
Unspecified changes to system configuration might have caused the problem.

Repair action: System Restore
Result: Failed. Error code = 0x1f
Time Taken = 6006 ms
etc..
```
But, I've kept the vcpu and memory exactly the same, so not too sure what else I can do for that end?

### Terraform code
```
resource "vsphere_virtual_machine" "win_testing" {
	name		= "win-testing"
	hostname	= "win-testing-nodes01"
	vcpu 		= 1
	memory		= 512
	datacenter	= "datacenter-1"
	skip_customization = true
	wait_for_guest_net = false

	network_interface {
		label	= "VM Network"
	}

	disk {
		datastore	= "datastore-1"
		vmdk 		= "/win_testing/win_test.vmdk"
		keep_on_remove	= true
	}
}
```
Can you suggest what could be done?

Thanks!

**Comment by vancluever** [comment]
Hey @SurferL, sorry you are having trouble!

This definitely sounds like something up during the migration process, and possibly how you are deploying the VM after you have imported the VMDK. Can you instead try to create a VM manually, make sure the OS type is set correctly there, and then convert that VM to a template? Then try to clone the VM off of that one and specify `template` in the `disk` parameter, omitting the `vmdk` path.

What I'm guessing is happening is that the OS type is just defaulting to a general "other linux" default as there's really no way for TF to know what OS the underlying VMDK is.

Thanks!

**Comment by SurferL** [comment]
Thanks for responding! 

I've given that a try and that does successfully create the VM without any startup issues. 

I'll try have a play at another work around as that wasn't what I was hoping to do, unless I could just upload templates from Fusion via terminal.

**Comment by vancluever** [comment]
Hey @SurferL, thanks for the reply!

I'm going to go ahead and close this now as it does not seem to be a problem with the resource. Glad it worked out for you!

**Comment by SurferL** [comment]
@vancluever Although not related with the resource, would you know how to automate the process you described above? 

Or if you know a better way of transferring Fusion VMs to ESXi using Terraform?

**Comment by vancluever** [comment]
Hey @SurferL - sorry for the delay in responding here!

Currently I don't really think there's a good route. With the provider's current form, the best route I'd say would be to migrate it to ESXi using native tools, convert it to a template, and then deploy that template using Terraform with no customization (`skip_customization = true`).

In the future, there will be a couple of things we will be striving for that will help you:

* First is the import from OVF workflow. Using this, you could export the VM to OVF, and then deploy that with Terraform.
* Second, which I actually think would be better for your scenario, is supporting of actual import of virtual machines. You will need to set an accurate config, but it should allow you to use `terraform import` on a natively migrated virtual machine and then from there control the lifecycle completely through Terraform. This method would be the most correct way of doing it more than likely as there would be no workarounds or extra artefacts to clean up later.

Keep an eye out for developments on the new virtual machine resource - we are starting work on it very soon!

**Comment by SurferL** [comment]
No worries :) 

Yeah, I've also found building on Fusion and getting it to ESXi being a massive issue! I did find this other [open source project](https://github.com/jetbrains-infra/packer-builder-vsphere) which enables Packer to build directly on ESXi hosts, but doesn't seem to support Windows guests via winrm yet sadly.

Thanks for the help 👍

**Comment by vancluever** [comment]
Hey @SurferL, if you are using Packer, there is the [vSphere post-processor](https://www.packer.io/docs/post-processors/vsphere.html). Have you tried that yet?

**Comment by SurferL** [comment]
I did take a look at it, and it seems to be using the `ovftool` provided with Fusion and it really didn't like my configurations it seems. I put an [issue](https://github.com/hashicorp/packer/issues/5464) in, but will probably come back to it at some point (as I'm now exploring the next stage with Terraform (with this project :) )

Main reason from moving away fromm that and to go to the other [open source project](https://github.com/jetbrains-infra/packer-builder-vsphere) was to basically remove the use of Fusion as a stepping stone of just provisioning (which also requires a machine to do it), and instead do everything on vsphere, as that is also the end point.
