### ISSUE TITLE
Feature request. Additional parameter requested for  vsphere_virtual_machine resource: network interface name

### ISSUE THREAD

**Issue by JamesTGrant** [terraform-providers/terraform-provider-vsphere#209]
Terraform version: 0.10.7
Provider version: terraform-provider-vsphere 0.4.1
Resource: vsphere_virtual_machine, network interface block

Using Terraform to create VMs from templates. Application(s) are installed after VM is running. Human user must specify network interface name in running applications GUI/API. 

Please could the interface name be configurable in Terraform?
For example:
ens192 is automatically generated name for CentOS7.4
eno16780032 is automatically generated for CentOS7.3
I wish to specify 'eth0' as the interface name. Please could this be added?

Details:
Currently I use a remote-exec to change the interface name after the VM has been created:

1.  get the interface name from the filename in /etc/sysconfig/network-scripts that contains the terraform configured IP address and use this to take the interface down (assumes only a single file will match the search)
2.  get the interface name from the filename in /etc/sysconfig/network-scripts that contains the terraform configured IP address and use this to rename the automatically created i/f name to a manually specifed name (eth0 in the example below)
3. move the file in /etc/sysconfig/network-scripts that contains the terraform configured IP address to a filename matching the manually specified name
4. bring up network interface
5. restart network service

Terraform script:

     # Define the Networking settings for the VM
    network_interface {
        label = "VM Network"
        ipv4_gateway = "192.168.35.254"
        ipv4_address = "${cidrhost("192.168.33.0/27", count.index + 7)}"
        ipv4_prefix_length = "22"
    }
 
    dns_servers = ["137.58.71.251", "137.58.65.3"]
    
    provisioner "remote-exec" {
        inline = [
          "ifconfig `grep -r ${cidrhost("192.168.33.0/27", count.index + 7)} /etc/sysconfig/network-scripts/ | cut -d: -f1 | cut -d- -f3` down",
          "/sbin/ip link set `grep -r ${cidrhost("192.168.33.0/27", count.index + 7)} /etc/sysconfig/network-scripts/ | cut -d: -f1 | cut -d- -f3`  name eth0",
          "mv `grep -r ${cidrhost("192.168.33.0/27", count.index + 7)} /etc/sysconfig/network-scripts/ | cut -d: -f1` /etc/sysconfig/network-scripts/ifcfg-eth0",
          "sed -i 's/.*NAME=.*$/NAME=eth0/g' /etc/sysconfig/network-scripts/ifcfg-eth0",
          "sed -i 's/.*DEVICE=.*$/DEVICE=eth0/g' /etc/sysconfig/network-scripts/ifcfg-eth0",
           "ifconfig eth0 up",
         "systemctl restart network",

**Comment by vancluever** [comment]
Hey @JamesTGrant, thanks for the request!

Unfortunately this crosses a critical provider boundary for us as what you are requesting is, as far as I know, outside of the scope of VM customization within the vSphere API itself which is the only thing that this provider is responsible for. Hence this isn't something we can't add.

I think the correct way to do this would possibly be to use [Packer](https://www.packer.io/) to roll yourself a template ahead of time that has device naming rules to match the naming that you want. Found [this](https://wiki.centos.org/FAQ/CentOS7#head-31ebc6642958a0df12304d6aab9a49034a3b7802) in the CentOS wiki, which might be a good place to start. Note that you want to use either the GRUB or udev rules to do this, as TF and VM customization will blow away the current NIC configuration on the template upon VM creation. YMMV on both methods as I haven't really tried this myself.

Good luck!
