### ISSUE TITLE
Can't create a standard virtual switch without any physical nic attached.

### ISSUE THREAD

**Issue by diwu1989** [terraform-providers/terraform-provider-vsphere#210]
### Terraform Version
Terraform v0.10.7

### vSphere Provider Version
provider.vsphere ~> 0.4

### Affected Resource(s)
vsphere_host_virtual_switch

### Terraform Configuration Files
```
resource "vsphere_host_virtual_switch" "switch2" {
  name           = "testSwitch"
  host_system_id = "${data.vsphere_host.host.id}"
  network_adapters = []
  active_nics = []
  standby_nics = []
}
```
### Debug Output
https://gist.github.com/diwu1989/2997e45dc0d7f37e67735b164693df38

### Expected Behavior
I should be able to create a virtual switch without any nic attached to it.

**Comment by vancluever** [comment]
Hey @diwu1989 - this is a known limitation in the `vsphere_host_virtual_switch` resource right now (ie: our implementation, not in vSphere). I don't have an ETA for a fix but I don't forsee this lingering for too long (and in fact I'll make a note that it gets done before v1.0.0).

Thanks and sorry you ran into this!

**Comment by diwu1989** [comment]
OOOOO, thanks!!! I was really afraid that it was just me being dumb...
The funny thing is, if a vswitch is already there, `terraform` is able to take off the NIC

**Comment by vancluever** [comment]
@diwu1989 just wanted to say that I didn't forget about this for 1.0.0 - the PR is in now!
