### ISSUE TITLE
Issue with using self.ip_address?

### ISSUE THREAD

**Issue by SurferL** [terraform-providers/terraform-provider-vsphere#211]
### Version information
```
terraform -v
Terraform v0.10.7
* provider.vsphere: version = "~> 0.4"
```
### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
# Create virtual machine and provision deployment with ansible
resource "vsphere_virtual_machine" "win-terraform-test" {
	name				= "win-terraform-test"
	vcpu 				= 2
	memory				= 2048
	datacenter			= "${var.vsphere_datacenter}"
	cluster				= "${var.vsphere_cluster}"
	skip_customization	= true
	wait_for_guest_net	= false

	network_interface {
		label			= "VM Network"
	}

	disk {
		datastore		= "${var.vsphere_datastore}"
		template 		= "win-base"
	}

	provisioner "file" {
		connection {
			type		= "winrm"
			user		= "${var.user}"
			password	= "${var.password}"
			host		= "${self.ip_address}"
		}

		source 		= "deploy.py"
		destination = "C:/Users/user/gitlab/deploy.py"
	}
}
```

### Debug Output

```
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.win-terraform-test: 1 error(s) occurred:

* Resource 'vsphere_virtual_machine.win-terraform-test.0' does not have attribute 'ip_address' for variable 'vsphere_virtual_machine.win-terraform-test.0.ip_address'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

I found [this](https://github.com/hashicorp/terraform/issues/2237) which seemed to work (although it was back in 2015), and the docs now say that `ip_address` is deprecated in favour of `ipv4_address` however, using that also gives the same error.

Main reason I need the host ip address is following on from [this](https://github.com/hashicorp/terraform/issues/14953) issue, which requires it for the `winrm` connection, and I thought that Terraform gives the `ip_address` of the newly created vpshere virtual machine.

Can anyone suggest the correct way of doing this?

**Comment by vancluever** [comment]
Hey @SurferL - those attributes are not exported to the base level, so if you actually wanted that, you might need to try `self.network_interface.0.ipv4_address`. However, I don't think that is necessary anymore with the config you have, as we fixed Windows provisioner support back in v0.3.0 with thew work that was done on the guest customization and network waiters. If the waiters are being used and Terraform can discover the current IP address (I see that you have `wait_for_guest_net` set to `false`) TF should auto-populate the provisioner connection info with the the IP address of the first interface.

Is there a reason why you can't use `wait_for_guest_net`? If you can, can you try turning it on and seeing if the provisioner connects properly without the need to specify the host manually?

**Comment by SurferL** [comment]
Thanks for the response @vancluever ! 

I've set the `wait_for_guest_net` to `true` as suggested, and it now successfully populates the connection info for the IP address of the vsphere machine, however now comes up with a timeout error which might suggest a winrm error? Although slightly confused why I'm having issues connecting with winrm as I previously connected via winrm with Packer and Ansible to provision the machine.
```
[DEBUG] plugin.terraform: file-provisioner (internal) 2017/10/19 09:42:19 Retryable error: unknown error Post http://ip-address:5985/wsman: dial tcp 10.1.10.195:5985: i/o timeout

Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.win-terraform-test: 1 error(s) occurred:

* unknown error Post http://ip-address:5985/wsman: dial tcp ip-address:5985: i/o timeout
```
Any thoughts?

**Comment by SurferL** [comment]
Looking further, it seems to be a firewall issue, even though I have the ports necessary for winrm open to allow anything in for both HTTPS and HTTP.

Turning off the firewall for testing seems to allow Terraform to work, however is not a solution, I don't suppose you know the correct settings for winrm to work with Terraform?

**Comment by vancluever** [comment]
Hey @SurferL - glad you figured it out!

One thing you might want to check is if you are doing this on Windows firewall is to make sure that you have allowed these ports on all profiles (sometimes the rules will be separate for the public, private, and domain profiles).

That's the best I can offer, unfortunately - we don't do anything special in the provider definitely - and the WinRM provisioner in TF core (which you are using here) makes use of the same connectivity components that Packer does. Have you tried some of the extra options available for the WinRM provisioner (found [here](https://www.terraform.io/docs/provisioners/connection.html#argument-reference)), if any apply to you?

Thanks!

**Comment by SurferL** [comment]
Thanks for the response @vancluever !

I've had another check, and the firewall settings do allow for both WinRM HTTP and HTTPS connections, for Home/Work (Private) and Public networks, with the VM being connected to a work network, so not sure what the issue could be..

Only main difference between Ansible connecting is this setting: `ansible_winrm_server_cert_validation: ignore`, if there's something similar with Terraform?

**Comment by vancluever** [comment]
Hey @SurferL, that sounds like [this option](https://www.terraform.io/docs/provisioners/connection.html#insecure). Let me know how it goes!

**Comment by SurferL** [comment]
@vancluever Yup that was it! Thanks 💯

**Comment by vancluever** [comment]
Awesome! Glad you got it worked out :+1:

**Comment by qiujinxuan** [comment]
@SurferL  Was "timeout" issue resolved after setting insecure to "true"?  Is it ok you paste the latest configuration here, i am having same issue as yours even after insecure="true" setting.
