### ISSUE TITLE
Error on terraform apply with datastores with spaces in the name

### ISSUE THREAD

**Issue by alexholliz** [terraform-providers/terraform-provider-vsphere#213]
### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest
version of Terraform, you can try upgrading, depending on if your problem is
with the provider or with Terraform core itself.

Terraform v0.10.7

### Affected Resource(s)
- vsphere provider

### Description
I recall this being an issue with an older version of the vsphere provider; but it had been fixed. Similar to https://github.com/terraform-providers/terraform-provider-vsphere/issues/52 except the VM is actually created correctly, terraform just spits out an error at the end of a terraform apply operation.

`[ERROR] Failed trying to parse disk path: [Compellent VMWare 5] centos-7-test/centos-7-test.vmdk`

### Expected Behavior

`terraform apply` should have created a single VM.

### Actual Behavior

`terraform apply` creates the VM but has an error at the end of the operation regarding being unable to parse the disk path.

### Steps to Reproduce
1. Create a VMWare datastore with spaces in the name and reference it in your config file
2. `terraform apply`

**Comment by vancluever** [comment]
Hey @alexholliz, thanks for the report! As we are ramping up efforts to refactor `vsphere_virutal_machine`, I'm not too sure when we will be fixing this bug in particular, but needless to say there will be some attention paid to the resource as a whole over the next few weeks. Part of that work will be more than likely moving the datastore search logic over to a data source, which will enable us to better troubleshoot these issues and better test them in general.

Sorry you are having trouble! If there is some time during the next few weeks to look into this to see if we can apply a maintenance fix to the logic here, and I'll update this issue if that happens!

**Comment by szechyjs** [comment]
Looking forward to a fix for this as well.

Currently breaks kubernetes-anywhere

kubernetes/kubernetes-anywhere#376

**Comment by vancluever** [comment]
Hey all - since we have significantly changed this functionality in 1.x and we have a report of it being fixed (thanks @divyenpatel!) I am going to close this. If there are indeed issues of this happening in the 1.x releases please open a new issue.

Thanks!
