### ISSUE TITLE
Question: move existing VM to another folder

### ISSUE THREAD

**Issue by lawrence-c** [terraform-providers/terraform-provider-vsphere#214]
Hi,

I was wondering how you would go about moving an existing VM from one folder to another? (idea behind this is to move from Testing to Production folders, or Resource Pools in the further future).

I'm assuming this would be something to do with using `vsphere_virtual_machine`? However I'm not sure the best way to go about using it, as it seems to be mainly creating and destroying VMs rather than modifying?

Thanks in advance!

**Comment by bill-rich** [comment]
The `vsphere_virtual_machine` resource has been refactored and the behavior has changed considerably. I'm going to close this issue as it likely no longer applies. If you're still experiencing this problem, please open a new issue with the current resource. Thanks!
