### ISSUE TITLE
Unable to specify new disk size of template

### ISSUE THREAD

**Issue by vernak2539** [terraform-providers/terraform-provider-vsphere#217]
The vsphere provider doesn't allow us to specify the size of the template we're basing our machine off of. 

This functionality definitely exists in the API.

### Terraform Version

`Terraform v0.10.7`

### vSphere Provider Version

`provider.vsphere ~> 0.4`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "box" {
  // ...
  disk {
    template  = "${var.disk_template}"
    bootable  = true
    datastore = "${var.disk_datastore}"
    type      = "${var.disk_type}"
    name = "some_name"
    size = 15
  }
}
```

### Debug Output

Error stating that size cannot be specified when using a template

### Panic Output

N/A

### Expected Behavior

I should be able to dynamically specify a size of a VM being created from a template.

### Actual Behavior

I am unable to perform the expected behaviour

### Steps to Reproduce

1. `terraform apply`

**Comment by vancluever** [comment]
Hey @vernak2539, thanks for the issue and sorry you are having trouble. You have stumbled upon another limitation of the `vsphere_virtual_machine` resource here that will be fixed in a pending refactor when v1.0.0 is released soon.

Will keep this open for now just to make sure we can close it when the new version of the resource is released.

Thanks!

**Comment by vernak2539** [comment]
@vancluever great thanks for the response! Is there somewhere I can go to view the progress on the v1.0.0?

**Comment by vancluever** [comment]
@vernak2539, sorry, but currently we are only tracking this internally. Our estimated release date is sometime next month. With all of that said, a new version of `vsphere_virtual_machine` (which is currently being built with high priority) may be out earlier than than if it is completed earlier and we decide there is still some loose ends we want to tie before the release.

Thanks!

**Comment by JamesTGrant** [comment]
When the disk size feature is added will the partition(s) in the template automatically be grown/shrunk to fit the new size (by some magic)? That would be amazingly handy.
Currently, when I modify my template and increase the disk size I have to launch the VM, connect to it,  and adjust the partition sizes of the OS (Linux example below):
•	Create a new LVM partition
•	Create a new physical volume on the new partition
•	Extend the volume group
•	Extend the logical volume
•	Grow the XLFS filesystem
Good instructions for which are here: https://www.rootusers.com/how-to-increase-the-size-of-a-linux-lvm-by-expanding-the-virtual-machine-disk/

**Comment by yves-vogl** [comment]
Hi,

as stated by @vernak2539 it seems that you cannot specify a size for the newly created disk. Do you have any news on this @vancluever?

Thanks!

**Comment by bill-rich** [comment]
The `vsphere_virtual_machine` resource has been refactored and the behavior has changed considerably. I'm going to close this issue as it likely no longer applies. If you're still experiencing this problem, please open a new issue with the current resource. Thanks!
