### ISSUE TITLE
Error when looking for DistributedVirtualPortgroup name

### ISSUE THREAD

**Issue by skywalk7** [terraform-providers/terraform-provider-vsphere#220]
func `getNetworkName` has issue which results in error retrieving `DistributedVirtualPortgroup` from `virtualDevice` which results in empty network name and resource recreation. 

> 2017-10-23T16:24:10.344-0700 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 2017/10/23 16:24:10 [ERROR]: Error retrieving portgroup ServerFaultCode: The object 'vim.dvs.DistributedVirtualPortgroup:dvportgroup-57167' has already been deleted or has not been completely created
> 2017-10-23T16:24:10.344-0700 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 2017/10/23 16:24:10 [DEBUG] device name
...
> network_interface.0.label:              "" => "DistributedVirtualPortgroup-Name-dvs01" (forces new resource)

Looks like correct fix would be using `dvPortgroupFromUUID` function instead of `object.NewDistributedVirtualPortgroup` at https://github.com/terraform-providers/terraform-provider-vsphere/blob/eb9a0ad0a0f80048cd3adc407c6e18e8f4d01f56/vsphere/resource_vsphere_virtual_machine.go#L2356

```
dvp, err := dvPortgroupFromUUID(c, portInfo.SwitchUuid, portInfo.PortgroupKey)
if err != nil {
  log.Printf("[ERROR]: Error retrieving portgroup %v", err)
  return "", err
 }
deviceName = dvp.Name()
```

PS I can't create PR now

**Comment by vancluever** [comment]
Hey @skywalk7, thanks for submitting the issue and sorry you are having trouble.

The `vsphere_virtual_machine` resource is in the middle of a refactor that will address this bug. There is no official ETA, but we are targeting mid-November for a full release.

For now I'll leave this open to note it as an outstanding bug. Stay tuned!

**Comment by jonathanallen** [comment]
Ran into this as well, a fix would be appreciated.

**Comment by jbraswell** [comment]
Just ran into this as well. Any idea when the refactor of the provider will be available?

**Comment by bill-rich** [comment]
This should be resolved by the `virtual_machine` refactor. If you're still experiencing this issue, please open a new issue with the current details. Thanks!
