### ISSUE TITLE
Terraform Crash ( terraform-provider-vsphere_v0.4.2_x4 - ESXi version: 6.5.0)

### ISSUE THREAD

**Issue by GraemeCrawford** [terraform-providers/terraform-provider-vsphere#223]
Apologies in advance if this is a duplicate.

### Terraform Version

- Terraform v0.10.7

(Was also seeing the same issue with v0.10.5 before upgrading to test with v.0.10.7)

### vSphere Provider Version

- linux_amd64 

- terraform-provider-vsphere_v0.4.2_x4

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl

provider "vsphere" {
    vsphere_server = "${var.vsphere_vcenter}"
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    allow_unverified_ssl = true
}

resource "vsphere_virtual_machine" "user-terraform-test" {
    name   = "user-terraform-test"
    vcpu   = 1
    memory = 1024
    domain = "company.local"
    datacenter = "${var.vsphere_datacenter}"

    # Define the Networking settings for the VM
    network_interface {
        label = "LAN"
        ipv4_gateway = "192.168.x.x"
        ipv4_address = "192.168.x.x"
        ipv4_prefix_length = "24"
    }

    dns_servers = ["192.168.x.x, "8.8.8.8"]

    # Define the Disks and resources. The first disk should include the template.
    disk {
        name = "user-test"
        datastore = "datastore1"
        size = "20"
    }
}

```

### Debug Output

https://gist.github.com/GraemeCrawford/6e08334f88e139c4a0133b9b38da2393#file-redacted-crash-log

### Panic Output

https://gist.github.com/GraemeCrawford/c7009510ad5be14211643fe5133f55e7#file-panic-log

### Expected Behavior

VM should have been deployed to vSphere host

### Actual Behavior

Terraform Panic

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

ESXi version: 6.5.0

### References

none

**Comment by GraemeCrawford** [comment]
I have built the latest terraform-provider-vsphere binary from the master branch and I am still seeing the same issue. To confirm I am using the newly built binary:

```
# cat .terraform/plugins/linux_amd64/lock.json
{
  "vsphere": "f965ccfef47973b6cde8609c8b920b471ff0ac31358999b73a4b60f600a9ceef"
}%

# shasum -a 256 /usr/local/bin/terraform-provider-vsphere
f965ccfef47973b6cde8609c8b920b471ff0ac31358999b73a4b60f600a9ceef  /usr/local/bin/terraform-provider-vsphere

```

**Comment by vancluever** [comment]
Hey @GraemeCrawford, I think there's a couple of issues here: first one is with govmomi where it should not be crashing on this error, and the second is that you seem to have a license problem. Check the log output:

```
2017-10-25T12:00:51.361+0100 [DEBUG] plugin.terraform-provider-vsphere_v0.4.2_x4: 2017/10/25 12:00:51 [ERROR] ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.
```

You might want to check what you are trying to do and correct the problem.

I will open an issue in vmware/govmomi to get this looked at. Thanks!

**Comment by vancluever** [comment]
Hey @GraemeCrawford I'm working on a fix for this right now. The bug is with us and govmomi... sorry!

If at all possible would you be able to try again against the PR when you have a chance, as you seem to know how to and are able to build the provider?

Thanks!

**Comment by vancluever** [comment]
Hey @GraemeCrawford can you test against #225 and check to make sure this fixes your issue?

**Comment by GraemeCrawford** [comment]
Hey @vancluever I'll try this first thing tomorrow morning when I get into the office and let you know how it goes. Thanks for the quick response.

**Comment by GraemeCrawford** [comment]
Hi @vancluever I've built the provider from [#255](https://github.com/terraform-providers/terraform-provider-vsphere/pull/225) and can confirm I no longer get the panic, just a nice clean licence error.

```
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.user-terraform-test: 1 error(s) occurred:

* vsphere_virtual_machine.user-terraform-test: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Happy to confirm this as fixed. Cheers!
