### ISSUE TITLE
Vsphere tag category - already exists, code 400 error

### ISSUE THREAD

**Issue by LeeKeery** [terraform-providers/terraform-provider-vsphere#238]
**Terraform Version**
Terraform v0.10.8

**vSphere Provider Version**
provider.vsphere 0.4.2

**Affected Resources**
- vsphere_tag_category
- vsphere_tag

**Terraform Configuration Files**
```
terraform {
  backend "consul" {}
}

module "infoblox" {
  #module source location
  source = "git::ssh://git@location.git"

  #credentials
  infoblox_user = "${var.infoblox_user}"
  infoblox_pass = "${var.infoblox_pass}"

  #record spec
  instance_count     = "${var.instance_count}"
  os_type            = "${var.os_type}"
  requested_hostname = "${var.requested_hostname}"
  environment        = "${var.environment}"
  seq_start          = "${var.seq_start}"
}

module "tagging" {
  #module source location
  source = "git::ssh://git@location.git"
  vsphere_user   = "${var.vsphere_user}"
  vsphere_pass   = "${var.vsphere_pass}"
  vsphere_server = "${var.vsphere_server}"
}

module "linux" {
  #module source location
  source = "git::ssh://git@location.git"
  instance_count = "${var.instance_count}"
  cpu_count      = 2
  memory         = 2048
  environment    = "${var.environment}"
  vsphere_user   = "${var.vsphere_user}"
  vsphere_pass   = "${var.vsphere_pass}"
  ipaddresses    = ["${module.infoblox.ip_addresses}"]
  dns_names      = ["${module.infoblox.dns_names}"]
  domains        = ["${module.infoblox.domains}"]
  chef_cookbook  = "${var.chef_cookbook}"
  linux_pass     = "${var.linux_pass}"
  tags           = ["${module.tagging.tags}"]
}
```

**Debug Output**

```
terraform apply 
module.infoblox.infoblox_host_record.mydomain: Creating...
  alias:     "" => "Test_2_0"
  cidr:      "" => "10.100.10.0/24"
  domain:    "" => "dev.com"
  fqdn:      "" => "<computed>"
  ipaddress: "" => "<computed>"
  name:      "" => "testServer"
  ttl:       "" => "3600"
module.infoblox.infoblox_host_record.mydomain: Creation complete after 1s (ID: record:host/*****...*****:testServer.dev.com/default)
module.tagging.vsphere_tag_category.category: Creating...
  associable_types.#:          "" => "1"
  associable_types.3125094965: "" => "VirtualMachine"
  cardinality:                 "" => "SINGLE"
  description:                 "" => "Managed by Terraform"
  name:                        "" => "terraform-provisioned"
Error applying plan:

1 error(s) occurred:

* module.tagging.vsphere_tag_category.category: 1 error(s) occurred:

* vsphere_tag_category.category: could not create category: Status code: 400: call failed: Error response from vCloud Suite API: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.already_exists"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

 **Expected Behavior**
Continue if category already exists and use the ID of the existing category. 

 **Actual Behavior**
Apply is abondoned 

**Steps to Reproduce**

1. Ensure you already have the tag category created in vSphere, manually or via another Terraform run. 
2. Terraform apply (with the same tag category name specified in your configs) 

### Important Factoids

Referencing the [Go library](https://github.com/vmware/vic/blob/master/pkg/vsphere/tags/tags.go). 

It looks like the vSphere provider is using the _**CreateCategory**_ function, rather than _**CreateCategoryIfNotExist**_. 

### References

#38 Appears to be a similar issue, except with the vsphere_folder resource.

**Comment by vancluever** [comment]
Hey @LeeKeery, thanks for submitting the issue and sorry you are having trouble.

The `vsphere_tag` and `vsphere_tag_category` resources are designed to manage _new_ tags and categories only - this is in line with the general principles of Terraform, which is to have exclusive management of the infrastructure it's directed to manage with no implicit import. We don't use `CreateCategoryIfNotExist` exactly for this reason.

If you want to use external tags and categories with Terraform, you have three options:

* [Import](https://www.terraform.io/docs/import/index.html) the resources you want - see the docs for importing [tags](https://www.terraform.io/docs/providers/vsphere/r/tag.html#importing) and [categories](https://www.terraform.io/docs/providers/vsphere/r/tag_category.html#importing)
* Use the [`vsphere_tag`](https://www.terraform.io/docs/providers/vsphere/d/tag.html) and [`vsphere_tag_category`](https://www.terraform.io/docs/providers/vsphere/d/tag_category.html) data sources
* (For when your tags are managed with a different Terraform config) use [`terraform_remote_state`](https://www.terraform.io/docs/providers/terraform/d/remote_state.html) to obtain the tag data you need from the state of another configuration.

Hope this helps!

**Comment by LeeKeery** [comment]
Thanks the for clarification @vancluever.
