### ISSUE TITLE
Are resource pools intended to be required for virtual machines?

### ISSUE THREAD

**Issue by raymondhoagland** [terraform-providers/terraform-provider-vsphere#262]
### Terraform Version
v0.11.0

### vSphere Provider Version
v1.0.0

### Affected Resource(s)
- `vsphere_virtual_machine`
- `vsphere_resource_pool`

### Expected Behavior
Should not be required to specify a resource pool to place the VM in.

### Actual Behavior
Resource pool is required for all new virtual machines.

### Steps to Reproduce
terraform apply

### Important Factoids
We currently have not defined any clusters or resource pools.  That being said I feel like this shouldn't be a requirement (it wasn't in 0.4.2).  I know the resource pool data source mentions a default resource pool for the cluster but I don't know that we have a cluster in the first place.

It might be something we look to implement in the future, but seems like an advanced option and not something that needs to be there.

**Comment by vancluever** [comment]
Hey @raymondhoagland - resource pools are indeed required for all virtual machine resources. `CreateVM_Task` requires a resource pool, and the old VM resource was abstracting this functionality away by doing the heavy lifting of locating this resource pool for you. As part of our continued effort to move this kind of provider-side searching/selection logic to data sources, this logic has been moved to the data source.

All compute resources in vSphere, be it clusters or standalone hosts, have a default resource pool.

What kind of setup do you have?

If you have a _standalone host_, reference the host in the place of the cluster:

```
data "vsphere_resource_pool" "pool" {
  name          = "standalone1/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```

If you are using ESXi directly, use the following:

```
data "vsphere_resource_pool" "pool" {}
```

Let us know how it goes!

**Comment by vancluever** [comment]
@raymondhoagland if you use ESXi just FYI that there is currently some issues with using the resource pool and VM resources on ESXi. A fix should be in shortly.

**Comment by vancluever** [comment]
@raymondhoagland the ESXi issues have been fixed and 1.0.1 should be out shortly. The info in my first response should be good now :slightly_smiling_face:

**Comment by raymondhoagland** [comment]
@vancluever awesome, thanks for the quick responses! it looked like
```
data "vsphere_resource_pool" "pool" {
  name          = "Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```
was working for me but I'll check out v1.0.1 and see if that changes anything :grin:

**Comment by raymondhoagland** [comment]
@vancluever looks like using just "Resources" still works for me in v1.0.1.  Thanks!

**Comment by vancluever** [comment]
@raymondhoagland glad it's working for you, but as just to clarify what I said above, if you are using ESXi, then you should not need to specify anything in the data source at all:

```
data "vsphere_resource_pool" "pool" {}
```

If you can specify `Resources` without running into a error that your search was too broad, it almost seems like you are using ESXi directly. I'd recommend using the short form of the resource instead. I'm going to close this now as this is not necessarily a bug, but just something to keep in mind.

PS: #250 is open which details a TODO for explicitly specifying a cluster or standalone host for `vsphere_resource_pool`. If this work gets done, we might block specifying a default resource pool by path, just to prevent confusion and make the usage path more explicit. If that happens, you will need to modify your implementation. But definitely continue to use this if it's working for you and you can make any adjustments when you have the opportunity!

**Comment by vancluever** [comment]
If that's the case, sounds like you are using vCenter. Do you just have a single host in your setup?

**Comment by raymondhoagland** [comment]
Yes I'm using Vcenter - there are 3 hosts, does that change anything?

**Comment by vancluever** [comment]
Hey @raymondhoagland, can you install and configure [govc](https://github.com/vmware/govmomi/tree/master/govc) if you don't have it already, and enter the following command, and let me know what the output looks like?

```
govc ls /dc/host
```

Where `dc` is the path to your datacenter (including datacenter folders if you use them).

I just need an abridged output, don't send the full output if it's sensitive from a host recon perspective. What I'm specifically curious about is if you have a cluster, but just don't know it, or if you are running on standalone hosts.

If it's the former (clusters), you will see something like:

```
/dc/host/cluster1
```

Listing this will show the hosts under the cluster and the default resource pool:

```
/dc/host/cluster1/Resources
/dc/host/cluster1/esxi1
/dc/host/cluster1/esxi2
/dc/host/cluster1/esxi3
```

If you are using standalone hosts, you should see the ESXi servers in their own hierarchy without the cluster:

```
/dc/host/esxi1
/dc/host/esxi2
/dc/host/esxi3
```

**Comment by raymondhoagland** [comment]
Hey @vancluever I see something like
```
govc ls /test/host/mp
/test/host/mp/Resources
/test/host/mp/host1
/test/host/mp/host2
/test/host/mp/host3
```

So based on what you said above, I guess I do have a cluster that I wasn't aware of!

Based on that, I should be able to change the data resource I have for the resource pool - let me try that and I'll update with my results - thanks again!

**Comment by vancluever** [comment]
Glad it worked out for you @raymondhoagland!

**Comment by avinash-fissionhq** [comment]
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_resource_pool" "pool" {}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${var.datastore}"

  num_cpus = 2
  memory   = 1024
  guest_id = "Microsoft Windows Server 2012 R2"

  network_interface {
    network_id = "VM Network | Adapter : E1000"
  }

  disk {
    label = "disk0"
    size  = 20
  }
}
