### ISSUE TITLE
Create VM using cloning fails due to spec.deviceChange.device

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#264]
I'm on tf 0.10.7. 

Just upgraded to the 1.0. version of the vpshere provider.  Lots of changes ..good work...
Trying to create/clone a vm .. resulting in this error
========

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "vsphere" (1.0.1)...
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_network.network2: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_network.network: Refreshing state...
vsphere_virtual_machine.vm_1: Creating...
  boot_retry_delay:                                     "" => "10000"
  change_version:                                       "" => "<computed>"
  clone.#:                                              "" => "1"
  clone.0.customize.#:                                  "" => "1"
  clone.0.customize.0.ipv4_gateway:                     "" => "146.89.142.193"
  clone.0.customize.0.linux_options.#:                  "" => "1"
  clone.0.customize.0.linux_options.0.domain:           "" => "test.internal"
  clone.0.customize.0.linux_options.0.host_name:        "" => "surajtest"
  clone.0.customize.0.linux_options.0.hw_clock_utc:     "" => "true"
  clone.0.customize.0.network_interface.#:              "" => "1"
  clone.0.customize.0.network_interface.0.ipv4_address: "" => "146.89.142.250"
  clone.0.customize.0.network_interface.0.ipv4_netmask: "" => "26"
  clone.0.customize.0.timeout:                          "" => "10"
  clone.0.template_uuid:                                "" => "4225a159-f154-3bf5-4606-ae1180dc38b4"
  clone.0.timeout:                                      "" => "30"
  cpu_limit:                                            "" => "-1"
  cpu_share_count:                                      "" => "<computed>"
  cpu_share_level:                                      "" => "normal"
  datastore_id:                                         "" => "datastore-245"
  default_ip_address:                                   "" => "<computed>"
  disk.#:                                               "" => "1"
  disk.0.attach:                                        "" => "false"
  disk.0.device_address:                                "" => "<computed>"
  disk.0.disk_mode:                                     "" => "persistent"
  disk.0.disk_sharing:                                  "" => "sharingNone"
  disk.0.eagerly_scrub:                                 "" => "false"
  disk.0.io_limit:                                      "" => "-1"
  disk.0.io_reservation:                                "" => "0"
  disk.0.io_share_count:                                "" => "0"
  disk.0.io_share_level:                                "" => "normal"
  disk.0.keep_on_remove:                                "" => "false"
  disk.0.key:                                           "" => "0"
  disk.0.name:                                          "" => "surajtest.vmdk"
  disk.0.size:                                          "" => "128"
  disk.0.thin_provisioned:                              "" => "true"
  disk.0.unit_number:                                   "" => "0"
  disk.0.write_through:                                 "" => "false"
  ept_rvi_mode:                                         "" => "automatic"
  firmware:                                             "" => "bios"
  folder:                                               "" => "surajtest"
  force_power_off:                                      "" => "true"
  guest_id:                                             "" => "sles12_64Guest"
  guest_ip_addresses.#:                                 "" => "<computed>"
  host_system_id:                                       "" => "<computed>"
  hv_mode:                                              "" => "hvAuto"
  imported:                                             "" => "<computed>"
  memory:                                               "" => "131072"
  memory_limit:                                         "" => "-1"
  memory_share_count:                                   "" => "<computed>"
  memory_share_level:                                   "" => "normal"
  migrate_wait_timeout:                                 "" => "30"
  name:                                                 "" => "surajtest"
  network_interface.#:                                  "" => "1"
  network_interface.0.adapter_type:                     "" => "vmxnet3"
  network_interface.0.bandwidth_limit:                  "" => "-1"
  network_interface.0.bandwidth_reservation:            "" => "0"
  network_interface.0.bandwidth_share_count:            "" => "<computed>"
  network_interface.0.bandwidth_share_level:            "" => "normal"
  network_interface.0.device_address:                   "" => "<computed>"
  network_interface.0.key:                              "" => "<computed>"
  network_interface.0.mac_address:                      "" => "<computed>"
  network_interface.0.network_id:                       "" => "network-264"
  num_cores_per_socket:                                 "" => "1"
  num_cpus:                                             "" => "4"
  reboot_required:                                      "" => "<computed>"
  resource_pool_id:                                     "" => "resgroup-356"
  run_tools_scripts_after_power_on:                     "" => "true"
  run_tools_scripts_after_resume:                       "" => "true"
  run_tools_scripts_before_guest_shutdown:              "" => "true"
  run_tools_scripts_before_guest_standby:               "" => "true"
  scsi_controller_count:                                "" => "1"
  scsi_type:                                            "" => "pvscsi"
  shutdown_wait_timeout:                                "" => "3"
  swap_placement_policy:                                "" => "inherit"
  uuid:                                                 "" => "<computed>"
  vmware_tools_status:                                  "" => "<computed>"
  vmx_path:                                             "" => "<computed>"
  wait_for_guest_net_timeout:                           "" => "5"
vsphere_virtual_machine.vm_1: Still creating... (10s elapsed)
vsphere_virtual_machine.vm_1: Still creating... (20s elapsed)
vsphere_virtual_machine.vm_1: Still creating... (30s elapsed)
vsphere_virtual_machine.vm_1: Still creating... (40s elapsed)
Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm_1: 1 error(s) occurred:

* vsphere_virtual_machine.vm_1: error reconfiguring virtual machine: A specified parameter was not correct: spec.deviceChange.device

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

This template ( aka vmware ) works perfect with the 0.4.2 -  Any thoughts ?

**Comment by vancluever** [comment]
Hey @surajsub - can you do a couple of things:

* Get the debug log of the problem as per the instructions in the [issue template](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/.github/ISSUE_TEMPLATE.md) and send along the gist?
* While you are collecting debug logs - can you do a run with `VSPHERE_CLIENT_DEBUG=1` set, and locate the `ReconfigVM_Task` call (will be in a `xxx-req.xml`) file, and put that in a gist as well? Please check it for sensitive information first (there should not be any but just in case).
* Finally, tell me a bit about your template? Namely its hardware config.

Thanks!

**Comment by AranVinkItility** [comment]
Got the same error after upgrading from 0.4 to 1.0

**Comment by vancluever** [comment]
@AranVinkItility thanks for the input. Can you send along the same info I've requested from @surajsub?

Thanks!

**Comment by AranVinkItility** [comment]
Already figured it out, I had set a disk size which wasn't the same as template I was cloning. This is mentioned in the docs, but the provider error message wasn't clear about what was going on. Maybe we could also include the faultmessage's 'key' in the providers error message?
```xml
<error>
  <fault xsi:type="InvalidArgument">
    <faultMessage>
      <key>msg.disk.extendFailure</key>
      <arg>
        <key>1</key>
        <value xsi:type="xsd:string">msg.disklib.INVAL</value>
      </arg>
      <message>The disk extend operation failed: One of the parameters supplied is invalid</message>
    </faultMessage>
    <invalidProperty>spec.deviceChange.device</invalidProperty>
  </fault>
  <localizedMessage>A specified parameter was not correct: spec.deviceChange.device</localizedMessage>
</error>
```
Setting the disk size the same as the template fixed this for me:
```
  disk {
    name     = "terraform-vm.vmdk"
    #Grab disk size from template data
    size = "${data.vsphere_virtual_machine.template.disk_sizes[0]}"
  }
```

Because the error message seems to be quite a general one, I'm not sure if @surajsub 's error has the same cause. (In that case sorry for the issue-hijack)

**Comment by surajsub** [comment]
@AranVinkItility - thanks for issue hijack - i did have the same issue :-) . Updated the template as per your fix 👍  - thanks got past the issue .

**Comment by vancluever** [comment]
Hey everyone, closing this now as it appears the issues were fixed and due to configuration issues. 1.1 and higher should have better validation for specific issues like this and we will continue to add more as they come up.

Thanks!

**Comment by johnjelinek** [comment]
Where do I find more details on this error in the docs? If I pick a disk size that is larger than my template, I get this error -- but I thought this should be supported if the VM disk is >= to the template.

**Comment by vancluever** [comment]
@johnjelinek are you using a linked clone? If you are the disk has to be the exact same size.

**Comment by johnjelinek** [comment]
@vancluever: I wasn't planning on using a linked clone -- how can I be sure? I'm just pointing to a template (the template is on an NFS datastore).

**Comment by johnjelinek** [comment]
@vancluever: I set `linked_clone  = false` in my `clone` block and it still complains (error: `spec.deviceChange.device`) when I set a size larger than the template.

**Comment by m4r10k** [comment]
I even have a similar strange behavior. If I do not set `linked_clone = false` terraform apply fails with no information on what parameter is not set.
```
018/01/16 13:14:30 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: error reconfiguring virtual machine: A specified parameter was not correct: 

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

If I add the parameter, then the apply works. What? And some more thing: Setting the disk size through template access does not work - returns 0. So I have to set it manually. Is there any documentation about `data.template`, what are the properties of this data type? 
```
size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
```
