### ISSUE TITLE
Host Pinning Ignored for Clones?

### ISSUE THREAD

**Issue by raymondhoagland** [terraform-providers/terraform-provider-vsphere#266]
### Terraform Version
v0.11.0

### vSphere Provider Version
v1.0.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "ms_vm" {
  name                          = "${var.vm_general_settings["name_prefix"]}-${var.host["number"]}-vm${var.vm_number}-v${replace(var.gm_version, ".", "")}"
  resource_pool_id              = "${data.vsphere_resource_pool.ms_pool.id}"
  datastore_id                  = "${data.vsphere_datastore.ms_ds.id}"
  host_system_id                = "${data.vsphere_host.ms_host.id}"

  num_cpus                      = "${var.vm_hardware_settings["num_cpus"]}"
  memory                        = "${var.vm_hardware_settings["memory"]}"
  guest_id                      = "${var.vm_general_settings["guest"]}"

  network_interface {
    network_id      = "${data.vsphere_network.ms_net.id}"
    adapter_type    = "e1000"
  }

  disk {
    name    = "${var.vm_general_settings["name_prefix"]}-${var.host["number"]}-vm${var.vm_number}-v${replace(var.gm_version, ".", "")}.vmdk"
    size    = "${var.vm_hardware_settings["disk_size"]}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.ms_template.id}"
  }

  wait_for_guest_net_timeout    = false
}
```

### Expected Behavior
VM is created on the specified host system.

### Actual Behavior
VM is created on one of the hosts in the cluster, not necessarily the one specified.

### Steps to Reproduce
1.  Specify a host to the data resource
2.  `terraform apply`

### Important Factoids
Looking at [this function](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine.go#L657-L783) I don't see any use of the `host_system_id` variable.  

Is it expected that host pinning is ignored for clones?  If so, maybe they should be marked as mutually exclusive somehow.

**Comment by vancluever** [comment]
Hey @raymondhoagland, you may have to change your DRS level to "Manual" to have this function 100% correctly right now.

I'm adding this as an enhancement - this is not necessarily an issue with the code, but possibly something we could look at - basically what is happening is that even though you create a VM/clone on one host, when it gets powered on DRS may move it to a different host. Can you check that stuff and let me know?

PS: The host for cloning is found in the relocate spec in vSphere and is set by TF during the clone process - [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go#L204) is the code.

Thanks!

**Comment by vancluever** [comment]
PS: In this situation, running another apply should vMotion it to the correct host after creation.

**Comment by raymondhoagland** [comment]
Completely forgot to respond to this - it appears to have resolved itself by switching to using the data resource to look up the id of the host rather than specifying it myself.  Everything is working as expected so I'll close out the issue.

I don't actually have DRS enabled at all at the moment which is why I was surprised that it could be moving.
