### ISSUE TITLE
Create VM ESXi 6.0.0 and 6.5.0 not possible on standalone license!

### ISSUE THREAD

**Issue by tommymunter** [terraform-providers/terraform-provider-vsphere#268]
Hi there,
Great work with new provider.vsphere v1.0.1 but it's not working on ESXi standalone :(
Only working with vcenter, Essentials Plus license. 
Or temporary in Evaluation Mode.

### Terraform Version
Terraform v0.11.1

### vSphere Provider Version
+ provider.vsphere v1.0.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "dc" {
  name = "ha-datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {}

data "vsphere_network" "mgmt_lan" {
  name          = "MGMT LAN"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "test2" {
  name             = "test2"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus   = 1
  memory     = 2048
  wait_for_guest_net_timeout = 0
  guest_id = "centos7_64Guest"
  nested_hv_enabled =true
  network_interface {
   network_id     = "${data.vsphere_network.mgmt_lan.id}"
   adapter_type   = "vmxnet3"
   use_static_mac = true
   mac_address    = "00:50:56:17:01:01"
  }

  disk {
   size             = 16
   name             = "test2.vmdk"
   eagerly_scrub    = false
   thin_provisioned = true
  }
}

```
### Expected Behavior

Create a new VM

### Actual Behavior

* vsphere_virtual_machine.test2: error shutting down virtual machine: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We have Standalone ESXi 6.0.0 u2 and ESXi 6.5.0, same behavior on both

Workaround:
remove license key, then it's possible to apply vm

Is the "Essentials Plus" license required????
I thought it should be possible to use the standalone license!

**Comment by vancluever** [comment]
Hey @tommymunter, thanks for the report.

Definitely we want to work to support standard here. Apologies for the issues that you are experiencing.

We will have to investigate what feature is causing this issue, but in the meantime, can you try this with `VSPHERE_CLIENT_DEBUG=1` set as an environment variable for your Terraform run? One of the logged responses in the `.govmomi` directory will have the error you are seeing - I'd like to know if there's any additional info on why exactly it's being blocked.

Thanks!

**Comment by tommymunter** [comment]
Hi,
I Will do that first thing in the morning, swedish time.
Hope I Will manage to get debuter on and catch the error.

**Comment by vancluever** [comment]
Hey Tommy,

I'm actually wondering - are you referring to _free_ ESXi by any chance?

I can't really see any difference in editions that would be causing this issue here otherwise, and API write operations are not allowed on free ESXi:

https://www.virtuallyghetto.com/2011/06/dreaded-faultrestrictedversionsummary.html

Can you confirm this? We will update the documentation in the meantime.

**Comment by tommymunter** [comment]
Hi
It was the "free license" we had on those standalone host. I thought if you had a license it's not the _free_ edition. So this should only be documented, could also place the _note_ about:
data "vsphere_resource_pool" "pool" {} a bit clearer (hard to find).

**Comment by vancluever** [comment]
Hey @tommymunter, #273 adds a bit of language to [this section](https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html#using-with-esxi) that will hopefully make it a bit clearer.

Glad you got this worked out!

**Comment by muthukumars** [comment]
I am facing this issue too. Did anyone have any solution for this ?

Please see below

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.TEST-VM: 1 error(s) occurred:

* vsphere_virtual_machine.TEST-VM: error creating virtual machine: ServerFaultCode: Current license or ESXi version prohibits execution of the requested operation.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

When I checked my ESxi (no vCenter) free hypervisor provided by VMWARE, license, i see in my vsphere client

Product: VMware vSphere 6 Hypervisor Licensed for 2 physical CPUs (unlimited cores per CPU)
License Key: XXXX-XXXX-XXXX-XXXXX
Expires: Never

Product Features: 
    Up to 8-way virtual SMP


When license is never expiry, the vmware also says, if we need we can buy support. other than that, the license is good to be used for any purpose. 

How does this vSphere provider not working to deploy a this infrastructure

Any help ?. is this doable to use terraform in this case or i am wasting my time.

**Comment by vancluever** [comment]
Hey @muthukumars, the Terraform vSphere provider is not supported on free ESXi due to a read-only lockdown of the API. We have a little blurb in the [provider index](https://www.terraform.io/docs/providers/vsphere/index.html) now mentioning this.

Thanks!

**Comment by muthukumars** [comment]
It is license driven , given as No cost by VMWARE. it may be a free
tool/open source by Vmware.

Do we have any work around

Muthukumar

**Comment by vancluever** [comment]
@muthukumars, sorry, there is no workaround. This provider is only usable with paid versions of vSphere.

**Comment by muthukumars** [comment]
Chris

is there any other provider who provides ? when you say provider, is it a
terminology used for this purpose by Teraform or 3rd party people who
provides this library

Muthukumar

**Comment by muthukumars** [comment]
thank you.
Muthukumar
