### ISSUE TITLE
Provide a way to set DRS affinity rules

### ISSUE THREAD

**Issue by mmb** [terraform-providers/terraform-provider-vsphere#274]
I would like to create virtual machines with Terraform and tell vSphere to keep them on different hosts.

govc has recently added support for this:

https://github.com/vmware/govmomi/pull/928

**Comment by vancluever** [comment]
Thanks for the info @mmb - super useful to know that govmomi has an example.

Cluster affinity is something we can probably touch when start the effort to add better cluster support ourselves - which is something we will be looking at soon, now that 1.0 is out!

**Comment by Matty9191** [comment]
+1 for this.

**Comment by d10sbt** [comment]
+2 for this

**Comment by seanmalloy** [comment]
+1 for this feature

**Comment by mjrider** [comment]
+4

**Comment by virtrixke** [comment]
Yes, definitly a useful feature...

**Comment by witchbutter** [comment]
+5 really need this.

**Comment by movergan** [comment]
+1 please!

**Comment by arri-cc** [comment]
Very nice

**Comment by vancluever** [comment]
Everyone - 1.5.0 is out now with all of the new override and rule resources. Check them out and if you have any problems please submit any issues you need to!

Thanks!
