### ISSUE TITLE
Potential backwards compatibility issues with vSphere 5.5

### ISSUE THREAD

**Issue by desmondrawls** [terraform-providers/terraform-provider-vsphere#286]
While working on a PR for vApp config support (#243), we noticed a few problems in acceptance tests that may be related to backwards compatibility (#258) with vSphere version 5.5.

Since vSphere 5.5 does not support customization for Linux guests, we wrote an acceptance test that clones a simple vm template with Ubuntu pre-installed and skips customization. That test fails with the following error:

```
Error applying: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: 1 error(s) occurred:

    		* vsphere_virtual_machine.vm: timeout waiting for a routeable interface
```

However, looking at the vm in vcenter while the test is running we see that it receives an IP address. This makes us wonder whether:
1. We are actually failing to create a routeable network interface.
2. The network waiter is reporting false negative because it expects vSphere 6.x-specific information.
3. Our test setup is somehow wrong.

The relevant part of the terraform template for this test is:
```
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 2048
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    name = "terraform-test.vmdk"
    size = "${data.vsphere_virtual_machine.template.disk_sizes[0]}"
  }

  disk {
    name = "terraform-test_1.vmdk"
	unit_number = 1
    size = "${data.vsphere_virtual_machine.template.disk_sizes[1]}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}
```

The other issue we noticed comes from cloning a template with vApp settings. Before attempting to deploy the vm, our test fails at [checking for perpetual diffs](https://github.com/hashicorp/terraform/blob/master/helper/resource/testing_config.go#L94-L101) with the following error:
```
After applying this step, the plan was not empty:

    		DIFF:

    		UPDATE: vsphere_virtual_machine.vm
    		  network_interface.0.bandwidth_limit:       "0" => "-1"
    		  network_interface.0.bandwidth_share_level: "" => "normal"
```
If we explicitly set a `bandwidth_limit` value in the network interface, we get an API error from vSphere:
```
error reconfiguring virtual machine: A specified parameter was not correct.
    		spec.deviceChange.device.resourceAllocation.limit
```
Some research indicated that bandwidth limit and bandwidth share level for network interfaces are new features in vSphere 6.0.

cc @rowanjacobs

**Comment by vancluever** [comment]
@desmondrawls for the first one - the waiter waits for a _routeable_ IP address - ie: one that can reach a default gateway that you have configured - if that's not happening for whatever reason, then the waiter needs to be disabled - set `wait_for_guest_net_timeout = -1`. Can you check your network configuration and make sure it is coming up with an IP address that can reach the internet? That will help us confirm if this is a compatibility issue or not.

I've confirmed that network interface resource management is not available in vSphere 5.5 - we will need to block and filter this in a fashion similar to how we are doing it for some of the disk resources.

**Comment by rowanjacobs** [comment]
Creating a new template seems to have fixed the routeable IP address issue.

**Comment by smohanrajece** [comment]
Hi Vancluever
Could you please tell me terraform compatible with vmware vsphere 6.0 UP2. Its for creating the virtual machines.
Thank you.
