### ISSUE TITLE
Resource provider for vSphere resource pool

### ISSUE THREAD

**Issue by josdotso** [terraform-providers/terraform-provider-vsphere#288]
Hello.

Today, there is a data provider for vSphere resource pool, but I didn't see a resource provider for the same.  Is this feature on the roadmap?

https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html

Thanks,
Joshua

**Comment by vancluever** [comment]
Hey @josdotso - we are indeed planning to work on this - it will be part of another part of work targeted at getting cluster management into the provider.

No ETA, but we are definitely looking at it in the next couple of months (holiday schedules and what not considering).

Thanks!

**Comment by sofixa** [comment]
@vancluever Do you have more clarity on when can this resource be added to the provider?

Cheers,
Adrian

**Comment by vancluever** [comment]
@sofixa I can't give hard dates, but now that storage clustering stuff is done with the upcoming release of 1.4.0 (being released today) our focus will be shifting to compute clustering resources, including resource pools.

Thanks!

**Comment by sofixa** [comment]
@vancluever @josdotso i think this issue can be closed seeing that the resource pool resource now exists? https://www.terraform.io/docs/providers/vsphere/r/resource_pool.html 

Adrian

**Comment by vancluever** [comment]
@sofixa indeed! Thanks for the reminder - will close this one out!
