### ISSUE TITLE
Terraform Init Error "Unknown root level key: vsphere_user"

### ISSUE THREAD

**Issue by alexholliz** [terraform-providers/terraform-provider-vsphere#293]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.11.1

### vSphere Provider Version

Running `terraform providers` gives me this output:
`Error: Unknown root level key: vsphere_user`
`Error: Unknown root level key: vsphere_password`

### Affected Resource(s)

`terraform init` 
I can't really get past this stage, so I can't say what else is causing this issue

### Terraform Configuration Files

```hcl
##terraform file

provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "Replaced for anonymity"
}

data "vsphere_datastore" "datastore" {
  name          = "sf-vmware-04"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "vds-production-data"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "centos-7-template"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name          = "it-docker-prod-01"
  datastore_id  = "${data.vsphere_datastore.datastore.id}"

  num_cpus      = 2
  memory        = 4096
  guest_id      = "other3xLinux64Guest"

  network_interface {
    network_id  = "${data.vsphere_network.network.id}"
  }

  disk {
    name        = "it-docker-prod-01"
    size        = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"


    customize {
        network_interface {
          ipv4_address  = "172.16.16.140"
          ipv4_netmask  = "24"
        }

    ipv4_gateway        = "172.16.16.1"
    dns_server_list     = ["172.16.16.16", "172.16.16.17", "172.16.16.18"]
    dns_suffix_list     = ["Replaced for anonymity.com"]

        linux_options {
          host_name     = "it-docker-prod-01"
          domain        = "Replaced for anonymity.com"
        }

    }
  }

}

##Variable file

variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}

##Secrets File
vsphere_user = "DOMAIN\\User"
vsphere_password = "Password"
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output:
https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the
debug output in the issue; just paste a link to the Gist.

### Expected Behavior

Terraform Init should have downloaded the required provider files

### Actual Behavior

Terraform Init did not download the required provider files

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Create a new terraform manifest for a new vm using the vsphere provider
2. `terraform init`

**Comment by vancluever** [comment]
@alexholliz this sounds like an issue in where you are putting your variables. While file are you placing your secrets in?

**Comment by alexholliz** [comment]
Variables are in `variables.tf` and secrets are in `secrets.tf`in the same directory as `it-docker-prod-01.tf`

**Comment by vancluever** [comment]
@alexholliz the secrets.tf file is the problem. These are essentially variable definitions and need to be in you `terraform.tfvars` file.

You can name this differently if you don't want that path specifically as well, but you will need to supply a different path to `terraform apply`:

```
  -var-file=foo          Set variables in the Terraform configuration from
                         a file. If "terraform.tfvars" or any ".auto.tfvars"
                         files are present, they will be automatically loaded.
```

Make sure you don't give it a `.tf` extension though or else Terraform will try to load and parse the file as Terraform code, giving you the error you see now.

**Comment by alexholliz** [comment]
Well I'll be a monkey's uncle, changing secrets.tf to terraform.tfvars worked just fine. Thanks @vancluever !

**Comment by vancluever** [comment]
:grinning: glad you got it worked out @alexholliz!
