### ISSUE TITLE
custom_configuration_parameters missing for 1.0.2

### ISSUE THREAD

**Issue by Veske** [terraform-providers/terraform-provider-vsphere#296]
```
Terraform v0.11.1
+ provider.vsphere v1.0.2
```

There used to be an option before the 1.x release to have a block like this:

```
custom_configuration_parameters {
    env = "dmz"
    role = "admin"
    server_service_name = "pt-tomcat"
  }
```

This was quite useful for people generating their Ansible inventory dynamically. This way you can give an identity to a VM in a simple manner.

I fail to find the same functionality for vSphere provider 1.0.2. Are there any plans to introduce this again or maybe I have just failed to find it from the documentation?

**Comment by vancluever** [comment]
Hey @Veske, these have now been moved to [`extra_config`](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#extra_config). Let me know if this fixes it for you!

**Comment by Veske** [comment]
@vancluever Sorry for the inconvenience. Completely missed that part in the documentation.
This solves my problem.

**Comment by vancluever** [comment]
Glad you figured it out @Veske!
