### ISSUE TITLE
Accessing variables from outer scope not possible

### ISSUE THREAD

**Issue by Veske** [terraform-providers/terraform-provider-vsphere#297]
**Terraform environment:**
```
Terraform v0.11.1
+ provider.vsphere v1.0.2
```

I seemed to stumble upon an issue where I am unable to access declared variables from an outer scope. This is an useful thing to be able to do because say you would like to create a certain machine with a count of > 1....  this assumes that each machine is named a bit differently. We have the convention to have a incremented number in the name of a service machine.

If I would drop the vm customization then the problem would not be there of course, but in case I do want to do it, the hostname and domain naming makes no sense because for a vm that is made with count, I see no way to increment a number in the name.

Is this a missing feature for now or am I missing something obvious?

Below is a sample which will not be accepted by current provider version.

```
resource vsphere_virtual_machine "dmz-admin" {
  name = "dmz-admin-${count.index + 1}.tlnlive.kek"
  datastore_id = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = "${data.vsphere_resource_pool.dmz-pool.id}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  count = 20
  folder = "${vsphere_folder.Dmz.path}"
  num_cpus = 1
  memory = 2048

  disk {
    name = "${data.vsphere_virtual_machine.template.name}.vmdk"
    size = "${data.vsphere_virtual_machine.template.disk_sizes[0]}"
  }

  network_interface {
    network_id = "${data.vsphere_network.dmz-network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${name}" <--- This here will not work
        domain = "${name}" <--- This here will not work
      }

      network_interface {}
    }
  }
}
```

**Comment by vancluever** [comment]
Hey @Veske, this is not a supported configuration in Terraform. You can reference a resource's own attributes using the `self` namespace, but only in provisioners. See [here](https://www.terraform.io/docs/configuration/interpolation.html#attributes-of-your-own-resource) for more information.

Thanks!

**Comment by jason-azze** [comment]
@Veske I'm doing something similar and I just ended up repeating the expression I'm using to build names and abstracting as much as I can into variables.

```
resource "vsphere_virtual_machine" "generic" {
  name             = "${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}"

...

customize {
      network_interface {}

      linux_options {
        host_name = "${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}"
        domain    = "${var.dns_domain}"
      }
```

**Comment by vancluever** [comment]
@jason-azze beat me to the punch! I was just typing that.

**Comment by Veske** [comment]
But am I using Terraform wrong then? 
Take the disk block for example:

```
disk {
    name = "my-incrementing-name-01.vmdk"
    size = "${data.vsphere_virtual_machine.template.disk_sizes[0]}"
  }
```

Say you want to create multiple copies of a scaling service, do you create a new .tf file for each one of them then? Before 1.x I never experienced this issue as there was no inner block requiring the name I put for the machine.

**Comment by Veske** [comment]
@jason-azze So count is referencable from an outer scope actually?
