### ISSUE TITLE
Deleting resource manually breaks TF

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#299]
Terraform 0.10.7
Provider:  Version 1.1.0

Reproducer:

1. run tf to clone windows vm.
1. manually Delete VM in Vsphere console.
1. run tf

Error message:
vsphere_virtual_machine.wks: Refreshing state... (ID: 422dbafe-5671-f3c6-132f-5e1ac75364e1)
Error refreshing state: 1 error(s) occurred:

* module.rismoney.vsphere_virtual_machine.wks: 1 error(s) occurred:

* module.rismoney.vsphere_virtual_machine.wks: vsphere_virtual_machine.wks: cannot locate virtual machine with UUID "422dbafe-5671-f3c6-132f-5e1ac75364e1": virtual machine with UUID "422dbafe-5671-f3c6-132f-5e1ac75364e1" not found

Expectation: TF should just recreate a new rismoney box, as actual doesn't match expected config.

Perhaps related to #271 ?

**Comment by rismoney** [comment]
Do you need additional info for this?  This one is causing a lot of usability issues for us as our pipeline cannot work around this without state mucking, as we provision and destroy often and the latter not always via TF.

**Comment by vancluever** [comment]
@rismoney, sorry for the delay. This was confirmed as being incorrect behaviour when the bug tag as added to it, and it's a relatively trivial fix, but there has just been a focus on adding safety to the virtual disk lifecycle before focusing on the other bugs. Now that that's out of the way, we will have time to focus on this and other other post-1.1 issues.

Thanks!
