### ISSUE TITLE
terraform plan fail with `err: disk.2: virtual disk "vm/vm_1.vmdk"` 

### ISSUE THREAD

**Issue by astraios** [terraform-providers/terraform-provider-vsphere#309]
### Terraform Version

`Terraform v0.11.1`

### vSphere Provider Version

`provider.vsphere v1.1.0`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
...
// VM instance
resource "vsphere_virtual_machine" "vm" {

  name = "vm"
  resource_pool_id = "${data.vsphere_resource_pool.root_rp.id}"
  datastore_id = "${data.vsphere_datastore.ds.id}"
  folder = "${var.vsphere_folder}"

  num_cpus = 2 
  memory = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id = "${data.vsphere_network.default.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  // sda
  disk {
    name             = "vm.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = false
    thin_provisioned = true
  }
  // sdb
  disk {
    name             = "vm_1.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = false
    thin_provisioned = true
    unit_number      = 1
  }
  // sdc: docker lvm thin pool
  disk {
    name             = "vm_2.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.2.size}"
    eagerly_scrub    = false
    thin_provisioned = true
    unit_number      = 2
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }


  // Extra parameters
  cpu_hot_add_enabled    = true
  cpu_hot_remove_enabled = true
  memory_hot_add_enabled = true
  enable_disk_uuid       = true

}
```

### Debug Output

https://gist.github.com/notuscloud/c8264ac26a8f70bc1ba502667fc8d24f

I truncated the output to show only the relevant part.

### Expected Behavior

As I did no modification, the second terraform plan should show me no changes.

### Actual Behavior

When terraform refreshes it's resources, it put the disk 1 in the place of disk 2 and detect a change if the two disks are not the same size.

The `terraform plan` fails with this message:

```
Error: Error running plan: 1 error(s) occurred:

2017/12/11 11:15:40 [ERROR] root: eval: *terraform.EvalDiff, err: disk.2: virtual disk "vm/vm_1.vmdk": virtual disks cannot be shrunk (old: 50 new: 16)
2017/12/11 11:15:40 [ERROR] root: eval: *terraform.EvalSequence, err: disk.2: virtual disk "vm/vm_1.vmdk": virtual disks cannot be shrunk (old: 50 new: 16)
* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: disk.2: virtual disk "vm/vm_1.vmdk": virtual disks cannot be shrunk (old: 50 new: 16)
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by notuscloud** [comment]
Hi, 

Any news on the subject? I'm not skilled enough at the moment to propose a fix. 
Unfortunately, this version of the vSphere provider is not usable...

Best regards

**Comment by pryorda** [comment]
This issue is mainly driven by the order of the disks from my perspective.

**Comment by bill-rich** [comment]
Hey @astraios! There have been a lot of changes to the disk management in virtual machines since this issue was opened. I'm going to close the issue for now, but let me know if you're still running into problems and we can either reopen this issue or open a new one with fresh information.
