### ISSUE TITLE
VM cannot boot off template

### ISSUE THREAD

**Issue by ntrvic** [terraform-providers/terraform-provider-vsphere#323]
Hello,

I have recently upgraded from 0.4 to 1.1. I am having trouble cloning off of a template. The system fails to boot with a dracut error. I build the template using packer. I am using Centos7 and `autopart` for my partitions. My terraform config looks roughly like:

```
resource "vsphere_virtual_machine" "vm" {
  name          = "${var.name}"
  resource_pool_id = "${data.vsphere_resource_pool.target-resource-pool.id}"
  num_cpus          = "${var.cpu}"
  memory        = "${var.memory}"
  datastore_id = "${data.vsphere_datastore.datastore.id}"
  guest_id = "centos64Guest"

  network_interface {
     network_id = "${data.vsphere_network.network.id}"
     adapter_type = "vmxnet3"
  }

  disk {
    name = "prov-test001.vmdk"
    size = "${var.disk_size}"
  }


  clone {
    template_uuid = "${data.vsphere_virtual_machine.example_template.id}"

    customize {
      linux_options {
          host_name = "prov-test001"
        domain    = "internal.net"
      }

    network_interface {
      ipv4_address       = "${var.ipv4}"
      ipv4_netmask = "24"
    }
...
```

the error I am seeing is

![screen shot 2017-12-14 at 2 33 44 pm](https://user-images.githubusercontent.com/5298940/34012339-5f31477c-e0e1-11e7-8256-58967ee78117.png)(same for `autopart`)

I suspect something is up with partition templating, but I am not sure. Looks like vsphere-terraform reconfiguration bug. Please advise. 

Thanks,
Victor

Terraform v0.11.0
+ provider.vsphere v1.1.0

Update:
Was able to start the system up in rescue mode. Investigating but still an issue.

**Comment by vancluever** [comment]
Hey @ntrvic, sorry you are having trouble. Have you by any chance looked in the `rdsosreport.txt` file after it goes to emergency boot to see what it says?

**Comment by vancluever** [comment]
Also, I noticed that you don't have `scsi_type` set to the type discovered from the template - you might want to try that. Refer to the [full cloning example](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cloning-and-customization-example) for info. It might be that the initrd was written with just the SCSI driver that was needed to load the specific controller and not much else.

Let us know!

**Comment by ntrvic** [comment]
interesting, the default is lsilogical, but when I set it explicitly, that did the trick. Thanks!
