### ISSUE TITLE
Query on SCSI Controller

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#325]
### Terraform Version
0.10.7 

### vSphere Provider Version
1.1.1
- vsphere_virtual_machine`

more of a query than an issue . I'd like to know if it's possible to create disks + attach them to a specific scsi_controller . 

By enabling the scsi_controller_count - i can add more scsi controllers but what i want to do is - 

disk1 to be attached to scsi_controller 1 
disk2 to be attached to scsi_controller 1

disk 3 to be attached to scsi_controller 2
disk 4 to be attached to scsi_controller 2  and so on... 

i don't see an option in the disk resource to do this .. only a unit number ...
Thoughts ?

**Comment by vancluever** [comment]
Hey @surajsub, this is indeed possible, you just need to make sure you adjust the `scsi_controller_count` to the number of controllers that you need and adjust the `unit_number` of the `disk` to the specific address space for the controller that you want. Each controller has 15 slots, so `unit_number` 15 to 29 will work for the second controller, 30 to 44 will be the third controller, and 45 to 59 will be the last controller.

A good example can be found in [this](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L2384) test fixture.

Thanks!

**Comment by surajsub** [comment]
Awesome !! - that worked - Thanks
