### ISSUE TITLE
resource_pool_id without DRS

### ISSUE THREAD

**Issue by ctramnitz** [terraform-providers/terraform-provider-vsphere#326]
When DRS is not enabled (i.e. due to licensing: Essentials, Essentials Plus, Standard) no resource pools can be created. But resource_pool_id is a mandatory parameter.

I've got mine by importing a VM and looking at the state file, but I think resource_pool_id should not be mandatory when there are cases where there is none (visible). Even with govc ls I could not find a pool in my installation.

**Comment by jason-azze** [comment]
Hi @ctramnitz.  #262 and #314 have some background/discussion of this topic.

The "Specifying the default resource pool for a cluster" section of the doc here https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html might be improved by mentioning the license limitations or by better describing the use case. It's not always clear to new users that not having a resource pool actually means you only have the default resource pool, which is invisible in the vSphere Client GUI.

**Comment by ctramnitz** [comment]
Thanks and sorry for the duplicate, I was only searching for license related issues in already closed issues. #314 was most helpful, this is what I implemented now.
