### ISSUE TITLE
Windows VMs not having their SIDs re-generated

### ISSUE THREAD

**Issue by vancluever** [terraform-providers/terraform-provider-vsphere#336]
We have a report in #335 that Windows VMs are not having their SIDs re-generated on clones.

This needs to be investigated - this should be something that should be happening by default, if at all possible.

This was empirically checked when we were rolling out 1.0.0 and I thought it was functional, although it could have been a by-product of how our image was built (it was sysprepped at one point in time but I thought I booted it to take it out of sysprep so that we could test a straight up clone). Will report more on this when I have more data.

**Comment by vancluever** [comment]
Update: After re-reading #335, it appears that the VM was not necessarily customized - if that's the case, then this is working as intended because we do not customize VMs where customization is not requested on, hence sysprep will not run.

Just to ensure all context is supplied for anyone else reading this issue.

**Comment by vancluever** [comment]
@saptaji also, do you know exactly why your 2K8 machine was not correctly customized? Did Terraform kick back an error or was it an error post-deploy?

**Comment by saptaji** [comment]
@vancluever 
PS D:\> terraform version
Terraform v0.11.1
+ provider.vsphere v1.1.1

This is the error message:
Error: Error applying plan:

1 error(s) occurred:

* module.createVMFromTemplate.vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm:
Virtual machine customization failed on "/vm/TSTWIN2K8_SB":

timeout waiting for customization to complete

-----------------------------
The network interface was not set properly so it couldn't communicate with the VM.

-----------------------------
This is the clone configuration section:

clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      timeout = 20

      windows_options {
        computer_name     = "${var.VMName}"
        admin_password    = "${var.windows_admin_password}"
        workgroup         = "${var.windows_workgroup}"
        full_name         = "${var.windows_full_name}"        
        organization_name = "${var.windows_organization_name}"
        product_key       = "${lookup(var.windows_product_keys, var.VMTemplate)}"
        time_zone         = "${var.VMTimeZone}"
      }

      network_interface {
        ipv4_address    = "${var.VMIPAddress}"
        ipv4_netmask    = "${var.VMNetmask}"
        dns_server_list = "${var.VMDNSServerList}"
        dns_domain      = "${lookup(var.VMDomains, var.Environment)}"
      }

      ipv4_gateway    = "${lookup(var.VMGateways, var.Environment)}"      
    }
  }  

--------------------------
As I mentioned in the other post. This also happens when I build the VM using PowerCLI. Only works when using GUI. So it works for win2012 but not win2008.
I don't think is NOT worth it to try to fix this problem unless VMWare fix their problem first.

**Comment by rismoney** [comment]
what i recall seeing w/ 2008, if my memory serves me - is that sysprep was actually working/delayed on a startup but you didn't know it.  You would think it was done, and thereby reboot it, but it would not actually do the work. sometimes it could take 10 minutes after vsphere said it did to actually customize.

Now I do a custom solution w/ powercli and tf, involving inspecting guestcust.log to guarantee it always works, not based on what vsphere reports on events but rather w/ the actual guest activity.

**Comment by vancluever** [comment]
Hey all, so I did a test with TF of creating two VMs off of the same template with customization on Windows Server 2016. Looks like the SIDs are being re-generated properly.

This is from the first server:
![terraform-test0](https://user-images.githubusercontent.com/10704423/34804269-8e5d2984-f62c-11e7-9427-48baa9797bba.png)

And from the second:
![terraform-test1](https://user-images.githubusercontent.com/10704423/34804274-92fc510e-f62c-11e7-98e7-aea76ba8df46.png)

Based off of this and the information mentioned in the issue already regarding the lack of customization and the mentioned workarounds, I don't think there's much TF can do here as established. As such, I'm closing this issue - this is something that VMware will have to look at in their 2K8 customziation if they so deem it worthwhile.

Thanks!
