### ISSUE TITLE
Terraform Fails on 1TB vm creation

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#345]
TF version - 0.10.7
Vsphere provider - 1.1.

More of question rather than an issue. I'm trying to provision a vm with a 1024 GB memory . However i get a failure with this message - A specified parameter was not correct - configSpec.memoryMB

partial snippet of my tf file
===========

variable "name" {
	description = "Name of the Virtual Machine"
}

variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}

variable "vcpu" {
	description = "Number of Virtual CPU for the Virtual Machine"
	default = 1
}

variable "memory" {
	description = "Memory for Virtual Machine in GB"
	
}
################## Resources ###############################

#
# Create VM with single vnic on a network label by cloning 
#
resource "vsphere_virtual_machine" "vm_1" {
  name   = "${var.name}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus   = "${var.vcpu}"
  memory = "${var.memory*1024}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
      network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    name = "${var.name}.vmdk"
    size = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  
  disk {
  	## THis is to extend the root vg - sdb - Set the size to 112
  	name = "${var.name}.1.vmdk"
    size = 112
    unit_number = 1
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    
	}
  
  disk {
  ## This will be sdc
  	name = "${var.name}.2.vmdk"
    size = "${var.data_disk_size}"
    unit_number = 2
    datastore_id = "${data.vsphere_datastore.datastore1.id}"
    disk_mode = "independent_persistent"
	}
    
 disk {
 	## This will be sdd
  	name = "${var.name}.3.vmdk"
    size = "${var.log_disk_size}"
    unit_number = 3
    datastore_id = "${data.vsphere_datastore.datastore1.id}"
    disk_mode = "independent_persistent"
	}
    
 disk {
 	## This will be sde
  	name = "${var.name}.4.vmdk"
    size = "${var.shared_disk_size}"
    unit_number = 4
    datastore_id = "${data.vsphere_datastore.datastore1.id}"
    disk_mode = "independent_persistent"
	}

**Comment by vancluever** [comment]
Hey @surajsub, the "specified parameter is incorrect" message comes from vSphere. Have you tried to create this in the console? Given the large amount of memory, I'd imagine there's the possibly that it's just not necessarily possible on your cluster.

**Comment by surajsub** [comment]
@vancluever  - thanks for responding - the template was incompatible -updated it and it went through fine - Thanks for responding and appreciate the patience and the response.

**Comment by vancluever** [comment]
Glad you got it worked out @surajsub!
