### ISSUE TITLE
Enhancement request - NSX provisioning

### ISSUE THREAD

**Issue by Matty9191** [terraform-providers/terraform-provider-vsphere#347]
We utilize VMware's NSX product which provides the ability to create software router, switches and load-balancers. It would be incredibly useful if you could utilize Terraform to provision each of these resources along with your virtual machines. Just having the ability to modify an edge device load-balancer (add and remove VMs to a pool) would be super useful for zero downtime deployments.

**Comment by vancluever** [comment]
Hey @Matty9191,

This is actually being implemented in a separate provider. I can't share specifics right now, but expect more details to be announced probably sometime in the spring.

In the meantime - you should be able to load your opaque networks in with the [`vsphere_newtork`](https://www.terraform.io/docs/providers/vsphere/d/network.html) data source.

Thanks!

**Comment by dandunckelman** [comment]
Secrets don't make friends 😉

**Comment by gberche-orange** [comment]
I see the nsxt provider code has [support for lb_pool](https://github.com/terraform-providers/terraform-provider-nsxt/blob/master/website/docs/r/lb_pool.html.markdown) but I could not yet find the related documentation on the provider official website at https://www.terraform.io/docs/providers/nsxt/index.html
