### ISSUE TITLE
vsphere_virtual_machine moid attribute desirable

### ISSUE THREAD

**Issue by charandas** [terraform-providers/terraform-provider-vsphere#348]
Hi there,

This is a feature request for re-exposing the `moid` for the resource `vsphere_virtual_machine`. A big refactor must have happened in separating this out of the main terraform repo sometime back, which has effectively removed the attribute.

### References

As this [PR](https://github.com/hashicorp/terraform/pull/14793) shows, it was once added. But the current version v1.2.0 does not expose it, only UUIDs of the vm are exposed as far as guids.

This nsx provider(https://github.com/sky-uk/terraform-provider-nsx/blob/master/resource_security_tag_attachment.go#L54) depends on that, and I very much would like to not use old terraform version.

### What I tried as a workaround (and failed)

I tried using a `data.external` with some script like:
```
# ./helpers/get-vsphere-vm-moid/get-vm-moid.sh"
#!/bin/bash

set -e

vsphere_dc_name=$1
vm_guest_name=`jq -r '.vm_guest_name'`
vm_moid=$(/usr/local/bin/govc ls -i "/${vsphere_dc_name}/vm/${vm_guest_name}" | sed -e 's/^VirtualMachine://')

jq -n --arg vm_moid $vm_moid '{"value": $vm_moid}'
```

But I cannot splat on the result object due to a known terraform [bug](https://github.com/hashicorp/terraform/issues/17048#issuecomment-357038473).

**Comment by charandas** [comment]
@vancluever what worked for me after some more tinkering is this:

```
"nsx_security_tag_attachment": {
         "client_vm": {
            "count": "${local.clientCount}",
            "moid": "${lookup(data.external.client_vm_moid.*.result[count.index], \"value\")}",
```

Coupled with something like this:
```
"client_vm_moid": {
    "count": "${local.clientCount}",
    "depends_on": [
        "vsphere_virtual_machine.client_vm"
    ],
    "program": [
        "bash",
        "./helpers/get-vsphere-vm-moid/get-vm-moid.sh",
        "name-of-the-dc"
    ],
    "query": {
        "vm_guest_name": "${element(local.clientHosts, count.index)}"
    }
  },
```

The combination of `lookup` with `[]` (another sugar over `element`) seems to get me the nested value in the map. Would be nice to just be able to get it from the resource `vsphere_virtual_machine` though.

**Comment by vancluever** [comment]
Hey @charandas, glad you have a workaround. Indeed there's no reason why we can't re-add this though, so we will re-expose it in a future minor release.

Thanks!

**Comment by benfab** [comment]
I am facing the same issue as @charandas , so it would be great to have the moid exposed ;-).

**Comment by vancluever** [comment]
Hey all, this is now done via #390 and will be in the next release.

Thanks!
