### ISSUE TITLE
vsphere provider 1.2.0 plan wants to delete and rename some disks made with 1.1.1

### ISSUE THREAD

**Issue by jason-azze** [terraform-providers/terraform-provider-vsphere#350]
### Terraform Version
```
$ terraform version
Terraform v0.11.2
+ provider.vsphere v1.2.0
```
### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "linux" {
  name             = "${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}"
...
  disk {
    name = "${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}.vmdk"
    size = "${data.vsphere_virtual_machine.source-template.disks.0.size}"
    ...
}
```

### Disk created with provider version 1.1.1
The one and only one disk attached to the VM created with 1.1.1 has this path is in the datastore:
```
[nubrgwf01-nu01] cent69-da03/cent69-da03_1.vmdk
```
### Plan output with provider 1.2.0
TF wants to rename it to meet my original disk naming spec. (Which makes sense, I guess. But how did I get here?)
```
      disk.#:                  "1" => "2"
      disk.0.name:             "cent69-da03/cent69-da03_1.vmdk" => "<deleted>"
      disk.1.attach:           "" => "false"
      disk.1.disk_mode:        "" => "persistent"
      disk.1.disk_sharing:     "" => "sharingNone"
      disk.1.eagerly_scrub:    "" => "false"
      disk.1.io_limit:         "" => "-1"
      disk.1.io_reservation:   "" => "0"
      disk.1.io_share_count:   "" => "0"
      disk.1.io_share_level:   "" => "normal"
      disk.1.keep_on_remove:   "" => "false"
      disk.1.key:              "" => "0"
      disk.1.name:             "" => "cent69-da03.vmdk"
      disk.1.size:             "" => "350"
      disk.1.thin_provisioned: "" => "true"
      disk.1.unit_number:      "" => "0"
      disk.1.write_through:    "" => "false"
```

### Expected Behavior

Terraform should leave the disk as it is (no change), or force a new resource if the change is required.

### Actual Behavior

TF is going to try to yank the OS disk out of a running VM and give it a new one. (I think. I haven't applied the plan).

### Steps to Reproduce
1. Create a VM with provider version 1.1.1 by cloning from a source with a disk name ending in `_1.vmdk`
2. Update to provider version 1.2.0.
3. Generate a new plan.

### Important Factoids
My source template is implicated somehow in this.
Another Linux VM who is a cousin of the one in question, which was provisioned on the same apply with 1.1.1 was born with a disk name that doesn't include `_1`.
```
[nubrgwf01-nu01] cent69-build22/cent69-build22.vmdk
```
The plan for this VM is as expected. No change required.

The parent template for the VM that TF wants to change used to have two disks earlier in its lifecycle, but now it has one. (I moved the boot partition onto the main OS disk so I could have a single-disk template.) The datastore directory for the template still contains the old disk file, but it's not attached:
```
cent69-dAtemplate.v5.vmdk
cent69-dAtemplate.v5_1.vmdk
```
That is, only the second disk file in that listing is connected to the template as Hard disk 1.
![cent69-da-harddisk1](https://user-images.githubusercontent.com/1788669/34949988-c90435d0-f9df-11e7-8b9b-eae251f7ca70.png)

The more I look at this, the more I wonder how I ever got a disk named cent69-dAtemplate.v5_1.vmdk using provider 1.1.1 when my disk naming specification looks like it does.
`${var.name_prefix}${format("%02d", count.index + var.name_starting_val)}.vmdk`

**Comment by jason-azze** [comment]
UPDATE:
False alarm. I applied the plan, and TF beautifully renames the disk, causing no harm to the running VM.
```
[nubrgwf01-nu01] cent69-da03/cent69-da03.vmdk
```

**Comment by rismoney** [comment]
This has become a critical issue for me.   Where we can no longer manage the infrastructure without it corrupting existing gear.  Not sure when this started, but it was this past week iirc.


```
16:50:02       disk.#:                                                    "1" => "1"
16:50:02       disk.0.attach:                                             "false" => "false"
16:50:02       disk.0.device_address:                                     "scsi:0:0" => <computed>
16:50:02       disk.0.disk_mode:                                          "persistent" => "persistent"
16:50:02       disk.0.disk_sharing:                                       "sharingNone" => "sharingNone"
16:50:02       disk.0.eagerly_scrub:                                      "false" => "false"
16:50:02       disk.0.io_limit:                                           "-1" => "-1"
16:50:02       disk.0.io_reservation:                                     "0" => "0"
16:50:02       disk.0.io_share_count:                                     "1000" => "0"
16:50:02       disk.0.io_share_level:                                     "normal" => "normal"
16:50:02       disk.0.keep_on_remove:                                     "false" => "false"
16:50:02       disk.0.key:                                                "2000" => "0"
16:50:02       disk.0.name:                                               "JGAL-NJ-OPS01/JGAL-NJ-OPS01.vmdk" => "JGAL-NJ-OPS01.vmdk"
16:50:02       disk.0.size:                                               "100" => "100"
16:50:02       disk.0.thin_provisioned:                                   "true" => "true"
16:50:02       disk.0.unit_number:                                        "0" => "0"
16:50:02       disk.0.write_through:                                      "false" => "false"
...
```

**Comment by bill-rich** [comment]
This issue is seems like it is probably stale at this point. Let me know if this is still an issue that needs addressing and I'll reopen it.
