### ISSUE TITLE
Make datastore optional on vsphere_virtual_machine

### ISSUE THREAD

**Issue by almoore** [terraform-providers/terraform-provider-vsphere#351]
This is an enhancement. 
I would like to have the datastore argument for a vsphere_virtual_machine resource be optional.
At my organization we use a datastore cluster the does load balancing and migration of resources and running terraform apply on a VM or a group of VMs in the plan will put them back on the datastore that is hard coded in the terraform plan. That will cause failures at times and can even fill up the datastores on large jobs. 
It would also be fine to specify a datastore cluster. Datastore clusters are referred to as storage pods in the vSphere API. 

### Terraform Version
- ` v0.11.1`

### Vsphere Provider Version
- `provider.vsphere v1.1.1`

### Affected Resource(s)
resources:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
variable "name" {}
variable "count" {}
variable "vcpu" {}
variable "memory" {}
variable "admin_username" {}
variable "admin_password" {}
variable "cluster" {}
variable "datacenter" {}
variable "datastore" {}
variable "template" {}

variable "domain" {}

variable "dns_suffixes" {
  default = [""]
}

variable "time_zone" {
  default = "America/Denver"
}

// These dns/nameserer defaults are for the dev gp2 env
variable "nameserver" {}

variable "dns_servers" {
  default = []
}

variable "network_ipv4_gateway" {
  default = ""
}

variable "ipv4_prefix_length" {
  default = 22
}

variable "offset" {
  default = 0
}

variable "environment" {
  default = 0
}


data "vsphere_datacenter" "dc" {
  name = "${var.datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.cluster}/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "net" {
  name          = "${element(data.external.ip_addr.*.result.label,0)}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "instance" {
  count    = "${var.count}"
  name     = "${var.name}-${count.index + 1 + var.offset}"
  num_cpus = "${var.vcpu}"
  memory   = "${var.memory}"
  guest_id = "ubuntu64Guest"

  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.name}-${count.index + 1  + var.offset}"
        domain    = "${var.domain}"
        time_zone = "${var.time_zone}"
      }

      network_interface {
        ipv4_address = "${element(data.external.ip_addr.*.result.ipv4_address, count.index)}"
        ipv4_netmask = "${var.ipv4_prefix_length}"
      }

      ipv4_gateway    = "${var.network_ipv4_gateway != "" ? var.network_ipv4_gateway : element(data.external.ip_addr.*.result.gateway,count.index)}"
      dns_server_list = ["${var.nameserver}"]
      dns_suffix_list = ["${var.dns_suffixes}"]
    }
  }

  network_interface {
    network_id = "${data.vsphere_network.net.id}"
  }

  disk {
    name             = "${var.name}-${count.index + 1 + var.offset}.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

}

output "hostnames" {
  depends_on = ["vsphere_virtual_machine.instance"]
  value      = "${list(vsphere_virtual_machine.instance.*.name)}"
}
```

### Important Factoids

Datastore clusters are referred to as storage pods in the vSphere API. 
[REF](https://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.vsphere.resmgmt.doc%2FGUID-598DF695-107E-406B-9C95-0AF961FC227A.html)

**Comment by jason-azze** [comment]
@almoore This goes all the way back to #2 . I'd like to +1 this enhancement request. I hadn't thought of the fact that VMs will be migrated back to the datastore that they were born on from some other datastore in the cluster on every subsequent TF run. That could, indeed, be a nasty surprise.

**Comment by vancluever** [comment]
Hey @almoore and @jason-azze, datastore cluster support will be coming in the next few months, however either a datastore or datastore cluster will _always_ be required for creating a virtual machine. Until said support is implemented, we can't reasonably change the top-level `datastore_id` to an optional parameter as it adds a level of ambiguity to the resource's functionality that we have been making efforts to move away from in the project as a whole.

Best thing I can recommend for now is to use the following in your `ignore_changes` block on a resource:

```
lifecycle {
  ignore_changes = [
    "datastore_id",
    "disk",
  ]
}
```

That should keep any changes coming from `datastore_id` and `disk` (where the datastore ID will propagate to) from triggering a diff.

Thanks!

**Comment by almoore** [comment]
@vancluever Can you add that tip to the docs as well? It would have helped with some other issues as well.

**Comment by soumyapanigrahi-k8s** [comment]
@vancluever is it possible to get to get the list and size(available/consumed)of data stores that are part of a resource-pool so creation of VM's can be automated without having to manually enter the data-store names.

**Comment by shearn89** [comment]
Hi - a question on this: at the moment if I create a VM with a disk attached to a datastore cluster, vSphere assigns the disk to a particular datastore within that cluster. Then, terraform constantly tries to migrate the disk.

Any ideas? Or do I need to raise a new issue?
