### ISSUE TITLE
Windows 2012 Deployment

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#355]
More of a question than an issue - Has anybody had success deploying 2012 using the new provider with version 1.1. 

When deploying the windows template with 1.1 version - i see the screen is waiting to choose the keyboard layout.  However using the same template with 0.4.2 of the vsphere provider seems to be working ..

Here is my template file.
====================
##################### Variables for Version 3.0.0###############################

variable "name" {
	description = "Name of the Virtual Machine"
}

variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}

variable "vcpu" {
	description = "Number of Virtual CPU for the Virtual Machine"
	default = 4
}

variable "memory" {
	description = "Memory for Virtual Machine in MBs"
	default = 128
}

variable "cluster" {
	description = "Target vSphere Cluster to host the Virtual Machine"
}

variable "network_label" {
	description = "vSphere Port Group or Network label for Virtual Machine's vNIC" 
}

variable "ipv4_address" {
	description = "IPv4 address for vNIC configuration"
}

variable "ipv4_gateway" {
	description = "IPv4 gateway for vNIC configuration"
}

variable "ipv4_prefix_length" {
	description = "IPv4 Prefix length for vNIC configuration"
}

variable "storage" {
	description = "Data store or storage cluster name for target VMs disks"
}

variable "vm_template" {
	description = "Source VM or Template label for cloning"
}

variable "ssh_user" {
	description = "User to login to the vm"
}

variable "ssh_user_password" {
	description = "Password to login to the vm"
}

variable "allow_selfsigned_cert" {
    description = "Communication with vsphere server with self signed certificate"
    default = true
}

variable "dns_suffixes" {
  description = "Name resolution suffixes for the virtual network adapter"

}

variable "user_public_key" {
description = "User Key to login to the vm"
}

        
############### Optinal settings in provider ##########
provider "vsphere" {
    version = "~> 1.1"
    allow_unverified_ssl = "${var.allow_selfsigned_cert}"
}
 
data "vsphere_datacenter" "datacenter" {
  name = "${var.datacenter}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vm_template}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.storage}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.cluster}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "network" {
  name          = "${var.network_label}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

################## Resources ###############################

#
# Create VM with single vnic on a network label by cloning 
#
resource "vsphere_virtual_machine" "vm_1" {
  name   = "${var.name}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus   = "${var.vcpu}"
  memory = "${var.memory*1024}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
      network_id = "${data.vsphere_network.network.id}"
  }
  
 

  disk {
    name = "${var.name}.vmdk"
    size = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  
  disk {
  	## 
  	name = "${var.name}.1.vmdk"
    size = 48
    unit_number = 1
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    
	}
  
  
    
        
        
      # Specify the ssh connection for windows
  connection {
  	type = "ssh"
    user        = "Administrator"
    password    = "${var.ssh_user_password}" 
    host       =  "${var.ipv4_address}"
    
  }   
 
  
    
# 

    
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
    
      timeout = "120"
    
      windows_options
      {
        computer_name = "${var.name}"
        admin_password = "${var.ssh_user_password}"

      }
    

      network_interface {
        ipv4_address = "${var.ipv4_address}"
        ipv4_netmask = "${var.ipv4_prefix_length}"
      }

       ipv4_gateway = "${var.ipv4_gateway}"
      
      
      
      
      
      
      dns_server_list = ["mydnsserverlist"] *** ignore this
      dns_suffix_list     = ["dnssuffix_list"] *** ignore this 
    
    }
    
   
  }
}

output "ipv4_address" {
  value = "${var.ipv4_address}"
}
output "disk_name" {
  value = "${vsphere_virtual_machine.vm_1.disk.name}"
}

**Comment by surajsub** [comment]
Issue has been resolved - was missing this line in the template - 
scsi_type = “${data.vsphere_virtual_machine.template.scsi_type}” - Stupid me :-)

**Comment by vancluever** [comment]
Glad you worked it out @surajsub!

PS: When pasting your config, you can enclose the text in  "```" to ensure it all comes in preformatted. You might want to see https://guides.github.com/features/mastering-markdown/ for more details.

This will ensure your configs get posted correctly formatted, like this:

```
variable "name" {
  description = "Name of the Virtual Machine"
}

variable "datacenter" {
  description = "Target vSphere datacenter for Virtual Machine creation"
}

variable "vcpu" {
  description = "Number of Virtual CPU for the Virtual Machine"
  default     = 4
}

variable "memory" {
  description = "Memory for Virtual Machine in MBs"
  default     = 128
}

variable "cluster" {
  description = "Target vSphere Cluster to host the Virtual Machine"
}

variable "network_label" {
  description = "vSphere Port Group or Network label for Virtual Machine's vNIC"
}

variable "ipv4_address" {
  description = "IPv4 address for vNIC configuration"
}

variable "ipv4_gateway" {
  description = "IPv4 gateway for vNIC configuration"
}

variable "ipv4_prefix_length" {
  description = "IPv4 Prefix length for vNIC configuration"
}

variable "storage" {
  description = "Data store or storage cluster name for target VMs disks"
}

variable "vm_template" {
  description = "Source VM or Template label for cloning"
}

variable "ssh_user" {
  description = "User to login to the vm"
}

variable "ssh_user_password" {
  description = "Password to login to the vm"
}

variable "allow_selfsigned_cert" {
  description = "Communication with vsphere server with self signed certificate"
  default     = true
}

variable "dns_suffixes" {
  description = "Name resolution suffixes for the virtual network adapter"
}

variable "user_public_key" {
  description = "User Key to login to the vm"
}

############### Optinal settings in provider ##########
provider "vsphere" {
  version              = "~> 1.1"
  allow_unverified_ssl = "${var.allow_selfsigned_cert}"
}

data "vsphere_datacenter" "datacenter" {
  name = "${var.datacenter}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vm_template}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.storage}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.cluster}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "network" {
  name          = "${var.network_label}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

################## Resources ###############################
```

Anyway, glad it worked out again!

**Comment by bab5470** [comment]
Thank you for posting the solution to this @surajsub ! This very same thing happened to me today and I was clueless why. There didn't even appear to be an option to set keyboard options in terraform and I never would have thought about the scsi_type being the cause so thank you again for taking the time to post the cause  after you figured it out. You saved me a ton of time.
