### ISSUE TITLE
Bug report - "diffs didn't match during apply" 

### ISSUE THREAD

**Issue by jason-azze** [terraform-providers/terraform-provider-vsphere#357]
While executing `terraform apply` on a plan that resulted in the forced creation of two new resources (because template UUIDs had changed)...
```
* module.linux-test.vsphere_virtual_machine.linux[1]: vsphere_virtual_machine.linux.1: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
...
* module.linux-test.vsphere_virtual_machine.linux[0]: vsphere_virtual_machine.linux.0: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.
```

### Error Details
Terraform Version: 0.11.2
provider.vsphere v1.2.0
Resource ID: vsphere_virtual_machine.linux.0
Mismatch reason: attribute mismatch: disk.1.attach
Diff one and two Gist links appear below.

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files
A called module using the vsphere provider.
```hcl
resource "vsphere_virtual_machine" "linux" {
etc. etc.
}
```
A bunch of calling modules that look similar to:
```hcl
module "linux-test" {
  source                   = "git::http://stash.mycompany.com/scm/ops/tf-modules.git//vsphere-mod-lin?ref=v1.1.14"
  vsphere_user             = "${var.vsphere_user}"
  vsphere_password         = "${var.vsphere_password}"
  vsphere_server           = "${var.vsphere_server}"

...
}
```

### Debug Output
https://gist.github.com/jason-azze/5eb94c45d0f4acfeb12b677200a1d4b5

### Expected Behavior

Resources should have been destroyed and recreated.

### Actual Behavior

Resources were destroyed and then TF emitted a "diffs didn't match during apply" error.
On a second plan and apply (with no other changes) the (re)creation of the resources succeeded.

### Steps to Reproduce

1. Call for a clone of a template with a UUID different from the one in the current state.
2. `terraform plan -var-file="devci-agents.tfvars" -out=recreate-linux-testers-again2`
3. `terraform apply "recreate-linux-testers-again2`

**Comment by danielbalagula** [comment]
Getting the same error with vsphere provider 1.3. Plan doesn't return any errors but apply returns the same as above. Happens after changing a vsphere virtual machine's hostname/ipv4 address. I get an error for the vm's disk.

**Comment by bill-rich** [comment]
There are a series of issues that are all related to the validation and matching of virtual machine subresources such as disks and network interfaces. In most cases they are related to the use of `lifecycle` to ignore certain changes, but some attributes are still being reset or marked as `computed`. 

Since this is the oldest occurrence of the issue, I'm going to close the others and track them all here. There is a considerable amount of additional information and context in the others though, so they should be referred to when making sure this is addressed.

**Comment by sofixa** [comment]
@bill-rich it seems that the bug is no longer present in 0.12 and recent provider versions (i couldn't find any commit that could have solved it on the provider side, so maybe it's in govmomi), so you can close this.

**Comment by aareet** [comment]
Thank you for reporting back to us @sofixa
