### ISSUE TITLE
Requested fixed IPv4, end up with IPv6, why?

### ISSUE THREAD

**Issue by eouti** [terraform-providers/terraform-provider-vsphere#365]
Hi there,

I want to deploy Linux VM on my vSphere.
My env is fixed IPs.
I fill my TF files, set IP, gateway, hostname and so on...
Unfortunately I end up with IPv6 VM :(

I use to run vSphere provider 0.4 and i didn't have this kind of problem.

### Terraform Version
Terraform v0.11.2
tested also with v0.10.8 (same behaviour)

### vSphere Provider Version

vSphere Provider ~> 1.2

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```
# Configure vSphere provider
provider "vsphere" {
        version = "~> 1.2"
        vsphere_server = "my_url"
        user = "user"
        password = "pass"
        allow_unverified_ssl = true
}

# Rerieve vSphere datacenter
data "vsphere_datacenter" "dc" {
  name = "MyDC" 
}

# Get the datastore
data "vsphere_datastore" "datastore" {
  name          = "DS4"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# Get the resource pool
data "vsphere_resource_pool" "pool" {
  name          = "CL4/Resources/DTA" 
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# Fetch atomic template
data "vsphere_virtual_machine" "template" {
  name          = "Templates/rhel-atomic-host"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# Get the network / VLAN
data "vsphere_network" "network" {
  name          = "vlan110" 
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

# RHEL Atomic virtual machine
resource "vsphere_virtual_machine" "rhel-atomic" {
  name             = "atomicnode1"  
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder           = "Atomics"

  num_cpus = 2  
  memory   = 1024

  guest_id = "rhel6_64Guest" 
  scsi_type = "lsilogic"

  wait_for_guest_net_timeout = 1

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
  }

  disk {
    name = "atomicnode1.vmdk"
    size = "10"
  }

  # virtual cdrom for cloud-config
  cdrom {
    datastore_id = "${data.vsphere_datastore.iso_datastore.id}"
    path         = "ISOs/cloud-config.iso"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "atomicnode1"
        domain    = "myteam.net"
      }

      network_interface {
        ipv4_address = "10.60.20.41"
        ipv4_netmask = 23
      }

      ipv4_gateway    = "10.60.20.1"
      dns_server_list = ["193.57.239.158"]
    }
  }
}
```
### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output:
https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the
debug output in the issue; just paste a link to the Gist.

### Expected Behavior

I expected my VM to be provisioned with the IPv4 I mentioned in my tf file. 

### Actual Behavior
When I connect to my vSphere, i can see the VM has an IPv6. Moreover, when i log on the VM, "ifconfig" shows me this same IPv6 error.

### Steps to Reproduce

terraform apply

### Important Factoids

I deal with static IPs, I am sure my network info (such as gateway, prefix, IP are valid)

**Comment by vancluever** [comment]
Hey @eouti, unless your template's IPv6 explicitly turned off (via sysctl values and the like), your VM will always have an IPv6 link-local address derived from your interfaces's MAC address. This is normal and not controlled by customization.

If your IPv4 address is missing, there was more than likely a problem with the customization process. You will want to check `/var/log/vmware-imc/toolsDeployPkg.txt` for more information on this, which will tell you what exactly is missing that's keeping custmoization from completing successfully.

Thanks!
