### ISSUE TITLE
HostAffinity with DRS groups

### ISSUE THREAD

**Issue by virtrixke** [terraform-providers/terraform-provider-vsphere#367]
### Terraform Version

v0.11.2

### vSphere Provider Version

v1.1

### Affected Resource(s)

- `vsphere_virtual_machine`

### Expected Behavior

Is there a way to set a virtual machine (our group of virtual machines) to a specific host group (Host Affinity)?
The idea would be to say that the virtual machine should or must run on a specific host or set of hosts.

**Comment by pryorda** [comment]
@vancluever Is anyone currently working on this. I was going to create a work ticket inside our company to possibly work on this. It wont be for awhile though.
