### ISSUE TITLE
Unable to find file after file upload

### ISSUE THREAD

**Issue by SurferL** [terraform-providers/terraform-provider-vsphere#369]
### Terraform Version
Terraform v0.11.1

### vSphere Provider Version
1.1.0

### Affected Resource(s)
- `vsphere_virtual_machine`
- `provisioner file`
- `provisioner "remote-exec"`

### Issue

I'm having an issue where, I'm using the terraform-provider-vsphere, to stand up a VM in vsphere, and upload a python script, and then run the python script. However, on some occasions (seems random), after the file upload, it fails the following `provisioner "remote-exec"` stage as it can't find the file.

```
* stat /.../terraform/test_env/.terraform/modules/f841ba80c506702640750cd77038b2e4/scripts/deploy.py: no such file or directory
* module.inf-win7.vsphere_virtual_machine.vpshere_build_machine: 1 error(s) occurred:
```

I'm unsure how to debug this, as it is only on occasion and not all the time. So I was wondering if this could be a timing issue, and I could add a wait in between the file upload and remote-exec call?

Any ideas?

### Terraform Configuration Files

```hcl
provider "vsphere" {
	version= "1.1.0"
	vsphere_server= "${var.vsphere_vcenter}"
	user = "${var.vsphere_user}"
	password = "${var.vsphere_password}"
	allow_unverified_ssl= true
}
...
# Create virtual machine and provision deployment
resource "vsphere_virtual_machine" "vpshere_build_machine" {
	name = "${var.vm_name}"
	folder = "${var.vm_folder}"
	
        ...

	# Upload deploy script
	provisioner "file" {
		connection {
			type	= "${var.connection_type}"
			insecure = true
			user	= "${var.user}"
			password = "${var.password}"
		}

		source = "${path.module}/scripts/deploy.py"
		destination = "${var.working_dir}/deploy.py"
	}

	# Run deploy script on remote machine
	provisioner "remote-exec" {
		connection {
			type	= "${var.connection_type}"
			insecure = true
			user	= "${var.user}"
			password = "${var.password}"
		}

		inline = [
			"python ${var.working_dir}/deploy.py"
		]
	}
}
```

**Comment by vancluever** [comment]
Hey @SurferL, provisioners are more the responsibility of [Terraform Core](https://github.com/hashicorp/terraform) and not the providers.

If you can open up an issue against that repo that would be great.

PS: The error message you have pasted indicates that the file is attempting to be located on the local filesystem, not the remote one (indicative by the `.terraform/modules` part of the path). You might want to review the logs, and your module, to make sure the deploy script is properly contained in the module.

Thanks!

**Comment by SurferL** [comment]
Sure - thanks for the response! :)
