### ISSUE TITLE
Packer/Terraform Reprovisioning Golden VM

### ISSUE THREAD

**Issue by jeremycornett** [terraform-providers/terraform-provider-vsphere#373]
Terraform Version: 0.11.2
vSphere Provider Version: 1.2.0
Affected Resources: vsphere_virtual_machine

I think this is operating as designed, but it seems less than ideal to me. I want to get your feedback to see if my expectations are valid or off-base.

I setup Packer to provision a VM to my vSphere instance. I set this Packer process to run once a week because it's helpful to catch anything that might have changed due to package updates that would break the unattended installation. Packer provisions the VM to a known location, overwriting the VM every time it runs. I then use terraform to provision from this "golden packer" VM from the known location. After a week passes, Packer runs again to reprovision the VM. No problem, until I run Terraform again. Since the template_uuid of the "golden packer" VM has changed, Terraform wants to destroy and recreate that VM. That is not the desired behavior. 

Is my only option to give a unique name to my "golden packer" VM and ensure I keep every version of it that I've referenced during my Terraform runs? Surely AWS doesn't work like this?

**Comment by rismoney** [comment]
https://github.com/terraform-providers/terraform-provider-vsphere/issues/353
I had the same issue.  I resolved it by avoiding using the data source to determine the template uuid and instead hard code the uuid for my guests.  Then if I want to update the guests, I update the uuid against the new template uuid when I'm ready for upgrading.

To help, i added a packer script to put the uuid in an annotation for easy discovery.

**Comment by bpoland** [comment]
Maybe you could use ignore_changes in the lifecycle block to avoid recreating the VM?

**Comment by rismoney** [comment]
if it's within a module, ignore_changes becomes clunky if you want to do it on a case by case basis as there may be other items to ignore at a global module level.

**Comment by bpoland** [comment]
Ah, true.

**Comment by vancluever** [comment]
Hey all, @rismoney's mention of #353 and the methods discussed there to do this are the correct method. There is a lot more detail as to the relationship between the resource and the data source and our rationale behind the structure of providing template UUIDs there.

Thanks!
