### ISSUE TITLE
Terraform - Error : ServerFaultCode: unexpected element tag "capacityInBytes"

### ISSUE THREAD

**Issue by avinash-fissionhq** [terraform-providers/terraform-provider-vsphere#379]
Unable to create windows server 2012 VM in esxi 5.1. Below is the template. Terraform version 0.11.0
=========
main.tf
=========
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {}

data "vsphere_datastore" "datastore" {
  name          = "${var.datastore_name}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus         = 2
  memory           = 4096
  cpu_hot_add_enabled    = true
  memory_hot_add_enabled = true
  guest_id 				 = "windows7Server64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0.vmdk"
    size  = "20"
	thin_provisioned = true
  }
}

While running "terrafrom apply"

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: error creating virtual machine: ServerFaultCode:
Unexpected element tag "capacityInBytes" seen

while parsing serialized DataObject of type vim.vm.device.VirtualDisk
at line 2, column 1497

while parsing property "device" of static type VirtualDevice

while parsing serialized DataObject of type vim.vm.device.VirtualDeviceSpec
at line 2, column 1301

while parsing property "deviceChange" of static type ArrayOfVirtualDeviceConfigS
pec

while parsing serialized DataObject of type vim.vm.ConfigSpec
at line 2, column 157

while parsing call information for method CreateVM_Task
at line 2, column 83

while parsing SOAP body
at line 2, column 77

while parsing SOAP envelope
at line 2, column 0

while parsing HTTP request for method createVm
on object of type vim.Folder
at line 1, column 0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by vancluever** [comment]
Hey @avinash-fissionhq, vSphere versions below 5.5 are not supported by this provider. Sorry!
