### ISSUE TITLE
resolv.conf search is not set if dns_suffix_list contains multiple entries

### ISSUE THREAD

**Issue by matthewvalimaki** [terraform-providers/terraform-provider-vsphere#384]
### Terraform Version
```
Terraform v0.11.3
+ provider.vsphere v1.3.1
```

### vSphere Provider Version

`provider.vsphere ~> 1.3`

### Affected Resource(s)
`vsphere_virtual_machine`

### Terraform Configuration Files

```
# variables.tf
variable "dns_suffix_list" {
  type    = "list"
}
```

```
# variables.tfvars
dns_suffix_list = ["first.local", "second.local"]
```

```
# resources.tf
resource "vsphere_virtual_machine" "cms" {
  count             = "${length(var.virtual_machine_names)}"
  name              = "${lookup(var.virtual_machine_names, count.index)}"
  num_cpus          = 2
  memory            = "${var.vm_memory}"
  guest_id          = "${data.vsphere_virtual_machine.template.guest_id}"
  resource_pool_id  = "${module.wh_vsphere.resource_pool_id}"
  datastore_id      = "${module.wh_vsphere.datastore_id}"
  scsi_type         = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id  = "${module.wh_vsphere.network_id}"
  }

  disk {
    label = "${lookup(var.virtual_machine_names, count.index)}.vmdk"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${lookup(var.virtual_machine_hostnames, count.index)}"
        domain    = "${var.vm_domain}"
      }

      network_interface {
        ipv4_address = "${lookup(var.virtual_machine_ips, count.index)}"
        ipv4_netmask = 24
      }

      ipv4_gateway    = "${var.ipv4_gateway}"
      dns_server_list = "${var.dns_server_list}"
      dns_suffix_list = "${var.dns_suffix_list}"
    }
  }
```

### Expected Behavior

A new VM should be provisioned and customized with `dns_suffix_list` so that in `/etc/resolv.conf` `search` would contain all in the list. 

### Actual Behavior

A new VM is provisioned and otherwise correctly customized with the exception of `/etc/resolv.conf` not containing `search` at all. `dns_server_list ` in its entirety is in there. Furthermore `/etc/sysconfig/network-scripts/ifcfg-eth0` is correctly listing `dns_server_list` and `dns_suffix_list`.

Having multiple items in `dns_suffix_list` seems to break modifying of `/etc/resolv.conf`. This of course could be `open-vm-tools` issue as well.

### Steps to Reproduce

1. Have more than one item in `dns_suffix_list`
2. `terraform apply`
3. Observe that `/etc/resolv.conf` has no `search`

### Important Factoids

Guest OS: `CentOS Linux release 7.4.1708 (Core)`
VMWare Tools: `VMware Tools daemon, version 10.1.5.59732 (build-5055683)`

**Comment by den-is** [comment]
+1

**Comment by nickkeyzer** [comment]
I believe this is a syntax issue. NetworkManager appears to expect a list of domains with space delineation to be surrounded by quotes. Using multiple search domains in Terraform for me results in the following configuration:

`/etc/sysconfig/network-scripts/ifcfg-ens192` contains:
```
DOMAIN=sub.lab.com lab.com other.com
```

When I manually change the entry to add proper quotation as such:
```
DOMAIN="sub.lab.com lab.com other.com"
```

Then restart NetworkManager via:
`systemctl restart NetworkManager`

The resulting `/etc/resolve.conf` contains:
```
# Generated by NetworkManager
search sub.lab.com lab.com other.com
nameserver 10.1.113.10
nameserver 10.1.113.11
```

This is causing an issue for us so we're working around this by using the `remote-exec` provisioner to modify the NetworkManager config through the `nmcli` tool using this command:

`nmcli con mod ens192 ipv4.dns-search "sub.lab.com lab.com other.com"`

You'll need to adjust your connection name as needed. Of course this isn't actually a proper fix so hopefully someone can address this issue with a patch.

**Comment by nickkeyzer** [comment]
Appears to be related to `open-vm-tools` as initially suspected and the fix is inside a vCenter update:
https://github.com/vmware/open-vm-tools/issues/251

**Comment by bill-rich** [comment]
Looks like this is fixed in the latest vCenter. Thanks @nickkeyzer!
