### ISSUE TITLE
Query  on shared disk - 

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#389]
This is more of a question than an issue 

### Terraform Version
0.10.7

### vSphere Provider Version

1.1

### Affected Resource(s)
vsphere_virtual_machine

So is there  a way to provision a disk resource and make it visible as a shared disk when we provision 'n' vm's so that it can be attached during provisioning the vm resources.

**Comment by vancluever** [comment]
Hey @surajsub, you don't necessarily mean using the [`attach`](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#attach) parameter do you?

That's basically the workflow right now for attaching external disks:

* Disk gets created with `vsphere_virtual_disk`
* Disk gets attached as an eternal disk using the `attach` parameter of the `disk` sub-resource

Let me know if that helps!

**Comment by surajsub** [comment]
@vancluever  - that's right - 
Can i attach the disk post vm creation or does this have to be done during the vm create ?

**Comment by vancluever** [comment]
@surajsub I think the answer to that is two part:

* Yes, you can modify a `vsphere_virtual_machine` resource _after_ creation and add it. No problem there, and this should work as intended (just like if you added new disks to a VM after).
* In the provider's resource hierarchy, this is unfortunately, the only path right now - in the future we might be adding a `vsphere_virtual_disk_attachment` resource that will allow disks to be attached by completely different configuration - such as if you wanted to perform the attachment via a module that takes an already created virtual machine as an input, while not requiring any extra modifications to the existing virtual machine's configuration. Such a resource is a bit off though as it kind of requires some forethought as to how we will end up being able to manage those disks, as right now the resource will disconnect any disks that it does not know about in state.

**Comment by surajsub** [comment]
@vancluever  - thanks for the response - Appreciate it

**Comment by vancluever** [comment]
No problem @surajsub! Hope it helped!
