### ISSUE TITLE
vsphere_virtual_machine.vm disk.size got 0

### ISSUE THREAD

**Issue by den-is** [terraform-providers/terraform-provider-vsphere#403]
After upgrading vCenter from 5.5 to 6.5 some optional steps stopped working.
In this case terraform plan is getting template disk size 0 while it is 250G.
So as workaround I've it "harcoded" in variables.

### Terraform Version
```
❯ terraform -v
Terraform v0.11.3
+ provider.vsphere v1.3.2
MacOS High Siera
```

### Affected Resource(s)
```
❯ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.ds: Refreshing state...
data.vsphere_resource_pool.rpool: Refreshing state...
data.vsphere_network.net: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
------------------------------------------------------------------------
Error: Error running plan: 1 error(s) occurred:
* module.tftest.vsphere_virtual_machine.vm: expected disk.0.size to be at least (1), got 0
```

disk declation:
```hcl
  disk {
    label = "${var.hostname_prefix}-${format("%02d", count.index + 1)}.${var.domain}_0"
    # size  = "${var.disk_size}" 
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"  # FIXME: Disabled after 6.5
  }
```

Adding debug output of how list of disks looks like shows this, actual zero:
```hcl
template_disks = [
    {
        eagerly_scrub = 0,
        size = 0,
        thin_provisioned = 1
    }
]
```

**Comment by ntmggr** [comment]
I m still seeing this issue using plugin version 1.3.2 @vancluever

**Comment by den-is** [comment]
@ntmggr this is not pushed to 1.3.2
probably they have to release 1.3.3

**Comment by ntmggr** [comment]
Thanks @den-is

**Comment by vancluever** [comment]
Hey all, 1.3.3. will be released this week, either today or tomorrow.

Thanks!

**Comment by MrFishFinger** [comment]
i am seeing a similar issue with vSphere 6.7 and plugin version 1.6.0.
is this a known issue with 6.7?

**Comment by MrFishFinger** [comment]
ahh, i worked-around this issue on 6.7 by ensuring my template was at VM-HardwareVersion-13 with SATA disks (the previous template was VM-HardwareVersion-14 with an IDE disk)
