### ISSUE TITLE
vsphere_virtual_machine.vm: error reconfiguring virtual machine: A general system error occurred: Cannot perform this operation, please contact support

### ISSUE THREAD

**Issue by lnomine** [terraform-providers/terraform-provider-vsphere#406]
Hi there,

### Terraform Version

Terraform v0.11.3

### vSphere Provider Version

1.3.2

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```variable "guestid" { type = "string" }
variable "user" { type = "string" }
variable "password" { type = "string" }
variable "vsphereserver" { type = "string" }
variable "datacenter" { type = "string" }
variable "datastore" { type = "string" }
variable "pool" { type = "string" }
variable "network" { type = "string" }
variable "template" { type = "string" }
variable "vm" { type = "string" }
variable "cpu" { type = "string" }
variable "memory" { type = "string" }
variable "disk1name" { type = "string" }
variable "disk1size" { type = "string" }
variable "disk2name" { type = "string" }
variable "disk2size" { type = "string" }
variable "uuid" { type = "string" }

provider "vsphere" {
  user           = "${var.user}"
  password       = "${var.password}"
  vsphere_server = "${var.vsphereserver}"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "${var.datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.network}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "${var.vm}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${var.cpu}"
  memory   = "${var.memory}"
  guest_id = "${var.guestid}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
  }

  disk {
    label            = "${var.disk1name}"
    size             = "${var.disk1size}"
  }

  disk {
    label            = "${var.disk2name}"
    size             = "${var.disk2size}"
    unit_number	     = 1
  }

  clone {
    template_uuid = "${var.uuid}"

    }

}

```

### Debug Output

https://gist.github.com/lnomine/4aa863c5a538f6643ce9d3e61268b2d9

### Expected Behavior

The VM should deploy successfully, just like our Dev setup.

### Actual Behavior

Error: Error applying plan:
1 error(s) occurred:
 * vsphere_virtual_machine.vm: 1 error(s) occurred:
 * vsphere_virtual_machine.vm: error reconfiguring virtual machine: error reconfiguring virtual machine: A general system error occurred: Cannot perform this operation, please contact support

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Dev: works fine, same code, vSphere 6.0.
Prod: not working, same code, vSphere 6.0.

Our Prod setup is able to launch a VM both manually or with Ansible (vmware_guest module).

Thanks by advance for your insights.

**Comment by lnomine** [comment]
I was able to isolate the problem. It occured only when the registered network in the template is the same than the one we want for a VM deployment :

* Template with "NET-dummy1" network name -> .tf file with the network "NET-dummy1" -> FAIL
* Template with "NET-dummy1" network name -> .tf file with the network "NET-dummy2" -> OK

Deploying with the same template manually or with another tool doesn't reproduce the problem. Looks like a provider/Terraform bug, IMHO.

**Comment by vancluever** [comment]
Hey @lnomine, sorry, but I'm having trouble reproducing this. I've tried cloning a VM both on the same network and also not just on the same network but with a modification of interface type (which is happening in your case based off of the logs you sent along).

At this point in time I'm not too sure what else we can do here. If the workaround is working for you, that's good, but if there is something else going on here VMware support might be able to help you. If you get any more info on this, please send a new issue in with some more detail.

Thanks!
