### ISSUE TITLE
terraform crashes when trying to create a vm from template in vmware vsphere. 

### ISSUE THREAD

**Issue by ajitesh06** [terraform-providers/terraform-provider-vsphere#407]
unable to create vm in vmware vsphere using a template, terraform crashes with a panic

### Terraform Version
- Terraform v0.10.8

### vSphere Provider Version
- v1.3.2

### Affected Resource(s)

- vsphere_virtual_machine.vm
-  vsphere_virtual_machine.vm: unexpected EOF

### Terraform Configuration Files

provider "vsphere" {
  user           = "xxx"
  password       = "xxx"
  vsphere_server = "xxx"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "datacenter"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore2"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "cluster/Resources"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "Templates/CentOS-7-Template"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test-vmware"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder = "Dev"
  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "disk0"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
    thin_provisioned = "true"
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
        }

}

### Panic Output

https://gist.github.com/ajitesh06/295b5408bb134def457d9e004d4f92d2

### Expected Behavior

centos VM should be created using the template in VMware

### Actual Behavior

centos VM is created but terraform crashes 

output :

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

panic: runtime error: invalid memory address or nil pointer dereference
2018-02-20T16:31:10.755-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf90c66]
2018-02-20T16:31:10.755-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4:
2018-02-20T16:31:10.755-0500 [DEBUG] plugin.terraform-provider-vsphere_v1.3.2_x4: goroutine 114 [running]:

### Steps to Reproduce

`terraform apply`

**Comment by vancluever** [comment]
Hey @ajitesh06, your gist 404's... can you re-upload the full crash output? Thanks!

**Comment by ajitesh06** [comment]
Hey @vancluever, sorry about the link I have changed it. Thanks

**Comment by vancluever** [comment]
Hey @ajitesh06, I think this happening due to the configuration of your CDROM device on your template. Can you mention the details of that? The error is happening due to a missing reference to the ISO's datastore.

**Comment by ajitesh06** [comment]
Hi @vancluever, I removed CDROM device from my template and that resolved the issue. I'm now able to create and destroy the VM, Thank you.
