### ISSUE TITLE
Question on setting the MTU

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#412]
### Terraform Version

0.10.7

### vSphere Provider Version
1.3

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

Question- Is there a way to set the MTU on the interface - i know the switch has a setting parameter but is it possible to set it on the vm via a tf configuration or would this need to be done post provisioning ? I need to set the MTU on  a specific interface to 9000 .

**Comment by vancluever** [comment]
Hey @surajsub, yeah this would need to be done via a provisioner or what not at the OS level after deploying. MTU on the vSphere side stops at the switch level - there's no setting for it on an individual virtual NIC.
