### ISSUE TITLE
Persistent Data Disks

### ISSUE THREAD

**Issue by deberon** [terraform-providers/terraform-provider-vsphere#428]
I was wondering if there are any best practices out there for creating a VM that has a persistent disk attached to it. Currently if I deploy a VM from a template and the template changes, the VM gets destroyed completely and recreated. I've been playing around with creating a vmdk separately and attaching it to the VM but have run into problems with where to store it, how to initialize it in the OS, etc. These are problems I can figure out, but I wanted to make sure this is the preferred way to do this before putting the effort into figuring it out. Any help would be appreciated. Thank you.

**Comment by vancluever** [comment]
Hey @deberon, here is an excerpt from [this test config](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_virtual_machine_test.go#L4095):

```hcl
resource "vsphere_virtual_disk" "disk" {
  size         = 1
  vmdk_path    = "${var.extra_vmdk_name}"
  datacenter   = "${var.datacenter}"
  datastore    = "${var.datastore}"
  type         = "thin"
  adapter_type = "lsiLogic"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus = 2
  memory   = 2048
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }

  disk {
    label        = "disk1"
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    path         = "${vsphere_virtual_disk.disk.vmdk_path}"
    disk_mode    = "independent_persistent"
    attach       = true
    unit_number  = 1
  }
}
```

Right now, unfortunately, `vsphere_virtual_disk` cannot manage folders, so you may have to create the folder to put the external VMDK in out of band. After you have created the virtual machine, you will need to use a [provisioner](https://www.terraform.io/docs/provisioners/index.html) to format the virtual disk and prepare it in the file system afterwards, or some other sort of supported method, such as using Ignition with a CoreOS OVA using vApp properties.

Thanks!
