### ISSUE TITLE
Customization failed: VM created but no custom IPv4 address is set

### ISSUE THREAD

**Issue by bartlenaerts** [terraform-providers/terraform-provider-vsphere#433]
### Terraform Version

v0.11.4

### vSphere Provider Version

v1.3.3

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  allow_unverified_ssl = true
  password = "******"
  user = "******"
  vsphere_server = "******"
}

data "vsphere_datacenter" "datacenter" {
  name = "******"
}

data "vsphere_datastore" "datastore" {
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  name = "******"
}

data "vsphere_network" "network" {
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  name = "******"
}

data "vsphere_resource_pool" "resource_pool" {
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  name = "******/Resources"
}

data "vsphere_virtual_machine" "template" {
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  name = "centos7_template"
}

resource "vsphere_virtual_machine" "terraform-test" {
  name = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.resource_pool.id}"
  datastore_id = "${data.vsphere_datastore.datastore.id}"
  folder = "Templates"

  num_cpus = "2"
  memory = "4096"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "disk0"
    size = "${data.vsphere_virtual_machine.template.disks.0.size}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    customize {
      linux_options {
        domain = "mydomain.com"
        host_name = "terraform-test"
      }
      network_interface {
        ipv4_address = "10.11.0.15"
        ipv4_netmask = 24
      }
      ipv4_gateway = "10.11.0.254"
    }
  }
}
```

### Debug Output

[https://gist.github.com/bartlenaerts/781d797f7c937e7459b7b12723b08fff](https://gist.github.com/bartlenaerts/781d797f7c937e7459b7b12723b08fff)

### Expected Behavior

Should result in creating a new VM based on the template with the IPv4 address set.

### Actual Behavior

The VM is created but the customization fails, so no new IPv4 address is set.

### Steps to Reproduce

`terraform apply`

### VMware

* vSphere: 6.5.0 Build 7801515

**Comment by sethmcurry** [comment]
@bartlenaerts, I had what looks to be the same issue when using a template built with CentOS 7 core packages.
  
I have resolved the issue by switching to a template built with the CentOS 7 base packages.  Perhaps there is a dependancy that is not met when using the core packages.  I believe that CentOS 7 core has about 100 fewer packages than base. 

If I can find the missing dependancy I will post it as it would be beneficial to be able to use a template based on the core packages.  I'm guessing it could be a perl package that is required but not present.

**Comment by bartlenaerts** [comment]
Hi @sethmcurry, you're a life saver!

I added the Perl package(s) to my Centos7 minimal template with `yum -y install perl`, and now creating a new VM with terraform from this template works like a charm!

Thank you!

**Comment by sethmcurry** [comment]
@bartlenaerts, good deal! 

Thanks for feeding back the package that you installed to get the minimal template working - that will help me out too.

**Comment by vioan** [comment]
I had the same issue and found the solution here. Thanks a lot!

**Comment by mblue01** [comment]
@bartlenaerts Installing perl worked like a charm!  Centos7 templates on VSphere 6.7 now coming up with adapter running and a DHCP address! This saved me, thank you!

**Comment by dotnetcanuck** [comment]
@bartlenaerts Over two years later, the same solution worked for Ubuntu 18.04! Thanks a lot!!
