### ISSUE TITLE
How to add or delete disk on existing VM through terraform 

### ISSUE THREAD

**Issue by sunielex** [terraform-providers/terraform-provider-vsphere#434]
# **Terraform Version**
Terraform v0.10.7

#**Terraform Configuration Files**

variable "name" {
	description = "Name of the Virtual Machine"
}

variable "datacenter" {
	description = "Target vSphere datacenter for Virtual Machine creation"
}

variable "cluster" {
	description = "Target vSphere Cluster to host the Virtual Machine"
}

variable "allow_selfsigned_cert" {
    description = "Communication with vsphere server with self signed certificate"
    default = true
}

variable "storage" {
	description = "Data store or storage cluster name for target VMs disks"
}

        
############### Optinal settings in provider ##########
provider "vsphere" {
    version = "1.1"
    allow_unverified_ssl = "${var.allow_selfsigned_cert}"
}
 
data "vsphere_datacenter" "datacenter" {
  name = "${var.datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.storage}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.cluster}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_virtual_machine" "vmname" {
  name          = "${var.name}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

################## Resources ###############################

resource "vsphere_virtual_disk" "disk_2" {
 

  
  	vmdk_path = "${var.name}.2.vmdk"
    size = 112
    datacenter = "${var.datacenter}"
    datastore = "${var.storage}"
    type         = "thin"
  

  
  
  
  
  
 }

#**Expected Behavior**
Need help how to add disk on existing VM
#**Actual Behavior**
#**Additional Context**
I am looking for solution to add and remove disk on existing VM
##References
None found.

**Comment by sunielex** [comment]
resource "vsphere_virtual_disk" "disk_2" {
  vmdk_path = "${var.name}.2.vmdk"
    size = 112
    datacenter = "${var.datacenter}"
    datastore = "${var.storage}"
    type         = "thin"
   }
This just create disk . How to attach this disk on existing VM

**Comment by surajsub** [comment]
disk 
{	attach = true
	path = "${vsphere_virtual_disk.disk_2.vmdk}"
	label = "diskshared"
	unit_number = 2
	datastore_id = "${data.vsphere_datastore.datastore.id}"
	}

You have to add this section to your template - Change it for the values that match your template.

**Comment by akhilesh0** [comment]
+1
