### ISSUE TITLE
Terraform crashes when deploying a vSphere VM

### ISSUE THREAD

**Issue by jmcd-msw** [terraform-providers/terraform-provider-vsphere#438]
### Terraform Version

2018/03/20 19:15:18 [INFO] Terraform version: 0.11.4  7878d66b386e5474102b5047722c2de2b3237278

### vSphere Provider Version

2018/03/20 19:15:18 [DEBUG] found provider "terraform-provider-vsphere_v1.3.3_x4"
2018/03/20 19:15:18 [DEBUG] found valid plugin: "vsphere", "1.3.3", "/home/developer/safe/terraform-vsphere-ubuntu/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.3.3_x4"

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_vcenter}"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name           = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name           = "${var.vsphere_datastore}"
  datacenter_id  = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name             = "${var.vsphere_cluster}"
  datacenter_id    = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name             = "${var.vsphere_port_group}"
  datacenter_id    = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name             = "${var.vsphere_vm_template}"
  datacenter_id    = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "ubuntu" {
  name             = "${var.vsphere_vm_name}"
  folder           = "${var.vsphere_vm_folder}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus         = "${var.vsphere_vcpu_number}"
  memory           = "${var.vsphere_memory_size}"
  guest_id         = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.vsphere_vm_name}"
        domain    = "macaroni.datcon.co.uk"
      }

      network_interface {
        ipv4_address = "${var.vsphere_ipv4_address}"
        ipv4_netmask = "${var.vsphere_ipv4_netmask}"
      }

      ipv4_gateway = "${var.vsphere_ipv4_gateway}"
    }
  }
}
```

### Debug Output

See https://gist.github.com/jmcd-msw/1cb7913f9537022c960e3f1837436330 for console output.

### Panic Output

See https://gist.github.com/jmcd-msw/4fb7d80561dfac86b89b0e7e2a1d6dd8 for crash.log.

### Expected Behavior

Single VM deployed successfully with full network configuration.

### Actual Behavior

Single VM created but Terraform crashed soon after VM creation and before it could be configured.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nothing obvious.  The source template for the VM is a standard Ubuntu image with VMware tools installed.

### References
Following issue looks similar but detail of crash differs.
- [GH-435](https://github.com/terraform-providers/terraform-provider-vsphere/issues/435)

**Comment by vancluever** [comment]
Hey @jmcd-msw, this should have been fixed with 1.4.0. If you can try again with that version that would be great, and if there are any new issues please open a new issue with the updated crash log.

Thanks!
