### ISSUE TITLE
vSphere customization of vm hangs

### ISSUE THREAD

**Issue by rrati** [terraform-providers/terraform-provider-vsphere#444]
### Terraform Version
Terraform v0.11.5

### vSphere Provider Version
provider.vsphere v1.3.3

### Affected Resource(s)
- vsphere_virtual_machine

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  disk {
    label = "disk1"
    size = "80"
    eagerly_scrub = "false"
    thin_provisioned = "true"
    unit_number = 1
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "terraform-test"
        domain = "cluster.local"
      }

      network_interface {}
    }

  }

  connection {
    type = "ssh"
    user = "username"
    password = "password"
    agent = "false"
  }

  provisioner "file" {
    source = "~/.ssh/id_rsa.pub"
    destination = "~/id_rsa.pub"
  }

  provisioner "remote-exec" {
    inline = [
      "mkdir ~/.ssh", 
      "chmod 755 ~/.ssh",
      "cat ~/id_rsa.pub >> ~/.ssh/authorized_keys",
      "chmod 600 ~/.ssh/authorized_keys",
      "rm -f ~/id_rsa.pub",
      "sudo reboot",
    ]
  }
}

### Expected Behavior

VM should start up in vSphere and be customized with the hostname/domain specified

### Actual Behavior

VM startup hangs, continually waiting for the VM to come up.  Similar behavior to when the networking information is correct.

### Steps to Reproduce
1. `terraform apply`

If the customize stanza is removed, the instance comes up just fine so it isn't a problem with the template.   The relevant information from plan:

  boot_retry_delay:                                 "" => "10000"
  change_version:                                   "" => "<computed>"
  clone.#:                                          "" => "1"
  clone.0.customize.#:                              "" => "1"
  clone.0.customize.0.linux_options.#:              "" => "1"
  clone.0.customize.0.linux_options.0.domain:       "" => "cluster.local"
  clone.0.customize.0.linux_options.0.host_name:    "" => "terraform-test"
  clone.0.customize.0.linux_options.0.hw_clock_utc: "" => "true"
  clone.0.customize.0.network_interface.#:          "" => "1"
  clone.0.customize.0.timeout:                      "" => "10"
...
  network_interface.#:                              "" => "1"
  network_interface.0.adapter_type:                 "" => "vmxnet3"
  network_interface.0.bandwidth_limit:              "" => "-1"
  network_interface.0.bandwidth_reservation:        "" => "0"
  network_interface.0.bandwidth_share_count:        "" => "<computed>"
  network_interface.0.bandwidth_share_level:        "" => "normal"
  network_interface.0.device_address:               "" => "<computed>"
  network_interface.0.key:                          "" => "<computed>"
  network_interface.0.mac_address:                  "" => "<computed>"

The instructions say to use an empty network_interface in customize for dhcp, and if network_interface is removed then vSphere complains that the customization doesn't have the same number of network interfaces.

**Comment by rrati** [comment]
This may be caused by issues with the vSphere server and customizations.  It seems the vSphere server I have to test against has issues doing customization even outside of terraform.

**Comment by rrati** [comment]
Looks like the root cause of this is actually a bug with vSphere/vmware-tools.  We've contacted VMWare and they think it's a bug.

**Comment by bill-rich** [comment]
Thank you for the followup @rrati! Do you happen have any information on the bug you're running into? I'd be interested to see if there is a failure case we could handle better. 

On the question about an empty `network_interface` for DHCP, you've got it right in the config you posted. Leaving it as follows will use DHCP:

```
customize {
 ...
  network_interface {}
}
```

If you want a static IP, the configuration would be as follows:
```
customize {
 ...
  network_interface {
    ipv4_address = "${var.ipv4_address}"
    ipv4_netmask = "${var.ipv4_netmask}
  }
  ipv4_gateway = "${var.ipv4_gateway}"
  }
}
```

**Comment by rrati** [comment]
@bill-rich Not yet.  We are still submitting the information to VMWare, but they likely won't have any kind of a public bug report that can be accessed.  I'll see if I can get a copy of the data we send to VMWare though.

**Comment by bill-rich** [comment]
@rrati That would be great if it doesn't end up being too much trouble. Thank you. I'll get this issue closed for now since it seems to be a VMware bug.

**Comment by bill-rich** [comment]
@rrati If the information can be posted here so we can keep track of it in the issue, that would be great. If the original info contains sensitive information, just a summary or steps to be able to replicate in another environment would be really helpful too.

**Comment by thiagoalves** [comment]
I am facing the same issue. When `terraform apply` I get a timeout, but the machine is created, although with its network adapter disconnected, so the machine doesn't get an IP.

If I remove the `customize` section, the `apply` command works fine and the machine is created with the network adapter connected.

Here's my tf file:

```
resource "vsphere_virtual_machine" "vm_central_docker_linux" {
  count                 = "1"
  name                  = "vm-central-docker-linux-${count.index+1}"
  datastore_cluster_id  = "${data.vsphere_datastore_cluster.datastore_cluster_dev.id}"
  num_cpus              = "1"
  memory                = "2048"
  guest_id              = "${data.vsphere_virtual_machine.ubuntu_1604_template1.guest_id}"
  resource_pool_id      = "${data.vsphere_compute_cluster.dev_cluster.resource_pool_id}"
  folder                = "Docker/Firstrain-Dev-Docker"
  annotation            = ""
  cpu_hot_add_enabled   = ""
  cpu_hot_remove_enabled= ""
  memory_hot_add_enabled= ""

  network_interface     = [
    {
      network_id = "${data.vsphere_network.dev_network.id}"
      adapter_type = "${data.vsphere_virtual_machine.ubuntu_1604_template1.network_interface_types[0]}"
    }
  ]

  disk = [
    {
      label = "disk0"
      size  = "16"
      keep_on_remove = "true"
    },
    {
      label = "disk1"
      size  = "8"
      unit_number = 1
    },
    {
      label = "disk2"
      size  = "8"
      unit_number = 2
    }
  ]

  clone {
    template_uuid = "${data.vsphere_virtual_machine.ubuntu_1604_template1.id}"
    customize {
      linux_options {
        host_name = "myhost"
        domain    = "mydomain"
      }
      network_interface {
        ipv4_netmask = 25
      }
    }
  }
}

output "central_proxy_linux_vm_id" {
  value = "${vsphere_virtual_machine.vm_central_proxy_linux.*.id}"
}

output "central_docker_linux_vm_id" {
  value = "${vsphere_virtual_machine.vm_central_docker_linux.*.id}"
}
```

and the output can be read at https://gist.github.com/thiagoalves/6ec872088b078af2e9f90e75dbd07a6b
