### ISSUE TITLE
Not getting macOS guest IP correctly

### ISSUE THREAD

**Issue by VictorBjelkholm** [terraform-providers/terraform-provider-vsphere#446]
### Terraform + vSphere Provider Version
```
Terraform v0.11.5
+ provider.vsphere v1.3.3
```

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      network_interface {}
    }
  }
}
```

### Expected Behavior

It should have created a new instance and be able to provide to it. `customize.network_interface` is defined empty as we have a DHCP server for assigning IP addresses within the network.

### Actual Behavior

Getting an error as the guest ID doesn't support customizations. `Customization of the guest operating system 'darwin15_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.`

However, I can not skip the customize step, as then vSphere won't understand we're using DHCP (is my understanding at least, from reading the documentation).

So we're stuck with either Terraform can't contact the instance after creation, or getting the error message above. 

I'm looking for a way to let vSphere provider use the automatically assigned IP address, but without having to define a empty `customize.network_interface` block within the `clone` block.

**Comment by jason-azze** [comment]
@VictorBjelkholm I don't think the customization block is required. But without it, your provisioned VMs will all end up with the same hostname as your template because one of the things the customization step does is rename the guest so it matches the name of the VM.

Maybe this is not a problem for you, in which case you can just make sure of two things:
1) Your source template has a NIC that is set to use DHCP
2) Terraform doesn't change the NIC type from whatever you have in your template to its default of VMXNET3. That is, if your template has an e1000 NIC and you don't specify either:
```
adapter_type = "e1000"
```
or 
```
adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
```
Terraform will create a new vmxnet3 NIC for your provisioned VM and any settings you had assigned to the template's NIC will be blown away. I learned this through painful experience.

Hmmm. The default settings for a brand new NIC might be DHCP anyway. So, it's possible all you need to do is remove that customization block entirely.

If you do this and need to give unique hostnames to your VMs, you will probably need to use a provisioner. Here's an example of one I'm using to name Windows guests in a case where I can't use a customization block.

```
  provisioner "remote-exec" {
    inline = [
      "cmd /C wmic computersystem where caption=\\'%computername%\\' rename \\'${var.name_prefix}${format("%03d", count.index + var.name_starting_val)}\\' > /home/test/remote.log 2>&1",
      "shutdown /r /t 30",
    ]

    connection {
      type     = "ssh"
      user     = "test"
      password = "${var.admin_password_value}"
    }
```
Note: I've got Cygwin sshd installed. Without that you'll need to use the `winrm` connection type.

**Comment by VictorBjelkholm** [comment]
Thanks a lot for the reply @jason-azze 

> But without it, your provisioned VMs will all end up with the same hostname as your template

That's fine. The guest (macOS) automatically reassigns it's hostname when it finds the collision, and we don't really use the hostname for anything. 

> Your source template has a NIC that is set to use DHCP

Yup, this is done (well, by default macOS creates a interface connected to the NIC attached in vSphere and that by default is using DHCP so all set). 

> Hmmm. The default settings for a brand new NIC might be DHCP anyway. So, it's possible all you need to do is remove that customization block entirely.

Yeah, exactly. So when I removed the customize block, the `apply` command never finishes, as it seems like Terraform is not sure how to connect to it. I don't know the IP in before-hand either, so can't hardcode it. 

However, the vSphere UI shows the IP correctly, so my guess is that the vSphere provider is either using the ipv6 address instead of ipv4 (and I don't have ipv6) or vSphere provider simply cannot find it at all so it gets stuck on finding the "routable ip" the instance can be found at.

![image](https://user-images.githubusercontent.com/459764/38151602-3d14b742-3464-11e8-914f-4cf40e5eae5a.png)

When running without the customize block, Terraform simply times out in the end, after ~five minutes of "Still creating..."

Here is the output when it's waiting for the instance, in case it's useful:

```
2018-03-30T21:50:55.865+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.3.3_x4: 2018/03/30 21:50:55 [DEBUG] Waiting for routeable address on VM "/MacStadium - D/vm/terraform-test" (timeout = 5m)
2018/03/30 21:50:57 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2018/03/30 21:50:57 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:50:57 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.vm"
vsphere_virtual_machine.vm: Still creating... (10s elapsed)
2018/03/30 21:51:02 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2018/03/30 21:51:02 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:02 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:07 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2018/03/30 21:51:07 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:07 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.vm"
vsphere_virtual_machine.vm: Still creating... (20s elapsed)
2018/03/30 21:51:12 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2018/03/30 21:51:12 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:12 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:17 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2018/03/30 21:51:17 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.vm"
2018/03/30 21:51:17 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.vm"
```

And it's repeated like that until it times out

**Comment by VictorBjelkholm** [comment]
Regarding "empty customize.network_interface block === DHCP" I got from here: https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#network-interface-settings

```
To use DHCP, declare an empty network_interface block for each interface being configured. So the above example would look like:
```

But guess this is for defining new interface, not just using the existing one from the template.

**Comment by jason-azze** [comment]
Sorry, I incorrectly assumed you were using some flavor of Windows guest that wasn't supported.

**Comment by VictorBjelkholm** [comment]
I also tried with `govc` which I understand to be the client-library being used by this provider. This correctly reports the IP as well.

**Comment by VictorBjelkholm** [comment]
@jason-azze no worries! The guest is `darwin15_64Guest` to be exact, should have been more clear with that.

**Comment by VictorBjelkholm** [comment]
Added some extra debug statements in the provider and got the following: https://gist.github.com/VictorBjelkholm/d291419bee605d5437d204fdfdd1d8a9

It's showing the values of [`v.GuestStackInfo`](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L229) and [`v.GuestNicInfo`](v.GuestNicInfo) in the [`WaitForGuestNet`](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/helper/virtualmachine/virtual_machine_helper.go#L209-L274) function, which never seems to return true here and therefore is stuck. Not sure what's wrong though.

**Comment by vancluever** [comment]
Thanks @VictorBjelkholm for the info here! Unfortunately it's hard for us to (of course) test MacOS as it's not something we can easily get our hands on but we will try and work on this.

Some things that I want to confirm here:

* @jason-azze is correct in saying that omitting the `customize` block in the clone sub-resource will skip customization. You want to do this as vSphere does not support customization of this guest. You seem to know this already though!
* Thanks for adding the extra debug snippets! Looks like VMware tools is not reporting a gateway, so we can't check to see if the IP is routeable. We have an open issue for loosening this up in #337 via a setting that controls whether or not the waiter should be checking for a routeable IP. The current waiter waits on an address that can reach the default gateway on a machine to ensure that we have a reachable address to report to any [provisioners](https://www.terraform.io/docs/provisioners/index.html). This can be a problem in some cases, such as machines with complex virtual networking set up (ie: a container runtime or hypervisor) where those IPs may be reported first.

For now, you can set `wait_for_guest_net_timeout = -1` and the guest networking waiter will be skipped. Will will definitely be working on adding this extra tweak to the waiter though, so you can keep an eye out no this issue or #337 for the fix.

Thanks!

**Comment by VictorBjelkholm** [comment]
> Unfortunately it's hard for us to (of course) test MacOS as it's not something we can easily get our hands on but we will try and work on this.

Yeah, makes sense. As we will be continuing to use Terraform + this provider with macOS guests, I'd be happy to help you to test things if I can.

> Looks like VMware tools is not reporting a gateway, so we can't check to see if the IP is routeable

This should be a bug in whatever library terraform-vsphere-provider is using right? Because I do have a gateway set on the macOS guest (it's set via DHCP) but it never ends up being reported in the `WaitForGuestNet` function.

> machines with a complex virtual networking setup

Thing is, it's not a complex setup really, there is just one NIC that gets created by default and uses DHCP to get it's information.

>  now, you can set wait_for_guest_net_timeout = -1 and the guest networking waiter will be skipped

Yeah, while this makes it not stuck on waiting for the routable IP, it also makes the provisioners not have any IP to connect to and I'm unsure how I can work around that fact. I have no way of getting the IP unless I shell out in the terraform configuration to the `govc` cli or something like that, I'm guessing? With `wait_for_guest_net_timeout = -1` defined, the provisioner tries to connect to localhost:22.

**Comment by VictorBjelkholm** [comment]
I worked around it by shelling out to govc to write the IP to disk and then use that for setting up the connection. This will only work with one host but easy to add numbering to it for multiple hosts.

```
resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus                   = 2
  memory                     = 1024
  guest_id                   = "${data.vsphere_virtual_machine.template.guest_id}"
  wait_for_guest_net_timeout = -1

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "disk0"
    size  = 20
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }

  provisioner "local-exec" {
    command = "govc vm.ip -v4 -a terraform-test > host-ip"

    environment {
      GOVC_INSECURE = 1
      GOVC_URL      = ""
      GOVC_USERNAME = ""
      GOVC_PASSWORD = ""
    }
  }

  connection {
    host     = "${file("host-ip")}"
    type     = "ssh"
    user     = "x"
  }

  provisioner "remote-exec" {
    inline = [
      "whoami",
      "df -h",
    ]
  }
}

```

Works fine, except `host-ip` needs to already exist otherwise Terraform validation will fail, because it checks if `file()` actually refers to a existing file when validating, instead of when running. But having a empty file fixes that issue and gets the right IP on the run.

**Comment by vancluever** [comment]
Hey all, #470 has now been merged which allows you to control the routable behaviour of the network waiter. Keep an eye out for 1.4.1 which will probably be out this week!
