### ISSUE TITLE
vsphere_virtual_machine and vsphere_folder race condition on destroy

### ISSUE THREAD

**Issue by jtauke** [terraform-providers/terraform-provider-vsphere#453]
### Terraform Version

Terraform v0.11.5
provider.vsphere v1.3.3

### vSphere Provider Version

v1.3.3

### Affected Resource(s)

- `vsphere_virtual_machine`
- `vsphere_folder`

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
resource "vsphere_folder" "folder" {
  path          = "${var.datacenter_info["parent_folder"]}/${var.client_info["folder_name"]}"
  type          = "vm"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "domain_controller" {
  name             = "${var.domain_controller.["hostname"]}.${var.client_info.["domain_name"]}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder           = "${var.datacenter_info["parent_folder"]}/${var.client_info["folder_name"]}"

  num_cpus = "${var.domain_controller.["cpu_sockets"]}"
  memory   = "${var.domain_controller.["memory"]}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      windows_options {
        computer_name = "${var.domain_controller["hostname"]}"
        organization_name = "${var.client_info.["folder_name"]}"
      }

      network_interface {
        ipv4_address = "${var.domain_controller.["ipv4_address"]}"
        ipv4_netmask = "${var.domain_controller.["ipv4_netmask"]}"
      }

      ipv4_gateway = "${var.client_info.["ipv4_gateway"]}"
    }
  }
}
```

### Debug Output

https://gist.github.com/jtauke/62727076b18479959c167b739c7c3a5c

### Expected Behavior

Terraform waits until all VMs are destroyed, then destroys the folder

### Actual Behavior

Terraform has a race condition in which a destroy is attempted on the folder before it's empty, causing the destroy to fail.

### Steps to Reproduce

```
terraform apply
terraform destroy
````
### References

https://github.com/terraform-providers/terraform-provider-vsphere/issues/23

**Comment by vancluever** [comment]
Hey @jtauke, I noticed there is no implicit dependency in your `vsphere_virtual_machine` configuration on `vsphere_folder`.

If you base your `folder` parameter in `vsphere_virtual_machine` off of data derived from `vsphere_folder`, this should be fixed:

```hcl
resource "vsphere_virtual_machine" "domain_controller" {
  name             = "${var.domain_controller.["hostname"]}.${var.client_info.["domain_name"]}"
  folder           = "${vsphere_folder.folder.path}"
  ...
}
```

This is actually documented (albeit not with virtual machines) [here](https://www.terraform.io/docs/providers/vsphere/r/folder.html#example-with-subfolders).

**Comment by jtauke** [comment]
That makes perfect sense.  Thanks for taking the time to help me out!
