### ISSUE TITLE
terraform apply hangs on still creating and stop with "timeout waiting for a routeable interface"

### ISSUE THREAD

**Issue by yaoBohoussou** [terraform-providers/terraform-provider-vsphere#462]
Hi,
I'm trying to create a new VMfrom template using terraform. My guest OS is pfSense (an os for routers/firewall) and I have vmware tools installed . when I run terraform apply, I can see the vm created in vsphere web client and all network interfaces correctly configured, but terraform gets stuck on the creating the VM state and stops with the error `timeout waiting for a routeable interface`
I have this issue only for these OS : [pfSense](https://www.pfsense.org/) and [vyos](https://vyos.io/).

I can't use `"wait_for_guest_net_timeout":0` because i will use provisionners to run configurations, and I can't use static ip address

## Configuration file

`{
    "resource":[
        {
            "vsphere_virtual_machine":{
                "rtr":{

                    "name":"rtr",
                    "num_cpus":1,
                    "resource_pool_id":"${data.vsphere_resource_pool.pool.id}",
                    "guest_id":"${data.vsphere_virtual_machine.Router_template.guest_id}",
                    "memory":1024,
                    "datastore_id":"${data.vsphere_datastore.datastore.id}",
                    "folder":"Virtual_machines",
                    "scsi_type":"lsilogic",
                    "disk":{
                        "eagerly_scrub":"${data.vsphere_virtual_machine.Router_template.disks.0.eagerly_scrub}",
                        "name":"rtr.vmdk",
                        "thin_provisioned":"${data.vsphere_virtual_machine.Router_template.disks.0.thin_provisioned}",
                        "size":"${data.vsphere_virtual_machine.Router_template.disks.0.size}"
                    },
                    "clone":{
                        "template_uuid":"${data.vsphere_virtual_machine.Router_template.id}"
                    },
                    "network_interface":[
                        {
                            "network_id":"${data.vsphere_network.network.id}",
                            "adapter_type":"${data.vsphere_virtual_machine.Router_template.network_interface_types[0]}"
                        },

                        {
                            "network_id":"${data.vsphere_network.network.id}",
                            "adapter_type":"${data.vsphere_virtual_machine.Router_template.network_interface_types[1]}"
                        }
                    
                    ]
                }
            }
        } 
    ],
    "data":[
        {
            "vsphere_datacenter":{
                "dc":{
                    "name":"datacenter"
                }
            }
        },
        {
            "vsphere_datastore":{
                "datastore":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"datastore"
                }
            }
        },
        {
            "vsphere_resource_pool":{
                "pool":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"resource_pool"
                }
            }
        },
        {
            "vsphere_network":{
                "network":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"network"
                }
            }
        },
        {
            "vsphere_virtual_machine":{
                "Router_template":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"Router_template_pfSense"
                }
            }
        }
    ],
    "provider":{
        "vsphere":{
            "allow_unverified_ssl":true,
            "password":"xxx",
            "version":"1.1.1",
            "vsphere_server":"x.x.x.x",
            "user":"xxx",
        }
    }
}
`

## Terraform apply
vsphere_virtual_machine.rtr: Still creating... (10s elapsed)
vsphere_virtual_machine.rtr: Still creating... (20s elapsed)
vsphere_virtual_machine.rtr: Still creating... (30s elapsed)
vsphere_virtual_machine.rtr: Still creating... (40s elapsed)
vsphere_virtual_machine.rtr: Still creating... (50s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m0s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m10s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m20s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m30s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m40s elapsed)
vsphere_virtual_machine.rtr: Still creating... (1m50s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m0s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m10s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m20s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m30s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m40s elapsed)
vsphere_virtual_machine.rtr: Still creating... (2m50s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m0s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m10s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m20s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m30s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m40s elapsed)
vsphere_virtual_machine.rtr: Still creating... (3m50s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m0s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m10s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m20s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m30s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m40s elapsed)
vsphere_virtual_machine.rtr: Still creating... (4m50s elapsed)
vsphere_virtual_machine.rtr: Still creating... (5m0s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.rtr: 1 error(s) occurred:

* vsphere_virtual_machine.rtr: timeout waiting for a routeable interface

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by vancluever** [comment]
@yaoBohoussou, pfSense runs FreeBSD, and BSD operating systems have a known issue where their version of VMware tools do not correctly report a gateway address. Unfortunately this means that you won't be able to set `wait_for_guest_net_timeout` to an enabled value at this time.

This will be fixed in future versions. In the meantime, you should be able to get the IP addressing data in a different resource (such as `null_resource`) and just run the provisioner there:

```
resource "null_resource" "vm_post_deploy" {
  ...
  connection {
    host = "${vsphere_virtual_machine.rtr.default_ip_address}"
  }

  provisioner "remote-exec" {
    inline ["uname -a"]
  }
}
```

**Comment by yaoBohoussou** [comment]
Thank you @vancluever  for your answer, I tried to use null_resource and I got this error
 ` Resource 'vsphere_virtual_machine.rtr' does not have attribute 'network_interface.default_ip_address' for variable 'vsphere_virtual_machine.rtr.network_interface.default_ip_address'`

**Comment by vancluever** [comment]
@yaoBohoussou It's not a sub-attribute of network_interface. Use the attribute as quoted in the example.

Thanks!

**Comment by yaoBohoussou** [comment]
Still the same issue, I get ` Resource 'vsphere_virtual_machine.rtr' does not have attribute 'default_ip_address' for variable 'vsphere_virtual_machine.rtr.default_ip_address'`
# Terraform file
`

{
    "resource":[
        {
            "vsphere_virtual_machine":{
                "rtr":{

                    "name":"rtr",
                    "num_cpus":1,
                    "resource_pool_id":"${data.vsphere_resource_pool.pool.id}",
                    "guest_id":"${data.vsphere_virtual_machine.Router_template.guest_id}",
                    "memory":1024,
                    "datastore_id":"${data.vsphere_datastore.datastore.id}",
                    "folder":"Virtual_machines",
                    "scsi_type":"lsilogic",
                    "wait_for_guest_net_timeout":0,
                    "disk":{
                        "eagerly_scrub":"${data.vsphere_virtual_machine.Router_template.disks.0.eagerly_scrub}",
                        "name":"rtr.vmdk",
                        "thin_provisioned":"${data.vsphere_virtual_machine.Router_template.disks.0.thin_provisioned}",
                        "size":"${data.vsphere_virtual_machine.Router_template.disks.0.size}"
                    },
                    "clone":{
                        "template_uuid":"${data.vsphere_virtual_machine.Router_template.id}"
                    },
                    "network_interface":[
                        {
                            "network_id":"${data.vsphere_network.network.id}",
                            "adapter_type":"${data.vsphere_virtual_machine.Router_template.network_interface_types[0]}"
                        },

                        {
                            "network_id":"${data.vsphere_network.network.id}",
                            "adapter_type":"${data.vsphere_virtual_machine.Router_template.network_interface_types[0]}"
                        }
                    
                    ]
                }
            }
        },
        {
            "null_resource":{
                "vm_post_deploy":{
                   "connection":{
                       "host":"${vsphere_virtual_machine.rtr.default_ip_address}"
                   },
                   "provisioner":[
                      {
                           "remote-exec":{
                               "inline":[
                                   "uname -a"
                               ]
                           }
                      }
                   ]
                }
            }
        }
    ],
    "data":[
        {
            "vsphere_datacenter":{
                "dc":{
                    "name":"datacenter"
                }
            }
        },
        {
            "vsphere_datastore":{
                "datastore":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"datastore"
                }
            }
        },
        {
            "vsphere_resource_pool":{
                "pool":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"resource_pool"
                }
            }
        },
        {
            "vsphere_network":{
                "network":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"network"
                }
            }
        },
        {
            "vsphere_virtual_machine":{
                "Router_template":{
                    "datacenter_id":"${data.vsphere_datacenter.dc.id}",
                    "name":"Router_template_pfSense"
                }
            }
        }
    ],
    "provider":{
        "vsphere":{
            "allow_unverified_ssl":true,
            "password":"xxx",
            "version":"1.1.1",
            "vsphere_server":"x.x.x.x",
            "user":"xxx"
        }
    }
}
`

**Comment by vancluever** [comment]
@yaoBohoussou, #470 has now been merged which allows you to control the routable behaviour of the network waiter. Keep an eye out for 1.4.1 which will probably be out this week! If you have been having trouble with getting the configuration right this might be a better longer term solution for you.

Thanks!
