### ISSUE TITLE
About resource_pool

### ISSUE THREAD

**Issue by JCHappytime** [terraform-providers/terraform-provider-vsphere#466]
Hi, I have a problem that when I use terraform-provider-vsphere, I cannot find where is my resource pool in my vSphere, when I tried to create a new resource pool, this button is grey. I used the Root Resource pool, but terraform told me that it couldn't find, why?

**Comment by vancluever** [comment]
Hey @JCHappytime, you may not have a resource pool per se. Make sure you read [this section](https://www.terraform.io/docs/providers/vsphere/d/resource_pool.html#specifying-the-root-resource-pool-for-a-cluster-or-standalone-host) of the `vsphere_resource_pool` resource, which will tell you what you want to load so you can get a cluster's default Resource pool.

We might be introducing a data source for this soon (when we work on the `vsphere_cluster` _resource_) so you can avoid this confusion surrounding lookup in the future.

Thanks!

**Comment by JCHappytime** [comment]
Get it, thank you so much @vancluever
