### ISSUE TITLE
error sending customication spec : fault.NicSettingMismatch.summary

### ISSUE THREAD

**Issue by jdor300** [terraform-providers/terraform-provider-vsphere#478]
hey, i have a problem while cloning a VM from template .
i have never seen this problem while doing the deployment manually, only with Terraform.

after using this code at my main.tf :

```
provider "vsphere" {
 user = "${var.viuser}"
 password = "${var.vipassword}"
 vsphere_server = "${var.viserver}"
 allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
 name = "${var.vidc}"
}

data "vsphere_resource_pool" "pool" {
 name = "${var.vipool}"
 datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore_cluster" "datastore_cluster" {
 name = "${var.vidscluster}"
 datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
 name = "${var.vinetwork}"
 datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
 name = "${var.vitemplate}"
 datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
 name = "${var.vmname}"
 datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}"
 num_cpus = 2
 memory = 4096
 folder = "${var.vifolder}"
 resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
 guest_id = "${data.vsphere_virtual_machine.template.id}"
 clone {
  template_uuid = "${data.vsphere_virtual_machine.template.id}"
  customize {
   linux_options {
    host_name = "${var.vmname}"
    domain = $"{var.vidomain}"
   }
  }
 }
 network_interface {
  network_id = "${data.vsphere_network.network.id}"
  adapter_type = "vmxnet3"
 }
 disk {
  label = "disk0"
  size = "${data.vsphere_virtual_machine.template.disks.0.size}"
  thin_provisioned = false
 }
}
```

I'm getting this Error :

> Error: Error applying plan:
> 1 error(s) occured:
> * vsphere_virtual_machine.vm: 1 error(s) occurred:
> * vsphere_virtual_machine.vm: error sending customization spec: fault.NicSettingMismatch.summary

I tried so many things, but nothing works.
some of the things i tried : 
1. removing the Nic device from the template.
2. removing the "adapter_type" property
3. change template to windows template (changing to "windows_options property" as well)

thank you.

**Comment by vancluever** [comment]
@jdor300, you are missing a `network_interface` instance in your `customize` block. This must be present, even if you are using DHCP. See [the documentation](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#network-interface-settings) for more details.

Thanks!

**Comment by jdor300** [comment]
@vancluever thank you very much, i lost 7 days trying to figure it out. thank you !
