### ISSUE TITLE
vsphere_virtual_machine portgroup lookup by key returned nil result for DVS UUID

### ISSUE THREAD

**Issue by Koleon** [terraform-providers/terraform-provider-vsphere#479]
Hey there,
regarding issue #456 I compiled terraform-provider-vsphere with golang 1.10.1 against the branch in the PR #471 and thanks to @vancluever I got DVS UUID and portgroup. Unfortunately the deploy failed again. I still wonder how come it's deployable via different distro.

### Terraform Version
```
$ tf -v
Terraform v0.11.7
+ provider.vsphere (unversioned)
```

### vSphere Provider Version

```
$ tf providers
.
├── provider.terraform
└── provider.vsphere
```

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files
Please see previous issue #456 

### Expected Behavior

Deploy without problem. 

### Actual Behavior

```hcl
$ tf apply

Error: Error applying plan:

2 error(s) occurred:

* vsphere_virtual_machine.ops_win7[0]: 1 error(s) occurred:

* vsphere_virtual_machine.ops_win7.0: network_interface.0: portgroup lookup by key returned nil result for DVS UUID "50 36 d2 92 e8 af e4 f6-9f c2 aa 9e a9 48 b2 95" and portgroup key "dvportgroup-1119"
* vsphere_virtual_machine.ops_win7[1]: 1 error(s) occurred:

* vsphere_virtual_machine.ops_win7.1: network_interface.0: portgroup lookup by key returned nil result for DVS UUID "50 36 d2 92 e8 af e4 f6-9f c2 aa 9e a9 48 b2 95" and portgroup key "dvportgroup-1119"
```
When I run `terraform destory`
```hcl
$ tf destroy

Error: Error refreshing state: 1 error(s) occurred:

* vsphere_virtual_machine.ops_win7: 2 error(s) occurred:

* vsphere_virtual_machine.ops_win7[1]: vsphere_virtual_machine.ops_win7.1: network_interface.0: cannot find network device: invalid ID ""
* vsphere_virtual_machine.ops_win7[0]: vsphere_virtual_machine.ops_win7.0: network_interface.0: cannot find network device: invalid ID ""
```

### Steps to Reproduce
1. `terraform apply`

### References
- issue #456 
- fix #471

**Comment by Koleon** [comment]
Alright, indeed the problem concern our template. So thanks again to @vancluever to help me with identification the VMs :) You can close this issue.

**Comment by vancluever** [comment]
Thanks @Koleon! PS: `master` right now has some fixes for the broken state issue you got after this as well. :slightly_smiling_face:
