### ISSUE TITLE
Terraform vSphere Authentication

### ISSUE THREAD

**Issue by ephos** [terraform-providers/terraform-provider-vsphere#486]
Hello - Somewhat odd issue, our environment recently was upgraded to vSphere 6.5.  Running the latest version of Terraform as well as the vSphere provider I can't get past a `terraform plan` without the error below.  I know something is off since I am able to authenticate both via the web and PowerCLI with the exact same credentials I am using with Terraform.  I referenced the provider documentation on the Terraform site but didn't see many additional options for the 'provider' connection values.  

`* provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.`

### Terraform Version

```bash
Terraform v0.11.7
+ provider.vsphere v1.4.1
```

### vSphere Provider Version

```bash
.
└── provider.vsphere ~> 1.4.1

```

### Affected Resource(s)

Please list the resources as a list, for example:

```hcl
provider "vsphere" {
  version              = "~> 1.4.1"
  vsphere_server       = "${var.vsphere_vcenter}"
  user                 = "${var.vsphere_user}"
  password             = "${var.vsphere_password}"
  allow_unverified_ssl = true
}
```

### Terraform Configuration Files

Can upload on request as I will need to scrub it first, it seems I am not even getting past the provider connection which is above so I wasn't sure if the rest of the config was needed.

### Debug Output

https://gist.github.com/ephos/9aec9cd4373a183c4252ab5493480a66

### Expected Behavior

Authenticates with the vCenter instance.

### Actual Behavior

```bash
Error: Error refreshing state: 1 error(s) occurred:

* provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids

vSphere vCenter 6.5

**Comment by ephos** [comment]
This was an error on my part.  Closing issue.

**Comment by sebbbastien** [comment]
Hi @ephos,

I've exactly the same output, probably the same error on my side.

Do you remember your error ?
