### ISSUE TITLE
Refresh does not update eagerly_scrub value

### ISSUE THREAD

**Issue by olljanat** [terraform-providers/terraform-provider-vsphere#491]
### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
1.4.1

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "server1" {
	name								= "server1"
	folder								= "${var.vsphere_folder}"
	num_cpus							= "${var.vm_docker_worker_cpu_count}"
	memory								= "${var.vm_docker_worker_memory}"
	guest_id							= "other3xLinux64Guest"
	resource_pool_id						= "${data.vsphere_resource_pool.pool.id}"
	datastore_id							= "${data.vsphere_datastore.datastore.id}"

	network_interface {
		network_id						= "${data.vsphere_network.network.id}"
	}

	disk {
		size							= "10"
		label							= "server1.vmdk"
		eagerly_scrub						= "false"
		thin_provisioned					= "true"
	}
}
```

### Debug Output
```
Error running plan: 1 error(s) occurred:
* vsphere_virtual_machine.server1: 1 error(s) occurred:
* vsphere_virtual_machine.server1: disk.0: virtual disk "server1.vmdk": cannot change the value of "eagerly_scrub" - (old: true new: false)
```

### Panic Output
 N/A

### Expected Behavior
Refresh should check current value for eagerly_scrub.

### Actual Behavior
Refresh does not update eagerly_scrub value on state file and generates error about it.

### Steps to Reproduce
1. Create VM
2. Manually change eagerly_scrub value on state file (or do VMotion to another datastore and update disk type and then back to original datastore and disk type).
3. Run `terraform refresh`
4. Run `terraform plan`

### Known workarounds
1. Do VMotion and make sure that disk type sets eagerly_scrub value back to same than it was originally.
2. Manually modify state file and set original value for eagerly_scrub.
3. Run `terraform plan` again.

**Comment by bill-rich** [comment]
This seems to be resolved at this point. `eagerly_scrub` is updated as part of the `virtual_machine` read. Let me know if you're still running into this issue and I'll reopen it.
