### ISSUE TITLE
Terraform reconfiguration task is not asynchronous with other vCenter tasks.

### ISSUE THREAD

**Issue by antonputra** [terraform-providers/terraform-provider-vsphere#493]
Hi there,
**Terraform version**:
Terraform v0.11.7

Provider:
└── provider.vsphere = 1.4.1

The current problem is: When you deploy a cluster with Terraform, the reconfiguration process of a vm gets blocked by the relocation task in Vcenter, which happens to be manually started by someone else in the Operations team usually at the same time. Until the relocation task is finished, Terraform isn’t able to complete reconfiguration of the vm.
Is there a way to have Terraform asynchronously deploy vm’s while relocation tasks are occurring in Vcenter at the same time?
Our Operations team likes to migrate 5TB databases during the day during working hours, and the relocation of each vm to another datastore takes 8 hours sometimes. I can’t wait 8 hours to deploy a vm in Terraform, so this is a serious problem for me.

**Terraform module**
```
data "vsphere_datacenter" "dc" {
  name = "${var.datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.network}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "${var.hostname}.${var.domain}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${var.num_cpus}"
  memory   = "${var.memory}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  disk {
    label            = "disk1"
    size             = "${var.disk1_size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
    unit_number      = 1
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {

      linux_options {
        host_name = "${var.hostname}"
        domain    = "${var.domain}"
      }

      network_interface {
        ipv4_address = "${var.static_ip}"
        ipv4_netmask = 24
      }

      ipv4_gateway = "${var.gateway}"
    }

  }
}
```

**Expected Behavior**
Terraform is able to provision VMs regardless of any other tasks that happen to be running in Vcenter at the same time.
**Actual Behavior**
Terraform reconfiguration of a vm is blocked by relocation task of some other vm that happens to be running in Vcenter at the same time.
After 5 minutes of reconfiguration attempt, the vm then proceeds to be deleted. And that deletion task hangs too. Both tasks hang for 8 hours until the blocking relocation task is finally complete.
**Additional Context**
The relocation of other vm’s is initiated by another team in my company, so it cannot be controlled by me (part of their job).

**Comment by vancluever** [comment]
Sorry @antonputra, but Terraform cannot do anything extra to push an operation through concurrent with other operations that may be happening at the same time. On the other hand, nothing that it does would be normally blocked by most other operations, given that you are not hitting any concurrency limits. I'd would actually check the [vCenter Server Maximums](https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.configmax.doc/GUID-BBD10A8B-7BDC-45F3-9CA4-C44EE77749BA.html) article to see if you are actually hitting a concurrency limit on certain VM operations.

Thanks!

**Comment by vancluever** [comment]
PS: It should be noted that there is at least one open issue (#408) that is tracking possibly tweaking the reconfiguration timeout value, but I don't know if we will be theoretically allowing such a high limit - a lot can happen in 8 hours' time and Terraform was not really designed to hang onto a provider connection for that long - a lot of things are contingent on whether or not this would actually succeed.

We may also eventually rotate out most configurable timeouts in favor of using Terraform core's built-in timeouts and cancelable execution contexts, but again, these are not designed to hold on to a connection for such a long time either. Your best course of action may be to co-ordinate your deployment efforts with the other team.
