### ISSUE TITLE
Terraform disks not always available

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#495]
Creating Windows VMs.  Nothing fancy...
Recently upgraded to 1.4.1 from 1.32. 
ESXi 6.0.0, 5572656

About 1/3 times a node is created, the disk is not bootable (goes to BIOS).  I thought at first it was specific to the ESX host, but its seemingly random.

It obviously fails ultimately due to a timeout, but the base issue is it looks like the disk isn't available for bootup.  If there are any troubleshooting steps - I'd be more than happy to run through them.

**Comment by vancluever** [comment]
@rismoney I think the next steps would be to take a look at the disks. Also, I noticed ESXi - is this just one host or multiple?

Maybe browse with the [MOB](https://www.terraform.io/docs/providers/vsphere/index.html#via-the-vsphere-managed-object-browser-mob-) (you will have to enable it on standalone ESXi). You can use it drill down to a virtual machine's hardware and see if there are any weird things that stand out with the disk devices versus a functional VM.

Can I see your Terraform config as well?

**Comment by bill-rich** [comment]
This issue has been closed because there has been no response to our request for more information. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
