### ISSUE TITLE
HostAffinity Support (Question ) 

### ISSUE THREAD

**Issue by surajsub** [terraform-providers/terraform-provider-vsphere#497]
Terraform Version

v0.11.3
vSphere Provider Version

v1.3
Affected Resource(s)

    vsphere_virtual_machine

Expected Behavior

Is there a way to set a virtual machine (our group of virtual machines) to a specific host group (Host Affinity)?
We looking to use this feature for building some placement constraints.

**Comment by vancluever** [comment]
Hey @surajsub, this is a feature that will be coming in 1.5.0.

Thanks!

**Comment by surajsub** [comment]
which is in ? :-)
