### ISSUE TITLE
winrm config reset by customization & run_once_command_list fire-and-forget 

### ISSUE THREAD

**Issue by k-brooks** [terraform-providers/terraform-provider-vsphere#502]
### Terraform Version
0.11.7

### vSphere Provider Version
1.4.1

### Affected Resource(s)

`vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  password = "pw"
  user = "user"
  vsphere_server = "vsphere"
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "dc"
}

data "vsphere_datastore" "eng_ds" {
  name = "eng"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "pool"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name = "Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "test-clone" {
  datastore_id = "${data.vsphere_datastore.eng_ds.id}"
  name = "TestCloneKB"
  num_cpus = 4
  memory = 8192

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "e1000"
  }
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  guest_id = "windows9Server64Guest"

  clone {
    template_uuid = "4200edb6-9aac-a75a-aa31-a8e1a1cec042"
    linked_clone = true
    customize {
      windows_options {
        computer_name = "TestCloneKB"
        admin_password = "pw"
        auto_logon = true
        auto_logon_count = 1
        full_name = "Administrator"
        run_once_command_list = [
          "winrm quickconfig -force",
          "winrm set winrm/config @{MaxEnvelopeSizekb=\"100000\"}",
          "winrm set winrm/config/Service @{AllowUnencrypted=\"true\"}",
          "winrm set winrm/config/Service/Auth @{Basic=\"true\"}"]
      }
      network_interface {
        dns_server_list = [
          "192.169.1.10",
          "192.169.1.16"]
      }
    }
  }
  scsi_type = "lsilogic-sas"
  disk {
    unit_number = 0
    datastore_id = "${data.vsphere_datastore.eng_ds.id}"
    label = "disk0"
    size = 60
    thin_provisioned = true
  }

  provisioner "file" {
    source = "variables.tf"
    destination = "C:/temp/variables.tf"

    connection {
      insecure = true
      host = "TestCloneKB"
      type = "winrm"
      user = "TestCloneKB\\Administrator"
      password = "pw"
    }
  }
}

```

### Debug Output
https://gist.github.com/k-brooks/1a515c3f2341a38994ee27d19add281f

### Expected Behavior
- Winrm config is maintained from source template
AND/OR
- run_once_command_list is synchronously executed prior completion of customization

### Actual Behavior
- Winrm config is reset when customization is used
- run_once_command_list is executed as 'fire-and-forget'
- eventually the provisioner times out

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- Vsphere version 6
- Template VM OS = Win Server 2016
- Customization is necessary for host name
- I also noticed admin_password is removing the admin password on the cloned vm, if it is not specified

**Comment by vancluever** [comment]
@k-brooks VM customization on Windows performs a sysprep, generalizing the VM image which will ultimately cause the issues you are seeing above, from what I would imagine.

We will work on reproducing this when we have a chance, but everything that you have described so far seems like normal behaviour. What you might need to do is ensure that the necessary minimum WinRM config is performed in customization as to make the VM available for provisioners.

Thanks!

**Comment by k-brooks** [comment]
@vancluever,
That may be the case, however, customization of the VM from other vectors (vsphere client, powercli) maintains the existing winrm config.
Additionally, I did try to configure winrm via the run_once_command_list, but execution looks to be fire-and-forget (non-blocking), so the provisioner runs prior to the winrm configuration completing.

**Comment by rismoney** [comment]
Not sure if this is related to your issue, but what I have realized is that Vsphere doesn't accurately know when customization completes.  You cannot use the VMware events to determine this.  Only the host truly knows.   I work around this by using a waiter script that inspects the sysprep/customization logs.  

I ensure all winrm configuration is performed via unattend file.  this carries through to the TF.  Puppet/Gpo closes this ingress post build.

I wonder if you need to bounce winrm service for your settings to take effect as I don't remember if the listener will take effect.

**Comment by k-brooks** [comment]
@rismoney 
Thanks for the tips. I tried bouncing the service, no luck (I'm fairly certain the changes are immediate).
I'll take a look (next week) at using `windows_sysprep_text` instead of `windows_options`, I suspect it may allow me to be more surgical.
Thanks!

**Comment by k-brooks** [comment]
So, I gave the `windows_sysprep_text` route a go...that looks to be suffering from a different bug. Will open a case against that.

**Comment by kristianmo** [comment]
Hey I struggled with this too. I ended up installing the built-in OpenSSH server on windows 10 to transfer the file.

provisioner "file" {
    source      = "BuildAgent1/buildAgent.properties"
    destination = "f:\\BuildAgent\\conf\\buildAgent.properties"
    connection {
      type     = "ssh"
      user     = "user"
      password = "password"
      timeout = "30m"
    }
  }

**Comment by k-brooks** [comment]
We ended up abandoning the customization process and using a remote provisioner (winrm) to rename the host, then rebooting in the same script.
Not ideal, however, it is much faster than windows customization.

**Comment by bavivek2003** [comment]
i figured out, basically Winrm service is in delayed start, so should start the service before config the winrm service.
"net start WinRM",
        "winrm set winrm/config/Service @{AllowUnencrypted=\"true\"}",
        "winrm set winrm/config/Service/Auth @{Basic=\"true\"}"

**Comment by k-brooks** [comment]
@bavivek2003 - I suspect that is a different issue.
The winrm config is reset during customization, and the run_once_command_list is executed on the first login, which is after terraform-vsphere has moved onto any provisioners which may exist.
I'm more of the opinion (now) that this is a defect in how Windows handles customization - and to avoid the process all-together.
I'd vote that this could be fulfilled by documenting the limitations and potential workarounds.

**Comment by gibonurs** [comment]
We are successfully using run_once_command_list with auto_logon option, and did not get any issues with vm customization, but to achieve this we had to remove content of %windir%\pather folder - there is a sysprep answer file that was causing problems described by author - from the template. We are using Packer for template creation so that was not a problem.

**Comment by bill-rich** [comment]
This appears to be a result of Sysprep being run as part of the customization process. Thanks everyone on the workarounds. Unfortunately, there is not much I can see to do on the provider side, as the problem tends to be with unwanted results of how vSphere customizes the OS.

**Comment by eminibm** [comment]
see the below error: terraform provisioner is currently not supporting ansible execution through winrm service.

Provisioning with \’ansible\’…\nvsphere_virtual_machine.mywindowsvm (ansible): Currently, only SSH connection is supported\n\n’, u’\nError: Currently, only SSH connection is supported\n\n\n’)

**Comment by eminibm** [comment]
my code:

provisioner "ansible" {
   plays {
      playbook {
        file_path = "./ansible_code/installBigfixClient.yml"
      }
   }
   connection {
      insecure = true
      port = 5986
      type     = "winrm"
      host     = "${var.ip}"
      user     = "${var.ad}\\administrator"
      password = "${var.ad_password}"
    }
 }  

see the below error: terraform provisioner is currently not supporting ansible execution through winrm service.

Provisioning with \’ansible\’…\nvsphere_virtual_machine.mywindowsvm (ansible): Currently, only SSH connection is supported\n\n’, u’\nError: Currently, only SSH connection is supported\n\n\n’)
