### ISSUE TITLE
Operating system not found while deploying windows OS templates with customization.

### ISSUE THREAD

**Issue by jdor300** [terraform-providers/terraform-provider-vsphere#504]
Terraform v0.11.6
provider.vsphere v1.4.1

Hey, i ran into a problem while deploying a normal clean template of any windows OS (2016, 2012, 2008),
Once i deploy it manually without Terraform it works perfectly.. even with customization.
When deploying the VM from Terraform with customization, it gets corrupted and get the errors below.

my resource code :

```
resource "vsphere_virtual_machine" "vm" {
 name="${var.vmname}"
 datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}"
 num_cpus = 2
 memory = 4096
 resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
 scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
 guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
wait_for_guest_net_routable = false
 clone {
  template_uuid = "data.vsphere_virtual_machine.template.id"
  customize {
   windows_options {
    computer_name = "${var.vmname}"
    join_domain = "${var.vidomain}"
    domain_admin_user = "${var.viuser}"
    domain_admin_password = "${var.vipassword}"
   }
   network_interface {}
  }
 }
 network_interface {
  network_id = "${data.vsphere_network.network.id}"
  adapter_type = "vmxnet3"
 }
 disk {
  label = "disk0"
  size = "${data.vsphere_virtual_machine.template.disks.0.size}"
  thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
 }
}
```

OUTPUT :

> Windows 2012 result :
> 
> TUI terminal (linux like), with info like "operating system not found" , "no DHCP or dhcp proxy found" "vmxnet3 failed" ..
> after 15 min of terraform runtime, the run crashes with unsuccessful customization apply.

> Windows 2016 result :
> 
> Blue Screen Of Death, with info "Your PC ran into a problem and needs to restart. We'll restart for you.",
> "stop code: INACCESSIBLE BOOT DEVICE"

NOTES :
* without the customization the creation works fine without crashes, iguess its because the VM won't powered on for extra customizations.

**Comment by jdor300** [comment]
another NOTE :
* Sometimes it does work on Windows 2016. Windows 2008,2012 still corrupt.

**Comment by jdor300** [comment]
Still having this Issue.

**Comment by RaceFPV** [comment]
Same issue on vsphere provider 1.7. If I skip customizing the OS it builds from template fine and does not bluescreen. The moment I add windows_options it corrupts and bluescreens.

**Comment by RaceFPV** [comment]
More digging revealed that this is because terraform is changing the SCSI controller after the windows vm is cloned. If a vm was built with the LSI Logic SAS controller, terraform will change it to paravirtual, which then bluescreens the newly cloned vm.

**Comment by jeremywiles** [comment]
Is there a workaround for this?  I'm getting a blue screen every time.

**Comment by bill-rich** [comment]
@RaceFPV @jeremywiles Can you try setting `scsi_type` to `lsilogic`? You could also set `scsi_type` to be pulled from the template. That way your cloned VM will always have the same `scsi_type` as the source.

**Comment by jeremywiles** [comment]
Thank you so much for the quick reply! That worked for me.  I added this line:
scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
 to force it to keep the same scsi_type as the template and it worked immediately.  Thanks again for the help!

**Comment by bill-rich** [comment]
@jeremywiles You're welcome! Glad it worked for you.
