### ISSUE TITLE
DHCP network configuration assigns the same IP address to multiple guest VMs

### ISSUE THREAD

**Issue by jasonwalsh** [terraform-providers/terraform-provider-vsphere#516]
As a disclaimer, I am not an expert with VMWare, so I apologize if this is not a Terraform provider-specific issue.

After the `apply` command executes successfully, two or more guest virtual machines exist in a resource pool. However, these virtual machines have the same IPv4 address. See below for more specific details.

Thank you!

### Terraform Version

Terraform v0.11.7

### vSphere Provider Version

v1.4.1

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

**Note:** The following snippet is *not* the full configuration.

```hcl
locals {
  name = "consul-${var.server ? "server" : "client"}"
}

resource "vsphere_virtual_machine" "consul" {
  datastore_id = "${var.datastore_id}"

  disk = [
    "${var.disk}",
  ]

  enable_logging = true

  guest_id = "${var.guest_id}"
  name     = "${local.name}-${count.index + 1}"

  network_interface {
    network_id = "${var.network_id}"
  }

  resource_pool_id            = "${var.resource_pool_id}"
  wait_for_guest_net_routable = "${var.wait_for_guest_net_routable}"

  clone {
    customize {
      linux_options {
        domain    = "consul.internal"
        host_name = "${local.name}-${count.index + 1}"
      }

      // To use DHCP, declare an empty network_interface block for each configured interface.
      network_interface {}
    }

    template_uuid = "${var.template_uuid}"
  }

  count = "${var.bootstrap_expect}"
}
```

### Debug Output

https://gist.github.com/jasonwalsh/131ca9d67bd9d46865b59833d94c9696

### Panic Output

n/a

### Expected Behavior

Two or more created guest VMs, each with a different `default_ip_address` attribute.

### Actual Behavior

Two or more created guest VMs, each with the *same* `default_ip_address` attribute.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

n/a

### References

n/a

**Comment by jasonwalsh** [comment]
Just leaving a comment, this *may* be an issue with our DHCP server not renewing leases and not the provider itself. I shall attempt to troubleshoot and close the issue if it is, in fact, the DHCP server causing the wrong behavior.

**Comment by maruedr-dylanrhysscott** [comment]
@jasonwalsh This may help you as I had this problem - it appears related to MAC addressing on VMs. VSphere allows duplicate mac addresses which in turn led to collisions from DHCP - Have you tried setting a static mac address? https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#mac_address

**Comment by rismoney** [comment]
I am having same issue with Ubuntu nodes.  Not happening on windows. 

Setting mac is hackish...

**Comment by jasonwalsh** [comment]
@maruedr-dylanrhysscott I have not tried configuring a static MAC address. I will give that a try and get back to you. Thanks!

**Comment by maruedr-dylanrhysscott** [comment]
I agree with @rismoney it is hacky but it solved my issue @jasonwalsh :) If your doing multiple VM's through a module I combine turned the last digit in the mac address to be equal to current count for unique addressing

**Comment by rismoney** [comment]
Investigating...I'm not sure it is always duplicate mac from a vsphere perspective.  Something on the initial image persists hwaddr.  On centos this can be remedied editing ifcfg-eth0 but I don't know on Ubuntu yet...

**Comment by jasonwalsh** [comment]
Thanks @rismoney, I'll give this a try.

**Comment by PauloASilva** [comment]
> alright confirmed- in my image ubuntu 1804 image, deleting and touching /etc/machine-id (i perform this now in packer), then shutting down fixes the issue. Next startup will occur via terraform and, a new machine id is generated, and the node gets a new ip address.

@rismoney :pray: I just spent hours because of this issue. I am using `terraform-provider-libvirt` and although all machines get a different IPv6 address, they were getting the same IPv4.

Your suggestion did the trick. I added it to my packer cleanup provisioner.

Thanks!
Paulo A. Silva

**Comment by jasonwalsh** [comment]
I'll close this issue in favor of the solution provided by @rismoney

**Comment by sukhkar** [comment]
> alright confirmed- in my image ubuntu 1804 image, deleting and touching /etc/machine-id (i perform this now in packer), then shutting down fixes the issue. Next startup will occur via terraform and, a new machine id is generated, and the node gets a new ip address.

I'm new in terraform and facing the same issue for ubuntu 18.04. Should i need to update anything on terraform file to fix the same?
Could you ( @jasonwalsh @rismoney ) please let me know the steps to resolve the issue?

**Comment by rismoney** [comment]
No this needs to be fixed in the template/image you are cloning.  Nothing on TF side.  In fact once you turn the reference template/image on again, you have to repeat purging the files prior to shutdown.

**Comment by sukhkar** [comment]
Thanks you so much @rismoney .

**Comment by samp-git18** [comment]
Hi, I'm not able to fix the issue with the above suggestion of removing and creating the machine-id file, i'm using centos template, I'm trying to create two VMs from it, the set IP is the same for both of them, any suggestion ?
