### ISSUE TITLE
Unable to access private ip address created by the terraform module with services running in template

### ISSUE THREAD

**Issue by arewm** [terraform-providers/terraform-provider-vsphere#522]
I am unable to access the private ip address created by the terraform module. It would be great if this information could be stored on `network_interface.*.ipv4_address`.

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.random v1.2.0
+ provider.vsphere v1.4.1
```

### vSphere Provider Version

```
$ terraform providers
.
└── module.my_module
    ├── provider.random
    └── provider.vsphere
```

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "my_worker" {
  count      = "${var.worker["nodes"]}"

  name              = "${random_pet.label.id}-${format("${lower(var.instance_name)}-worker-%01d", count.index + 1) }"
  folder            = "${vsphere_folder.vm_folder.path}"
  resource_pool_id  = "${data.vsphere_resource_pool.my_pool.id}"
  host_system_id    = "${data.vsphere_host.my_hosts.*.id[count.index%data.vsphere_host.my_hosts.count]}"
  datastore_id      = "${data.vsphere_datastore.my_datastore.id}"

  num_cpus = "${var.worker["vcpu"]}"
  memory   = "${var.worker["memory"]}"
  guest_id = "ubuntu64Guest"

  network_interface {
    network_id = "${data.vsphere_network.my_private_network.id}"
  }

  disk {
    label             = "disk0"
    size              = "${data.vsphere_virtual_machine.my_template.disks.0.size}"
    thin_provisioned  = true
    datastore_id      = "${data.vsphere_datastore.my_datastore.id}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.my_template.id}"

    customize {
      linux_options {
        host_name = "${random_pet.label.id}-${format("${lower(var.instance_name)}-worker-%01d", count.index + 1) }"
        domain    = "${var.vsphere_domain}"
      }

      network_interface {}
      dns_server_list = ["${var.worker_dns_servers}"]
    }
  }
}
```

### Expected Behavior

I would be able to directly access the ip address for the public network created on this vm.

### Actual Behavior

The template has docker installed and set up to start on boot. While this is not a problem, the docker ip address is showing up in the `guest_ip_addresses` (which is the only way to get the ip address for this vm). I cannot even depend on Docker's ip address to be `guest_ip_addresses.1` as sometimes the order of `0` and `1` are swapped.

```
"guest_ip_addresses.#": "3",
"guest_ip_addresses.0": "192.168.0.55",
"guest_ip_addresses.1": "172.17.0.1",
"guest_ip_addresses.2": "fe80::250:56ff:fea8:9dbb",
```

### Steps to Reproduce

1. Create a template that has docker (or similar service that reserves an adapter) on boot
2. Provision the vm on this template

### Workaround

I was able to achieve the desired behavior by creating another template that does not have docker running at the start (i.e. `systemctl stop docker; systemctl disable docker`). I then have to manually start it on the VM after provisioning. When you do this, the private ip address will be `guest_ip_addresses.0`.

**Comment by vancluever** [comment]
@arewm the "primary" IP address - in other words, the IP address that is associated with the system's default gateway, is always saved as [`default_ip_address`](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#default_ip_address), outside of the whole address list stored in `guest_ip_addresses`. This is your best bet for getting a reachable IP address so long as you have a default gateway in your network. This _should_ get you around the issue where the docker IP address is being reported out of order from the actual routable address.

Thanks!
