### ISSUE TITLE
Terraform vmware vsphere provider - Getting crash when running terraform plan

### ISSUE THREAD

**Issue by dsmith60** [terraform-providers/terraform-provider-vsphere#531]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

qsi019935:vmware_101 dwights$ terraform -v
Terraform v0.11.7
+ provider.vsphere v1.5.0

### vSphere Provider Version

qsi019935:vmware_101 dwights$ terraform providers
.
└── provider.vsphere

qsi019935:vmware_101 dwights$ terraform -v
Terraform v0.11.7
+ provider.vsphere v1.5.0

### Affected Resource(s)

vsphere_virtual_machine.vm

### Terraform Configuration Files

https://www.dropbox.com/s/dzdti0yjpn4jz2p/vmware_101.zip?dl=0

### Debug Output

https://gist.github.com/dsmith60/3c7f4b35c8f8ebd87d23e0cb9c3a8a9e

### Panic Output

https://gist.github.com/dsmith60/3c7f4b35c8f8ebd87d23e0cb9c3a8a9e

### Expected Behavior

should see plan when running "terraform plan -out "plan"

### Actual Behavior

Received error: panic: runtime error: invalid memory address or nil pointer dereference

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out "plan"`

### Important Factoids

Nothing special that we are aware of.

### References

None that we know

**Comment by bill-rich** [comment]
@dsmith60 or @movergan Are you able to see the latency sensitivity settings through the vCenter client for the VM? Do you run into this crash with any VMs or is it just specific ones? If it is will all VMs, can you provide information on the license editions that are in use?

It seems that the latency sensitivity info missing from the VM configurations, so I'm looking for anything that could set

**Comment by movergan** [comment]
The problem there indeed! What I did was:

0. Run terraform import, it fails as described in the bug.
1. Go to vSphere and check VM "latency sensitivity" option (vSphere->VM->Edit Settings ->VP Option tab-> Advanced ->Latency sensitivity), the option set to Normal
2. Change to High and save.
3. Repeat step 1, the option is still set to **normal**, 
4. Run terraform import, it is not failing anymore!

**Comment by jcollie** [comment]
I can confirm that the steps described by @movergan fixed the problem for me. Using 1.6.0 of the vsphere plugin and 0.11.7 of terraform.

**Comment by jcollie** [comment]
Also, I only saw the problem when the VM in question was powered off...

**Comment by movergan** [comment]
Using the option in VM config did the trick for me.

resource "vsphere_virtual_machine" "app-vm" {
...
latency_sensitivity = "normal"
...
}

**Comment by movergan** [comment]
Faced the same issue after vCenter restart even with VMs where the WA has been applied.
