### ISSUE TITLE
Unable to Customize ens192 on Fedora Atomic 28

### ISSUE THREAD

**Issue by alexgaganashvili** [terraform-providers/terraform-provider-vsphere#538]
Hi,

I'm using Terraform v0.11.7.
It won't customize the network interface on a VM. Instead of customizing ens192, it creates a new interface configuration file /etc/sysconfig/network-scripts/ifcfg-ether and tries to customize it.
The OS is Fedora Atomic 28.

Thanks
Alex

**Comment by vancluever** [comment]
@alexgaganashvili this is more than likely an issue with VMware tools, not Terraform. You will want to open a bug against https://github.com/vmware/open-vm-tools.

Thanks!
