### ISSUE TITLE
VM's cannot communicate with each other when on different ESXI hosts for DHCP allocation

### ISSUE THREAD

**Issue by maruedr-dylanrhysscott** [terraform-providers/terraform-provider-vsphere#543]
Hi,

Tearing my hair out on this one - I am running a DHCP VM with a static IP address on VSphere - All other VM's created by Terraform use DHCP. We have 2 ESXI hosts and any VM's that end up on the same ESXI host as the DHCP VM successfully get allocated IPs. Any VM's that end up on the other host do not. When I log into the VMs and attempt to ping the gateway I get network unreachable.

When I create the VMs manually through the VSphere interface regardless of which host they end up on networking works and my DHCP server successfully allocates an IP

Any ideas?

Cheers!

### Terraform Version

Terraform v0.11.7

### vSphere Provider Version

provider.vsphere v1.6.0

### Affected Resource(s)

- `vsphere_virtual_machine`

#### Resource Definition

```
resource "vsphere_virtual_machine" "vm" {
  name             = "${var.vsphere_common_vmname}-${count.index}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  count = "${var.vsphere_common_count}"

  num_cpus = "${var.vsphere_common_vcps}"
  memory   = "${var.vsphere_common_mem}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label = "${var.vsphere_common_disk_label}"
    size  = "${var.vsphere_common_disk}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
  }
}
```

#### Datastores

```
data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "${var.vsphere_cluster}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.vsphere_network}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vsphere_common_template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```

#### Module Vars

```
variable "vsphere_datacenter" {}
variable "vsphere_datastore" {}
variable "vsphere_cluster" {}
variable "vsphere_network" {}
variable "dependent_resource_ips" {
  default = []
}
variable "vsphere_common_template" {
  default = "packer-templates/centos7-base"
}
variable "vsphere_common_vcps" {
  default = 2
}
variable "vsphere_common_mem" {
  default = 2048
}
variable "vsphere_common_vmname" {
  default = "vsphere-machine"
}
variable "vsphere_common_count" {
  default = 1
}
variable "vsphere_common_disk" {
  default = 60
}
variable "vsphere_common_disk_label" {
  default = "disk0"
}
variable "vsphere_mac_address_base" {
  default = 4
}
```

### Debug Output

https://gist.github.com/maruedr-dylanrhysscott/9fc8489f18d261d5e5ad5cde4795800e

### Expected Behavior

VM's should be able to communicate with each other when on the same network - regardless of which ESXI host they are on

### Actual Behavior

Terraform times out waiting for an IP address Inside the VM there is a self assigned IPV6 addresses and any gateway or machine ping results in network unreachable

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Run a VM with DHCP server on host one
1. Run `terraform plan -out server.plan`
1. Run `terraform apply server.plan`
1. Any VMs which end up on another ESXI host cannot communicate properly

### Important Factoids

* VMs are running CentOS 7 and have openvm-tools installed
* All VM's are connected to the same network
* Network adapters are connected at power on
* There is no firewall rules blocking communication between ESXI hosts
* Setting static IP addresses for networking on the machines works - I can ping any other connected VM's
* VM Network has associated VLAN ID

![tfdebug](https://user-images.githubusercontent.com/39556276/40967729-b680b470-68ab-11e8-93fd-283624b9194c.png)

**Comment by bill-rich** [comment]
Hi @maruedr-dylanrhysscott. Thats a real interesting one. My best guess right off is maybe something is happening with the mac address on the VMs that aren't working. If you log into one of the VMs that lands on another host, do you get an IP address if you run DHCP manually? If you have access to the DHCP server, can you check the logs to see if there any messages there about the VMs that are failing, or can you get a packet dump during the time the DHCP requests are coming in to see if the traffic is making it through to the DHCP server?

**Comment by maruedr-dylanrhysscott** [comment]
Hi @bill-rich Running DHCP manually has no effect - looking at the DHCP logs on machines that can't get an IP address I am seeing the following:

In the host that cant get an IP

![tfdhcperr](https://user-images.githubusercontent.com/39556276/41024405-0ca2128e-6967-11e8-9194-726e1d8ceee9.png)

![dhcpdisc](https://user-images.githubusercontent.com/39556276/41024451-341371f0-6967-11e8-9bb9-c448245cce97.png)

TCPDump of ports 67 and 68 on DHCP server show no traffic

![tfdhcppackets](https://user-images.githubusercontent.com/39556276/41024435-23f25c82-6967-11e8-8db4-00c1a8de3723.png)

If I try to ping the gateway I get network unreachable. I can see DHCP requests from other machines (that are on the same ESXI host) hitting DHCP and eventually getting leases. I also see it happen on machines as they get load balanced from one ESXI (inaccessible) to the other (accessible).

Mac addresses are assigned dynamically by VSphere and they are definitely all on the same network with the same VLAN ID. Really confused as I don't think its my DHCP conf because it does assign IP addresses. I've been told by our provider they are not blocking traffic between hosts

Doing some reading I have a feeling this maybe the problem - we are using standard VSwitches

> A standard switch that has no associated adapters is called an internal vSwitch. Virtual machines connected to an internal vSwitch cannot communicate with other virtual machines outside of the host

https://www.pluralsight.com/blog/it-ops/vmware-networking-configuring-vnetwork-1

**Comment by gaeldb** [comment]
Seems to be MAC address related, did you try to active promiscuous mode on your vswitch ?
Also confirm your ESXI's are bare-metal ? (not nested ESXI's : ESXI's in another ESXI)

**Comment by maruedr-dylanrhysscott** [comment]
This has been resolved by our provider - thanks for your help
