### ISSUE TITLE
vsphere_virtual_machine: Source VM Must Be Powered Off

### ISSUE THREAD

**Issue by Midacts** [terraform-providers/terraform-provider-vsphere#549]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

0.11.7

### vSphere Provider Version

1.6.0

### Affected Resource(s)

vsphere_virtual_machine`

### Terraform Configuration Files

Works with any config. Nothing specific.

### Debug Output

* vsphere_virtual_machine.vm: virtual machine must be powered off to be used as a source for cloning

[Link to code](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go#L73)

### Expected Behavior

It should allow end users to clone a VM even if it is running.

The PowerCLI cmdlet `New-VM` allows us to have VMs/Templates that are powered on when we create clones.

### Actual Behavior

It does not allow you to create a clone

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References

[Link to code](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/internal/vmworkflow/virtual_machine_clone_subresource.go#L73)

**Comment by vancluever** [comment]
@Midacts, sorry, but while this is not specifically a requirement of vSphere, it is a requirement in the Terraform vSphere provider. This, along with the other cloning restrictions documented [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#additional-requirements-and-notes-for-cloning), are design decisions that we have made to ensure the stability of the source and reduce the chance for edge cases.

I just noticed that the power state requirement is not listed in that section - we will get it added.

Thanks!

**Comment by Midacts** [comment]
Sad day...
Do you know the logic behind the design decision to have the VM powered off?

**Comment by chuanran** [comment]
Hi @vancluever , thanks for the explanation. I have the same concern/questions as @Midacts . We actually have scenarios for such case. For example, if we want to clone an existing production environment, where we cannot power off the VMs before cloning, is it expected  that terraform should support that?

From Vsphere Client, actually when you right click any running VM, and choose `Clone` -> `Clone to virtual machine`, it can work pretty well. We know the best practice is always NOT cloning a running vm to avoid edge cases, but at least terraform should provide the possibility to ask end users to decide, right?  Thanks.

**Comment by vmovva** [comment]
Hi @vancluever ; Could you also confirm linked_clone **ONLY** works with template and not with a VM? I created a snapshot of a running VM - hoped to use `linked_clone` , unfortunately, i still get VM must be turned off.
