### ISSUE TITLE
Panic, unexpected EOF

### ISSUE THREAD

**Issue by movergan** [terraform-providers/terraform-provider-vsphere#550]
Hello,

Most of the actions fails with Terraform crash. 
For example terraform import:

terraform import module.s001waax00.vsphere_virtual_machine.app-vm[0] /DC1/vm/S001/s001waax000.domain.tld
module.s001waax00.vsphere_virtual_machine.app-vm: Importing from ID "/DC1/vm/S001/s001waax000.domain.tld"...
module.s001waax00.vsphere_virtual_machine.app-vm: Import complete!
  Imported vsphere_virtual_machine (ID: 42066dd9-38b1-ddce-4cc1-e6030bd365b3)
module.s001waax00.vsphere_virtual_machine.app-vm: Refreshing state... (ID: 42066dd9-38b1-ddce-4cc1-e6030bd365b3)

Error: module.s001waax00.vsphere_virtual_machine.app-vm[0] (import id: /DC1/vm/S001/s001waax000.domain.tld): 1 error(s) occurred:

* import module.s001waax00.vsphere_virtual_machine.app-vm[0] result: 42066dd9-38b1-ddce-4cc1-e6030bd365b3: vsphere_virtual_machine.app-vm: unexpected EOF

panic: runtime error: invalid memory address or nil pointer dereference

### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
provider.vsphere v1.6.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

https://www.dropbox.com/s/9dds2eiv6c29i0e/main.tf?dl=0
### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output:

2018-06-11T21:49:18.187+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4: github.com/terraform-providers/terraform-provider-vsphere/vsphere.flattenLatencySensitivity(0xc4201cc3f0, 0x0, 0x0, 0x0)
2018-06-11T21:49:18.187+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.6.0_x4:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-vsphere/vsphere/virtual_machine_config_structure.go:457 +0x22

### Panic Output

https://gist.github.com/movergan/3fce4e13c8d074956e1f6ae1f46463c4

### Expected Behavior

Terraform should import VM from vSphere

### Actual Behavior

Terraform crashed

### Steps to Reproduce

`terraform import module.s001waax00.vsphere_virtual_machine.app-vm[0] /DC1/vm/S001/s001waax000.domain.com`

### Important Factoids
N/A

**Comment by movergan** [comment]
looks like a duplicate of #531

**Comment by bill-rich** [comment]
@movergan Looks like you're right. I'll close this one and we can track it over there. Thanks!
