### ISSUE TITLE
Creating a virtual machine from template when I don't have a cluster

### ISSUE THREAD

**Issue by vioan** [terraform-providers/terraform-provider-vsphere#553]
Hello,

I have a template (created in vCenter with Clone -> Create Template from VM) and I would like to create a new virtual machine from it. I was looking and trying this example: 

[https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cloning-and-customization-example](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#cloning-and-customization-example)

but it seems that is not working because I don't have any cluster and the `resource_pool_id` seems mandatory for `vsphere_virtual_machine`.

Any idea how to create a virtual machine from a template when there is no `cluster` available?

Thank you very much.

**Comment by bill-rich** [comment]
Hi @vioan! In that case, you can use the host data source instead. Here is an example of what you would need to modify in that example. 

```
data "vsphere_host" "host" {
  name          = "host1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
...
  resource_pool_id = "${data.vsphere_host.host.resource_pool_id}"
...
}
```

See [here](https://www.terraform.io/docs/providers/vsphere/d/host.html) for more details on the host data source.

**Comment by vioan** [comment]
@bill-rich thank you very much for reply. I've got the resource pool with `govc find -type p` and then used the `vsphere_resource_pool` instead, and works :)
