### ISSUE TITLE
add support of VM hardware version upgrade

### ISSUE THREAD

**Issue by figo** [terraform-providers/terraform-provider-vsphere#557]
terraform vSphere does not support VM hardware version while working with vm template,

in my current working project: add vsphere support on CNCF cross-cloud CI: https://github.com/crosscloudci/cross-cloud
the vm template from coreos is with hardware version 7,
which limit the max vcpu to 8, but we need to set vm vcpu to larger than 8.

**Comment by bill-rich** [comment]
Hi @figo! Although I see how it could make management outside of vCenter easier, I think a better way to handle this issue would be to update the hardware version on the template. My concern with managing the hardware version through Terraform is that there could potentially be issues that need addressing that could not be communicated in a user friendly manner.

Having said that, I very well could just be overlooking a set of use cases, so if you have feedback, please let me know!
