### ISSUE TITLE
Lets use environment variables for authorization. Because HCL modules cannot access it.

### ISSUE THREAD

**Issue by belonesox** [terraform-providers/terraform-provider-vsphere#561]
Hello!

I try to follow Hashicorp TAO about "simple, modular, composable" and make my top-level terraform modules clean and minimal, with "module calls" like this:

    module "some-vmware-server" {
      source               = "./modules/vcenter-for-this.mycompany.com"
      vmname               = "science"
      memory               = "32768"
      disk                 = 512
      num_cpus             = "4"
    }

hiding 100500 lines of provider/datasources/resources/networks/templates about vmware and this vcenter  guts inside the module.

It will be great, but I can not. :(

Because  ``provider "vsphere" `` requires **user/password as input parameters**.

Consider all options:
* Hardcode password in module — NO
* Put some "terraform.tfvars" with password (out of VCS) inside module  — also bad, but not worked anyway — Terraform ignore terraform.tfvars inside modules.
* Define environment variable ``TF_VAR_vmpassword``  — not work inside modules, see https://github.com/hashicorp/terraform/issues/14874 

The only way is define environment variable ``TF_VAR_vmpassword/TF_VAR_vmpassword`` or put "terraform.tfvars"  on top level, and put a lot of trash in main module:

    variable "viuser" {}
    variable "vipassword" {}

plus  

    viuser     = "${var.viuser}"
    vipassword = "${var.vipassword}"

for each "call" for module.

----
* Why not use environment variables for authorization, like AWS plugin does (AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY)? 
* Why not use standard for VMWare environment variables  VSPHERE_USER/VSPHERE_PASSWORD?
  * Let this plugin check this variables, and if defined, NOT REQUIRE it?

… /vsphere/provider.go 

			"password": &schema.Schema{
				Type:        schema.TypeString,
				Required:    true,  → Optional:    true,

**Comment by belonesox** [comment]
Actually, I have found that putting providers inside modules is bad TF practice, according for https://www.terraform.io/docs/modules/usage.html#providers-within-modules 
and I have to define providers inside main module (and there is no need to put authorization inside modules).  

So this issue has low priority.

But IMO,  support for VSPHERE_USER/VSPHERE_PASSWORD still will be good.

**Comment by vancluever** [comment]
Hey @belonesox, what you are looking for is actually already available! The [provider docs](https://www.terraform.io/docs/providers/vsphere/index.html#argument-reference) document the environment variable equivalents to all of the provider-level config values. In this case, you are looking for `VSPHERE_USER` and `VSPHERE_PASSWORD`.

**Comment by belonesox** [comment]
Dear @vancluever 

* Provider Docs requires ``user`` and ``password`` params for ``vsphere`` provider.
* I tried to make them empty and override them with exported VSPHERE_USER and VSPHERE_PASSWORD
 but got 
``* provider.vsphere: error setting up new vSphere SOAP client: ServerFaultCode: Cannot complete login due to an incorrect user name or password.``

Is it bug or a feature?

**Comment by vancluever** [comment]
Hey @belonesox, our examples in the vSphere provider are usually as detailed as possible, so you will sometimes see values like this that are not necessarily needed or have environment variable aliases. The reason they are marked in the documentation as required is because they are - they need to be provided either via configuration or environment variables.

I think your problem is that is sounds like you are still providing them in confguration where you should not be. If you have something like:

```hcl
provider "vsphere" {
  user           = ""
  password       = ""
  vsphere_server = "vcenter.local"
}
```

Remove `user` and `password` altogether:

```hcl
provider "vsphere" {
  vsphere_server = "vcenter.local"
}
```

You could probably even forgo the entire thing, and just supply `VSPHERE_SERVER` along with the rest of the environment variables.

Note that it's still a good idea to version lock your provider, so you should be providing:

```hcl
provider "vsphere" {
  version = "~> 1.5"
}
```

**Comment by belonesox** [comment]
Sorry, I was sure, that I tried both variants, with ommited user/pass and emptied. 
I was wrong, you are right, it works with ommited user/pass. 
Thank you!

**Comment by vknemanavar** [comment]
Do we have enhanced plugin available to use authorization inside the module or do we need to continue to use environment variable for authorization?
