### ISSUE TITLE
Can't change disk type when provisioning from template

### ISSUE THREAD

**Issue by conorcasey** [terraform-providers/terraform-provider-vsphere#562]
ISSUE:-

I'm leveraging Terraform to provision vSphere VMs from a template for a customer. The template is thin provisioned and I want the provisioned VM to be Thick Lazy Zeroed. Based to the documentation the following should work:-

  disk {
    label = "${var.vsphere_disk0_label}"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub = false
    thin_provisioned = false
  }

However I get the following error:-

"vsphere_virtual_machine.vm: error reconfiguring virtual machine: error processing disk change post-clone: disk.0: cannot  change the value of "thin-provisioned" (old: true new: false)"

### Terraform Version

v0.11.7

### vSphere Provider Version

v1.5.0 x4

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

# Setup vSphere provider
provider "vsphere" {
  version        = "~> 1.4"
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  allow_unverified_ssl = "${var.vsphere_unverified_ssl}"
}

# Data sources for resources
data "vsphere_datacenter" "datacenter" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.vsphere_resource_pool}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "network" {
  name          = "${var.vsphere_network}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vsphere_template}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

# Create a vSphere VM
resource "vsphere_virtual_machine" "vm" {
  name             = "${var.vsphere_vm_name}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  scsi_type        = "${data.vsphere_virtual_machine.template.scsi_type}"

  # VM resources
  num_cpus = "${var.vsphere_cpus}"
  memory   = "${var.vsphere_memory}"

  #guest_id = "${var.vsphere_guest_id}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  disk {
    label = "${var.vsphere_disk0_label}"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub = false
    thin_provisioned = false
  }

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      windows_options {
        computer_name = "${var.vsphere_vm_name}"

      //  join_domain = "${var.vsphere_domain}"
      //  domain_admin_user = "${var.vsphere_domain_user}"
      //  domain_admin_password = "${var.vsphere_domain_password}"
        //domain_ou = "${var.vsphere_domain_ou}"
      }

      network_interface {
        ipv4_address = "${var.vsphere_ipv4_address}"
        ipv4_netmask = "${var.vsphere_ipv4_netmask}"
        dns_server_list = "${var.vsphere_dns_server_list}"
      }

      ipv4_gateway = "${var.vsphere_ipv4_gateway}"
    }
  }
}

### Debug Output

N/A

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing
the output of the `crash.log`.

### Expected Behavior

I would expect the disk type to be changed from thin-provisioed to thick-eager-zero. This is possible if provisioning a VM from a template directly in vCenter or via PowerCLI so I would assume is possible here in Terraform like the documentation suggests.

### Actual Behavior

See description under "ISSUE" at start of text.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Are there anything atypical about your infrastructure that we should know about
that could be causing an edge case or something not necessarily obvious? If so,
please state it here.

### References

Are there any other GitHub issues (open or closed) or Pull Requests that should
be linked here? For example:
- GH-1234

**Comment by bill-rich** [comment]
Hi @conorcasey! I was looking more closely at this and see there is a difference in what is possible through vCenter vs what can be done in Terraform. The tricky thing about implementing the ability to change disk type during the cloning process is that it needs to be applied to all disks, and isn't on a disk by disk basis.

This is something that can be implemented, it will just take a little reworking. I'm thinking the way it could be done would be to require that all the disks either match what is currently in the template, or to all have changed to a new and matching disk type. In the example you provided, it would work exactly as you'd hoped. The limitation would be when there are multiple disks in a template. Then you would not be able to set one to be thin and one to be thick lazy zeroed.

In the meantime, you could change the disk type in the source template to be thick lazy zeroed. That way you would be able to make clones with the desired disk type.

**Comment by conorcasey** [comment]
Hi Bill,

Thanks for the feedback. I want to make sure I understand you correctly so might be easier get confirmation this way -

 * currently the template I’m using only has one disk
 * making the template disk thin provisioned is not an option (due to design constraints of solution we are working on)

So with those two things in mind, should I be able to provision a vm from the template with a thick provisioned disk type? And if so, then how (as my current config is not working).

Thanks
Conor

Sent from my iPhone

On Jul 6, 2018, at 6:17 PM, Bill Rich <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @conorcasey<https://github.com/conorcasey>! I was looking more closely at this and see there is a difference in what is possible through vCenter vs what can be done in Terraform. The tricky thing about implementing the ability to change disk type during the cloning process is that it needs to be applied to all disks, and isn't on a disk by disk basis.

This is something that can be implemented, it will just take a little reworking. I'm thinking the way it could be done would be to require that all the disks either match what is currently in the template, or to all have changed to a new and matching disk type. In the example you provided, it would work exactly as you'd hoped. The limitation would be when there are multiple disks in a template. Then you would not be able to set one to be thin and one to be thick lazy zeroed.

In the meantime, you could change the disk type in the source template to be thick lazy zeroed. That way you would be able to make clones with the desired disk type.

**Comment by bill-rich** [comment]
You cannot currently switch from a thick disk to a thin disk during cloning using Terraform. It is a feature that shouldn't be too difficult to implement, but would require adding some additional validation to disk configs along with a change to the VM clone config.

Unfortunately, the only workaround I can think of with the existing limitations is to change the disk type of the template. If that isn't possible, I don't believe you will be able to accomplish what you're hoping for until the additional feature is added. Sorry for the inconvenience!

**Comment by conorcasey** [comment]
Understood, thanks for the clarification Bill. I think the documentation threw me off a little, but its clear to me now that that info is specific to provisioning a VM brand new and doesn't yet apply to provisioning from a template. Thanks again for your help.

**Comment by kaizoku0506** [comment]
@bill-rich - has this enhancement been implemented?  We are hitting the same issue (a thick provisioned template is ~30GB and thus significantly slower to clone compared to a thin provisioned template is ~1.2GB.).  If this is coming in a soon-to-be-released version, that would be fantastic news.

**Comment by chris-sanders-dot-org** [comment]
Is there a weird bug associated with this?

I have a case where a disk is Thick Provision Lazy Zeroed. Terraform gets this value from vSphere. 

`eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"`

The disk, when inspected in the web interface, is Thick Provisioned Lazy Zeroed. 

The Terraform state file has:

`"disk.0.thin_provisioned": "false"`

Yet when I run terraform plan I get:
`module.globalrelay.vsphere_virtual_machine.vm[0]: disk.0: virtual disk "graphiteglobalrelaydev_0": cannot change the value of "thin_provisioned" - (old: false new: true)`

No idea where new: true could possibly be coming from.

**Comment by thetuxkeeper** [comment]
I think it's a strange behavior of vSphere. At least the value of "thin provisioned" changes over the time. I think in my case the disk was full at least once, so "thin provisioned" doesn't really apply anymore (if you see it as a state). But it's annoying that, what is believed to be a setting, is also some kind of state.
I don't have thick provisioned disks, but I think it's the same setting/state source, so there could be events that change eagerly_scrub to thin_provisioned too (perhaps trim commands inside the vm?)

**Comment by bbecomp99** [comment]
I had the exact same issue, its pulling values from the template to get the provisioning values. If you vmotion the asset without using TF, TF is not aware of the change, and is pretty much effed. My fix was to edit the state file to the proper (new) values then re run the plan. 

Error: disk.0: virtual disk "disk0": cannot change the value of "thin_provisioned" - (old: true new: false)

  on qmac-2/qa_win.tf line 29, in resource "vsphere_virtual_machine" "vm1":
  29: resource "vsphere_virtual_machine" "Terraform" {

Worked great.
