### ISSUE TITLE
Cloning from template in folder

### ISSUE THREAD

**Issue by koboldul** [terraform-providers/terraform-provider-vsphere#567]
Hi,

I'm trying to clone a machine from template using terraform with vsphere provider. 

when doing terraform apply:
If I don't specify a folder for my vm resource I get Permission denied. 
If I specify a folder I get vsphere_virtual_machine.xxx: folder '/DataCenter/vm/Dev-vm/zzz/Temp VMs/yyy' not found. Before confirming the plan shows that will add a resource.

If I use: ```terraform import vsphere_folder.folder "/DataCenter/vm/Dev-vm/zzz/Temp VMs/yyy" ```
nothing gets created; no error.

I would really appreciate if someone can point at what I'm doing wrong or if there is something wrong with the folders in the vsphere provider. I must mention that I double checked all the id's that are populating the tfstate using power CLI and all of them check. The path exist the proper resources are found.
I also have permissions for the folder in cause but not for the root of datacenter.. 

Terraform v0.11.7
+ provider.vsphere v1.6.0

Here is the instance.tf

``` Ruby 
data "vsphere_datacenter" "dc" {
  name = "DataCenter"
}

data "vsphere_datastore" "datastore" {
  name          = "DEV_2TB_06"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "Test Cluster 1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "VLAN 117"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "pq-template"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

#terraform import vsphere_folder.folder "/DataCenter/vm/Dev-vm/zzz/Temp VMs/yyy" 

resource "vsphere_virtual_machine" "xxx" {
  name = "xxx"

  folder           = "/DataCenter/vm/Dev-clean/zzz/Temp VMs/yyy"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      windows_options {
        computer_name         = "win16test1"
        join_domain           = "ddd.dd"
        domain_admin_user     = "some_user@ddd.dd"
        domain_admin_password = "pwd"
      }
    }
  }
}
```
Thank you

Bogdan

**Comment by koboldul** [comment]
```terraform apply -auto-approve```

I've attached the trace output . It is weird because the template is found within the same path.

[terra.log](https://github.com/terraform-providers/terraform-provider-vsphere/files/2236031/terra.log)

**Comment by koboldul** [comment]
Thank you for the advice bill...unfortunately is
 not working . I have also taken out everything except the data center and  try to create a folder in a known path just to simplify the things.

```Ruby
provider "vsphere" {
  user           = "${var.viuser}"
  password       = "${var.vipassword}"
  vsphere_server = "${var.viserver}"

  # if you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "datacenter"
}

terraform import vsphere_folder.folder "/datacenter/vm/Dev-clean/ERP/Temp VMs/BVC"
resource "vsphere_folder" "NF" {
  path          = "${vsphere_folder.folder.path}/NF"
  type="vm"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}


```

Ap2018/08/04 09:09:57 [DEBUG] plugin: waiting for all plugin processes to complete...
ply complete! Resources: 0 added, 0 changed, 0 destroyed.
2018-08-04T09:09:57.147-0400 [WARN ] plugin: error closing client during Kill: err="unexpected EOF"

Is this the correct way? Again, if i take out the import and simply use the path the plan shows that a resource will be added but the apply fails with 'folder not found'.

Thank you

**Comment by bill-rich** [comment]
The importing can be a little tricky. Especially with folders since you need to use the complete path in the import command, but the relative path in the config. In your case, you would need to following:

1) Put the folder to be imported in your Terraform config
```
resource "vsphere_folder" "folder" {
  path                =  "Dev-clean/ERP/Temp VMs/BVC" // This path is relative
  type                = "vm"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}
```
2) Run the import command
`terraform import vsphere_folder.folder /datacenter/vm/Dev-clean/ERP/Temp VMs/BVC`
3) Run `terraform plan` to make sure the state for the new folder matches the configuration
4) Then add in the `vsphere_virtual_machine.tarraform_notWk2`or `vsphere_folder.NF`  resource with the reference to `vsphere_folder.folder.path`.

**Comment by bill-rich** [comment]
@koboldul Thats strange. I'd like to try and narrow down exactly where the problem is. Would it be possible to use govc to check where things are breaking down for you? Getting the output of the following would be very helpful.

`govc ls /`
`govc ls /datacenter`
`govc ls /datacenter/vm`
`govc ls /datacenter/vm/Dev-clean`

With that info, we should be able to figure out the next steps to get this sorted out.

Thanks for taking the time to work through this with me!

**Comment by koboldul** [comment]
This is really interesting. 
 I did 
```govc ls /datacenter/vm/Dev-clean```
Nothing came. Looked one level up and i see DEV-clean (not Dev-clean)
then:
```govc ls /datacenter/vm/DEV-clean```
I get all the folders under. I run 
```terraform import vsphere_folder.folder /Waterloo/vm/DEV-clean```
Import works fine then when apply i get the NF folder created.(later also the vm starts beeing created it just fails on some network setup whichI have to sort out).
Now i run 
```govc ls /datacenter/vm/DEV-clean```
Nothing.
I run 
```govc ls /datacenter/vm/Dev-clean``` - folders are showing.

This is extremely confusing. Thanks for taking the time to analyze this and for showing me the govc tool ; seems to be more useful than power cli.
Let me know If you want me to do some more investigations.
