### ISSUE TITLE
Distributed Port Group -- Count

### ISSUE THREAD

**Issue by austin-millan** [terraform-providers/terraform-provider-vsphere#568]
Hi there! I believe this is is a new issue for this provider, as a search on closed/open issues didn't return any results. 

### Terraform Version
```
$ terraform --version
Terraform v0.11.7
```

### vSphere Provider Version
```
+ provider.vsphere v1.6.0
```

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_distributed_port_group`

### Issue

The `count` param doesn't apply to the affected resource, which I believe it should. 

Without this parameter, it is currently difficult to configure a setup with a large number of distributed port groups over distributed virtual switches.

**Comment by bill-rich** [comment]
Hi @austin-millan! You should be able to use `count` with `vsphere_distributed_port_group`. Thats odd that it isn't working for you. Can you please provide an example of your configuration and the error you're receiving?

Thanks!

**Comment by austin-millan** [comment]
You're totally right, I actually ran into an error a few months ago when I first started using Terraform so I think it was just user error. `count` works for port groups. Thanks for getting back to me about this..
