### ISSUE TITLE
Problem with deploy other machine via VShpere

### ISSUE THREAD

**Issue by adrslaw** [terraform-providers/terraform-provider-vsphere#572]
Hi I have small problem. 
I with success deploy one of machine with terraform, but if i want to deploy other one, the configuration thinks that i want to change this existing machine state.
How can I create the other machine? 
I try changing a localization of configure files etc. 

Thank for any help ;)

**Comment by bill-rich** [comment]
Hi @adrslaw! It sounds like you are using the same resource name in a different configuration file. When this happens, Terraform is seeing that `vsphere_virtual_machine.vm_example1` has been changed, and attempts to update it. What you want is for `vsphere_virtual_machine.vm_example1` and `vsphere_virtual_machine.vm_example2` to both exist.

Here is an example of how to do that:
```
data "vsphere_datacenter" "dc" {
  name = "dc1"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "cluster1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "public"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "terraform-resource-name1" {
  name             = "name-that-shows-up-in-vcenter2"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }
}

resource "vsphere_virtual_machine" "terraform-resource-name2" {
  name             = "name-that-shows-up-in-vcenter2"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2
  memory   = 1024
  guest_id = "other3xLinux64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 20
  }
}
```

The nice thing about this type of configuration is that it should accurately describe what you have deployed, and each time you run a `terraform apply`, you are making sure that everything is in sync. 

Hope this helps!
