### ISSUE TITLE
vsphere_virtual_machine - cannot find OS family for guest ID "ubuntu64Guest": NoPermission

### ISSUE THREAD

**Issue by Koleon** [terraform-providers/terraform-provider-vsphere#577]
Hello guys,

I run into following error when execute terraform plan.

### Terraform Version
```
$ tf version
Terraform v0.11.7
+ provider.vsphere v1.6.0
```

### vSphere Provider Version
```
$ terraform providers
.
└── provider.vsphere ~> 1.6
```
### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`
- `vsphere_resource_pool`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "ubuntu" {
  #count            = "${var.ubuntu_count}"
  count            = "${terraform.workspace == "default" ? "${var.ubuntu_count}" : 0}"
  name             = "${element(local.ubuntu_names, count.index)}-ubuntu"
  resource_pool_id = "${local.pool_name}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  num_cpus         = 1
  memory           = 1024
  folder           = "${local.cycz_folder}"
  depends_on 	   = ["vsphere_folder.folder"]
  guest_id         = "${data.vsphere_virtual_machine.ubuntu.guest_id}"
  scsi_type        = "${data.vsphere_virtual_machine.ubuntu.scsi_type}"
  network_interface {
    network_id = "${data.vsphere_network.pisecek.id}"
  }
  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.ubuntu.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.ubuntu.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.ubuntu.disks.0.thin_provisioned}"
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.ubuntu.id}"
    customize {
      linux_options {
        host_name = "${element(local.ubuntu_names, count.index)}"
        domain    = "cycz.test"
      }
      network_interface {
        ipv4_address = "${local.pisecek_ip_prefix}.${element(local.ubuntu_ip_rest_fields, count.index)}"
        ipv4_netmask = 24
      }
      ipv4_gateway   = "${local.pisecek_gtw}"
      dns_server_list = ["1.1.1.1", "1.0.0.1"]
    }
  }
}
```

### Debug Output

https://gist.github.com/Koleon/f38ce00ab765ba27db2f30ec331096f1

### Expected Behavior

Deploy VMs

### Actual Behavior

`$ terraform plan` end up with errors.

### Steps to Reproduce
`terraform apply`

### Important Factoids
We actually migrate most of our VMs on new VMware Version 6.5.0.13000 including VMware roles and set it properly. Unfortunately the same main.tf works only against the old VMware Version 6.5.0.10000. 
When I try to deploy VM manually from the same template to the same directory, it works.
Is there anyway how to debug the problem with permission more verbosely please?
Thank you for any hint.

**Comment by Koleon** [comment]
After a few hours of investigation and digging into VMware permission. I figure it out that I missed one VMware read-only role for my datastore.

**Comment by paddycarver** [comment]
Awesome, thanks for the update. Closing this out.

**Comment by timcrall** [comment]
@Koleon what was the missing role?

**Comment by pdkreid** [comment]
@Koleon Running into this same issue. Can specify which role you had to add to make this work? @timcrall did you ever figure out what role was needed?

**Comment by Koleon** [comment]
Hello @timcrall, @pdkreid,
sorry it took me while. I'm not a hundred percent sure there days, but I guess it was Read-only role for the specific datastore I tried to deploy the VM to. And another Read-only was required on the Datacenter.

**Comment by conallab24** [comment]
This is what I changed.
ESX Agent Manager Privileges > View
Host Profile > View
Storage View > View
