### ISSUE TITLE
vsphere_virtual_machine/template_uuid possible race condition

### ISSUE THREAD

**Issue by failshell** [terraform-providers/terraform-provider-vsphere#589]
### Terraform Version

Terraform v0.11.7

### vSphere Provider Version

provider.vsphere v1.6.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

template module

```hcl
module "template" {
    source = "./modules/template/"

    # base
    user             = "${var.vsphere_user}"
    password         = "${var.vsphere_pass}"
    server           = "${var.vsphere_server}"

    # vsphere
    datacenter       = "${var.dc}"
    folder           = "${vsphere_folder.user_lab.path}"
    dvs_id           = "${data.vsphere_distributed_virtual_switch.dvs.id}"
    resource_pool_id = "${data.vsphere_resource_pool.root.id}"
    datastore_id     = "${data.vsphere_datastore.ds.id}"
    mgmt_network_id  = "${data.vsphere_network.mgmt.id}"

    # networking
    mgmt_subnet    = "${var.mgmt_subnet}"
    switch_ips_map = "${var.switch_ips_map}"

    # templates
    veos_template_name           = "${var.veos_template_name}"
    veos_iso_name                = "${var.veos_iso_name}"
    veos_template_uuid           = "${data.vsphere_virtual_machine.veos.id}"
    veos_template_guest_id       = "${data.vsphere_virtual_machine.veos.guest_id}"
    veos_template_interface_type = "${data.vsphere_virtual_machine.veos.network_interface_types[0]}"
}
```

the template module has this output

```hcl
output "vm_id" {
    value = "${vsphere_virtual_machine.template.id}"
}
```

the template uuid is then feed to another module

```hcl
module "router_couple_1" {
    source = "./modules/simple_couple/"

    # base
    user             = "${var.vsphere_user}"
    base_name        = "foo"
    model            = "bar"
    pair_members_map = "${var.pair_members_map}"

    # vsphere
    folder           = "${vsphere_folder.user_lab.path}"
    dvs_id           = "${data.vsphere_distributed_virtual_switch.dvs.id}"
    resource_pool_id = "${data.vsphere_resource_pool.root.id}"
    datastore_id     = "${data.vsphere_datastore.ds.id}"
    mgmt_network_id  = "${data.vsphere_network.mgmt.id}"

    # networking
    mgmt_subnet    = "${var.mgmt_subnet}"
    switch_ips_map = "${var.switch_ips_map}"

    # templates
    veos_template_name           = "${module.template.name}"
    veos_iso_name                = "${var.veos_iso_name}"
    veos_template_uuid           = "${module.template.vm_id}"
    veos_template_guest_id       = "${data.vsphere_virtual_machine.veos.guest_id}"
    veos_template_interface_type = "${data.vsphere_virtual_machine.veos.network_interface_types[0]}"

    build_after = [
        "${module.gateway_couple_1.vm_ids}"
    ]
}
```

the second module receives the uuid and uses it in a vsphere_virtual_machine resource like this:

```hcl
clone {
        template_uuid = "${var.veos_template_uuid}"
}
```

### Debug Output

```
Error: Error running plan: 1 error(s) occurred:

* module.router_couple_1.vsphere_virtual_machine.switch: 2 error(s) occurred:

* module.router_couple_1.vsphere_virtual_machine.switch[1]: cannot locate virtual machine or template with UUID "": virtual machine with UUID "" not found
* module.router_couple_1.vsphere_virtual_machine.switch[0]: cannot locate virtual machine or template with UUID "": virtual machine with UUID "" not found
```

### Expected Behavior

I thought Terraform would see that it's waiting for the template module to be processed before checking if template_uuid is valid or not. If I create the template first, then it works.

### Actual Behavior

template_uuid is validated before the first module is done processing.

### Steps to Reproduce

The error happens when running `terraform plan`.

**Comment by bill-rich** [comment]
Hi @failshell! Sorry you're running into this issue. You should be able use an ID from a virtual machine data source or resource and have the dependencies properly calculated. I'll look more into what is happening in this situation and see if I can find a solution for you.

**Comment by bill-rich** [comment]
The reason you're running into this issue is that the UUID from the first module is not available until after it is created, but validation needs to be done on the second during the planning process. I've removed some of the restrictions on this in v1.12.0 of the provider, but `template_uuid` is still required at planning time as there are many necessary checks that are needed before creation can begin.

The best way to work around this is to apply you plan in stages. First just apply the template module, and then re apply with the full config.
