### ISSUE TITLE
Update govmomi library

### ISSUE THREAD

**Issue by ondj** [terraform-providers/terraform-provider-vsphere#591]
This provider currently uses govmomi library v 0.15, but latest version is 0.18 (https://github.com/vmware/govmomi/releases). The new version fixes provider segfault when bad persmission is set for network switch (see https://github.com/vmware/govmomi/issues/1035).

**Comment by bill-rich** [comment]
Thanks @ondj! I'll be running the acceptance tests with 0.18 to make sure we don't run into any problems and hopefully will be using the new version in the next release.

**Comment by bill-rich** [comment]
Updated govmomi in #600.
