### ISSUE TITLE
Remove computer object from active directory when terraform destroy is run

### ISSUE THREAD

**Issue by whiggs** [terraform-providers/terraform-provider-vsphere#598]
I noticed that when terraform destroy is run on domain joined machines, the machines are not removed from active directory.  So, I was thinking it would be very useful if terraform, when a vm is destroyed using terraform destroy, would also remove the active directory computer object associated with the destroyed machine if "join_domain" is configured for that particular vsphere_virtual_machine" resource.

### Terraform Version

Terraform v0.11.8

### vSphere Provider Version

+ provider.vsphere v1.6.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
	provider "vsphere" {
	user           = "user"
	password       = "password"
	vsphere_server = "vcenter-test.domain.com"

  # If you have a self-signed cert
	allow_unverified_ssl = true
}

	data "vsphere_datacenter" "dc" {
	name = "Test Environment"
}

	data "vsphere_datastore" "datastore" {
	name          = "NFS_CDOTSAS_Busintellocal"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

	data "vsphere_compute_cluster" "compute_cluster" {
	name          = "Test Environment"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

	data "vsphere_network" "network" {
	name          = "Production"
	datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

	data "vsphere_virtual_machine" "template" {
		name	= "Templates/vagrbase"
		datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

	resource "vsphere_virtual_machine" "vm" {
	name             = "terraform-test"
	folder			 = "B.Local/Hyperion"
	resource_pool_id = "${data.vsphere_compute_cluster.compute_cluster.resource_pool_id}"
	datastore_id     = "${data.vsphere_datastore.datastore.id}"

	num_cpus = 4
	memory   = 12288
	guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

	scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

	network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  clone {
  template_uuid = "${data.vsphere_virtual_machine.template.id}"
  customize {
       network_interface {}
	windows_options {
		computer_name  = "terraform-test"
		admin_password = "password"
	        join_domain = "domain.com"
		domain_admin_user = "user"
		domain_admin_password = "password"
	}
  }
}
}
```

### Expected Behavior

The computer object in active directory is removed

### Actual Behavior

The computer object in active directory still exists.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform destroy on a domain-joined vm`

### Important Factoids

vsphere vCenter Server Version 5.5.0

**Comment by bill-rich** [comment]
Hi @whiggs! I think that is a really good idea with a lot of potential. Unfortunately, managing AD is outside of the scope of this provider. 

Even using something like an AD provider in conjunction with the vSphere provider would probably not cover your use case since the object is being created from the virtual machine joining the domain. You would need to be able to import that into the Terraform state after the customization was done. 

I recommend looking into using a local-exec destroy provisioner to execute a script which could destroy the object in AD.
