### ISSUE TITLE
Continuation of issue #598

### ISSUE THREAD

**Issue by whiggs** [terraform-providers/terraform-provider-vsphere#601]
Hold on one second.  How can you tell me with a straight face that "managing ad is outside the scope of this provider" when this provider has the "join_domain" option which joins the computer to a domain?!?   If you read my post, all I was recommending was that the provider remove the computer from the domain **if and only if** the vm had been joined to a domain using the "join_domain" built into the provider, which is not only well within terraform's capabilities, I would argue is most definately within the scope of the provider.  If its not, then remove the "join_domain" option.  I would not expect the provider to remove devices from a domain that were added by any other means, but if you are going to include a feature which joins devices to a domain, don't tell me that you can't remove the device from the domain when terraform destory is run because it is outside the scope of the provider.  I have neither the time nor patience for these ludicrous games, so I would ask that they stop being played.

**Comment by rismoney** [comment]
I would say, I am against this feature as a Windows admin since I never want TF talking to AD.


This might also be of interest - https://github.com/GSLabDev/terraform-provider-ad

One final note - try not to be so confrontational.  There are really nice people here trying to help people out. I have nothing to do with Hashicorp or this project, but I just thought your post was abrasive without cause.

**Comment by bill-rich** [comment]
Hi @whiggs. I apologize for not explaining the situation better in #598.

As @rismoney said in his explanation, the the vSphere provider is not actually touching AD at all. It is only working through the vSphere APIs. The API provides a method to pass identification data to sysprep through the [CustomizationIdentification object](https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.customization.Identification.html), but there isn't a way to remove the computer through the vSphere API.

To remove a computer, we would need to interact directly with AD. Unfortunately, managing AD is outside the scope of the vSphere provider. What I mean by this is that: Terraform providers generally only auth and hit a single set of APIs. This change would require we also include an AD client and AD auth mechanism into the vSphere provider. This would be very non-idiomatic for a provider to do. I think the best way to handle your use case would be with the local-exec provisioner. For the PowerShell script, you could have something like:
```
Remove-Computer -ComputerName $args[0] -UnjoinDomainCredential Domain01\Admin01 -WorkgroupName "Local" -Force
```

And then in your Terraform config you could have the following:

```
var "name" {
  default = "terraform-test"
}
...
resource "vsphere_virtual_machine" "vm" {
  ...
  provisioner "local-exec" {
    when    = "destroy"
    command = "C:\\path\\remove_from_ad.ps1 ${var.name}"
    interpreter = ["PowerShell"]
  }
}
```

Again, I'm sorry for the confusion on this. I understand how it seems very counter intuitive to be able to join a domain through the provider, but not able to remove the computer later. I hope the explanation clears things up for you. Please let me know if you have any other questions I can answer!
