### ISSUE TITLE
Terraform doesn't allow ignore_changes for template_uuid

### ISSUE THREAD

**Issue by kaizoku0506** [terraform-providers/terraform-provider-vsphere#604]
### Terraform Version

- Terraform v0.11.7

### vSphere Provider Version

- provider.vsphere v1.6.0

### Affected Resource(s)

- vsphere_virtual_machine

### Terraform Configuration Files

*main.tf*
```
resource "vsphere_virtual_machine" "tfvm" {
  count               = "${var.vsphere_vm_count}"
  name                = "tfvm${count.index+1}.${var.vsphere_vm_domain}"  
  resource_pool_id    = "${data.vsphere_resource_pool.resource_pool.id}"
  datastore_id        = "${data.vsphere_datastore.datastore.id}"
  num_cpus            = "${var.vsphere_vm_cpu}"
  memory              = "${var.vsphere_vm_ram}"
  guest_id            = "${data.vsphere_virtual_machine.vm_template.guest_id}"
  scsi_type           = "${data.vsphere_virtual_machine.vm_template.scsi_type}"

  network_interface {
    network_id        = "${data.vsphere_network.net.id}"
    adapter_type      = "${data.vsphere_virtual_machine.vm_template.network_interface_types[0]}"
  }

  disk {
    label             = "disk0"
    size              = "${data.vsphere_virtual_machine.vm_template.disks.0.size}"
    eagerly_scrub     = "${data.vsphere_virtual_machine.vm_template.disks.0.eagerly_scrub}"
    thin_provisioned  = "${data.vsphere_virtual_machine.vm_template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid     = "${data.vsphere_virtual_machine.vm_template.id}"

    customize {
      linux_options {
        host_name     = "tfvm${count.index+1}"
        domain        = "${var.vsphere_vm_domain}"
      }

      network_interface {
        ipv4_address  = "${var.vsphere_vm_ip_address["${count.index}"]}"
        ipv4_netmask  = "${var.vsphere_vm_ip_netmask}"
      }

      ipv4_gateway    = "${var.vsphere_vm_ip_gateway}"
      dns_server_list = ["${var.vsphere_vm_dns_servers}"]
      dns_suffix_list = ["${var.vsphere_vm_domain}"]
    }
  }

  lifecycle {
    ignore_changes = [
      "cluster",
      "disk",
      "resource_pool_id",
      "template_uuid",
    ]
  }
}
```

*data_sources.tf*
```
data "vsphere_datacenter" "dc" {
  name              = "${var.vsphere_vm_datacenter}"
}

data "vsphere_resource_pool" "resource_pool" {
  name              = "/${var.vsphere_vm_datacenter}/host/${var.vsphere_vm_compute_cluster}/Resources/${var.vsphere_vm_resource_pool}"
  datacenter_id     = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name              = "${var.vsphere_vm_compute_cluster}"
  datacenter_id     = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "datastore" {
  name              = "${var.vsphere_vm_datastore}"
  datacenter_id     = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "vm_template" {
  name              = "${var.vsphere_vm_template}"
  datacenter_id     = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "net" {
  name              = "/${var.vsphere_vm_datacenter}/network/${var.vsphere_vm_network}"
  datacenter_id     = "${data.vsphere_datacenter.dc.id}"
}
```

*variables.tf*
```
variable "vsphere_password" {
  type = "string"
  description = "Password used to connect to the vSphere instance"
  default = "default"
}

variable "vsphere_server" {
  type = "string"
  description = "FQDN for the vSphere instance"
  default = "default"
}

variable "vsphere_user" {
  type = "string"
  description = "User used to connect to the vSphere instance"
  default = "default"
}

variable "vsphere_vm_compute_cluster" {
  type = "string"
  description = "Compute cluster onto which the VMs will be deployed"
  default = "default"
}

variable "vsphere_vm_count" {
  type = "string"
  description = "the number of VMs to deploy"
  default = "1"
}

variable "vsphere_vm_datacenter" {
	type = "string"
	description = "vSphere datacenter into which VMs will be deployed"
	default = "default"
}

variable "vsphere_vm_datastore" {
  type = "string"
  description = "Datastore LUN onto which VMs will be deployed"
  default = "default"
}

variable "vsphere_vm_dns_servers" {
  type = "list"
  default = ["10.1.2.3", "10.2.3.4"]
}

variable "vsphere_vm_domain" {
  type = "string"
  default = "default"
}

variable "vsphere_vm_name" {
  type = "string"
  default = "default"
}

variable "vsphere_vm_network" {
  type = "string"
  description = "VM_Network or equivalent for 1G traffic"
  default = "default"
}

variable "vsphere_vm_resource_pool" {
	type = "string"
	description = "vSphere resource pool into which VMs will be deployed"
  default = "default"
}

variable "vsphere_vm_template" {
  type = "string"
  description = "VM template to use for deployment"
  default = "default"
}

variable "vsphere_vm_ip_address" {
  type = "list"
  default = ["10.228.170.87", "10.228.170.88", "10.228.170.89", "10.228.170.90", "10.228.170.91"]
}
```

### Expected Behavior

Changes to the VM Template (referenced by name in the data_sources.tf file as `vsphere_virtual_machine.vm_template.name` and then in main.tf as `template_uuid` should not trigger a rebuild of existing VMs.

### Actual Behavior

`terraform plan` results in:
`Plan: 2 to add, 0 to change, 2 to destroy.`

`template_uuid` is forcing the new resource:
`clone.0.template_uuid:                                "564dbefa-8a99-1aad-542d-a1e751c5beba" => "564dc68c-99ba-dce2-4d68-920cd9528027" (forces new resource)`

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change variable for VM Template name
3. `terraform plan`

### Environmental Specifics

All variables are passed in through environment variables using Direnv:
- `TF_VAR_vsphere_password`             - The password for the vSphere_user
- `TF_VAR_vsphere_server`               - The vSphere FQDN (Either vCenter Server or a single ESXi host will suffice.  Do not include `https://`)
- `TF_VAR_vsphere_user`                 - The user account used to connect to the vSphere instance
- `TF_VAR_vsphere_vm_compute_cluster`   - The VMware host cluster onto which VMs should be deployed (currently must be the same for all VMs in a given project)
- `TF_VAR_vsphere_vm_count`             - The number of VMs to deploy
- `TF_VAR_vsphere_vm_datacenter`        - The VMware Datacenter into which VMs should be deployed (currently must be the same for all VMs in a given project)
- `TF_VAR_vsphere_vm_datastore`         - The VMware datastore onto which VMs should be deployed (currently must be the same for all VMs in a given project)
- `TF_VAR_vsphere_vm_domain`            - The domain for any resulting VMs (currently must be the same for all VMs created in a given project)
- `TF_VAR_vsphere_vm_network`           - The VMware network to which created VMs should connect (currently must be the same for all VMs in a given project)
- `TF_VAR_vsphere_vm_resource_pool`     - The VMware Resource Pool into which VMs should be deployed (currently must be the same for all VMs in a given project)
- `TF_VAR_vsphere_vm_template`          - The VM template to be used for cloning VMs (currently must be the same for all VMs in a given project)

**Comment by bill-rich** [comment]
Hi @kaizoku0506! The reason `template_uuid` is not being ignored is that it is actually a part of the `clone` sub resource. In order to ignore it, you need to instead use 'clone.0.template_uuid`. That way, you are specifying that `template_uuid`, which is part of the first `clone` sub resource, should be ignored.

I know the ideal use case is often not the real world one, but I just wanted to make sure to warn about being careful when using `ignore_changes` because then your configuration is no longer an accurate reflection of your infrastructure.

**Comment by rismoney** [comment]
My guess is OP wants to update template without forcing new release.  The workaround for this is using a static uuid for the guests instead of querying the template for the data template id.  Then existing nodes never get modified on template rebuilds.  I ran into the same thing, as I use packer for template generation.

**Comment by lapfrank12** [comment]
Hi @kaizoku0506. Did you ever find a solution for this?

@rismoney. I ran into the same problem here. I was wondering how you deal with obsolete templates & cleanup if you hard code the template_uuid? Are you keeping an infinite number of templates to ensure the template_uuid you specified is always valid? I usually keep 2 versions of templates at a maximum which are re-generated weekly.

I'm not sure how to prevent forced rebuilds in that case outside of manually changing the terraform state file which is definitely not what I'd want to do.

Thanks,
