### ISSUE TITLE
How we can do IP management in vsphere provider

### ISSUE THREAD

**Issue by vknemanavar** [terraform-providers/terraform-provider-vsphere#607]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.11.7
+ provider.vsphere v1.7.0

### vSphere Provider Version
+ provider.vsphere v1.7.0
### Affected Resource(s)

how can we do IP management using vsphere provider

**Comment by bill-rich** [comment]
Hi @vknemanavar! Can you provide some more details on what you are looking to be able to do?

**Comment by vknemanavar** [comment]
I am using vsphere provider to provision VM on vCenter, currently I am passing IP and hostname manually while provisioning the VM, I want to know if vsphere provider has any feature to automate to pick IP and hostname?

**Comment by surajsub** [comment]
@vknemanavar - you could adjust the template to first make a call to an ipam provider which will return an ip / gateway / subnet information and use that as input to the vsphere provider.

**Comment by rismoney** [comment]
I've wondered about this, do you need to assign Mac addresses to do this reliably? My guess is you won't be able to get this to be idempotent otherwise.

**Comment by vknemanavar** [comment]
@surajsub  - Do you know any IPAM which is supported by Terraform?

**Comment by bill-rich** [comment]
I don't know that we have any official providers for an IPAM service, but I believe there are some community providers. We don't do any testing of community providers, but you can usually do a search online for the service you're looking to use and "terraform provider" to see if any are available. At first glance, I was able to find: https://github.com/prudhvitella/terraform-provider-infoblox. 

You can also check out our official providers to see if I've overlooked anything at https://www.terraform.io/docs/providers/index.html.
