### ISSUE TITLE
terraform doesn't close sessions after using it

### ISSUE THREAD

**Issue by anfernee** [terraform-providers/terraform-provider-vsphere#618]
### Terraform Version
```console
terraform -v
Terraform v0.11.8
```

### vSphere Provider Version
```console
terraform providers
.
├── provider.template ~> 1.0.0
└── provider.vsphere ~> 1.5.0
```

### Affected Resource(s)
None

### Terraform Configuration Files
n/a 

### Expected Behavior
terraform should close the session after the command is finished. 

### Actual Behavior
```console
govc object.collect -json -s SessionManager:SessionManager sessionList | jq '.[].Val | .UserSession | .[] | .IpAddress' | sort | uniq -c | sort -rn
      1 "100.116.232.47"
terraform apply
# ...
govc object.collect -json -s SessionManager:SessionManager sessionList | jq '.[].Val | .UserSession | .[] | .IpAddress' | sort | uniq -c | sort -rn
      2 "100.116.232.47"
terraform apply
# ...
govc object.collect -json -s SessionManager:SessionManager sessionList | jq '.[].Val | .UserSession | .[] | .IpAddress' | sort | uniq -c | sort -rn
      3 "100.116.232.47"
```

### Steps to Reproduce
Described above

**Comment by vancluever** [comment]
Hey @anfernee, this is currently a challenge to do in the existing Terraform provider architecture. We looked into this earlier this year when working on the [session persistence support](https://github.com/terraform-providers/terraform-provider-vsphere/pull/422).

In the current Terraform provider architecture, [`ResourceProvider.Configure`](https://github.com/hashicorp/terraform/blob/3776e6ddc956a603e32f7d0d197a83618f880f39/terraform/resource_provider.go#L54-L60) is called to set up the provider - this is usually where provider connections are set up. This returns immediately so it's hard to do things like defer logouts here, etc. Unfortunately, there is no teardown hook right now in `ResoruceProvider`, so there's no way to terminate any connections that may be running at the time on plugin shutdown.

I would personally not want to fight the interface here with workarounds (ie: a goroutine that watches for the specific signals that get sent on graceful plugin shutdown might be viable, but that's not necessarily a stable API), so while I can't necessarily speak for the rest of the team on this one, I would say that the current behavior won't change until it's possible to hook into the plugin shutdown process somehow. The best thing that I can recommend is that if you are running into session scalability issues, you look into the persistence options outlined [here](https://www.terraform.io/docs/providers/vsphere/index.html#session-persistence-options).

Thanks!

**Comment by anfernee** [comment]
@vancluever Hi Chris, thanks for the quick response. Agreed with everything you said. A workaround is the last thing I want. I also spent some time looking into an interface to properly close the session. I noticed the provider has an interface called `ResourceProviderCloser` defined here: 
https://github.com/hashicorp/terraform/blob/d4ac68423c4998279f33404db46809d27a5c2362/terraform/resource_provider.go#L187:6
and used here: https://github.com/hashicorp/terraform/blob/d4ac68423c4998279f33404db46809d27a5c2362/terraform/eval_context_builtin.go#L121 

I thought it was what I want, and I briefly wrote this: https://github.com/anfernee/terraform-provider-vsphere/commit/9d4e0d2506bb59b7bd65c598db928eced4780d3e but it doesn't seem to work as expected. but I don't have time to dig deeper. Is that interface not intended for provider resource release?

**Comment by vancluever** [comment]
@anfernee many apologies! I should have knew about that interface.

The closer definitely appears to be what should be implemented to perform this. Did you try to add any logging to see if the closer was actually firing (like even a simple `log.Println` in `Close`)? Have you checked to see if `govc session.logout` works as well as I think that uses the logout functionality?

In any case - knowing that this can be hooked into the existing API helps greatly. I still can't say exactly _when_ this will be implemented but there's an obvious difference considering we now have a good idea of what exact work needs to be done, barring any particular debugging that's necessary to make it happen.

**Comment by anfernee** [comment]
I tried `client.Logout`, it will reduce the session number. I think the function didn't get called for some reason. Does `log.Println` in provider binary make it to stdout? If it does, it would definitely help for debugging. Knowing that this is the right path, I'll spend more time to make the patch and send a PR later.

**Comment by vancluever** [comment]
@anfernee amazing! :grinning: We'll keep an eye out for it.

Regarding the logging - using `log` is the general accepted method to debug log in TF providers right now. You might want to do something like the following in `Close`:

```go
log.Println("[DEBUG] Closing vSphere provider connections")
```

FWIW this probably would be a good idea to add into `Close` permanently, so when you add it, it'd be fine to leave there.

In order to see the debug messages you will need to run Terraform with `TF_LOG=debug` set in the environment. You can also pass this to acceptance tests too to get the logging as well.

Thanks for taking this on!

**Comment by anfernee** [comment]
Thanks for the tips. The log works. but the close method is still not getting called. I traced into terraform code. The visitor mode is so complicated. I still didn't figure it out. but this looks strange:

https://github.com/hashicorp/terraform/blob/d4ac68423c4998279f33404db46809d27a5c2362/terraform/transform_provider.go#L132

where cpm collects all closers but never used anywhere. at the same time, it looks like the closer is attached to some node. 

```golang
func (t *CloseProviderTransformer) Transform(g *Graph) error {
	pm := providerVertexMap(g)
	cpm := make(map[string]*graphNodeCloseProvider)
	var err error

	for _, v := range pm {
		p := v.(GraphNodeProvider)

		// get the close provider of this type if we alread created it
		closer := cpm[p.Name()]

		if closer == nil {
			// create a closer for this provider type
			closer = &graphNodeCloseProvider{ProviderNameValue: p.Name()}
			g.Add(closer)
			cpm[p.Name()] = closer
		}

		// Close node depends on the provider itself
		// this is added unconditionally, so it will connect to all instances
		// of the provider. Extra edges will be removed by transitive
		// reduction.
		g.Connect(dag.BasicEdge(closer, p))

		// connect all the provider's resources to the close node
		for _, s := range g.UpEdges(p).List() {
			if _, ok := s.(GraphNodeProviderConsumer); ok {
				g.Connect(dag.BasicEdge(closer, s))
			}
		}
	}

	return err
}
```

**Comment by bill-rich** [comment]
Hi @anfernee! I looked more into your suggestion and found out that `ResourceProviderCloser` is actually intended to shut down the RPC connection, and isn't available on the plugin side. Unfortunately, I do not think there is a way to deal with shutting down connections on the plugin side. 

As @vancluever said, the best bet is probably to ensure you're utilizing session persistence to minimize your session count.

Thank you for taking the time to look into this possibility I learned quite a bit by looking into what you had already uncovered. Even though it didn't end up in a PR, you've certainly helped me out! Please let me know if you've got any questions on session persistence, and please continue to report issues and contribute in the future.

**Comment by anfernee** [comment]
Thanks for the updates @vancluever . For short term, as you said, we gonna have to live with that, and be careful for session count. In longer term, It would still be nice if the `terraform` could support it. 

Anyway, thanks again for investigating this issue.
