### ISSUE TITLE
Provider doesn't support data source: vsphere_compute_cluster

### ISSUE THREAD

**Issue by yogendramummaneni** [terraform-providers/terraform-provider-vsphere#622]
Hello,

I am getting the error "Provider doesn't support data source: vsphere_compute_cluster" when I use the data source vsphere_compute_cluster, I am using latest version of terraform and vsphere provider. Not sure whats wrong I am doing here?

Thanks,
Yogi.

[gsadmin@ansible-server test-yogi-vm-terraform]$ terraform version
Terraform v0.11.8
+ provider.vsphere v1.4.0

[gsadmin@ansible-server test-yogi-vm-terraform]$ terraform providers
.
├── provider.vsphere 1.4.0
└── module.clone_vm_module
    └── provider.vsphere (inherited)

From data_sources.tf
==========
data "vsphere_compute_cluster" "compute_cluster" {
  name = "test-cluster"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

[gsadmin@ansible-server test-yogi-vm-terraform]$ terraform apply

Error: data.vsphere_compute_cluster.compute_cluster: Provider doesn't support data source: vsphere_compute_cluster

[gsadmin@ansible-server test-yogi-vm-terraform]$

**Comment by bill-rich** [comment]
Hi @yogendramummaneni! Looks like you're actually a few versions behind on the vSphere provider. You have v1.4.0, but the `vsphere_compute_cluster` data source was added in v1.5.0. The latest is v1.8.1.

To get a newer version of the provider, you can either set the version to 1.8.1 in your config and run ```terraform init```, or you can run ```terraform init --upgrade```.
