### ISSUE TITLE
vsphere_virtual_disk missing count.

### ISSUE THREAD

**Issue by Smithx10** [terraform-providers/terraform-provider-vsphere#629]
Hello terraform_provider_vsphere,

We are trying to create a terraform module that will create multiple virtual disks.  

How can we create many virtual disks,  normally we use count,  but that doesn't seem to be available.

### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
terraform-provider-vsphere_v1.8.1_x4

### Affected Resource(s)
vsphere_virtual_disk

### Terraform Configuration Files

```hcl
data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_dc}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_disk" "disk" {
  datacenter          = "${var.vsphere_dc}"
  datastore           = "${var.vsphere_datastore}"
  size                = "${var.size}"
  vmdk_path           = "${var.vmdk_path}-${uuid()}.vmdk"
  type                = "${var.type}"
  create_directories  = true

  lifecycle {
    ignore_changes = [
      "vmdk_path"
    ]
  }
}

resource "null_resource" "rs_datastore_id" {
  triggers = {
    "value" = "${data.vsphere_datastore.datastore.id}"
  }
}
```

**Comment by bill-rich** [comment]
Hi @Smithx10! `count` is supported in `vsphere_virtual_disk`. What is the issue you're running into with it?

**Comment by Smithx10** [comment]
I'll give it a try,  but it doesn't look like this documentation mentions it.
https://www.terraform.io/docs/providers/vsphere/r/virtual_disk.html

**Comment by bill-rich** [comment]
Sorry for the confusion there. We don't generally have `count` documented in the resource docs as it is available on all resources. In your case, something like this should work:

```
resource "vsphere_virtual_disk" "disk" {
  count                  = "${var.vsphere_disk_count}"
  datacenter          = "${var.vsphere_dc}"
  datastore           = "${var.vsphere_datastore}"
  size                = "${var.size}"
  vmdk_path           = "${var.vmdk_path}-${uuid()}-${count.index}.vmdk"
  type                = "${var.type}"
  create_directories  = true

  lifecycle {
    ignore_changes = [
      "vmdk_path"
    ]
  }
}
