### ISSUE TITLE
vsphere_virtual_disk - create_directories fails if using COUNT to create multiple VMDKs at one time

### ISSUE THREAD

**Issue by tigerhawk6** [terraform-providers/terraform-provider-vsphere#633]
### Terraform Version

Terraform v0.11.8

### vSphere Provider Version

terraform-provider-vsphere_v1.8.1_x4

### Affected Resource(s)

- `vsphere_virtual_disk`

### Terraform Configuration Files

```hcl
variable "disk_num" {
  default = 5
}

resource "vsphere_virtual_disk" "myDisk" {
  count                 = "${var.disk_num}"
  size                  = "${var.disk_size}"
  vmdk_path             = "${var.client_name}/${var.client_name}-disk${count.index + 1}.vmdk"
  datacenter            = "${var.vsphere_dc}"
  datastore             = "${var.vsphere_datastore}"
  create_directories    = true
}
```

### Expected Behavior

Check to see if directory exists and if not create it.  
Then create VMDKs within the specified directory on the datastore.  

### Actual Behavior

Only the first VMDK is created.  Every loop tries to create the directory for the next VMDK and fails because it exists.  
If I don't use this option then no VMDKs are created.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Base vSphere deployment with vSAN datastore.
Creating VMDKs outside of VM directory location.
```
Error: Error applying plan:

4 error(s) occurred:

* vsphere_virtual_disk.myDisk[0]: 1 error(s) occurred:

* vsphere_virtual_disk.myDisk.0: ServerFaultCode: A general system error occurred: Invalid fault
* vsphere_virtual_disk.myDisk[2]: 1 error(s) occurred:

* vsphere_virtual_disk.myDisk.2: ServerFaultCode: Cannot complete the operation because the file or folder [WorkloadDatastore] client1 already exists
* vsphere_virtual_disk.myDisk[3]: 1 error(s) occurred:

* vsphere_virtual_disk.myDisk.3: ServerFaultCode: A general system error occurred: Invalid fault
* vsphere_virtual_disk.myDisk[1]: 1 error(s) occurred:

* vsphere_virtual_disk.myDisk.1: ServerFaultCode: A general system error occurred: Invalid fault
```
### References

Couldn't find any others with this option

**Comment by tigerhawk6** [comment]
Simple explanation of the issue is that the "create_directories" argument states that it will create any directories that are a part of the vmdk_path parameter **IF** they are missing.  This is only working for the FIRST disk I create in that directory and failing for each one after when this argument is used in a module or as noted above.

**Comment by tigerhawk6** [comment]
As a follow-up...  if I use the "create_directories" argument with "vsphere_file" it works as expected, meaning that IF the folder exists it just creates it and moves on instead of failing.

**Comment by bill-rich** [comment]
I tried to reproduce this issue, but am having trouble doing so. Can you try this on a non-vSAN datastore and also provide the debug output?

**Comment by tigerhawk6** [comment]
Thanks @bill-rich for working on this. I'll test it out when I get a chance.
