### ISSUE TITLE
terraform vsphere provider on arm32 tries IPv6 to resolve the hostname and fails

### ISSUE THREAD

**Issue by arno01** [terraform-providers/terraform-provider-vsphere#636]
### Terraform/vSphere Provider Version

```
Terraform v0.11.8
+ provider.vsphere v1.8.1
```

### Debug Output

Short:

```
* provider.vsphere: error setting up new vSphere SOAP client: Post https://mysite.com/sdk: dial tcp: lookup mysite.com on [::1]:53: read udp [::1]:36389->[::1]:53: read: connection refused
```

Long https://gist.github.com/arno01/68b49dd79c6813788e590f7088d62dc3

### Expected Behavior

terraform should not struggle resolving the hostname.

### Actual Behavior

terraform tries IPv6 to resolve the hostname and fails.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I think the issue lies down to how DNS resolution is implemented in the Golang as I came across the same exact issue with the minio client arm64 build https://github.com/minio/mc/issues/2564

**Comment by arno01** [comment]
I think this has something to do with https://github.com/golang/go/issues/25321

> Go (go resolver, not the Cgo one) prefers the IPv6 address over the IPv4 address and does not fall back to the IPv4 address if IPv6 is disabled.

**Comment by bill-rich** [comment]
I think you're correct there. Thanks for following up with the solution. I'll get this issue closed.
