### ISSUE TITLE
Thick provisioning with multiple disks fails :  error reconfiguring virtual machine: Post https://x/sdk: context deadline exceeded

### ISSUE THREAD

**Issue by sunilagrawal86** [terraform-providers/terraform-provider-vsphere#641]
I am trying to provision a thick provisioning for clustering and It fails for reconfiguration if additional disks(at least 2) size more than ~160 GB 

### Terraform Version
Terraform v0.11.7

### vSphere Provider Version
terraform-provider-vsphere_v1.8.1_x4

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

vsphere_virtual_machine.vm_1: Still creating... (13m0s elapsed)
Error: Error applying plan:
1 error(s) occurred:
* vsphere_virtual_machine.vm_1: 1 error(s) occurred:
* vsphere_virtual_machine.vm_1: 
WARNING:
There was an error performing post-clone changes to virtual machine "/A/vm/- TEST CUSTOMER/NFL-APP/sunilsles01":
error reconfiguring virtual machine: Post https://<vcenter>/sdk: context deadline exceeded

### Expected Behavior

It should successful without any issue 

### Actual Behavior

Its fails if more than 1 additional  disk and size >100 GB  

### Steps to Reproduce
1: Create a VM with thick template with 3 additional disks (eagerZeroedThick)
2. `terraform apply`

### References

**Comment by bill-rich** [comment]
Hi @sunilagrawal86! This looks like an issue with the API call timing out due to the time it takes to create the larger disks. I believe this can be adjusted, but is not currently supported. I'll get it on the backlog to add support for custom timeouts.

**Comment by gitcdb** [comment]
Any luck with this one? It essentially hoses one's ability to create systems with large disks, ala database nodes.

**Comment by chuanran** [comment]
@bill-rich any luck on this one please?  I also this issue intermittently. thanks
