### ISSUE TITLE
vSphere provider - Network in 'disconnected' state after booting from a template

### ISSUE THREAD

**Issue by hassenius** [terraform-providers/terraform-provider-vsphere#645]
Having exactly the same issues as #26 

Cloning from console works as expected, with network coming up without issues. Cloning from terraform does not, with the new VM having cable in a Disconnected state.
/etc/network/interfaces is configured correctly, so if we connect the network from the vsphere console the VM boots happily.

Terraform: 0.11.9
provider.vsphere v1.8.1
Ubuntu: 16.04
open-vm-tools: 10.2.0.1608 (build-7253323)

The only thing that is different in this template versus other templates is the addition of cloud-init, but not sure if/how that would cause our issues.

**Comment by bill-rich** [comment]
Hi @hassenius! Can you please include a copy of your terraform configuration? I wasn't able to replicate the issue right off, so I'd like to compare to try and pinpoint the difference.

**Comment by bill-rich** [comment]
Closing issue since there has been no response.
