### ISSUE TITLE
provider doesn't support resource vsphere_compute_cluster

### ISSUE THREAD

**Issue by cpoosala** [terraform-providers/terraform-provider-vsphere#648]
hi,

I am trying to create cluster and add host using terraforms, below is the error caused while doing this. any thoughts 

Error: vsphere_compute_cluster.compute_cluster: Provider doesn't support resource: vsphere_compute_cluster

I can run a script to create cluster and add host, but I want terraform to do it as it has resources 

data "vsphere_host" "hosts" {
  count         = "${length(var.hosts)}"
  name          = "${var.hosts[count.index]}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_compute_cluster" "compute_cluster" {
  name            = "terraform-compute-cluster-test"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
  host_system_ids = ["${data.vsphere_host.hosts.*.id}"]

  drs_enabled          = true
  drs_automation_level = "fullyAutomated"

  ha_enabled = true
}

**Comment by bill-rich** [comment]
Hi @cpoosala! It looks like you may be using an older version of the vsphere provider. Please double check to make sure you are using at least v1.5.0 if you would like to use `vsphere_compute_cluster`. If you are running an older version, make sure you do not have a constraint set in your config file and run ```terraform init -upgrade```. That should get you to the latest version of the provider.

**Comment by cpoosala** [comment]
Thanks bill was able to create cluster resources after upgrade.
