### ISSUE TITLE
Unknown root level key: host 

### ISSUE THREAD

**Issue by chan87** [terraform-providers/terraform-provider-vsphere#649]
Hi there,

I am trying to created cluster and add host and then assign virtual switch for that host, got 
Error: Unknown root level key: host

here is the code: 

variables have esxihost, datacenter, cluster details

data "vsphere_host" "hosts" {
  name          = "${var.esxihost}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_compute_cluster" "compute_cluster" {
  name            = "${var.cluster_name}"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
  host_system_ids = ["${data.vsphere_host.hosts.id}"]

  drs_enabled          = false
  drs_automation_level = "fullyAutomated"

  ha_enabled = true
}

resource "vsphere_distributed_virtual_switch" "dvs" {
  name          = "${var.site}-${var.dv_switchName}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"

  uplinks         = ["uplink2","uplink1"]
  active_uplinks  = ["uplink1", "uplink2"]
  #standby_uplinks = ["uplink3", "uplink4"]

  host {
    host_system_ids    = ["${data.vsphere_host.hosts.id}"]
    devices        = ["${var.network_interfaces}"]
  }
  }

**Comment by bill-rich** [comment]
Hi @chan87! The `Unknown root level key` error message is odd, but I do see a config issue that can be addressed as a first step. In the `vsphere_distributed_virtual_switch` resource, in the `host` sub-resource, the attribute should be `host_system_id` instead of `host_system_ids`. Please give the below example a try and let me know if it resolves your issue.
```
resource "vsphere_compute_cluster" "compute_cluster" {
  name = "${var.cluster_name}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
  host_system_ids = ["${data.vsphere_host.hosts.id}"]

  drs_enabled = false
  drs_automation_level = "fullyAutomated"

  ha_enabled = true
}

resource "vsphere_distributed_virtual_switch" "dvs" {
  name = "${var.site}-${var.dv_switchName}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"

  uplinks = ["uplink2","uplink1"]
  active_uplinks = ["uplink1", "uplink2"]
  #standby_uplinks = ["uplink3", "uplink4"]

  host {
    host_system_id = "${data.vsphere_host.hosts.id}"
    devices = ["${var.network_interfaces}"]
  }
}
```

**Comment by bill-rich** [comment]
When you are running Terraform, is the host already added to vCenter? Currently there is not a resource to support adding a host. If it is already added, can you give me an idea of the inventory tree in vCenter and where the host is within that tree?

**Comment by chan87** [comment]
Bill - presently the esxi host is not added to the vCenter yet, so it errors out. But I could add that same host with Add-VMHost -Name "test1-esxihost.com"

if I add it manually or via script I could pull the information;  and creates "dv_switch" using terraform resource "vsphere_distributed_virtual_switch" and set  
host_system_id = "${data.vsphere_host.hosts.id}" or else it will error out. 

Below if the inventory structure :

esxi host install/ configure 
- esxi installation
 - SYstem customization 
- configure Management network
      - Network Adaptors 
      - vlan
      - ip config ()
      - dns config 


I think terraform should able to Add the host inorder to provision other resources "compute_cluster" "dv_switch" adding host to "network_interfaces" or someone has to add it before.

**Comment by bill-rich** [comment]
@chan87 I agree that the ability to manage ESXi hosts through Terraform would be very useful. There isn't an ETA yet, but it is a planned feature. Its currently being tracked in #570.
