### ISSUE TITLE
Vsphere Clone Operation Fails to set Gateway IP correctly

### ISSUE THREAD

**Issue by generalconsensus** [terraform-providers/terraform-provider-vsphere#658]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Terraform v0.11.10
+ provider.vsphere v1.9.0

### vSphere Provider Version

terraform-provider-vsphere_v1.9.0_x4

### Affected Resource(s)

vsphere_virtual_machine

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user           = "XXX"
  password       = "XXX"
  vsphere_server = "XXX"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "XXX"
}

data "vsphere_datastore" "datastore" {
  name          = "XXX"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "XXX"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "XXX"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_tag_category" "category" {
  name        = "terraform-test-category"
  cardinality = "SINGLE"
  description = "Managed by Terraform"

  associable_types = [
    "VirtualMachine",
    "Datastore",
  ]
}

resource "vsphere_tag" "tag" {
  name        = "terraform-test-tag"
  category_id = "${vsphere_tag_category.category.id}"
  description = "Managed by Terraform"
}

resource "vsphere_virtual_machine" "testlampstack" {
  name             = "terraform-testlampstack"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 1
  memory   = 4096
  guest_id = "ubuntu64Guest"
  cpu_hot_add_enabled           = true
  cpu_hot_remove_enabled        = true
  memory_hot_add_enabled        = true
  enable_logging                = true

  scsi_type = "lsilogic"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
    adapter_type = "vmxnet3"
  }

  disk {
    label            = "disk0"
    eagerly_scrub    = 0
    thin_provisioned = 1
    size  = 20
  }
  disk {
    label       = "disk1"
    eagerly_scrub    = 0
    thin_provisioned = 1
    size  = 40
    unit_number = 1
  }


  tags = ["${vsphere_tag.tag.id}"]


  clone {
    template_uuid = "421fe30c-7bfd-93e7-1f02-c88d169fa841"

    customize {
      linux_options {
        host_name = "terraform-test"
        domain    = "XXX"
      }
      network_interface {
        ipv4_address = "10.129.65.108"
        ipv4_netmask = 24
      }
      dns_server_list = ["10.129.65.3"]
      ipv4_gateway = "10.129.65.1"
    }
  }

    # This is where we configure the instance with ansible-playbook
    provisioner "local-exec" {
      command = "printf [${self.name}] \n '${self.guest_ip_addresses.0}' >> ${path.cwd}/terraform.hosts; sleep 120; ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i terraform.hosts playbook.yml  --extra-vars '@passwd.yml'  --vault-password-file=../../vaultpassword"
    }
}

```

### Debug Output

https://gist.github.com/generalconsensus/628d161932b6545ab6e3462f1e077390

### Panic Output

N/A

### Expected Behavior

The /etc/network/interfaces file should have been properly set to

```
      ipv4_gateway = "10.129.65.1"

```

### Actual Behavior

The /etc/network/interfaces file shows:

```
auto ens160 
iface ens160 inet static
address 10.129.65.108
netmask 255.255.255.0
up route add default gw 10.129.65.1
dns-nameservers 10.129.65.3
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

I'm new to terraform and I believe my configuration is correct

**Comment by bill-rich** [comment]
Hi @generalconsensus! Your configuration looks good. It actually looks like the gateway is being set, but using a `up` command and `ip` rather than `gateway`.

`up route add default gw 10.129.65.1` is setting the default gateway, so it appears the `ipv4_gateway` parameter is being passed to VMware properly. The exact way VMware implements the customization parameters varies based on the client operating system.

Hope this helps!

**Comment by generalconsensus** [comment]
@bill-rich Thanks for taking a look at this for me -- the issue I am seeing is the statement:

```
up route add default gw 10.129.65.1
``` 
as you mentioned above. I believe this is a mistake as the /etc/network/interfaces file is not properly created. The file /etc/network/interfaces has the actual command deposited instead of having the statement assigning the gateway which should be the case. The file should look like this:

```
auto ens160 
iface ens160 inet static
address 10.129.65.108
netmask 255.255.255.0
gateway 10.129.65.1
dns-nameservers 10.129.65.3
```

not like this:

```
auto ens160 
iface ens160 inet static
address 10.129.65.108
netmask 255.255.255.0
up route add default gw 10.129.65.1
dns-nameservers 10.129.65.3
```

**Comment by bill-rich** [comment]
Hi @generalconsensus. I'm not sure right off why VMware chose to implement it in this way. Unfortunately, there isn't much that we can do on the Terraform side. All of the customization work is done through the vSphere API, so we can't actually control how VMware implements that customization.

In this case, we are using the `gateway` field in [CustomizationIPSettings](https://www.vmware.com/support/developer/converter-sdk/conv43_apireference/vim.vm.customization.IPSettings.html#field_detail). It isn't ideal, but you could use a provisioner to modify the interfaces file after the VM is created.

**Comment by generalconsensus** [comment]
@bill-rich ok last question than, how would I get ansible to connect back to the server if I can't get the gateway set correctly and basically networking is broken until the gateway is set correctly? Is there a way to just cat 'gateway 10.129.65.1' >> /etc/network/interfaces as a way to duct-tape this together until vsphere corrects their mistake?

**Comment by bill-rich** [comment]
What is it about the `up` script that isn't working? It should still be adding the default gateway when the interface is brought up. Sorry if I'm overlooking something!

If your source template supports the vApp option, you could work around no network connectivity by doing something like this:

```
data "template_file" "config_data" {
        template = <<EOS
#!/bin/sh
cat > /etc/network/interfaces << EOT
auto lo
iface lo inet loopback

auto ens192
iface ens192 inet static
    address ${var.ipv4_address}
    netmask ${cidrnetmask("${var.ipv4_address}/${var.ipv4_netmask}")}
    gateway ${var.ipv4_gateway}
EOT
reboot
EOS
}

resource "vsphere_virtual_machine" "vm" {
...
  "vapp" {
    "properties" {
      "user-data" = "${base64encode(data.template_file.config_data.rendered)}"
    }
  }
}
```
