### ISSUE TITLE
Can't create new VM without specifying valid value for memory_reservation parameter

### ISSUE THREAD

**Issue by cbascom** [terraform-providers/terraform-provider-vsphere#672]
### Terraform Version

Terraform v0.11.10

### vSphere Provider Version

master branch commit 3a0043d0b6e4cf6fc6f84bb942e472cb77dc62b5

### Affected Resource(s)

vsphere_virtual_machine

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user = "${var.vsphere_user}"
  password = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  allow_unverified_ssl = true
  client_debug = true
}

data "vsphere_datacenter" "datacenter" {
  name = "${var.vsphere_datacenter}"
}

data "vsphere_datastore" "datastore" {
  name = "${var.vsphere_datastore}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_resource_pool" "pool" {
  name          = "${var.vsphere_esx_host}/Resources"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vsphere_vm_template}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

data "vsphere_network" "mgmt" {
  name          = "${var.vsphere_network_mgmt}"
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name               = "BIG-IP-1"
  num_cpus           = 4
  memory             = 8192
#  memory_reservation = 8192
  resource_pool_id   = "${data.vsphere_resource_pool.pool.id}"
  datastore_id       = "${data.vsphere_datastore.datastore.id}"

  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.mgmt.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  wait_for_guest_net_timeout = 0

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    linked_clone = true
  }
}
```

### Debug Output

https://gist.github.com/cbascom/57226fa466b32b68b236c719f0ada70f

### Expected Behavior

Creation of a new VM should be successful.

### Actual Behavior

Creation of a new VM fails with the following error:

```
* vsphere_virtual_machine.vm: error reconfiguring virtual machine: error reconfiguring virtual machine: A specified parameter was not correct: spec.memoryAllocation.reservation
```

### Steps to Reproduce

1. `terraform apply`

### References

I believe that the fix for #655 has made it a requirement to specify a valid value for the previously optional memory_reservation parameter for the vsphere_virtual_machine resource to avoid this issue. This issue does not occur with the released version v1.9.0 of this provider.

**Comment by bill-rich** [comment]
Hi @cbascom! I wasn't able to reproduce this issue. When no value is set for `memory_limit`, it will default to `0`. Are all VMs affected by this change? Can you try creating a new one to test with either from scratch or from a different template?

**Comment by cbascom** [comment]
Hi @bill-rich! I just dug a little deeper and I believe I have figured out the root cause. There is a parameter named memoryReservationLockedToMax that is currently not supported by the provider at all. This parameter is part of [VirtualMachineConfigInfo](https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.ConfigInfo.html) and [VirtualMachineConfigSpec](https://www.vmware.com/support/developer/converter-sdk/conv60_apireference/vim.vm.ConfigSpec.html).

In my case, this parameter is true when the VM gets cloned regardless of whether or not it is set to true on the template I am cloning from. It appears that when this parameter is set to true, sending a memory_reservation parameter of 0 is different than not sending a memory_reservation parameter at all, since any memory_reservation value that is not equal to the amount of memory configured for the VM is flagged as invalid on the vCenter server side.

I'm thinking that because of this, maybe it would make sense to add support in the provider for the memoryReservationLockedToMax parameter. With it supported, if the value is true for this parameter, no value for memory_reservation would ever be sent. This logic would have to know the API version that is in use somehow though since that parameter is only supported since vSphere API 5.0.

As it stands now, anyone that has this parameter set to true will be forced to specify a memory_reservation equal to the total memory configured for the VM which is how I am working around it now. So far I have not figured out how to prevent it from being set to true by default, so I always have to use this workaround for now.

**Comment by bill-rich** [comment]
Thats great information @cbascom! Thank you for doing the additional research to find out what was going on. I agree that a good way to fix this would be to add support for `memory_reservation_locked_to_max`. I'm going to look into adding this feature, and will update this issue with progress.

**Comment by bill-rich** [comment]
@cbascom I've looked some more into this and implementing `memory_reservation_locked_to_max` is possible, but after looking more closely I think it adds some unnecessary complexity. Since the same thing can be achieved by setting `memory_allocation` to `${vsphere_virtual_machine.name.memory`, I think a better way to get this fixed would be to make it so that when `memory_allocation` is `nil` (not `0`), the parameter is not sent. Going this route will require the Terraform 0.12 release, so it will not be an immediate fix.

**Comment by cbascom** [comment]
@bill-rich I assume you mean `memory_reservation` instead of `memory_allocation`.

The problem with going that route is that it prevents anyone with a vCenter like mine that sets `memory_reservation_locked_to_max` to true by default from ever configuring a reservation less than the maximum memory during VM creation. Instead of exposing `memory_reservation_locked_to_max` as a new parameter, what about simply setting it to false in the VirtualMachineConfigSpec that is sent when you detect a `memory_reservation` value that is greater than 0 but less than `memory`? Would that avoid the extra complexity you are referring to? The only scenario that wouldn't be supported at that point would be specifically setting `memory_reservation_locked_to_max` to true.

If the above doesn't work, I'm fine waiting until the terraform-0.12 release to fix this since in my case I always want the memory fully reserved anyway. However, I just want to make sure you are aware that if the next release of this provider comes before then, configs that were working fine prior to the fix for #655 may start to fail until those configs are updated to use the workaround.

**Comment by bill-rich** [comment]
@cbascom Yes, you are correct! I meant `memory_reservation`. Thanks for catching that.

That is a good point about situation where a user would want to set `memory_reservation` lower than `memory_allocation`. The issue with implementation before the 0.12 Terraform release is that a user may want `memory_reservation` to be `0`, or they may not want to specify it, but in pre 0.12, there is no way to differentiate between a parameter that is the zero value and one that is not set. I think that always setting `memory_reservation_locked_to_max` to false in the virtual machine config spec could work since there isn't an option to control it in the provider, but there is a way to have similar functionality by setting `memory_reservation` to `memory_allocation`. Does this seem like a workable solution to you?

**Comment by cbascom** [comment]
@bill-rich Yes, that is what I was suggesting since I think it gives almost full functionality. The only part of my suggestion that was slightly different is that instead of always setting `memory_reservation_locked_to_max` to false, set it to false only if `memory_reservation != memory_allocation`. If `memory_reservation == memory_allocation`, just don't send the `memory_reservation_locked_to_max` parameter just as things are now.

In my case, that would allow me to specify `memory_reservation = memory_allocation` and `memory_reservation_locked_to_max` would remain set to true (because my vCenter defaults it to true when it isn't included). This would work immediately without terraform-0.12. It would also allow for specifying `memory_reservation < memory_allocation` which would result in `memory_reservation_locked_to_max` being set to false and `memory_reservation` successfully being set to the specified value.

That said, if that logic is too complicated, I think always setting `memory_reservation_locked_to_max` to false is still better than the current behavior since it at least allows control of the amount of memory that is reserved in all cases.
