### ISSUE TITLE
Default Gateway Not Set As Per .tf File

### ISSUE THREAD

**Issue by luckerby** [terraform-providers/terraform-provider-vsphere#674]
Hi everyone,

I'm using Terraform v0.11.11 with provider.vsphere v1.9.0. Currently on a very simple setup - actually the first thing I did after deploying terraform - spawning a Windows Server 2016 machine based on an already existing template. Everything works just fine and the new VM shows up just as expected; the IP and network mask is set correctly, however there's just one issue - the default gateway isn't set at all, despite being specified in the .tf file:

![image](https://user-images.githubusercontent.com/31319583/50173873-55bfe200-0301-11e9-9838-3b04dc29cde3.png)

The "apply" step thus times out (I'm guessing due to the VM itself not reaching an internet address, thus failing a test the vsphere provider might be running in the back):
![image](https://user-images.githubusercontent.com/31319583/50173712-f06bf100-0300-11e9-9a9d-85cb91878769.png)

Would turning to the [debug logs ](https://www.terraform.io/docs/internals/debugging.html)be the right thing ? Or is this maybe a known issue with this specific Windows version ? Just trying to figure out what my next step should be.

Regards,
Mihai

**Comment by bill-rich** [comment]
Hi @luckerby! The debug logs may end up being helpful, but I'd like to narrow down the problem a bit also if you're willing to do some additional troubleshooting. The first one is a silly one, but I just want to make sure all the bases are covered. Can you confirm that the default gateway falls in the network range specified in `ipv4_address` and `ipv4_netmask`? Next, can you check if the same customization options work when entered through the web client? And finally, if you have another template can you please try the same configuration, but with that template?

**Comment by luckerby** [comment]
Bill - the first check isn't silly at all ! It turns out I was using a /24 mask instead of a /23, causing the gateway not to fall within the range :) As soon as I corrected this in my .tf file, and applied it, it worked just fine (picture below).

I'm guessing the vsphere provider+terraform refused to set the gateway in the first place, since Windows will accept it (although produce a warning). Are the debug logs what I'm after, or is there something more specific just for the network part ? I'm also trying to figure out what those 4m30 were spent on after applying the new plan, since the machine was up in about 10s, and the only difference introduced was the /24 -> /23 in the netmask.

![image](https://user-images.githubusercontent.com/31319583/50204106-5346a200-036c-11e9-81c8-ac0a5708a152.png)

**Comment by rameshcreations** [comment]
Hello All,

I also tested with Terraform v0.11.11 with provider.vsphere v1.9.0 for the CentOS 7x64.  As @luckerby default gateway not set up according to the terraform. Might be an issue with using open-vm-tools + terrafrom. I disabled terrafrom "vsphere_virtual_machine" waiter to ignore this error.

  wait_for_guest_net_routable = false
  wait_for_guest_net_timeout = -1

![s1](https://user-images.githubusercontent.com/35482633/50436462-0e8eae00-090c-11e9-8857-f6a07dff341a.PNG)
![s2](https://user-images.githubusercontent.com/35482633/50436464-10587180-090c-11e9-94c6-b9085c8b9acc.PNG)
![s3](https://user-images.githubusercontent.com/35482633/50436466-13536200-090c-11e9-9fb6-d60087ffcda8.PNG)

**Comment by bill-rich** [comment]
@luckerby Thats good to hear! The reason for the wait is that (as @rameshcreations pointed out), there is a timer to wait for networking to come up by default. If you set `wait_for_guest_net_timeout` to `-1`, then Terraform will finish as soon as the VM is created.

**Comment by rameshcreations** [comment]
@bill-rich Thanks for the comment. But the issue is Default gateway not set by the provider. So setting up 'wait_for_guest_net_timeout = -1' is not a solution for this.We have to set the default gateway manually.I didn't check with any Windows versions yet. Any suggestion?

**Comment by bill-rich** [comment]
@rameshcreations Sorry, I misunderstood part of the issue! There is a function in the setup of the VM customization that checks that the gateway falls within a specified network. Is there a reason you would want to specify a gateway outside of the networking available on the VM?

**Comment by rameshcreations** [comment]
@bill-rich Thanks for the comment. Please find the attached image for the availble network.As an example 10.101.15.0/24 is our subnet and 10.101.15.254 is the default gateway of this. 
![network](https://user-images.githubusercontent.com/35482633/50554135-1f0fa180-0cdb-11e9-8cb5-f38fd78892bc.PNG)

**Comment by rameshcreations** [comment]
@luckerby  This issue has been fixed after upgrading vCenter version to 6.7
