### ISSUE TITLE
vsphere_virtual_machine: support files of VM cloned from template are left on datastore of template

### ISSUE THREAD

**Issue by ezibode** [terraform-providers/terraform-provider-vsphere#681]
### Terraform Version

0.11.7

### vSphere Provider Version

1.6.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

The following are the relevant bits of the HCL. Major portions are excluded to improve clarity.

```hcl
#
# datacenter
#
data "vpshere_datacenter" "testvm_datacenter" {
   name = "TEST"
}
#
# cluster
#
data "vsphere_compute_cluster" "testvm_cluster" {
   name          = "Production"
   datacenter_id = "${data.vpshere_datacenter.testvm_datacenter.id}"
}
#
# location of template
#
data "vsphere_virtual_machine" "testvm_template" {
   name          = "TEST-SUITE/Template/RHEL-6.10"
   datacenter_id = "${data.vpshere_datacenter.testvm_datacenter.id}"
}
#
# datastore for cloned VM
#
data "vsphere_datastore" "testvm_datastore0" {
   name          = "test_vm_1"
   datacenter_id = "${data.vpshere_datacenter.testvm_datacenter.id}"
}
#
# definition for cloned VM
#
resource "vsphere_virtual_machine" "testvm" {
   # ... removed for clarity
   disk {
      label             = "disk0"
      size              = "70"
      datastore_id      = "${data.vpshere_datastore.testvm_datastore0.id}"
      thin_provisioned  = "true"
      unit_number       = "0"
   }
   clone {
      template_uuid = "${data.vsphere_virtual_machine.testvm_template.id}"
      # ... removed for clarity
   }
}
```
### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

When a VM is cloned from template the VMDK and all other supporting files (i.e. VMX, VMXF, VMXD, VSWP, NVRAM) should end up on the specified target datastore for the cloned VM as specified in the disk { ... datastore_id = "XXX"  ... } block of the HCL. 

### Actual Behavior

The VMDK ends up on the specified target datastore for the cloned VM, but all other supporting files (i.e. VMX, VMXF, VMXD, VSWP, NVRAM) reside on the datastore where the template resides.

The VM deploys, powers on and functions properly. However, the datastore on which the template resides fills up unexpectedly when a large number of VMs are cloned and powered on.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- vCenter 6.5
- vSphere 5.5 and 6.0
- Running terraform on Linux
- Cloning Linux templates

I have looked through all of the checkins for newer versions of the provider but I don't see any reports that would indicate the behavior has changed in subsequent versions.

### References
N/A

**Comment by bill-rich** [comment]
Hi @ezibode! In order to have all of your virtual machine files be stored on `data.vpshere_datastore.testvm_datastore0`, you'll need to specify the `datastore_id` in `vsphere_virtual_machine` rather than in the `disk` subresource. If you don't specify a `datastore_id` in `vsphere_virtual_machine`, the default datastore will be used to store the virtual machine files. It is a little non-intuitive having both available, but the reason is so that different disks can be placed on different datastores if needed.

**Comment by ezibode** [comment]
@bill-rich: thanks for the quick and clear response and my apologies for not recognizing this from the existing documentation! Keep up the great work.
