### ISSUE TITLE
No documentation how to proceed after configuring the hardware

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-vsphere#682]
Hi there,

I was playing around with the vSphere Provider for Terraform.

Unfortunately I haven't found much documentation / information how to proceed after I setup the hardware.

E.g. 

- What are the options to install the operating system after the creation?
- What are the other options (image based while changing the configuration (networking, hostname, ...))
- Other options

I think to provide the user the documented options how to proceed after the main deployment would be interesting. Some small examples would be fine. Or at least to describe the further options briefly.

**Comment by bill-rich** [comment]
Hi @tkak! 

Thanks for the feedback on this. I've been thinking about how to add this additional documentation, but I think it ends up falling outside of the scope of the provider. I see how it could be helpful to have documentation on how to do some tasks like OS installation. The concern is that opens up a lot of extra expectation for what will be supported in an area in which the best practices are regularly changing. 

I would be happy to help point you in the right direction though if there is some info you're looking for. To answer your questions specifically, to install the OS, I'd recommend either pre-installing the OS and using cloud-init or using PXE boot and OS install automation. If you decide to go with PXE booting, check out [netboot](https://github.com/google/netboot/). It has a few caveats, but really simplifies the PXE boot process.

**Comment by tkoeck** [comment]
Hi @bill-rich,

thank's for the answer.

I didn't expect to be the installation in the scope of the documentation. I would have been glad if there were some reference, links and/or experience of the users they prefer to do it thou. It can be in short 'hints' or 'advices' what options are generally out there and what methods has been proven successful and are 'best practices'.
