### ISSUE TITLE
Destroy/Recreate Only When IPs Change

### ISSUE THREAD

**Issue by luckerby** [terraform-providers/terraform-provider-vsphere#692]
### Terraform Version
`Terraform v0.11.11`

### vSphere Provider Version
`1.9.0`

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files
I'm provisioning multiple similar VMs. The configuration itself is relatively straight-forward, resembling the first code snipped [here](https://www.hashicorp.com/blog/using-infrastructure-as-code-to-automate-vmware-deployments). The only particularity is that using an external provider, I'm invoking a external tool (.exe) which gets a free IP address for each VM from our internal IPAM solution. The trouble is that after each terraform state refresh - when all instances of the external tool are invoked again, and possible different IPs are returned -, all the VMs are scheduled to be destroyed and recreated, as seen below, instead of simply modifying the IPs.

### Expected Behavior
I would have expected a `~` signalling the IPs need to change as part of applying the plan, but that's it.

### Actual Behavior
```
C:\Users\malbert\Desktop\Excel2VM>terraform plan -out deployVM
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.external.IPregexMatchPattern: Refreshing state...
data.external.NetworkObtainedData[0]: Refreshing state...
data.external.NetworkObtainedData[1]: Refreshing state...
data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_network.network: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
vsphere_virtual_machine.vm[1]: Refreshing state... (ID: 4227a1a3-bf73-0024-e240-5c925147e96a)
vsphere_virtual_machine.vm[0]: Refreshing state... (ID: 42275cfa-4dde-3c2d-4ece-44edd599ad9d)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

-/+ vsphere_virtual_machine.vm[0] (new resource required)
      id:                                                        "42275cfa-4dde-3c2d-4ece-44edd599ad9d" => <computed> (forces new resource)
      boot_retry_delay:                                          "10000" => "10000"
      change_version:                                            "2019-01-22T18:07:30.209148Z" => <computed>
      clone.#:                                                   "1" => "1"
      clone.0.customize.#:                                       "1" => "1"
      clone.0.customize.0.ipv4_gateway:                          "192.168.0.1" => "192.168.0.1"
      clone.0.customize.0.network_interface.#:                   "1" => "1"
      clone.0.customize.0.network_interface.0.dns_server_list.#: "2" => "2"
      clone.0.customize.0.network_interface.0.dns_server_list.0: "192.168.0.2" => "192.168.0.2"
      clone.0.customize.0.network_interface.0.dns_server_list.1: "192.168.0.3" => "192.168.0.3"
      clone.0.customize.0.network_interface.0.ipv4_address:      "192.168.0.101" => "192.168.0.100" (forces new resource)
      clone.0.customize.0.network_interface.0.ipv4_netmask:      "24" => "24"
...
```

### Steps to Reproduce
`terraform plan`

**Comment by bill-rich** [comment]
Hi @luckerby! The reason the new resource is being forced is that the customization process is done as part of the clone. When anything in customization is changed, the only way to keep the VM in sync with the configuration is to create a new VM. 

To work around this, you can use `ignore_changes` so that the changes to the IP address will not force a new resource. For example, in your case, you could use the following configuration:
```
resource "vsphere_virtual_machine.vm" "vmname" {
  ...
  lifecycle {
    ignore_changes = ["clone.0.customize.0.network_interface.0.ipv4_address"]
  }
}
