### ISSUE TITLE
Dependent disk_mode supported?

### ISSUE THREAD

**Issue by rsmith11** [terraform-providers/terraform-provider-vsphere#710]
Hello,

When creating a VM with `vsphere_virtual_machine` resource, currently the valid disk_mode options are `persistent nonpersistent undoable independent_persistent independent_nonpersistent append`.  In Vcenter 6.7 the disk_mode options listed in the GUI are `Dependent`, `Independent - Persistent`, and `Independent - Nonpersistent`.  Is the Dependent mode supported?

### Terraform Version

Terraform v0.11.11
+ provider.vsphere v1.9.1

Thank you for your help.

**Comment by bill-rich** [comment]
I believe you would want `persistent` for the equivalent of `Dependent`. `Dependent` mode through the GUI means changes to the disk will persist after power off, and will be included in snapshots which is the same behavior as `persistent`.
