### ISSUE TITLE
remoteHostNames is an unexpected element in vim.host.NasVolume.Specification on vsphere 5.1

### ISSUE THREAD

**Issue by bobdoah** [terraform-providers/terraform-provider-vsphere#715]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v0.11.11
+ provider.vsphere v1.9.1
```
### vSphere Provider Version
v1.9.1_x4

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_nas_datastore`

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files

```hcl
provider "vsphere" {}
variable "hosts" {
  default = [
    "10.41.0.36",
    "10.41.10.140",
    "10.41.10.150",
  ]
}

data "vsphere_datacenter" "mh_dc1" {
  name = "mh-dc1"
}

data "vsphere_host" "mh_dc1_hosts" {
  count         = "${length(var.hosts)}"
  name          = "${var.hosts[count.index]}"
  datacenter_id = "${data.vsphere_datacenter.mh_dc1.id}"
}
resource "vsphere_nas_datastore" "packer_templates" {
  name            = "packer_templates"
  host_system_ids = ["${data.vsphere_host.mh_dc1_hosts.*.id}"]
  type            = "NFS"
  remote_hosts    = ["10.41.10.5"]
  remote_path     = "/data/packer_templates/"
}

```

### Debug Output

https://gist.github.com/bobdoah/ba40cee0617e57f41f2d7542da5e423d

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing
the output of the `crash.log`.

### Expected Behavior

NAS datastore created on ESXi hosts

### Actual Behavior

```
Unexpected element tag "remoteHostNames" seen

while parsing serialized DataObject of type vim.host.NasVolume.Specification
at line 2, column 164
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Using licensed ESXi version 5.1 hosts. The [vim.host.NasVolume.Specification](https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.host.NasVolume.Specification.html#top) only lists a `remoteHost` property, `remoteHostNames` is not named. This may be an older version of the documentation, but I couldn't find the latest. 

The [helper](https://github.com/terraform-providers/terraform-provider-vsphere/blob/81dfbbf27cb1c9416a28d725280451a6859fb8f0/vsphere/host_nas_volume_structure.go) sets both from `remote_hosts` attribute supplied

**Comment by bill-rich** [comment]
Hi @bobdoah! 

It does look like remoteHostNames is a newer field. It is in `HostNasVolumeSpec`, but doesn't appear to be supported on ESXi 5.1. We will need to add a version check in order to support the 5.1 use case. Thank you for pointing this out!

**Comment by bobdoah** [comment]
Hi @bill-rich was going to close this because elsewhere it looks like anything less than 5.5 isn't supported. Your comment suggests otherwise?

**Comment by bill-rich** [comment]
I think that is a good idea @bobdoah. I'd like to avoid starting adding support for 5.1-only fields. Thanks for noticing that!
