### ISSUE TITLE
timeout waiting for an available IP address

### ISSUE THREAD

**Issue by SteveYf** [terraform-providers/terraform-provider-vsphere#718]
Error Message:
Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm: timeout waiting for an available IP address

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

config file:

provider "vsphere" {
  user           = "admin"  # login username
  password       = "admin"  # login password
  vsphere_server = "10.200.35.240"  # host

  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = "Datacenter"
}

data "vsphere_resource_pool" "pool" {
  name          = "yangwb-poll"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_datastore" "datastore" {
  name          = "datastore22"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "uydc.base.o.a_node.mpkn_152_copy1"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  name             = "test-01"  
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = 2 
  memory   = 2048
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "test-01"
        domain    = ""
      }

      network_interface {
        ipv4_address = "10.200.35.131"
        ipv4_netmask = 24
      }

      ipv4_gateway = "10.200.35.255"
    }
  }
}

I hope to get your help. thanks!

**Comment by weakcamel** [comment]
I wonder what's the question here; have you read the docs for https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#wait_for_guest_ip_timeout ?

**Comment by bill-rich** [comment]
Hi @SteveYf! Can you please take a look in the vSphere client and see if the IP address is showing up there? The vSphere provider is looking for the address that is picked up by VMware Tools, so if that isn't being detected, then the Terraform provider will time out.

If the address is not showing up in the vSphere client, and you'd still like the VM creation to complete successfully despite that, you can set `wait_for_guest_net_timeout` to `-1`.

**Comment by andrewsav-datacom** [comment]
I have similar config and the same outcome. In my case customization seems to complete successfully, the VM receives the specified IP and I can see the IP in vSphere. But I'm still getting the timeout.

If there is anything else I need to supply to help troubleshoot please let me know.

**Comment by rymdlego** [comment]
I have experienced the same issue. VM deploys, boots up, and reports its IP in vSphere, but Terraform never picks it up and eventually times out. I have tried setting **wait_for_guest_net_routable: "false"** but the result is the same.
In my case, I'm deploying OpenBSD VMs, and it uses the vmt implementation of VMware Tools. I'm not sure if that's got something to do with it. But like I said, the IP shows in vSphere just fine.

**Comment by andrewsav-datacom** [comment]
So in my case the issues were with customization. The OS I used was ubuntu 18. I do not know what exactly caused them but when I switched from cloud-init to perl customization and used 18.04.2 instead of 18.04 image everything has worked for me.

**Comment by bill-rich** [comment]
Thanks for the additional information @andrewsav-datacom and @rymdlego. The operating system _shouldn't_ matter since the IP address is coming from the vSphere API, but it does seem that something is going on there. Perhaps there is some difference in how the IP information is presented in the API.

I think the next steps will be to take a look at what information is presented, and comparing one that works vs one that doesn't. This does seem like a bug though and I'll get it on the backlog to look further into.

**Comment by AndrewSav** [comment]
>I think the next steps will be to take a look at what information is presented

I cannot see anything relevant even with Debug logs enabled. It seem to cycle the following 4 lines:

```
2019/05/09 21:53:50 [TRACE] dag/walk: vertex "root", waiting for: "provider.vsphere (close)"
2019/05/09 21:53:50 [TRACE] dag/walk: vertex "provider.vsphere (close)", waiting for: "vsphere_virtual_machine.machine"
2019/05/09 21:53:50 [TRACE] dag/walk: vertex "meta.count-boundary (count boundary fixup)", waiting for: "vsphere_virtual_machine.machine"
2019/05/09 21:53:50 [TRACE] dag/walk: vertex "provisioner.remote-exec (close)", waiting for: "vsphere_virtual_machine.machine"
```

**Comment by rymdlego** [comment]
Not sure if this helps, but I'll chime in just in case. The IP-address of a VM in vSphere can be found in several different paths, and I believe different VMs (OS's) behave differently. Using the MOB, browsing a VM, the IP adress can be read from:

- guest.ipAddress
- summary.guest.ipAddress
- guest.net.{nic}.ipConfig.ipAddress

The latter being the most comprehensive, for a VM with multiple NICs you can get all IP's instead of just the one that vSphere happened to pick up first.

**Comment by bill-rich** [comment]
Thanks @rymdlego. That is a good point. In the OpenBSD case, its possible vmt is populating the legacy guest IP field. If that is the case, I believe the solution from@weakcamel ([wait_for_guest_ip_timeout](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#wait_for_guest_ip_timeout)) should work for you. Can you give that a try to see if the IP address waiter works properly?

**Comment by rymdlego** [comment]
Yeah I'm an idiot. **wait_for_guest_ip_timeout** works as intended, as OpenBSD does indeed populate the legacy IP field. Thanks for your patience :)

**Comment by camharris** [comment]
I'm experiencing the same issue as @andrewsav-datacom, when deploying Ubuntu 18.04 vm's. It seems that my virtual machines are fully provisioned and powered on but they network adapter shows that it is not 'connected' in vcenter. Setting the network adapter to 'connected' in vcenter makes my vm's network interface route-able. Is there an option to pass to this provider to make sure the network adapter is set to 'connected'?

**Comment by AndrewSav** [comment]
@camharris, yes, I can confirm that during my numerous expirements I expirenced the not connected problem too.

**Comment by andrewsav-datacom** [comment]
@camharris, yes, I can confirm that during my numerous experiments I experienced the not connected problem too.

**Comment by bill-rich** [comment]
@camharris and @andrewsav-datacom, the problem you're describing seems to be a bit different than the one originally brought up in this issue. In some cases vSphere will leave NICs disconnected if guest OS customization fails. Please check the logs on the guest to ensure customization is successful, or try removing the `customization` section from your config (if you're including it).

If those all check out, please open a new issue and we'll take a closer look at what is going on.

**Comment by andrew-lee-metaswitch** [comment]
This thread was really useful thanks and fixed my issue. 😃 

Does anyone know what version on VMware tools the `wait_for_guest_net_timeout` function starts working on? I have a VM with version `9.10.2` where it does not work, and a VM on version `10.2.5.3619`, so I assume it's somewhere between those versions. 
I'm having to write code which says if VMware tools version is then than version 10 use the `wait_for_guest_ip_timeout` function, else use the `wait_for_guest_net_timeout` function.

It occurred to me, wouldn't it be great if terraform was able to detect which version of vmwaretools was installed on the box and then use the `wait_for_guest_ip_timeout`  / `wait_for_guest_net_timeout`  function accordingly? 

VMware exposes an API to query which version of vmwaretools a VM is running (see https://code.vmware.com/apis/358/doc/vim.vm.ToolsConfigInfo.html) 

Do let me know if there is a more appropriate place to put this (if this counts as an enhancement and should therefore be raised somewhere other than a closed-bug thread)

**Comment by aareet** [comment]
Thanks for the comment @andrew-lee-metaswitch, I'll log this as an enhancement for us to track.
