### ISSUE TITLE
Virtual Machine name when terraform plan

### ISSUE THREAD

**Issue by elcidowneador** [terraform-providers/terraform-provider-vsphere#721]
### Terraform Version

Terraform v0.11.11

### vSphere Provider Version

+ provider.vsphere v1.9.1

### Affected Resource(s)

- `vsphere_virtual_machine`

### Actual Behavior

When i do terraform plan with custom module to manage VMs, the result of plan look like this (please note the name of resource):

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
Terraform will perform the following actions:
  + vsphere_virtual_machine.LinuxVM
      id:                                                   <computed>
      boot_retry_delay:                                     "10000"
      change_version:                                       <computed>
      clone.#:                                              "1"
      clone.0.customize.#:                                  "1"
```

### Expected Behavior

With this previous resource naming, i can't difference between the affected VMs, because all appears as a 'LinuxVM'. But, with AWS provider, the changes show like this:

```
 -/+ module.backend_api.aws_instance.instance (new resource required)
       id:                                                "i-004088c2b0ece479c" => <computed> (forces   new resource)
       ami:                                               "ami-7f675e4f" => "ami-7f675e4f"
       associate_public_ip_address:                       "false" => "false"
       availability_zone:                                 "us-west-2c" => <computed>
       disable_api_termination:                           "false" => "false"
       ebs_block_device.#:                                "0" => "1" 
```

Is there any way to show the vm name in plan with vSphere provider?

### Steps to Reproduce

1. `terraform plan`

**Comment by MattPumphrey** [comment]
Yes, Because unlike the AWS provider the VMWare provider requires you to give a name.  However if you would like to get a similar unique id naming scheme, my suggestion is to use the random_id provider, and do something like this

```
resource "random_id" "unique_id" {
  count = "${var.node_count}"

  keepers {
    template_id = "${data.vsphere_virtual_machine.template.id}"
  }

  byte_length = 8
}
```
Then us something like this
```
resource "vsphere_virtual_machine" "vm" {
  name                 = "${var.vsphere_vm_name}-${random_id.unique_id.*.hex[count.index]}"
```

**Comment by elcidowneador** [comment]
Thank you so much for your help @MattPumphrey, but unfortunately, i tried your solution and having same problem.

Im using a module to manage my infra (https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm), so, as you can see in the code (https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm/blob/master/main.tf), vm resource name is hardcoded. If i try to add to the name your solution, the problem continues:

`Terraform will perform the following actions:

  - random_id.unique_id[1]

  - vsphere_virtual_machine.LinuxVM[1]`

The only difference in this case is the output is easier to identify vms:

`vm_name = [
    base-1-94dd82f69f86009f,
    base-2-f35bed175e0be005
]`

But the problem, like as i said... continues at plan.

**Comment by bill-rich** [comment]
Hi @elcidowneador!

Can you post the source for the module you are using? The output during plan should be appearing as you are describing with the AWS provider. It should include the name given to the module in the main Terraform config, rather than just the changes to the resource in use in the module.

**Comment by elcidowneador** [comment]
Hi @bill-rich,

Thank you so much for your support.

Im using this module: 
https://github.com/Terraform-VMWare-Modules/terraform-vsphere-vm

Also is available in Terraform registry:
https://registry.terraform.io/modules/Terraform-VMWare-Modules/vm/vsphere/0.10.0
