### ISSUE TITLE
Target a specific host with in the computer cluster

### ISSUE THREAD

**Issue by vmovva** [terraform-providers/terraform-provider-vsphere#722]
### Terraform Version

0.11.11

### vSphere Provider Version

1.9.1 

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Usage question : 

Is it possible to target a specific host within the Compute cluster when creating a VM using Terraform?

**Comment by bill-rich** [comment]
Hi @vmovva!

It is possible to specify a host to place a VM on using the `host_system_id` option. You will need to either know the host's managed object ID, or use the `vsphere_host` data source. See [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#host_system_id) for more details.

**Comment by chuanran** [comment]
Hi @bill-rich could you give some example on how to use vsphere_host or host_system_id?
 the question from @vmovva is how to make sure a vm cloned/provisioned to a specific host in a compute cluster. so maybe the following link should be the right solution?  
 Thanks.
https://www.terraform.io/docs/providers/vsphere/r/compute_cluster_vm_host_rule.html

**Comment by chuanran** [comment]
@bill-rich I tried `host_system_id ` method you mentioned, but found sometimes it does not work, the vm provisioned to another host instead of the one with the `host_system_id` defined.  Do you know what could be the reason? thanks

**Comment by vaneyckt** [comment]
@bill-rich I get the same problem as @chuanran. Is this a known bug?
