### ISSUE TITLE
no storage drs recommendations were found for the requested action "clone" - when using datastore cluster

### ISSUE THREAD

**Issue by pneigel-ca** [terraform-providers/terraform-provider-vsphere#724]
### Terraform Version

v0.11.13

### vSphere Provider Version

v1.9.1

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "qa_vm" {
  count = "${var.vmcount}"
  name             = "${var.nameFirst}${format("%02d", count.index+1)}${var.nameSuffix}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}"
  num_cpus = 2
  memory   = 8192
  guest_id = "windows9_64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    linked_clone = true
    customize {
      windows_options {
        computer_name = "${var.nameFirst}${format("%02d", count.index+1)}${var.nameSuffix}"
        workgroup    = "workgroup"
        time_zone = "35"
      }
      network_interface {}
    }
  }

}

data "vsphere_datastore_cluster" "datastore_cluster" {
  name    = "Datastore-Cluster"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

```

### Expected Behavior

Terraform creates a number of VMs specified by variable **vmcount** to be placed in the destination datastore cluster. SDRS is enabled on this cluster with no strange rules.

### Actual Behavior

Terraform apply starts to run without issue but after a few minutes errors out with the following:

```1 error(s) occurred:

* vsphere_virtual_machine.qa_vm: 1 error(s) occurred:

* vsphere_virtual_machine.qa_vm: error cloning virtual machine: error cloning on datastore cluster "Datastore-Cluster": no storage DRS recommendations were found for the requested action (type: "clone")

```

When manually cloning to a datastore cluster using vSphere 6.5 normal behavior is experienced and a recommendation for datastore is provided. In this case, my datastore cluster is comprised of 3 datastores.

### Steps to Reproduce

terraform apply with any number of VMs for variable **vmcount** will fail after terraform indicates 'still creating'

### Important Factoids

Interactively cloning to a SDRS enabled datastore cluster works when using the GUI and a recommendation of a datastore is provided. 

To work around this, you can target a specific datastore with terraform instead of a cluster (avoiding SDRS recommendation)

**Comment by bill-rich** [comment]
Hi @pneigel-ca.

I'll look into reproducing this issue. In the meantime, can you please try a few configurations to help isolate the issue?

First, please try the following:
```
resource "vsphere_virtual_machine" "qa_vm" {
  name             = "vmtest"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}"
  num_cpus = 1
  memory   = 1024
  guest_id = "windows9_64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = 1
    thin_provisioned = true
  }
}
```

If that works, please try something like this:
```
resource "vsphere_virtual_machine" "qa_vm" {
  name             = "vmtest"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_cluster_id = "${data.vsphere_datastore_cluster.datastore_cluster.id}"
  num_cpus = 1
  memory   = 1024
  guest_id = "windows9_64Guest"

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  disk {
    label = "disk0"
    size  = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    linked_clone = true
   }
}
```

That information should help to figure out if there are specific configuration elements that are causing the issue in case I am not able to reproduce the issue in my environment.

**Comment by pneigel-ca** [comment]
@bill-rich first of all, thank you for your response. 

Running your first bit of suggested code, the operation was successful and I was able to then destroy the created instance without issue, which utilized a datastore cluster.

The second suggestion was not successful, and displayed the same behavior in that it indicated a resource was being created while the vSphere GUI showed no task activity and no indication the VM was created.

`* vsphere_virtual_machine.qa_vm: error cloning virtual machine: error cloning on datastore cluster "Datastore-Cluster": no storage DRS recommendations were found for the requested action (type: "clone")`

**Comment by bill-rich** [comment]
Thank you @pneigel-ca for helping to track down the source of the issue.

I believe it may have to do with the order of operations the vSphere provider uses when cloning a VM. Rather than modifying the hardware configuration as the clone happens, the provider first makes a clone of the source and then reconfigures it to match the resource configuration. 

Can you provide some additional information on the hardware configuration of the source VM? Especially related to the number of disks, disk size, and disk type.

Another useful bit of information would be if you can create a clone of your source VM, delete all disks except a single 1GB disk, and then use that as your source in your Terraform configuration.

**Comment by bill-rich** [comment]
This issue has been closed because there has been no response to our request for more information. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
