### ISSUE TITLE
docs: clarify/amend vapp-properties example

### ISSUE THREAD

**Issue by lucab** [terraform-providers/terraform-provider-vsphere#725]
For context, this comes originally from the discussion at https://github.com/coreos/coreos-assembler/pull/379#pullrequestreview-214139072 and a private chat with @alexsomesan.

https://github.com/terraform-providers/terraform-provider-vsphere/pull/303/files#diff-dc0e72edddc0d9ca0c01b859b58a226d introduced some vapp-properties examples that looks like this:
```
  vapp {
    properties {
      "guestinfo.hostname"                        = "${var.vm_name}.foobar.local"
      "guestinfo.interface.0.name"                = "ens192"
      "guestinfo.interface.0.ip.0.address"        = "10.0.0.100/24"
      "guestinfo.interface.0.route.0.gateway"     = "10.0.0.1"
      "guestinfo.interface.0.route.0.destination" = "0.0.0.0/0"
      "guestinfo.dns.server.0"                    = "10.0.0.10"
    }
  }
```
That is reflected  in rendered doc at https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#using-vapp-properties-to-supply-ovf-ova-configuration.

While the `vapp.properties` is generic and useful on it own, I have some concerns about the specific key-value pairs.
To my understanding, those keys are defined by coreos-cloudinit: https://github.com/coreos/coreos-cloudinit/blob/master/Documentation/vmware-guestinfo.md (note: not the pythonic cloud-init found in most distros, only the CoreOS-specific Go one).

If that is the case, as we are trying to steer users out of coreos-cloudinit, it would be good to drop those examples in favor of something less specific (eg. key.foo1=bar).

As I'm not very familiar with vsphere, can anybody please double-check that those are indeed specific to coreos-cloudinit only, and then get rid of them?

/cc @bill-rich

**Comment by bill-rich** [comment]
Hi @lucab! 

I believe those examples were pulled from a CoreOS example. I'm not certain right off if they're coreos-cloudinit specific, but I'd be happy to switch them out.

I haven't been following the cloudinit situation in CoreOS. Is the plan to be switching it out to vanilla cloudinit?

**Comment by lucab** [comment]
For Container Linux, coreos-cloudinit is on a deprecated path, replaced by Ignition: https://coreos.com/ignition/docs/latest/what-is-ignition.html#ignition-vs-coreos-cloudinit.
Ignition does not use the specific properties above (but still uses vapp-properties transport for userdata).

For [Fedora CoreOS](https://coreos.fedoraproject.org/), there will be Ignition only.

Thus the examples above (iff consumed by coreos-cloudinit only) are also involved in this deprecation.

**Comment by lucab** [comment]
@bill-rich as I haven't heard any arguments opposing this, I think I can just go ahead and take out those examples in favor of something generic.

**Comment by lucab** [comment]
PR up at https://github.com/terraform-providers/terraform-provider-vsphere/pull/740
