### ISSUE TITLE
Permission Issue Cause Not Logged

### ISSUE THREAD

**Issue by luckerby** [terraform-providers/terraform-provider-vsphere#729]
Hello,

Running terraform `v0.11.11`.

I'm simply spawning 2 clones based on an existing Vmware template, and doing basic customization (change VM name, assign IP/netmask/gateway/DNS servers). The trouble is that I'm running into a permissions issue (relevant output below). The task/events pane in Vmware's UI doesn't show any activity when terraform throws the errors.

If using the same account used to manually connect to Vsphere as above, and clone the same template from within Vmware's UI, everything works as expected.

Using an account with far more powerful permissions however results in terraform creating the VMs as expected. So it's definitely a permission issue. My problem is that the exact thing that the terraform Vsphere provider is trying to execute is not visible in the terraform logs. I'm already running with TF_LOG at TRACE level, so not sure if and how I can get more info out of terraform.

From a past issue I've entered, I've understood that _govmomi_ is used for the Vmware calls. Is it a matter of having the right logs passed back from this library, or more of a terraform issue ?
 

```
2019-03-19T17:03:04.185+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.9.1_x4.exe: 2019/03/19 17:03:04 [DEBUG] DiskCloneRelocateOperation: Disk relocator list:
2019-03-19T17:03:04.185+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.9.1_x4.exe: 2019/03/19 17:03:04 [DEBUG] DiskCloneRelocateOperation: Disk relocator generation complete
2019-03-19T17:03:04.185+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.9.1_x4.exe: 2019/03/19 17:03:04 [DEBUG] ExpandVirtualMachineCloneSpec: Clone spec prep complete
2019-03-19T17:03:04.185+0200 [DEBUG] plugin.terraform-provider-vsphere_v1.9.1_x4.exe: 2019/03/19 17:03:04 [DEBUG] Cloning virtual machine "/HQ/NYC/vm/GVA-TF1"
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalWriteState
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalIf
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalWriteState
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalApplyPost
2019/03/19 17:03:04 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* vsphere_virtual_machine.vm.1: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
2019/03/19 17:03:04 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
* vsphere_virtual_machine.vm.1: error cloning virtual machine: ServerFaultCode: Permission to perform this operation was denied.
2019/03/19 17:03:04 [TRACE] [walkApply] Exiting eval tree: vsphere_virtual_machine.vm[1]
2019/03/19 17:03:04 [TRACE] root: eval: *terraform.EvalApply
2019/03/19 17:03:04 [DEBUG] apply: vsphere_virtual_machine.vm.0: executing Apply
```

Regards,
Mihai

**Comment by bill-rich** [comment]
Hi @luckerby!

At the stage of the create function you are running into a problem, the only call being made is `CloneVM_Task`. For that to succeed you will need the following permissions depending on which situation fits:
- source is virtual machine, destination is virtual machine - VirtualMachine.Provisioning.Clone
- source is virtual machine, destination is template - VirtualMachine.Provisioning.CreateTemplateFromVM
- source is template, destination is virtual machine - VirtualMachine.Provisioning.DeployTemplate
- source is template, destination is template - VirtualMachine.Provisioning.CloneTemplate
- `VirtualMachine.Inventory.Create` on the folder where the VM is being created

govc would be a good tool for testing as it is using the same calls as the Terraform provider, but I do not believe it has any additional logging about required permissions.

I don't believe the vSphere client is using the vSphere API which leads to some cases where behavior does not match perfectly between the two. For cases like this, I recommend checking out the vSphere API Reference documentation. It includes additional information such as the permissions required for certain API calls.
