### ISSUE TITLE
Computed values not available from one resource to another

### ISSUE THREAD

**Issue by prakashvv** [terraform-providers/terraform-provider-vsphere#732]
### Terraform Version

Terraform v0.11.12

### vSphere Provider Version

provider.vsphere 1.10.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_nas_datastore`
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_resource_pool" "pool" {
  name          = "Resources"
  datacenter_id = "datacenter-12345"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "datacenter-12345"
}

resource "vsphere_nas_datastore" "datastore" {
  name            = "terraform-test"
  host_system_ids = ["host-12346"]

  type         = "NFS"
  remote_hosts = ["esxi1"]
  remote_path  = "/test"
}

# Create a vSphere VM
resource "vsphere_virtual_machine" "tf-db" {
  # VM placement #
  name             = "tf-db-instance"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${vsphere_nas_datastore.datastore.id}"

  # VM resources #
  num_cpus = "1"
  memory   = "1024"

  # VM storage #
  disk {
    label            = "disk0"
    datastore_id     = "${vsphere_nas_datastore.datastore.id}"
    attach           = true
    path             = "tf-db-instance/tf-db-instance.vmdk"
  }

  # VM networking #
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
  }

  depends_on = ["vsphere_nas_datastore.datastore"]
}

vsphere_virtual_machine
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The plan should work correctly and `id` value of created datastore should be available while creating VMs.

### Actual Behavior

`terraform plan` fails with the error message below
```
Error: Error running plan: 1 error(s) occurred:

* vsphere_virtual_machine.tf-db: 1 error(s) occurred:

* vsphere_virtual_machine.tf-db: disk.0: size for disk "disk0": required option not set
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform plan`

### Important Factoids

N/A

### References

None

**Comment by bill-rich** [comment]
Hi @prakashvv!

There are some subresource attributes that will result in an error at planning when using a computed value. This sometimes causes problems, but is the result of a trade off between allowing more flexibility and validating data. Some values need to be available during planning in order to ensure the resource plan is valid.

A way to work around this trade off is to first run `terraform apply --target=vsphere_nas_datastore.datastore` and then running `terraform apply` as usual.

Sorry for the inconvenience!

**Comment by prakashvv** [comment]
Thanks @bill-rich for the details. I think it solves my purpose.
