### ISSUE TITLE
Resource 'vsphere_virtual_machine.vm' does not have attribute 'ipv4_address' for variable 'vsphere_virtual_machine.vm.ipv4_address'

### ISSUE THREAD

**Issue by federicodallari1** [terraform-providers/terraform-provider-vsphere#734]
Hi team,
Thanks to support to investigate on this possible bug

### Terraform Versio + vSphere Provider Version
2019/03/28 08:56:04 [INFO] Terraform version: 0.11.13
2019/03/28 08:56:04 [INFO] Go runtime version: go1.11.5
2019/03/28 08:56:04 [INFO] CLI args: []string{"/usr/bin/terraform", "-v"}
2019/03/28 08:56:04 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2019/03/28 08:56:04 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
Terraform v0.11.13
2019/03/28 08:56:04 [INFO] CLI command args: []string{"version", "-v"}
2019/03/28 08:56:04 [DEBUG] checking for provider in "."
2019/03/28 08:56:04 [DEBUG] checking for provider in "/usr/bin"
2019/03/28 08:56:04 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2019/03/28 08:56:04 [DEBUG] found provider "terraform-provider-vsphere_v1.10.0_x4"
2019/03/28 08:56:04 [DEBUG] found valid plugin: "vsphere", "1.10.0", "/opt/terransible/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.10.0_x4"
2019/03/28 08:56:04 [DEBUG] plugin: waiting for all plugin processes to complete...
+ provider.vsphere v1.10.0

### Affected Resource(s)

* vsphere_virtual_machine.vm: Resource 'vsphere_virtual_machine.vm' does not have attribute 'ipv4_address' for variable 'vsphere_virtual_machine.vm.ipv4_address'

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user           = "${var.vsphere_user}"
  password       = "${var.vsphere_password}"
  vsphere_server = "${var.vsphere_server}"

  # If you have a self-signed cert
  allow_unverified_ssl = "${var.vsphere_ssl}"
}

data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_dc}"
}

data "vsphere_datastore" "datastore" {
  name          = "${var.vsphere_ds}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name          = "${var.vsphere_compute}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name          = "${var.vsphere_net}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name          = "${var.vsphere_template}"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  wait_for_guest_ip_timeout = "5"
  name             = "${local.vsphere_vm}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus = "${var.vsphere_cpu}"
  memory   = "${var.vsphere_mem}"
  folder   = "${var.vsphere_folder}"
  guest_id = "${data.vsphere_virtual_machine.template.guest_id}"

  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  network_interface {
    network_id   = "${var.vsphere_net2}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "${local.vsphere_disk0}"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
  disk {
    label            = "${local.vsphere_disk1}"
    unit_number      = 1
    size             = "${data.vsphere_virtual_machine.template.disks.1.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.1.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.1.thin_provisioned}"
  }
  disk {
    label            = "${local.vsphere_disk2}"
    unit_number      = 2
    size             = "${data.vsphere_virtual_machine.template.disks.2.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.2.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.2.thin_provisioned}"
  }

 clone {
   template_uuid = "${data.vsphere_virtual_machine.template.id}"
   customize {
      linux_options {
        host_name = "${local.vsphere_hostname}"
        domain    = "${var.vsphere_domain}"
      }
     network_interface {}
     network_interface {}
   }
 }

 # Copies ssh key if not available
 provisioner "file" {
   source      = "/root/.env"
   destination = "/root/.env"
   connection {
     password = "${var.root_password}"
   }
 }

 # Execute Ansible software provisioning
 #provisioner "local-exec" {
 #  command = "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${vsphere_virtual_machine.vm.public_ip} echo -e \"Host 10.26.49.*\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\" > /etc/ssh/ssh_config"
 #}

 # Execute Ansible software provisioning
 provisioner "local-exec" {
   environment {
        PUBLIC_IP  = "${vsphere_virtual_machine.vm.ipv4_address}"
    }
   command = <<EOT
     echo [${var.build_stage}] >> ${var.local_ansible_dir}/.inventory
     echo ${vsphere_virtual_machine.vm.ipv4_address} >> ${var.local_ansible_dir}/.inventory
     ansible-playbook -u root --private-key ~/.ssh/id_rsa -inventory=${vsphere_virtual_machine.vm.ipv4_address}, ${var.local_ansible_dir}/ansible.yml
   EOT
 }
}
```

### Debug Output

https://gist.github.com/federicodallari1/a9cd081a432349d52ea5f9b7d7c30f52

### Expected Behavior

Ipv4_address should be filled with the value

### Actual Behavior

What actually happened?

### Steps to Reproduce

terraform apply -lock=false -input=false -auto-approve

### Important Factoids

I'm able to deploy the vm without any issue but is the variable valorization that is not happening as expected in fact based on the debug log I can see that terraform is reading the IP values but not able to address it to the variable.
I've tried many different possible cases, troubleshooting all steps and the issue is happening in  provisioner "local-exec" block.
Already tried all variables, using self, vm, network interface or ip_address, public_ip and so on but the result never changes.
Please give me help on this.

**Comment by bill-rich** [comment]
Hi @federicodallari1!

The reason you're receiving the error about the VM not having the `ipv4_address` attribute is that `ipv4_address` is actually an sub-attribute of `network_interface` in `clone`. This is probably not the attribute you need for what you're trying to accomplish as it is used for customizing newly cloned VMs. If you need the IP address of the VM, `default_ip_address`. See [here](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#default_ip_address) for more details.

**Comment by cmetcalf202** [comment]
I flipped many tables before finding out how to do this. For what it's worth, here is what worked for me using Terraform 0.12.20

I'm using modules so here is the outputs.tf file for my module:

output "ip_address" {
    value = module.testing2.ip_address
}

Here is the outputs.tf file for the module being called (in my case the vsphere_virtual_machine.vm module):

output "ip_address" {
  value = vsphere_virtual_machine.vm.*.clone.0.customize.0.network_interface.0.ipv4_address
}

Rejoice!!!!
