### ISSUE TITLE
An error occurred while customizing VM

### ISSUE THREAD

**Issue by kotyara85** [terraform-providers/terraform-provider-vsphere#735]
Hi there,

The latest version of terraform and vsphere provider cannot modify VM config (ip, dns, network)

It might be something with my templates though.

I checked most of the resource and everyone complaints about perl package is it's not installed.

Perl package & open-vm-tools are installed on both centos76 & ubuntu18 and still the error emerges.

### Terraform Version

v0.11.13

### vSphere Provider Version

v1.10.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

Error:

vsphere_virtual_machine.vm: Still creating... (10s elapsed)
vsphere_virtual_machine.vm: Still creating... (20s elapsed)

Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.vm: 1 error(s) occurred:

* vsphere_virtual_machine.vm:
Virtual machine customization failed on "/DC/vm/example1.com":

An error occurred while customizing VM example1.com. For details reference the log file <No Log> in the guest OS.

Any help is appreciated.

Thanks

**Comment by bill-rich** [comment]
Hi @kotyara85!

Can you please try customizing the a VM from those templates manually from vCenter? You'll need to check that the customization data is properly utilized as vCenter often won't report an error on a failure. This will help narrow down if it is a template issue or a Terraform provider issue.

Thanks!

**Comment by kotyara85** [comment]
Hi @bill-rich,
By customizing you mean cpu/memory change or something else?
I feel like it might be a template issue. 
We generate templates with govc as we don’t have dhcp and packer doesn’t work for us. 
Any recommendation what can I check on templates side?
Thanks!

**Comment by bill-rich** [comment]
You can manually try the same customization process through the vSphere client by following [these](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) directions.

The requirements for guest customization can be found [here](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html)

Another possible trick to try if your template meets all the requirements, but customization still fails is to convert the template to a VM, boot it up and let it sit until vSphere detects the version of VMware tools, then shut it down and convert it back to a template. Sometimes vSphere will not allow guest customization if it doesn't detect VMware Tools on the source template.
