### ISSUE TITLE
Maximum Character Limit For run_once_command_list Attribute

### ISSUE THREAD

**Issue by luckerby** [terraform-providers/terraform-provider-vsphere#738]
Running terraform `v0.11.11`, along with vsphere provider `v1.9.1`.

The problem I'm running into is that if the length of any of the commands in the `run_once_command_list` attribute within `customize`'s `windows_options` section is large enough, once the VMs being created boot, that particular entry will be disregarded.

Let's consider a practical example:
```
clone {
      template_uuid = "${data.vsphere_virtual_machine.template.id}"
      
      customize {
          windows_options {
              run_once_command_list = ["powershell.exe -command \"Get-MyCommand\"",
                                                        "powershell.exe -command \"Set-Cmdlet | Build-AReallyReallyReaaaallyyLongStringHereThatExceeds256Characters\""]
              auto_logon = true
              auto_logon_count = 1
              admin_password = "P@ssw0rd"
```

If the 2nd string being passed as command exceeds a large-enough length, then that particular command will be ignored once the machine boots up. I'm assuming that value is 255 or 256 characters, based simply on the fact that a 270 inline command set failed to run, while trimming the same command set (by eliminating whitespace and restructing a bit) to be under 250 characters worked as intended.

If the above is indeed right, could the [documentation](https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#run_once_command_list)  be updated to reflect this please ?

**Comment by bill-rich** [comment]
Thanks for finding this @luckerby! At first glance, I didn't find where the command length limitation is, but it does appear that there is a limit somewhere. I will look more into where that limit is imposed and adjust if possible, and update the documentation to reflect the maximum character count otherwise.
