### ISSUE TITLE
Temporary datastore resource that is destroyed on end of run

### ISSUE THREAD

**Issue by prakashvv** [terraform-providers/terraform-provider-vsphere#741]
### Terraform Version

Terraform v0.11.12

### vSphere Provider Version

provider.vsphere 1.10.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_nas_datastore`
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
data "vsphere_resource_pool" "pool" {
  name          = "Resources"
  datacenter_id = "datacenter-12345"
}

data "vsphere_network" "network" {
  name          = "VM Network"
  datacenter_id = "datacenter-12345"
}

data "vsphere_datastore" "local_datastore" {
  name          = "local-ds"
  datacenter_id = "${data.vsphere_datacenter.example_datacenter.id}"
}

resource "vsphere_nas_datastore" "datastore" {
  name            = "terraform-test"
  host_system_ids = ["host-12346"]

  type         = "NFS"
  remote_hosts = ["esxi1"]
  remote_path  = "/test"
}

# Create a vSphere VM
resource "vsphere_virtual_machine" "tf-db" {
  # VM placement #
  name             = "tf-db-instance"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${vsphere_nas_datastore.datastore.id}"
  new_datastore_id     = "${vsphere_datastore.local_datastore.id}"

  # VM resources #
  num_cpus = "1"
  memory   = "1024"

  # VM storage #
  disk {
    label            = "disk0"
    datastore_id     = "${vsphere_nas_datastore.datastore.id}"
    new_datastore_id     = "${vsphere_datastore.local_datastore.id}"
    attach           = true
    path             = "tf-db-instance/tf-db-instance.vmdk"
  }

  # VM networking #
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
  }

  depends_on = ["vsphere_nas_datastore.datastore"]
}

vsphere_virtual_machine
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I want to achieve this workflow in using a single TF plan.

1. Create a NFS datastore using an NFS share path
2. Create VM from the VM configuration/disks available in the mounted datastore
3. Change datastore of the VM to a local VMFS datastore(so that the vm config and disks are migrated using vMotion but the VM can still be usable)
4. Unmount the NFS datastore on vMotion completion

### Actual Behavior

Currently I'm achieving this using multiple runs.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. do `terraform apply` for target `vsphere_nas_datastore.datastore` to create datastore
2. do `terraform apply` to create VM
3. Edit the plan and change `datastore_id` and run `terraform apply` to trigger storage vMotion

### Important Factoids

N/A

### References

None

**Comment by bill-rich** [comment]
Hi @prakashvv! 

That is an interesting use case! We don't generally support temporary resources, but you could probably accomplish something similar by using the `vsphere_file` resource. With that, you could either upload or copy the files to the target datastore, and then create the VM using those files instead.

Another option would be to create a VM from the "temporary" NFS datastore, then create the target VM by cloning the first. After the cloned VM is created, you could use a local-exec provisioner to destroy the source VM and the NFS datastore.

**Comment by prakashvv** [comment]
Thanks @bill-rich for the possible approaches

Both of these will bring up the VM on the local datastore eventually but the VM will not be instantly available for use. The case I was looking for was to make the VM instantly available and move the VM transparently even if the user is using it.
