### ISSUE TITLE
Terraform detaches disks which are not managed by itself.

### ISSUE THREAD

**Issue by andreipetrescu95** [terraform-providers/terraform-provider-vsphere#750]
Hi guys,

I have created some VMs using Terraform and have deployed a Kubernetes cluster on top of them using Kubespray. These VMs sit on top of a vSphere cluster, and the Kubernetes API has access to the vSphere API to create persistent volumes. The problem is that when I run the Terraform scripts again, I get an output like this:

``` 
 ~ vsphere_virtual_machine.worker[1]
      disk.1.label: "orphaned_disk_0" => "<remove, keep disk>"
      disk.2.label: "orphaned_disk_1" => "<remove, keep disk>"
      disk.3.label: "orphaned_disk_2" => "<remove, keep disk>"

  ~ vsphere_virtual_machine.worker[2]
      disk.1.label: "orphaned_disk_0" => "<remove, keep disk>"

  ~ vsphere_virtual_machine.worker[3]
      disk.1.label: "orphaned_disk_0" => "<remove, keep disk>"
      disk.2.label: "orphaned_disk_1" => "<remove, keep disk>"

  ~ vsphere_virtual_machine.worker[5]
      disk.1.label: "orphaned_disk_0" => "<remove, keep disk>"
      disk.2.label: "orphaned_disk_1" => "<remove, keep disk>"
```

I have applied this configuration and it detached all my volumes from my VMs.
Is there any way that I can configure Terraform to bypass these changes so I can scale my cluster without having Terraform detach my disks?

### Terraform Version

Terraform v0.11.10

### vSphere Provider Version

v1.9.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

If this issue appears to affect multiple resources, it may be an issue with
Terraform's core, so please mention this.

### Terraform Configuration Files

```
resource "vsphere_virtual_machine" "worker" {
  count            = "${length(var.k8s_worker_ips)}"
  name             = "${var.k8s_node_prefix}-worker-${count.index}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder           = "${vsphere_folder.folder.path}"

  num_cpus         = "${var.k8s_worker_cpu}"
  memory           = "${var.k8s_worker_ram}"
  guest_id         = "${data.vsphere_virtual_machine.template.guest_id}"
  enable_disk_uuid = "true"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "${var.k8s_node_prefix}-worker-${count.index}.vmdk"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    linked_clone  = "${var.vm_linked_clone}"

    customize {
      linux_options {
        host_name = "${var.k8s_node_prefix}-worker-${count.index}"
        domain    = "${var.k8s_domain}"
      }

      network_interface {
        ipv4_address = "${lookup(var.k8s_worker_ips, count.index)}"
        ipv4_netmask = "${var.k8s_netmask}"
      }

      ipv4_gateway    = "${var.k8s_gateway}"
      dns_server_list = ["${split(",", var.k8s_dns)}"]
    }
  }

  provisioner "remote-exec" {
    connection {
      type        = "ssh"
      private_key = "${file("id_rsa")}"
    }

    inline = [
      "sudo apt-get update",
      "sudo apt-get install -y ntp",
      "sudo swapoff -a",
      "sudo sed -i '/ swap / s/^/#/' /etc/fstab",
      "sed -i '/^pool/ d' /etc/ntp.conf",
      "echo \"pool ${var.time_server} iburst\" >> /etc/ntp.conf",
      "service ntp stop",
      "service ntp start",
    ]
  }

  depends_on = ["vsphere_virtual_machine.master"]
}
```

### Expected Behavior

I expect Terraform to not detach disks which are not managed by itself.

### Actual Behavior

Terraform detaches my disks, thus causing problems to my Kubernetes pods.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I have tried to update to the v1.10.0 version of the provider, but I am facing the same problem.

**Comment by serverbaboon** [comment]
Have you looked at the lifecycle commands, I have to use it to leave Annotations and tags alone.

The downside is you cannot change the managed disk sizes with Terraform if you tell it to ignore disks, maybe not what you wanted but its may help. The datastore_id is there to stop terraform doing vmotions if you have moved it from the deployed datastore.

e.g.

 lifecycle {
    ignore_changes = ["annotation", "tags", "datastore_id", "disk" ]
  }

**Comment by bill-rich** [comment]
Hi @andreipetrescu95! The reason for the detaching is to ensure that the actual state of the managed resource matches what is in the configuration file to avoid drift. When Terraform is run and sees the resource has changed, it creates the plan to bring it back into sync with the configuration file. 

If you'd like to override this behavior for certain attributes, then @serverbaboon has the right idea. You can use lifecycle options to ignore the changes to disks.
