### ISSUE TITLE
Scales down before scaling up if some vsphere instances have failed when changing count

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-vsphere#752]
### Background

Terraform is run to spin up 8 instances which are zero indexed in terraform as 0, 1, ..., 6, 7. Instances 0, 2, 3, and 5 fail leaving 4 healthy instances. A developer notices that a count of 4 is not enough so increases terraform's count to 6. Terraform then sees this instruction as spin down instances 6 and 7, and spin up the dead instances. So basically we end up scaling down before scaling up.

It would be nice when the terraform is run that terraform could some how check for dead instances and if there are dead instances, remove those instances from the state, so in the previous example, terraform would spin up would clear the dead instances, and then spin up 2 healthy instances as expected.

### Terraform Version

0.11.13

### vSphere Provider Version

1.10.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "windows_server" {
  name             = "TF-${var.environment}-${var.role}-${random_id.instance_id.*.hex[count.index]}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool_id}"
  host_system_id   = "${data.vsphere_host.host.*.id[element(local.service_hosts, count.index)]}"
  folder           = "${lower(var.environment)}"

  guest_id  = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"

  num_cpus = "${var.vm_cpus}"
  memory   = "${var.vm_memory}"

  count = "${var.scale}"

  wait_for_guest_net_timeout = 60

  disk {
    label            = "windows-server.vmdk"
    size             = "${var.disk_size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

  network_interface {
    network_id = "${data.vsphere_network.network.id}"
  }

  lifecycle {
    ignore_changes = "clone"
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"
    ...
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Check if hosts in tf state are dead before scaling up

### Actual Behavior

Does not check and tries to scale up dead instances

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. Make count = 8
2. `terraform apply`
3. Turn off and delete 4 machines
4. Set count = 6
5. `terraform apply`
6. Notice that terraform will try to remove 2 healthy instances instead of first checking if current instances in the state have been deleted.

### Important Factoids

Unsure if this is a bug in the provider. If so then this ticket makes sense, if not, then how can we resolve this in terraform itself?

If it's not possible, we're considering creating a step before our CICD of terraform to first check if anything in the tf remote state is dead, remove it from the state, then apply the terraform.

### References

N/A

**Comment by bill-rich** [comment]
Hi @nitrocode! There is actually a way to enable similar behavior using [create_before_destroy](https://www.terraform.io/docs/configuration/resources.html#create_before_destroy). I'm afraid it may not work for you in this case because of the naming restrictions in vSphere. With that option enabled, when VMs need to be recreated, the new ones will be created before the old ones are destroyed. If they have failed, but still exist in vSphere, this will result in a duplicate name (unless you have names uniquely generated). 

As for removing missing items from the state before continuing, that should actually be happening if the resources are fully removed from vSphere when the plan is run. Can you provide some more details about what constitutes a dead state in your use case?

**Comment by bill-rich** [comment]
If the VM is gone from vSphere, Terraform should be recreating it as expected. Terraform could be checking that VMs are powered on or looking for certain errors or warnings that indicate a failure. Any details on specific use cases could help expedite this, but I think either way that it could be a useful feature to have on the backlog.

**Comment by bill-rich** [comment]
I'm going to close this issue for now as the original problem seems to already be addressed. If there becomes demand for additional checks on VM status, we'll get a new feature request opened.

**Comment by nitrocode** [comment]
@bill-rich  One of our engineers tried the create_before_destroy which was a very useful suggestion but it did not remove reindex the terraform remote state without first terminating healthy VMs in the scenario described in the original issue.
