### ISSUE TITLE
Changing the admin_password cause a redeploy of the VM

### ISSUE THREAD

**Issue by serverbaboon** [terraform-providers/terraform-provider-vsphere#753]
Can the provider either ignore a change in the value of admin_password in the windows customisation of a template deploy by default or allowed to be ignored in the lifecycle policy.

This is not something we would ever set via Terraform after the initial deployment it would be done externally and Terraform should not try and change it. If a vm needs to be redeployed with a new admin password and there is no other way to set it then you
should probably taint the resource instead.

If this variable is being set dynamically by environment variable or secrets stores you could
cause (potentially) a redeployment of your virtual machines if there has been a global change of this password.

### Terraform Version

0.11.13

### vSphere Provider Version
1.10

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files
Tried to ignore the setting with.

  lifecycle {
    ignore_changes = ["annotation", "tags", "admin_password"]
  }

### Expected Behavior

The provider should ignore a change in the local admin password or you should be able to ignore a changein your script with the lifecycle function.

### Actual Behavior

The provider will redeploy the whole vm again.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. change your value for admin_password
2. `terraform apply`

### Important Factoids

The passwords are being pulled from environment variables.

### References

A quick search did not reveal any related issues.

**Comment by serverbaboon** [comment]
I can see from an unrelated ticket that I can add the whole "clone" section to the life cycle policy ignore section which does seem to work.......

However if the password has changed AND you decide to increase one of the disks then everything gets confusing.

instead of:

---
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.directapp.vsphere_virtual_machine.vm[1]
      disk.1.size: "100" => "120"
Plan: 0 to add, 1 to change, 0 to destroy.

Error: Apply cancelled.


You get get a plan to change all disks on all the vm's in the deployment not just the VM you have changed the disk size on. This will actually fail as the Scsi ID's are already assigned. ( I can raise this as an issue if the ignore_changes = ["clone"] is a legit one.

 module.directapp.vsphere_virtual_machine.vm[1]
   disk.#:                  "2" => "2"
   disk.0.attach:           "false" => "false"
   disk.0.datastore_id:     "datastore-189" => "<computed>"
   disk.0.device_address:   "scsi:0:0" => <computed>
   disk.0.disk_mode:        "persistent" => "persistent"
   disk.0.disk_sharing:     "sharingNone" => "sharingNone"
   disk.0.eagerly_scrub:    "false" => "false"
   disk.0.io_limit:         "-1" => "-1"
   disk.0.io_reservation:   "0" => "0"
   disk.0.io_share_count:   "1000" => "0"
   disk.0.io_share_level:   "normal" => "normal"
   disk.0.keep_on_remove:   "false" => "false"
   disk.0.key:              "2000" => "0"
   disk.0.label:            "disk0" => "disk0"
   disk.0.path:             "xxxxx/xxxx.vmdk" => <computed>
   disk.0.size:             "75" => "75"
   disk.0.thin_provisioned: "true" => "true"
   disk.0.unit_number:      "0" => "0"
   disk.0.uuid:             "6000C297-5948-aca0-7c0f-31f0af689bb2" => <computed>
   disk.0.write_through:    "false" => "false"
   disk.1.attach:           "false" => "false"
   disk.1.datastore_id:     "datastore-189" => "<computed>"
   disk.1.device_address:   "scsi:0:1" => <computed>
   disk.1.disk_mode:        "persistent" => "persistent"
   disk.1.disk_sharing:     "sharingNone" => "sharingNone"
   disk.1.eagerly_scrub:    "false" => "false"
   disk.1.io_limit:         "-1" => "-1"
   disk.1.io_reservation:   "0" => "0"
   disk.1.io_share_count:   "1000" => "0"
   disk.1.io_share_level:   "normal" => "normal"
   disk.1.keep_on_remove:   "false" => "false"
   disk.1.key:              "2001" => "0"
   disk.1.label:            "disk1" => "disk1"
   disk.1.path:             "XXXXX/XXXX_1.vmdk" => <computed>
   disk.1.size:             "100" => "120"
   disk.1.thin_provisioned: "true" => "true"
   disk.1.unit_number:      "1" => "1"
   disk.1.uuid:             "6000C292-13e9-b45b-c9d0-ccb87054643c" => <computed>
   disk.1.write_through:    "false" => "false"

**Comment by bill-rich** [comment]
Hi @serverbaboon! I see that it can be frustrating that changing `admin_password` results in redeploying the VM. The reason for it though it that we configuration should match what is actually on the machines. Since we cannot update the admin password through the vSphere API once the VM has been cloned, the only way to ensure the two match is be redeploying it. 

You are on the right track using `ignore_changes`, and you can actually be more specific on what exactly to ignore also. For example, you could ignore just the `admin_password` with:
```
ignore_changes = ["clone[0].customize[0].windows_options[0].admin_password"]
```

It is odd that all the disks are updating though with the changes just on one. Can you please provide a copy of your configuration so I can take a closer look at what may be going on?

**Comment by serverbaboon** [comment]
mmm not sure I see the value in that, especially if the password is pulled from a secret store and its value rotates to comply with company policy. However the work around is enough to try.

Do you want me top open a separate issue or keep it in this?

**Comment by bill-rich** [comment]
In your use case, I agree that it doesn't make a lot of sense to make a change in `admin_password` trigger a rebuild. There are some cases where the expectation is that whatever is in the config is what is on the VM. It is a bit of a pain to have to include the lifecycle settings, but it does allow for both use cases.

Lets do a new issue for the disk issue. That way it will be easier to find for anyone with similar issues. Thanks!

**Comment by serverbaboon** [comment]
I have been out of the office so was only able to try this today and your suggestion did not work.

**Comment by serverbaboon** [comment]
If you come across this thread the correct expression is:

"clone.0.customize.0.windows_options.0.admin_password"

Although checkout

https://github.com/terraform-providers/terraform-provider-vsphere/issues/764
