### ISSUE TITLE
 * provider.vsphere: Error connecting to CIS REST endpoint: Login failed: - status: 401 Unauthorized

### ISSUE THREAD

**Issue by HimaruKitaro** [terraform-providers/terraform-provider-vsphere#756]
Hi,

 I would like seek some assistance.  I'm trying to deploy VM but I'm experiencing an "Error connecting to CIS REST endpoint". Please see below the complete error message. I removed the resources and leave only the data "vsphere_datacenter" to simulate but there still an error.  I can see my account was able to login and logout in vcenter whenever I run "terraform plan".  My account privilege on vCenter is also an administrator.   

* provider.vsphere: Error connecting to CIS REST endpoint: Login failed: body: {"type":"com.vmware.vapi.std.errors.unauthenticated","value":{"messages":[{"args":[],"default_message":"This method requires authentication.","id":"vapi.method.authentication.required"}]}}, status: 401 Unauthorized
 
### Terraform Version
Terraform v0.11.13

### vSphere Provider Version
provider.vsphere v1.10.0

### Affected Resource(s)
- vsphere_virtual_machine 

### Terraform Configuration Files

```hcl
provider "vsphere" {
  vsphere_server       = "${var.vsphere_server}"
  user                 = "${var.vsphere_user}"
  password             = "${var.vsphere_password}"
  allow_unverified_ssl = true
  version              = "1.10.0"
}

data "vsphere_datacenter" "dc" {
  name = "${var.vsphere_dc}"
}

data "vsphere_datastore" "datastore" {
  name            = "${var.vsphere_datastore}"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_compute_cluster" "cluster" {
  name            = "${var.vsphere_cluster}"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_network" "network" {
  name            = "${var.vsphere_network}"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_virtual_machine" "template" {
  name            = "${var.vm_template}"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
}


resource "vsphere_virtual_machine" "vm" {
  name             = "${var.vm_name}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  resource_pool_id = "${data.vsphere_compute_cluster.cluster.resource_pool.id}"

  num_cpus  = "${var.vm_cpu}"
  memory    = "${var.vm_memory}"
  guest_id  = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type = "${data.vsphere_virtual_machine.template.scsi_type}"
  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }
  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }
}

```

### Actual Behavior
$ terraform plan -var-file mysqlvm-data.tfvar
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

Error: Error refreshing state: 1 error(s) occurred:

* provider.vsphere: Error connecting to CIS REST endpoint: Login failed: body: {"type":"com.vmware.vapi.std.errors.unauthenticated","value":{"messages":[{"args":[],"default_message":"This method requires authentication.","id":"vapi.method.authentication.required"}]}}, status: 401 Unauthorized

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform init -var-file mysqlvm-data.tfvar`
2. `terraform plan -var-file mysqlvm-data.tfvar`

**Comment by bill-rich** [comment]
Hi @HimaruKitaro! It seems to be a problem specifically with the CIS endpoint. There are a couple steps we can take to narrow down where the problem is. First, can you check where the permissions are applied in vCenter? If you have administrator, but it is not at the vCenter level (datacenters or lower), it could be causing the issue you're running into.

If everything looks good there, another good test would be using the API explorer. You can access that by going to https://<vcenter_address>/apiexplorer. From there, you can use the CIS api, and try running an API call. Just make sure to use the same user as you are for Terraform. 

Let me know what details you find in those steps and we can see what to look into next.

**Comment by HimaruKitaro** [comment]
Hi @bill-rich,the account has administrator privilege on vCenter level. I can clone a VM through API as well.  But after I set only the vCenter URL to no_proxy, it works.  I'll try to recall the settings of the OS also the original settings of no_proxy to check if I can reproduce the error.  I'm closing this case and thanks for the assistance.
