### ISSUE TITLE
Could not assign ipv6 in an IPv6-exclusive environment

### ISSUE THREAD

**Issue by SerenaLi279** [terraform-providers/terraform-provider-vsphere#759]
Environment: not have a DHCP server on the network, I want to configure only IPv6 with static ips
### Terraform Version

Terraform v0.11.11

### vSphere Provider Version

terraform-provider-vsphere_v1.9.1_x4

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl

resource "vsphere_virtual_machine" "vm-node" {
    name = "${var.hostname}"
    resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
    datastore_id = "${data.vsphere_datastore.datastore.id}"
    wait_for_guest_net_timeout = 0
    shutdown_wait_timeout = 10

    num_cpus = "${var.vm_cpu}"
    memory = "${var.vm_ram}"
    guest_id = "${data.vsphere_virtual_machine.app_template.guest_id}"
    scsi_type = "${data.vsphere_virtual_machine.app_template.scsi_type}" 

    clone {
        template_uuid = "${data.vsphere_virtual_machine.app_template.id}"
        customize {
            linux_options {
                host_name = "${var.hostname}"
                domain    = "${var.domain}"
            }
            # dns_server_list = ["${var.dns_server1}", "${var.dns_server2}"]  

            network_interface {
                ipv6_address = "${element(split(" ", var.NIC_0_ipv6), var.count_index)}"
                ipv6_netmask = 64
            }
            ipv6_gateway = "2001:250:4000:2000::1" 
        }
    }

    network_interface {
        network_id = "${data.vsphere_network.network_label_net-02.id}"
        adapter_type = "${data.vsphere_virtual_machine.app_template.network_interface_types[0]}"
    } 
}
```

### Expected Behavior
Could set ipv6 with static ip which configed in vsphere_virtual_machine, and vm could use this ipv6

### Actual Behavior
has set wait_for_guest_net_timeout = 0
ipv6 not configured for the network interface, because the ipv4 use DHCP Iin ifcfg-eth0 which generated by terraform, there is no DHCP for ipv4 and I do not want to use ipv4.
```hcl
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:84:c0:12 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::250:56ff:fe84:c012/64 scope link 
       valid_lft forever preferred_lft forever
```
```hcl
HWADDR=00:50:56:84:c0:12
NAME=eth0
DEVICE=eth0
ONBOOT=yes
USERCTL=no
BOOTPROTO=dhcp
PEERDNS=yes
IPV6_DEFAULTGW=2001:250:4000:2000::1
IPV6INIT=yes
IPV6ADDR=2001:250:4000:2000::61/64
IPV6ADDR_SECONDARIES=""

check_link_down() {
 return 1; 
}
```

And If I delete BOOTPROTO=dhcp and add IPADDR='' then ifup eth0, it will work
```hcl
HWADDR=00:50:56:84:c0:12
NAME=eth0
DEVICE=eth0
ONBOOT=yes
USERCTL=no
PEERDNS=yes
IPV6_DEFAULTGW=2001:250:4000:2000::1
IPV6INIT=yes
IPV6ADDR=2001:250:4000:2000::61/64
IPADDR=''
IPV6ADDR_SECONDARIES=""

check_link_down() {
 return 1; 
}
```
```hcl
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:84:c0:12 brd ff:ff:ff:ff:ff:ff
    inet6 2001:250:4000:2000::61/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe84:c012/64 scope link 
       valid_lft forever preferred_lft forever
```
### Question
How could I only configure ipv6 with static ips not use ipv4(and there is no DHCP server)?

**Comment by SerenaLi279** [comment]
Hi @vancluever,
I found that you have mentioned https://github.com/terraform-providers/terraform-provider-vsphere/issues/231, if set wait_for_guest_net_timeout = 0, only set ipv6 static ips in a  an IPv6-exclusive environment could work.
I also found related description in https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html:
```hecl
NOTE: The minimum setting for IPv4 in a customization specification is DHCP. If you are setting up an IPv6-exclusive network without DHCP, you might need to set wait_for_guest_net_timeout to a high enough value to cover the DHCP timeout of your virtual machine, or turn it off altogether by supplying a zero or negative value. Keep in mind that turning off wait_for_guest_net_timeout will more than likely mean that IP addresses will not be reported to any provisioners you may have configured on the resource.
```
But in my case it dose not work, could you help me to check it?

Thanks a lot~

**Comment by bill-rich** [comment]
Hi @SerenaLi279! Normally the VM will try to use DHCP for IPv4, time out, apply the IPv6 address and continue on. I'd like to try and narrow down what is different in this case so I can try to reproduce the issue and figure out how best to address it. What operating system is on the VM that is exhibiting this behavior? Is the VM hanging during boot, or is it booting but no IPv6 address applied to the interface?

**Comment by SerenaLi279** [comment]
@bill-rich,
1. Use Red Hat 4.8.5-36 on on the VM that is exhibiting this behavior:
Linux version 3.10.0-957.10.1.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Feb 7 07:12:53 UTC 2019

2. Is it booting but no IPv6 address applied to the interface:
I could login the vm from console, and no IPv6 address applied to the interface(I have described in **Actual Behavior**)

**Comment by bill-rich** [comment]
Thanks for the additional information. I suspect the problem you're running into is a [compatibility issue](https://kb.vmware.com/s/article/2105648) with VMware and NIC configs on certain operating systems. To confirm, you can try deploying a VM from that template using the guest customization in the vCenter web UI and see if it results in the same lack of address.

If that is the case, you will probably be stuck with working around the issue. One possibility would be to assign a static dummy IPv4 address so that the `BOOTPROTO` will be static and hopefully will move on to assigning the IPv6 address.
