### ISSUE TITLE
Vsphere workspace issue

### ISSUE THREAD

**Issue by gowthamakanthan** [terraform-providers/terraform-provider-vsphere#772]
Hi Team,

Am trying to make the terraform codes reusable across the vspheres. And trying to configure "terraform workspace". But it's throwing the below-mentioned errors.

### Terraform Version

Terraform v0.12.0

### vSphere Provider Version

+ provider.vsphere v1.11.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_server'
- `vsphere_datacenter` 'dc'
- and continues 

### Terraform Configuration Files

`#cat provider.tf 
provider "vsphere" {
 version        = "~> 1.10"
  user           = var.vsphere_user
  password       = var.met_vsphere_password
  vsphere_server = var.vsphere_server
  allow_unverified_ssl = true
}

#cat variables.tf
#providers

variable "vsphere_user" {
}

variable "vsphere_password" {
}

variable "met_vsphere_password" {
}

#variable "vsphere_server" {}

variable "vsphere_server" {
  type = map(string)

  default = {
    met  = "met-hx-vc.dcloud-cisco.com:443"
    idev = "pl-vcsa-plat.dcloud-cisco.com:443"
  }
}
variable "dc_name" {
  type = "map"

  default = {
    met = "met-hx"
    idev = "Platform-DC"
  }
}`

### Expected Behavior

Terraform plan should provide for the planned output.

### Actual Behavior
'#terraform plan

Error: Incorrect attribute value type

  on provider.tf line 5, in provider "vsphere":
   5:   vsphere_server = var.vsphere_server

Inappropriate value for attribute "vsphere_server": string required.

#terraform plan

Error: Invalid value for input variable

  on terraform.tfvars line 7:
   7: dc_name = "met-hx"

The given value is not valid for variable "dc_name": map of any single type
required.'

### Steps to Reproduce

1. `terraform apply`

**Comment by bill-rich** [comment]
Hi @gowthamakanthan! It looks like you're on the right track. The issue you're running into is that you're passing a map (of strings) to arguments that require a string. It looks like the idea would be that the workspaces are `met` and `idev`. You can use `terraform.workspace` to specify which item from the map to use for the arguments that vary based on workspace. I believe the following example should work for your purposes.

```
provider "vsphere" {
  version              = "~> 1.10"
  user                 = var.vsphere_user[terraform.workspace]
  password             = var.vsphere_password[terraform.workspace]
  vsphere_server       = var.vsphere_server[terraform.workspace]
  allow_unverified_ssl = true
}

variable "vsphere_user" {
  type = map(string)
}

variable "vsphere_password" {
  type = map(string)
}

variable "vsphere_server" {
  type = map(string)
  default = {
    met  = "met-hx-vc.dcloud-cisco.com:443"
    idev = "pl-vcsa-plat.dcloud-cisco.com:443"
  }
}

variable "dc_name" {
  type = "map"
  default = {
    met  = "met-hx"
    idev = "Platform-DC"
  }
}
```
With this config, the config will use the workspace name to pick the correct value from maps for the user, password, and server. For example, if you are using environment variables, you could run something like:
```
TF_VAR_vsphere_user='{met="met_user", idev="idev_user"}' \
TF_VAR_vsphere_password='{met="met_password", idev="idev_password"}' \
terraform apply
```

**Comment by gowthamakanthan** [comment]
Working perfectly. You are awesome. Thank you.
