### ISSUE TITLE
question about disk size behaviors on Windows 2016+

### ISSUE THREAD

**Issue by rismoney** [terraform-providers/terraform-provider-vsphere#776]
When you clone from template, and specify disk sizes larger than the template, should customization handle OS level disk resizing or does that require additional post scripts.  OS Windows 2016+.

Right now if my template is 80GB, and I deploy to a disk that is 100, I end up with 20GB of unpartition space, that I subsequently need to extend the OS to.  Is this expected behavior?

**Comment by serverbaboon** [comment]
As far as I know extending of the disk partitions is not in the vmware os customisation feature set.

You can either run a script after deployment or supply your own sysprep.inf file as I think you can extend with sysprep.

**Comment by rismoney** [comment]
Thanks for the tip - within sysprep I see I could do this.  Unfortunately sysprep files are mutually exclusive with the other options.    


```xml
<ExtendOSPartition>
<Extend>true</Extend>
</ExtendOSPartition>
```

I guess I will add a powershell remote-exec to extend c:
```powershell
$MaxSize = (Get-PartitionSupportedSize -DriveLetter c).sizeMax
Resize-Partition -DriveLetter c -Size $MaxSize
```

**Comment by serverbaboon** [comment]
Yes I use the a script.
