### ISSUE TITLE
Error: Cycle: vsphere_virtual_machine while using count. [Terraform Workspace]

### ISSUE THREAD

**Issue by gowthamakanthan** [terraform-providers/terraform-provider-vsphere#779]
Hi there,

Terraform code is working fine when am going with count 1. Also, the code is working fine without a workspace(Multiple counts of VM as well). Strange error, middle of production deployment. Please help.

### Terraform Version

Terraform v0.12.0
+ provider.vsphere v1.11.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files
```
#cat consul.tf



resource "vsphere_virtual_machine" "consul-vm" {
  name             = "${var.consul-vm_name}-${count.index + 1}"
  count            = "${var.consul-vm_count}"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"
  folder            = var.vsphere_folder[terraform.workspace]
  num_cpus = 2
  memory   = 5120
  guest_id   = "${data.vsphere_virtual_machine.template.guest_id}"
  scsi_type  = "${data.vsphere_virtual_machine.template.scsi_type}"
  annotation = "Build via Terraform"

  network_interface {
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${data.vsphere_virtual_machine.template.network_interface_types[0]}"
  }

  disk {
    label            = "disk0"
    size             = "${data.vsphere_virtual_machine.template.disks.0.size}"
    eagerly_scrub    = "${data.vsphere_virtual_machine.template.disks.0.eagerly_scrub}"
    thin_provisioned = "${data.vsphere_virtual_machine.template.disks.0.thin_provisioned}"
  }

 disk {
   label       = "swap-disk"
   size        = 10
   unit_number = 1
  }

  clone {
    template_uuid = "${data.vsphere_virtual_machine.template.id}"

    customize {
      linux_options {
        host_name = "${var.consul-vm_name}-${count.index + 1}"
        domain    = "${var.vsphere_domain}"
        time_zone = "${var.vsphere_time_zone}"
      }

      network_interface {
        ipv4_address = "10.1.24.${80 + count.index}"
        ipv4_netmask = "24"
      }

      ipv4_gateway = "10.1.24.1"
    }
  }

  provisioner "local-exec" {
    command = "echo ${self.guest_ip_addresses.0} > /Auto/idev/terraform/ansible/inventory_${var.consul-vm_name}-${count.index + 1}.yml"
  }

  provisioner "local-exec" {
    command = "cd /Auto/idev/ansible-playbooks/lstack2/provisioning  && ansible-playbook -i /Auto/idev/terraform/ansible/inventory_${var.consul-vm_name}-${count.index + 1}.yml -b -u root -e 'ansible_ssh_pass=${var.vm_password}' terra-consul-playbook.yml"
  }


}
```

### Expected Behavior

Terraform needs to create the vm based on the counts. 

### Actual Behavior

Throwing below error

``` 
terraform apply
var.consul-vm_count
  Total number of the consul server

  Enter a value: 2

var.consul-vm_name
  The hostname for the  consul VM

  Enter a value: consul

var.db-vm_count
  Total number of the database server

  Enter a value: 1

var.db-vm_name
  The hostname for the database server

  Enter a value: db

var.micro-vm_count
  Total number of the microservice server

  Enter a value: 1

var.micro-vm_name
  The hostname for the microservice  server

  Enter a value: micro

data.vsphere_datacenter.dc: Refreshing state...
data.vsphere_datastore.datastore: Refreshing state...
data.vsphere_resource_pool.pool: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_network.network: Refreshing state...
vsphere_virtual_machine.micro-vm[0]: Refreshing state... [id=4219da93-7687-4d5e-4fa3-1180a44348c4]
vsphere_virtual_machine.db-vm[0]: Refreshing state... [id=4219cf9b-3165-ed26-3e99-bf740633afa0]

**Error: Cycle: vsphere_virtual_machine.consul-vm[1], vsphere_virtual_machine.consul-vm[0]**

```
### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by gowthamakanthan** [comment]
team, please help me on this.

**Comment by bill-rich** [comment]
Hi @gowthamakanthan. The `Error: Cycle` message means there is a cycle in the graph generated by Terraform. According to the message, it is between the two VMs in the `consul-vm` resource, but I am not seeing where the cycle is coming from. I tried to reproduce the issue without success, so perhaps it has something to do with the variables being use? It recommend taking a closer look at those. Another options would be to start replacing variables with hardcoded values until you find the one that is causing the issue.

If the variables all check out, I'd cutting back to a minimal config and adding sections back in until you're able to find which is causing the cycle. If you're able to pinpoint which sections of config and/or variables are the culprit, I may be able to provide more insight into what is going on.

**Comment by gowthamakanthan** [comment]
It's worked. Lovely.. Thank you very much.


---
Best regards,
Gowtham
07798838879


=====================
Learn from mistakes....

Please consider the environment before printing this email - Thanks

**Comment by bill-rich** [comment]
Glad to hear you were able to get it fixed!

**Comment by raviseal** [comment]
@gowthamakanthan how did you fix it i have similar error.

**Comment by gowthamakanthan** [comment]
@raviseal I have faced this issue when i using the "extra-var" for the Ansible as the local provisioner. Let me know your code, I can try my best.
