### ISSUE TITLE
is the vSphere Provider capable of setting Advanced Options

### ISSUE THREAD

**Issue by jgs40687** [terraform-providers/terraform-provider-vsphere#782]
Hi there,

### Terraform Version
v0.12.0

### vSphere Provider Version
terraform-provider-vsphere_v1.11.0_x4.exe

### Affected Resource(s)
vsphere_virtual_machine

This is a question at this stage
I can provision a virtual machine without issue
my question is, Security require us to add/change some Advanced Settings for the vm shell, can the Terraform vSphere Provider do this? I have seen people comment on the ability to use extra_config {} etc but can't find the correct syntax

the settings I need to add/change are for example are
isolation.tools.diskShrink.disable = true
isolation.tools.diskWiper.disable = true

and a few more but you get the idea

do I need to drop in a local-exec running the equivalent govc command for example? just means coding the passing of the credentials which is a little messy

Thanks in advance

**Comment by bill-rich** [comment]
The provider does support advanced options via `extra_config`. To add the settings you listed, you would just need to add the following to your `vsphere_virtual_machine` resource:

```
extra_config = {
  "isolation.tools.diskShrink.disable" = "true"
  "isolation.tools.diskWiper.disable" = "true"
}
```
