### ISSUE TITLE
vsphere_virtual_machine: unexpected EOF

### ISSUE THREAD

**Issue by 5330** [terraform-providers/terraform-provider-vsphere#794]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform
issue trackers reserved for bug reports and feature requests. For general usage
questions, please see: https://www.terraform.io/community.html.

### Terraform Version

Run `terraform -v` to show the version. If you are not running the latest
version of Terraform, you can try upgrading, depending on if your problem is
with the provider or with Terraform core itself.

Terraform v0.11.14
(also same errors w/ version 12. 
Recreated issue on both darwin and linux versions. 

### vSphere Provider Version
+ provider.vsphere v1.12.0

terraform providers
.
└── provider.vsphere

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

( only tried this one resource ) 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
## Configure the vSphere Provider
provider "vsphere" {
    vsphere_server = "${var.vsphere_server}"
    user = "${var.vsphere_user}"
    password = "${var.vsphere_password}"
    allow_unverified_ssl = true
//  version = "1.11.0"
}

## Build VM
data "vsphere_datacenter" "dc" {
  name = "EXP1"
}

data "vsphere_datastore" "datastore" {
  name          = "exp1_vs01_dev_ds_2"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

data "vsphere_resource_pool" "pool" {
  name = "Development/Resources/ngc-tf-resource_pool"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"

}

data "vsphere_network" "mgmt_lan" {
  name          = "DVS2-Development_OTV"
  datacenter_id = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "ngc_tf_vm01" {
  name             = "ngc-tf-vm01"
  resource_pool_id = "${data.vsphere_resource_pool.pool.id}"
  datastore_id     = "${data.vsphere_datastore.datastore.id}"

  num_cpus   = 1
  memory     = 2048
  wait_for_guest_net_timeout = 10 
  guest_id = "ngc-tf-vm01"
  nested_hv_enabled =true
  network_interface {
   network_id     = "${data.vsphere_network.mgmt_lan.id}"
  }

  disk {
   size             = 40
   name             = "ngc-tf-vm01.vmdk"
   eagerly_scrub    = false
   thin_provisioned = true
  }
}


```

### Debug Output

https://gist.github.com/5330/01388a5f110edbc5c2045d01d1a376ce

### Panic Output

https://gist.github.com/5330/f4e2b98bdbc4696616e081e7245a2463

### Expected Behavior

Plan worked but apply crashes.  VM should have been created. 

### Actual Behavior

Plan worked but apply crashes.  VM should have been created. 

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
terraform apply 

### Important Factoids

This is my 1st attempt.  It seems likely that I have a config issue but since it crashes I am sending along the details.  I have tried version 12 of terraform, also different versions of the provider and also the mac and linux versions of terraform.

**Comment by sofixa** [comment]
Can confirm this happens pretty regularly for us ( the second part of #762  ) but i don't have the time to debug further.

**Comment by bill-rich** [comment]
Hi @5330! Can you please try building the provider using the `govmomi-v0.18.0` branch and let me know if you're still getting the same error? I haven't been able to reproduce the issue so far. @sofixa first came across this issue after an release that was mostly dependency updates. I'm trying to narrow it down to see what needs to be done to reproduce the issue, and where the fix will need to be applied.

**Comment by 5330** [comment]
will do.  thanks.

**Comment by bill-rich** [comment]
I haven't heard a response on this one in a while. I'm going to close the issue for now. Let me know if you're able to run through the troubleshooting and we can get the issue reopened.
