### ISSUE TITLE
error during upgrade of PTFE code from 0.11.14 to 0.12.2 

### ISSUE THREAD

**Issue by orlybagasala** [terraform-providers/terraform-provider-vsphere#797]
Hi there,

I tried to upgrade our TF code from 0.11.14 to 0.12.2 and it was upgraded without issue using terraform 0.12.2 binary from command line. But when I push my upgraded code to our git repo and run it on my TFE workspace its throwing the below error related to state lock. Please advise.

Terraform v0.12.2

Initializing plugins and modules...
2019/06/25 19:06:46 [DEBUG] Using modified User-Agent: Terraform/0.12.2 PTFE/e63ebf6
local_file.pass: Creating...
local_file.user: Creating...
local_file.pass: Creation complete after 0s [id=64f6f18c78c78f968671fe544ef2af799e9053b1]
local_file.user: Creation complete after 0s [id=dff1f5b3f06b6e421d352e325d0f5929927159dd]
Failed to save state: Error uploading state: Conflict

This workspace is locked by Run
run-SAkpMYQg4MsmvR9v and will only accept state uploads from
them while locked.

Error: Failed to persist state to backend.

### Terraform Version
Terraform v0.12.2

### vSphere Provider Version

* provider.local: version = "~> 1.2"
* provider.vsphere: version = "~> 1.12"
* provider.vault = ~> 2.0.

- backend.tf
terraform {
  backend "atlas" {
    name = "devops/vm-test"
    address = "https://test-server01.xxx.com"
  }
}

**Comment by bill-rich** [comment]
Hi @orlybagasala! I'd like to be able to help out with that, but unfortunately my expertise is in the vSphere provider. To get help on a PTFE issue, please log in and create a ticket at https://support.hashicorp.com. The PTFE support team should be able to help you out.
