### ISSUE TITLE
Virtual machine customization failed 

### ISSUE THREAD

**Issue by ARivoliRam** [terraform-providers/terraform-provider-vsphere#806]
Hi there,
I am getting below error and some times my vm is provisioning and some time it is getting below error and vm provisioning stops.

Virtual machine customization failed on "/infra/vm/machinename":\n\nPost https://ip/sdk: EOF\

### Terraform Version

Terraform v0.12.2
### vSphere Provider Version

6.5 vsphere version

**Comment by bill-rich** [comment]
Hi @ARivoliRam! The first thing to check when guest customization is failing is that your source VM meets the [requirements](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) for guest OS customization on vSphere. The next would be to run through some cusomization [troubleshooting](https://kb.vmware.com/s/article/1026317). If everything looks ok on both of those, you can also try [manually setting up customization](https://pubs.vmware.com/vsphere-50/index.jsp?topic=%2Fcom.vmware.vsphere.vm_admin.doc_50%2FGUID-80F3F5B5-F795-45F1-B0FA-3709978113D5.html) through the vCenter client.

If you're still running into issues after running through those troubleshooting steps, please open an issue with a complete debug log attached and the results of the above steps so we can get a better idea of the cause of the problem.
