### ISSUE TITLE
remote-exec provisioning gets empty Host:

### ISSUE THREAD

**Issue by pavel-mutafchiev** [terraform-providers/terraform-provider-vsphere#811]
### Terraform Version

Terraform v0.12.5

### vSphere Provider Version

+ provider.vsphere v1.12.0

### Affected Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  vsphere_server       = "vmware"
  user                 = "root"
  password             = "password"
  allow_unverified_ssl = true
}

resource "vsphere_virtual_machine" "vmware_vm" {
  count                = 1
  name                 = "testvm"
  resource_pool_id     = "resgroup-18"
  datastore_cluster_id = "group-p91"
  
  num_cpus                   = 2
  memory                     = 2048
  guest_id                   = "centos64Guest"
  scsi_type                  = "pvscsi"
  wait_for_guest_net_routable = true
  wait_for_guest_net_timeout = 5

  network_interface {
    network_id   = "dvportgroup-24"
    adapter_type = "vmxnet3"
  }

  disk {
    label            = "disk0"
    size             = 100
    eagerly_scrub    = false
    thin_provisioned = true
  }

  clone {
    template_uuid = 42165fbd-756e-6523-34f2-0254b47a457b
  }

  provisioner "remote-exec" {
    inline = [
      "echo test > samplefile"
    ]
  }

```

### Expected Behavior

After VM is created, the Host field when provisioning must be populated properly and remote-exec will work and have the sameplefile.

### Actual Behavior

Since Terraform 0.12 we are getting the following remote-exec error when trying to use provisioner:

module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec): Connecting to remote host via SSH...
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   Host:
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   User: root
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   Password: false
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   Private key: false
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   Certificate: false
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   SSH Agent: true
module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0] (remote-exec):   Checking Host Key: false

### Steps to Reproduce

Just try to create a VM with latest terraform 0.12.5

### Important Factoids

On terraform 0.11.14 works just fine. However with any 0.12 version it fails every time. With debugging enabled, i have noticed this:

2019-07-19T12:29:57.263+0300 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: 2019/07/19 12:29:57 [DEBUG] vsphere_virtual_machine (ID = 4216eac2-a629-220a-c0ab-fbe1304891a5): Checking guest networking state
2019-07-19T12:29:57.263+0300 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: 2019/07/19 12:29:57 [DEBUG] vsphere_virtual_machine (ID = 4216eac2-a629-220a-c0ab-fbe1304891a5): Primary IP address: 10.64.1.115
2019-07-19T12:29:57.263+0300 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: 2019/07/19 12:29:57 [DEBUG] vsphere_virtual_machine (ID = 4216eac2-a629-220a-c0ab-fbe1304891a5): All IP addresses: 10.64.1.115
2019-07-19T12:29:57.263+0300 [DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4: 2019/07/19 12:29:57 [DEBUG] vsphere_virtual_machine (ID = 4216eac2-a629-220a-c0ab-fbe1304891a5): Read complete
2019/07/19 12:29:57 [WARN] Provider "vsphere" produced an unexpected new value for module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .cpu_performance_counters_enabled: was null, but now cty.False
      - .alternate_guest_name: was null, but now cty.StringVal("")
      - .folder: was null, but now cty.StringVal("")
      - .nested_hv_enabled: was null, but now cty.False
      - .boot_retry_enabled: was null, but now cty.False
      - .run_tools_scripts_before_guest_reboot: was null, but now cty.False
      - .boot_delay: was null, but now cty.NumberIntVal(0)
      - .memory_hot_add_enabled: was null, but now cty.False
      - .sync_time_with_host: was null, but now cty.False
      - .enable_disk_uuid: was null, but now cty.False
      - .enable_logging: was null, but now cty.False
      - .memory_reservation: was null, but now cty.NumberIntVal(0)
      - .cpu_hot_remove_enabled: was null, but now cty.False
      - .cpu_reservation: was null, but now cty.NumberIntVal(0)
      - .annotation: was null, but now cty.StringVal("")
      - .cpu_hot_add_enabled: was null, but now cty.False
      - .clone[0].linked_clone: was null, but now cty.False
      - .disk[0].datastore_id: was cty.StringVal("<computed>"), but now cty.StringVal("datastore-11")
      - .disk[0].io_share_count: was cty.NumberIntVal(0), but now cty.NumberIntVal(1000)
      - .disk[0].key: was cty.NumberIntVal(0), but now cty.NumberIntVal(2000)
      - .disk[0].name: was null, but now cty.StringVal("")
      - .network_interface[0].use_static_mac: was null, but now cty.False
2019/07/19 12:29:57 [TRACE] module.vsphere_vm: eval: *terraform.EvalMaybeTainted
2019/07/19 12:29:57 [TRACE] module.vsphere_vm: eval: *terraform.EvalWriteState
2019/07/19 12:29:57 [TRACE] EvalWriteState: writing current state object for module.vsphere_vm.vsphere_virtual_machine.vmware_vm[0]
2019-07-19T12:29:57.270+0300 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/07/19 12:29:57 [DEBUG] connecting to TCP connection for SSH
2019-07-19T12:29:57.270+0300 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/07/19 12:29:57 [DEBUG] handshaking with SSH
2019-07-19T12:29:57.294+0300 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/07/19 12:29:57 [WARN] ssh: handshake failed: EOF
2019-07-19T12:29:57.294+0300 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/07/19 12:29:57 [WARN] retryable error: ssh: handshake failed: EOF
2019-07-19T12:29:57.294+0300 [DEBUG] plugin.terraform: remote-exec-provisioner (internal) 2019/07/19 12:29:57 [INFO] sleeping for 1s

**Comment by rothwerx** [comment]
In my pre-0.12 configuration I had a connection section for my ssh provisioner, but in 0.12 they now require a new key 'host'. It took me a while to figure out what syntax was needed for the value, but the following works for me:
```  
provisioner "remote-exec" {
    inline = [
      "hostnamectl set-hostname ${var.vmname}0${count.index + 1}",
    ]
    connection {
      type     = "ssh"
      host     = self.default_ip_address
      user     = var.vmuser
      password = var.vmpass
    }
  }
```

**Comment by aareet** [comment]
@pavel-mutafchiev does rothwerx's solution work for you? Can this be closed?
