### ISSUE TITLE
How to connect vmkernel to Distributed Port Group with vSphere provider

### ISSUE THREAD

**Issue by majakubo** [terraform-providers/terraform-provider-vsphere#813]
Hi, i am using terraform to automate vSphere infrastructure and i need to connect specific vmkernels to Port Group, because i need isolate vSan network. I've read documentation and I still don't know is it possible to do it with Terraform

**Comment by bill-rich** [comment]
Hi @majakubo! There is not currently a way to manage vmkernels. It is on the long term road map, but as of now, most of the vSphere resources are focused around VM management.
