### ISSUE TITLE
Error: Attribute name required

### ISSUE THREAD

**Issue by mrmodolo** [terraform-providers/terraform-provider-vsphere#815]
Hi,

Until version 0.12.4 I could ignore the value of a specific attribute (which changes from outside terraform). The attribute is a custom_attributes with value 103.
The odd thing is that using the quoted **"custom_attributes.103"** syntax I get the error '**Dot must be followed by attribute name**'.

If you do not use quotation marks, no errors are reported but the attribute is not ignored.

### Terraform Version

Terraform v0.12.6

### vSphere Provider Version

provider.vsphere v1.12.0

### Affected Resource(s)

- `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "vm" {

  lifecycle {
    ignore_changes = [
      "boot_delay",
      "guest_id",
      "custom_attributes.103",
    ]
  }
```

### Expected Behavior

I expected attribute 103 to be ignored!

### Actual Behavior

Error: Attribute name required

  on ansible-awx/modules/vmware/main.tf line 66, in resource "vsphere_virtual_machine" "vm":
  66:       "custom_attributes.103"

Dot must be followed by attribute name.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids

Until v0.12.4 I could ignore the value of "custom_attributes.103". In versions v0.12.5 and v0.12.6 I always ended up with the same error.

Version v0.12.6 had the error 'Dot must be followed by attribute name'. 

I can only ignore all attributes using only the value "custom_attributes".

If I use the custom_attributes.103 value without quotation marks the error does not appear but the attribute is not ignored!

```
"custom_attributes": {
              "1": "Marcelo Módolo \u003cmodolo@globosat.com.br\u003e",
              "101": "Alexandre Henrique Burgos \u003caburgos@globosat.com.br\u003e",
              "102": "55 21 2145-7408",
              "103": "28/07/2019 23:20:39",
              "1601": "SUM Servers Manual",
              "1701": "SR941560",
              "301": "Backup do Openshift Dedicated Cluster – ODC",
              "302": "Openshift Dedicated Cluster rsync",
              "401": "TECEG-ARQUITETURA CORPORATIVA",
              "501": "03/07/2019",
              "601": "55 21 2145-7238",
              "602": "Lilian Couceiro"
            },
```

**Comment by bill-rich** [comment]
Hey @mrmodolo! It looks like you got the answer on this one in hashicorp/terraform#22307, so I'm going to close this issue. Let me know if I overlooked something.
