### ISSUE TITLE
Move a vm to existing DRS_cluster_vm_group

### ISSUE THREAD

**Issue by dhansuhvt** [terraform-providers/terraform-provider-vsphere#820]
I was wondering how to move newly created VM to existing drs cluster vm group.

resource "vsphere_compute_cluster_vm_group" "cluster_vm_group" {
  name                = "windows"
  compute_cluster_id  = "${data.vsphere_compute_cluster.cluster.id}"
  virtual_machine_ids = ["${vsphere_virtual_machine.cloned_virtual_machine.id}"]
}

When i run above one, it's throwing an error that as drs cluster vm group is already exist.

**Comment by aareet** [comment]
Thank you for your question @dhansuhvt - we try to reserve our github issues for bugs or enhancements. Questions are better asked on the Community forum https://discuss.hashicorp.com/c/terraform-providers. Closing for now, please reopen if you think this is a bug instead and we can investigate.
