### ISSUE TITLE
[new resource] vsphere_host

### ISSUE THREAD

**Issue by xelite** [terraform-providers/terraform-provider-vsphere#829]
### Terraform Version

0.12

### vSphere Provider Version
vsphere_v1.12.0_x4

I want to automate process of adding new hypervisor to cluster. Currently it is not possible. Resource `vsphere_host` could add host to existing cluster and set or update configuration settings of host (eg. change vm startup behavior, set ntp, turn off ssh service)

**Comment by aareet** [comment]
Related to #570

**Comment by aareet** [comment]
Host resources were implemented in #836, and has been released in v1.13.0 of the provider. If you have any questions or feature requests regarding the new host resource, please feel free to open a new issue.
