### ISSUE TITLE
vSphere - VM customization is picking up network port "ether" instead of "ens160"

### ISSUE THREAD

**Issue by orlybagasala** [terraform-providers/terraform-provider-vsphere#837]
Hi there,

We have some issue provisioning our VM on the different vCenter. We have a TF code module that works fine in one of our vCenter but having issue when we use it to deploy VM on another vSphere/vCenter. The issue happen during VM customization of network ports. 

On vCenter that works fine, it found NIC suffix as ens160 which is the correct port and using /usr/sbin/ip command.

DEBUG: Command: whereis ip
DEBUG: Result: ip: /usr/sbin/ip /usr/share/man/man7/ip.7.gz /usr/share/man/man8/ip.8.gz

DEBUG: Command: /usr/sbin/ip addr show
DEBUG: Result: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
INFO: NIC suffix = ens160

On the vCenter that having problem, it’s using “ifconfig –a” and found “ether” as the NIC suffix. This is the reason why TF deployment is failing because the correct NIC port is ens160 but it configured port ether which is not the right one.

DEBUG: Result:  ens160: flags=4163<UP,BROADCAST,MULTICAST>  mtu 1500
        ether xx:xx:xx:xx  txqueuelen 1000  (Ethernet)
        RX packets 1565325  bytes 430503054 (410.5 MiB)
        RX errors 0  dropped 193  overruns 0  frame 0
        TX packets 1850752  bytes 240570740 (229.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 64  bytes 5664 (5.5 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 64  bytes 5664 (5.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
INFO: NIC suffix = ether

### Terraform Version
$ terraform -v
Terraform v0.12.3
+ provider.null v2.1.2
+ provider.vault v2.0.0
+ provider.vsphere v1.12.0

### Affected Resource(s)
- `vsphere_virtual_machine`

### Expected Behavior
What should have happened?
It should use NIC suffix = ens160 

What actually happened?
It is using NIC suffix = ether

Thanks and please advise.

**Comment by bill-rich** [comment]
Hi @orlybagasala! Unfortunately this is an issue with vSphere's processing of the vmtools output. The possible solutions to this depend on your environment and the operating systems involved. See [this](https://github.com/vmware/open-vm-tools/issues/130) issue for some more background and possible solutions.
