### ISSUE TITLE
Resize-Partition is already requested size - Happens when I run terraform apply second iterative onwards

### ISSUE THREAD

**Issue by arunjan2019** [terraform-providers/terraform-provider-vsphere#839]
Scenario: I tried to expand the disk size of vsphere template which was created by packer in VMware vSphere center via terraform.
In packer template I define the disk size as below..
![image](https://user-images.githubusercontent.com/47745176/64606427-20db4a00-d3be-11e9-8b40-1ae412d691a1.png)

In terraform main file
![image](https://user-images.githubusercontent.com/47745176/64606491-48321700-d3be-11e9-9e6f-a0d3870da15d.png)

my module - Vpshere file looks like below..
![image](https://user-images.githubusercontent.com/47745176/64606604-7fa0c380-d3be-11e9-96a2-f228b3a95ed3.png)

![image](https://user-images.githubusercontent.com/47745176/64606654-a232dc80-d3be-11e9-8c7c-894633aaf871.png)

Issue: When I tried to provision the VMs from template, terraform scripts it runs well on the first time and when I run for scale up the vms for example ...it throws the following error..
![image](https://user-images.githubusercontent.com/47745176/64606724-cf7f8a80-d3be-11e9-9d6e-225e5769f77b.png)

looks like Unit is not matching between packer template which is in MB and terraform is in GB...but when I print the template variable it throws in GB only...not sure how to resolve this problem?

Appreciate if anyone provide soultion to solve this issue at the earliest.

**Comment by bill-rich** [comment]
Hi @arunjan2019! Is it correct the the disk size is not being increased by Terraform? If you set the `disk` `size` to `500` without the conditional, does the rest work as expected? I'm trying to narrow down where the problem so we can get a reproduction going as quickly as possible. Thanks!

**Comment by arunjan2019** [comment]
@bill-rich - Thanks much for your response.  Sorry, I didn't mention the disk size result. Yes, even without the conditional the disk size is increased to 500GB. I can't shirk the disk size in Terraform less than template disk size which is 200GB.

**Comment by arunjan2019** [comment]
@bill-rich - Appreciate if you could respond at the earliest.

**Comment by koikonom** [comment]
Hi @arunjan2019 ! Can you please run `terraform apply` again but this time set the environment variable TF_LOG to DEBUG?

(See this https://www.terraform.io/docs/internals/debugging.html for an explanation what this variable does)

**Comment by arunjan2019** [comment]
@koikonom - Thanks much for your response. I will try soon your suggestion as I currently parked this issue and working something else. I will pick up and test this soon. Otherwise, I need to use some Ansible disk increase module in post provisioning of resource via Terraform

**Comment by bill-rich** [comment]
I'm going to close this issue for now, but let us know if it is still relevant and it we'll get it reopened.
