### ISSUE TITLE
VM Deploy Error - error fetching network: cannot traverse type VmwareDistributedVirtualSwitch

### ISSUE THREAD

**Issue by neogen19** [terraform-providers/terraform-provider-vsphere#855]
Hello,
I am trying to deploy a VM in our Production environment. There are multiple VLANs in production with most of the VLANs under dvswitches/ dvportgroup and few of them as regular ones. The deployment works fine when we try to deploy the VM in a regular VLAN without any dvswitches/ dvportgroup. However, when we try to use the dvportgroup, it fails with error “error fetching network: cannot traverse type VmwareDistributedVirtualSwitch”. Have tried using just dvportgroup name, dvswitch/dvportgroup name as suggested in some solution but nothing has worked so far. 

**Terraform Version**
$ terraform version
Terraform v0.12.9
+ provider.vsphere v1.12.0 

vSphere Provider Version
$ terraform providers
.
└── provider.vsphere
terraform-provider-vsphere_v1.12.0_x4

**Affected Resource(s)**
Please list the resources as a list, for example:
•	vsphere_network

**Terraform Configuration Files**
data "vsphere_datacenter" "dc" {
  name = "DC1"
} 

data "vsphere_network" "network" {
  name            = "dvswitch/dvportGroup"
  datacenter_id   = "${data.vsphere_datacenter.dc.id}"
}

resource "vsphere_virtual_machine" "vm" {
  
  …
  …
  …

  annotation = "Deployed via Terraform"

  network_interface {   
 
    network_id   = "${data.vsphere_network.network.id}"
    adapter_type = "${var.vsphere_NetworkAdapterType}"
  }

**Debug Output**
[DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4.exe: [DEBUG] Looking for cluster "Cluster1" in datacenter "/DC1"
[DEBUG] plugin.terraform-provider-vsphere_v1.12.0_x4.exe: [DEBUG] Attempting to locate compute cluster "Cluster1" in datacenter "/DC1"
[ERROR] <root>: eval: *terraform.EvalReadData, err: error fetching network: cannot traverse type VmwareDistributedVirtualSwitch
[ERROR] <root>: eval: *terraform.EvalSequence, err: error fetching network: cannot traverse type VmwareDistributedVirtualSwitch
[TRACE] [walkRefresh] Exiting eval tree: data.vsphere_network.network[0]
[TRACE] vertex "data.vsphere_network.network[0]": visit complete
[TRACE] vertex "data.vsphere_network.network": dynamic subgraph encountered errors
[TRACE] vertex "data.vsphere_network.network": visit complete
[TRACE] <root>: eval: *terraform.EvalIf
[TRACE] <root>: eval: *terraform.EvalSequence
[TRACE] <root>: eval: *terraform.EvalWriteState 

**Panic Output**
There is no panic or crash.log.
Expected Behavior
Create VM with provided VLAN.
Actual Behavior
The deployment fails with error
error fetching network: cannot traverse type VmwareDistributedVirtualSwitch [0m
Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.	terraform plan
2.	terraform apply

**Comment by neogen19** [comment]
ok, i had to finally make use of datasource vsphere_distributed_virtual_switch for the provider to find out the dvportgroup. It went to next stage now where it's able to parse the dvportgroup. But it fails as it has a "/" character in it. 

**Current Format:** 
dvswitch: VTESTQA00
dvportgroup: VM-TEST_ID01_1.1.1.1/24


When I rename "/" to "-", it works fine. Not able to use "/" though. We have many VLANs and it would be tough to rename everything. 

Could someone please help me out here to find out how to escape this character in terraform ?

**Comment by jimlcl** [comment]
Hey @neogen19, I checked the doc regarding String Literals [https://www.terraform.io/docs/configuration/expressions.html](url) and I think you could use \u002f (002f being the Unicode character for '/') to escape / in dvportgroup name. Is that what you're looking for ?

**Comment by neogen19** [comment]
Thanks @jimlcl for your help. I used "%2f" instead of "/" and it worked fine.
Not sure if this should be taken up as a bug or has to be added up into documentation.
