### ISSUE TITLE
Guest IP addresses not available on data.vsphere_virtual_machine

### ISSUE THREAD

**Issue by sirlatrom** [terraform-providers/terraform-provider-vsphere#901]
### Terraform Version

```
Terraform v0.12.13
```

### vSphere Provider Version

```
.
└── provider.vsphere ~> 1.13
```

### Affected Resource(s)

- `data.vsphere_virtual_machine`

### Terraform Configuration Files

main.tf
```hcl
provider "vsphere" {
...
}
data "vsphere_datacenter" "dc" {
  name = var.datacenter
}
data "vsphere_virtual_machine" "consul_server" {
  for_each      = toset(var.vm_paths)
  name          = each.value
  datacenter_id = data.vsphere_datacenter.dc.id
}
```

outputs.tf
```hcl
output "vm_eth1_ip_addresses" {
    value = [for n in data.vsphere_virtual_machine.vm : n.guest_ip_addresses[1]]
}
```

### Debug Output

N/A

### Expected Behavior

A list of IP addresses.

### Actual Behavior

It is not implemented. Output is as follows:

```
Error: Unsupported attribute

  on outputs.tf line 2, in output "vm_eth1_ip_addresses":
   2:     value = [for n in data.vsphere_virtual_machine.vm : n.guest_ip_addresses[1]]

This object does not have an attribute named "guest_ip_addresses".
```

### Steps to Reproduce

1. Have an output as in the example config
2. Point to a list of existing VMs with a `data.vsphere_virtual_machine` block
3. `terraform refresh`

### Important Factoids

The VMs have been created with another Terraform config, and in the resource attributes of those I can see the guest IP addresses. It is just not implemented on the data source side.

### References

The information will be more useful if #819 were to be merged.

**Comment by mc-meta** [comment]
Hello @aareet, any chance to have relevant pull requests reviewed and eventually merged? This new feature is much awaited to be able to automate in presence of vm lifecycles happening outside of vsphere provider. Thanks for any update.
