### ISSUE TITLE
[BUG] Cannot create SOAP client, EOF

### ISSUE THREAD

**Issue by bigbadossi** [terraform-providers/terraform-provider-vsphere#934]
### Terraform Version
Terraform version: 0.12.16

### vSphere Provider Version
1.14.0

### Affected Resource(s)
Please list the resources as a list, for example:
- `provider`

### Terraform Configuration Files

```hcl
provider "vsphere" {
  user              = var.user
  password          = var.password
  vsphere_server    = var.vsphere_server

  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = "Datacenter"
}

data "vsphere_compute_cluster" "compute_cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_datastore" "datastore" {
  name          = "example_ds"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = "example_network"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = "terraform_ubuntu_18.04.3"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_resource_pool" "resource_pool" {
  name		= "Terraform"
  parent_resource_pool_id = data.vsphere_compute_cluster.compute_cluster.resource_pool_id
}

resource "vsphere_folder" "folder" {
  path          = "Terraform"
  type          = "vm"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vms" {
  count		       = "2"
  name                    = "${var.name}-vm-${count.index + 1}"
  resource_pool_id = vsphere_resource_pool.resource_pool.id
  datastore_id         = data.vsphere_datastore.datastore.id
  annotation	      = "Automatically generated via Terraform"
  folder	              = vsphere_folder.folder.path
  num_cpus = 2
  memory    = 4096
  guest_id    = "ubuntu64Guest"

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label = "disk0"
    size  = 50
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      linux_options {
        host_name = "example${count.index}"
        domain = "example.net"
      }

      network_interface {
        ipv4_address = "172.23.84.${197 + count.index}"
        ipv4_netmask = 23
      }

      ipv4_gateway = "172.23.84.1"
    }
  }
}
```
Different variables are defined in an extra file, that I would like to keep private. Here the smaller version is posted.

### Debug Output
https://gist.github.com/bigbadossi/f296659b45495260a896a23e9f640e54

### Expected Behavior
Since this exact configuration is running on another computer, I thought the apply would work without issues.

### Actual Behavior
An error occurred on my computer:
Error: error setting up new vSphere SOAP client: Post https://XXX/sdk: EOF

XXX represents the vSphere server.

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply`

### Important Factoids
- the configuration provided is not the exact configuration that was used
- the configuration works on another machine, but on my machine there is the error above
- all plugins and versions are the same (was checked with md5 and sha265 sums)
- Terraform is the same since it is running in a docker container on our side
- the configuration (with provider specific changes in the resources) works on OpenStack (no logical error)
- tried the same configuration on different other machines and they get the same error, only one machine can apply this configuration
- we also tried newer versions of Terraform (0.12.18) and the same issue occurs

**Comment by bill-rich** [comment]
That error means that the vSphere API endpoint is not reachable. Since it is working on another computer, it sounds like there is something preventing you from reaching the endpoint on the computer you are having problems with. I'd recommend first checking that you can reach the web client in a browser, and if that works try using the [govc](https://github.com/vmware/govmomi/tree/master/govc) client.
