### ISSUE TITLE
vsphere provider alias may not be working

### ISSUE THREAD

**Issue by bby-bishopclark** [terraform-providers/terraform-provider-vsphere#947]
## this could be just a noob error; don't discount that ! 

We're looking into terraform, but we're new.  I think the config is as correct as it can be, but as shown in the simplified example it's losing track of one resource or more.  I can't see the typo, so if you find one please flame accordingly.

### Terraform Version

0.12.19

(terraform-0.12.19-1.el7.harbottle.x86_64)

### vSphere Provider Version

1.14.0

(golang-github-terraform-provider-vsphere-1.14.0-0.1.x86_64)

### Affected Resource(s)

- `vsphere_network`
- `vsphere_virtual_machine`

and more..

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {}
}

provider "vsphere" {
  vsphere_server = "10.12.8.21"
  allow_unverified_ssl = true
}

provider "vsphere" {
  vsphere_server = "10.12.8.11"
  allow_unverified_ssl = true
  alias = "prod"
}

data "vsphere_datacenter" "test" {
  name = "NetApp-HCI-Datacenter"
}

data "vsphere_datacenter" "prod" {
  provider = vsphere.prod
  name = "PROD Datacenter"
}

data "vsphere_network" "TEST-APP" {
  name          = "TEST-APP_908"
  datacenter_id = "${data.vsphere_datacenter.test.id}"
}

data "vsphere_network" "DMZ-prod" {
  name          = "DMZ-prod_618"
  datacenter_id = "${data.vsphere_datacenter.prod.id}"
}
```

### Debug Output

https://gist.github.com/bby-bishopclark/882eedc1ee8902b6ec5fed2a9344ac07

### Actual Behavior

```
(. ~/.tform-preload ; TF_LOG=DEBUG; TF_LOG_PATH=/tmp/tf-out; terraform init ; terraform plan)

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.vsphere_datacenter.test: Refreshing state...
data.vsphere_network.TEST-APP: Refreshing state...
data.vsphere_datacenter.prod: Refreshing state...
data.vsphere_network.DMZ-prod: Refreshing state...

Error: cannot locate datacenter: could not find datacenter with id: datacenter-2: ServerFaultCode: The object 'vim.Datacenter:datacenter-2' has already been d\
eleted or has not been completely created

  on dc-prod.tf line 31, in data "vsphere_network" "DMZ-prod":
  31: data "vsphere_network" "DMZ-prod" {
```

### Steps to Reproduce

Please list the steps required to reproduce the issue, for example:
1. be new.
1. `(. ~/.tform-preload ; TF_LOG=DEBUG; TF_LOG_PATH=/tmp/tf-out; terraform init ; terraform plan)`  (so really just   . ~/variables; terraform init; terraform plan)

``` 
# a file pre-loaded with the gitlab info as a cheap hack for the simplified case
awk -F= '{print $1}' ~/.tform-preload

export GITLAB_ACCESS_TOKEN
export TF_VAR_chef_admin_username
export TF_VAR_chef_provisioner_private_key
export TF_VAR_ssh_admin_password
export TF_VAR_ssh_admin_username
export VSPHERE_ALLOW_UNVERIFIED_SSL
export VSPHERE_PASSWORD
export VSPHERE_SERVER
export VSPHERE_USER

```

### Important Factoids

We have, at least, two separate vCenters with their own (largely-)distinct resources, on which I'm hoping to build a few machines, in one invocation.  We're trying to do this:
https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances

### References

This smells like #563 , but I'm not sure.

**Comment by sofixa** [comment]
@bby-bishopclark you need to specify the provider on each and every resource and data source that doesn't use the default one ( and personally i'd recommend you alias both providers and avoid using a default one precisely to avoid this type of misconfiguration).

**Comment by bby-bishopclark** [comment]
Hey Sofixa,

Will you look.at.that.  I did indeed miss one.  

> data "vsphere_network" "DMZ-prod" {
>   provider      = vsphere.prod
>   name          = "DMZ-prod_618"
>   datacenter_id = "${data.vsphere_datacenter.prod.id}"
> }

I'm so embarrassed.  And grateful.  Mainly grateful; and sorry to waste your time.

**Comment by bby-bishopclark** [comment]
Oh!  I tried aliasing both providers before, and found I needed to have a 'null' profile for the non-aliased one; maybe for AWS, can't remember now.  But that lost weekend scarred me in a time of great vulnerability and influenced the patterns.

But I'll take the idea to heart.  Thanks for that too.
