### ISSUE TITLE
Unable to create a VM from template and specify a separate datastore for one of the disks 

### ISSUE THREAD

**Issue by andrew-lee-metaswitch** [terraform-providers/terraform-provider-vsphere#960]
### Terraform Version

Terraform v0.12.18
+ provider.local v1.4.0
+ provider.vsphere v1.14.0

### Affected Resource(s)

- disks in `vsphere_virtual_machine`

### Terraform Configuration Files

```hcl
resource "vsphere_virtual_machine" "my_vm" {
  clone {
    template_uuid  = data.vsphere_virtual_machine.template.id
  }
  datastore_id               = data.vsphere_datastore.datastore[count.index].id
  disk {
    keep_on_remove             = false
    label                      = "disk0"
    size                       = var.boot_disk_size
    thin_provisioned           = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }
  disk {
    keep_on_remove             = true
    label                      = "disk1"
    size                       = var.data_disk_size
    thin_provisioned           = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
    unit_number                = 1
    datastore_id               = data.vsphere_datastore.data_disk_datastore[count.index].id
  }
 ....
}
```

I have a terraform file, when I do not specify a datastore_id  for disk "disk1" then terraform deploys my VM without complaint, if however I specify a datastore_id for this disk I get the following error:
```
Error: 
WARNING:
There was an error performing post-clone changes to virtual machine "/Automation/vm/al6-aut-1081-sas-2":
error reconfiguring virtual machine: Invalid configuration for device '0'.
Additionally, there was an error removing the cloned virtual machine:
disk.1: cannot find disk device: disk UUID is missing
```

If I remove the "keep_on_remove" line I still get an error:

```
2020/01/29 18:29:32 [ERROR] module.sas-data-1: eval: *terraform.EvalApplyPost, err: error reconfiguring virtual machine: error reconfiguring virtual machine: Invalid configuration for device '0'.
ne: error reconfiguring virtual machine: Invalid configuration for device '0'.

Error: error reconfiguring virtual machine: error reconfiguring virtual machine: Invalid configuration for device '0'.

  on sas-data-1/main.tf line 81, in resource "vsphere_virtual_machine" "sas-data-1_vms":
  81: resource "vsphere_virtual_machine" "sas-data-1_vms" {

```

Full debug logs at:

https://gist.github.com/andrew-lee-metaswitch/1e52d99b5cfe97498e27af74f8f0ae56

### Expected Behavior

After cloning, the disk should have moved to the specified datastore

### Actual Behavior

Terraform did not deploy the VM

### Steps to Reproduce

terraform apply...

### References

I suspect this may be related to https://github.com/terraform-providers/terraform-provider-vsphere/issues/935
We've found problems with post-clone disk changes before.

**Comment by andrew-lee-metaswitch** [comment]
So the problem here was that the datastore I was putting my additional disk was not one that could be reached from the host, changing the datastore to one that was reachable worked.

Two things:
(1) vSphere's errroring continues to be opaque
(2) It's really unclear in Terraform whether an error has come from Terraform or from vSphere

We can't do anything about (1), but I wonder if there's a sensible enhancement to terraform to make it clearer where the error originated from?

**Comment by aareet** [comment]
(2) is a good thought, we will discuss to see if there's a feature request we can create from it.

Thank you for reporting back on this issue.
