### ISSUE TITLE
v1.16 Error: Error: disk.0: virtual machine with UUID "<uuid>" not found

### ISSUE THREAD

**Issue by ajchiarello** [terraform-providers/terraform-provider-vsphere#967]
### Terraform Version
Terraform v0.12.20

### vSphere Provider Version
v1.16.0

### Affected Resource(s)

vsphere_virtual_machine

###

Since upgrading to 1.16.0, the plugin is no longer respecting ignore_changes to the template_uuid. If the template originally used to create the VMs is no longer present, this causes the resource to fail to refresh. Reverting back to 1.15.0 allows the script to operate normally (ignoring changes to the template_uuid).

**Comment by bill-rich** [comment]
Hi @ajchiarello! Thank you for reporting this issue. I've been able to track down the issue with the information you've provided. #968 covers the same issue, so I'm going to consolidate and track it there.
