### ISSUE TITLE
Using Custom Profile during vSphere Build

### ISSUE THREAD

**Issue by dfoley84** [terraform-providers/terraform-provider-vsphere#973]
Hi there,
I'm unable to deploy a VM  with Custom OS_Profiles 

```

   custom_configuration_parameters = {
    spec = "Win2016"
    } 
```

### Terraform Version

`Terraform v0.12.19
+ provider.vsphere v1.16.1`

**Comment by aareet** [comment]
@dfoley84 can you share the log output and any other relevant bits of the issue template please?
