### ISSUE TITLE
Error performing post-clone changes to virtual machine

### ISSUE THREAD

**Issue by glenfiddich** [terraform-providers/terraform-provider-vsphere#976]
### Terraform Version

Terraform v0.12.20

### vSphere Provider Version

provider.vsphere v1.15.0

I am forcing the use of v1.15.0 due to an issue with v1.16.0 issue I have reported in #966 
Most recently, I tried Terraform v0.12.20 + vSphere Provider v1.16.0 but #966 is ongoing

### Affected Resource(s)

vsphere_virtual_machine.vm

### Terraform Configuration Files

::::::::::::::
config.tf
::::::::::::::
provider "vsphere" {
  version = "< 1.16.0"
  vim_keep_alive       = 30
  vsphere_server       = "MYHOST"
  user                 = "MYACCT"
  password             = MYPW
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "datacenter" {
  name = var.vmware_datacenter
}

data "vsphere_datastore_cluster" "datastore_cluster" {
  name          = var.vmware_datastore
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vmware_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_network" "network" {
  name          = var.vmware_vlan
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_virtual_machine" "template" {
  name          = var.vm_template
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

resource "vsphere_virtual_machine" "vm" {
  name                 = local.fqdn
  resource_pool_id     = data.vsphere_compute_cluster.cluster.resource_pool_id
  datastore_cluster_id = data.vsphere_datastore_cluster.datastore_cluster.id

  num_cpus               = var.vcpus
  memory                 = var.vram
  guest_id               = data.vsphere_virtual_machine.template.guest_id
  folder                 = var.folder
  memory_hot_add_enabled = true
  cpu_hot_add_enabled    = true

  // tags = ["${var.backup_tag.tag.id}"]

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = data.vsphere_virtual_machine.template.network_interface_types[0]
  }

  disk {
    label            = "disk0"
    size             = 5000   ### YES, 5TB
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
    unit_number      = 0
  }

  clone {
    template_uuid = data.vsphere_virtual_machine.template.id

    customize {
      linux_options {
        host_name = var.hostname
        domain    = var.domainname
      }

      network_interface {
        ipv4_address = var.ipaddress
        ipv4_netmask = var.netmask
      }

      ipv4_gateway    = var.defaultgw
      dns_server_list = ["MYDNS"]
      dns_suffix_list = [var.domainname]
    }
  }

  provisioner "local-exec" {
    command = "/home/MYPATH/terraform-vsphere/virtual.machines/${local.fqdn}/buildConfig ${local.fqdn}"
  }

  provisioner "local-exec" {
    command = "/home/MYPATH/terraform-vsphere/bin/keytab ${local.fqdn}"
  }

  provisioner "file" {
    source      = "${local.fqdn}.keytab"
    destination = "/tmp/krb5.keytab"

    connection {
      host        = self.default_ip_address
      type        = "ssh"
      user        = "MYUSER"
      private_key = file("~/.ssh/id_rsa")
    }
  }

  provisioner "local-exec" {
    command = "rm -f ${local.fqdn}.keytab"
  }

  provisioner "file" {
    source      = "conf/MYRPM"
    destination = "/var/tmp/MYRPM"
    connection {
      host        = self.default_ip_address
      type        = "ssh"
      user        = "MYUSER"
      private_key = file("~/.ssh/id_rsa")
    }
  }

# MORE RPMS

  provisioner "file" {
    source      = "conf/automation-scripts.tar"
    destination = "/var/tmp/automation-scripts.tar"
    connection {
      host        = self.default_ip_address
      type        = "ssh"
      user        = "terraformer"
      private_key = file("~/.ssh/id_rsa")
    }
  }

  # --

  provisioner "remote-exec" {
    inline = [
      "cd /var/tmp && sudo tar xvf automation-scripts.tar",
      "sudo /bin/chmod 0750 /var/tmp/bootstrap.sh",
      "sudo /bin/mv /tmp/krb5.keytab /etc/krb5.keytab",
      "sudo /var/tmp/bootstrap.sh ${var.puppet_role} ${var.team} ${local.puppet_environment}",
    ]

    connection {
      host        = self.default_ip_address
      type        = "ssh"
      user        = "MYUSER"
      private_key = file("~/.ssh/id_rsa")
    }
  }
}

::::::::::::::
variables.tf
::::::::::::::
variable "hostname" {
  type    = string
  default = "MYHOST"
}

variable "domainname" {
  type    = string
  default = "MYDOMAIN"
}

locals {
  fqdn = "${var.hostname}.${var.domainname}"
}

variable "ipaddress" {
  type    = string
  default = "MYIP"
}

variable "folder" {
  type    = string
  default = "/IS/MYOTHERPATH/"
}

variable "netmask" {
  type    = string
  default = "24"
}

variable "defaultgw" {
  type    = string
  default = "MYGW"
}

variable "vmware_vlan" {
  type    = string
  default = "MYVLAN"
}

variable "vmware_datacenter" {
  type    = string
  default = "MYDatacenter"
}

variable "vmware_cluster" {
  type    = string
  default = "MYCLUSTER"
}

variable "vmware_datastore" {
  type    = string
  default = "MYFlash"
}

variable "vm_template" {
  type    = string
  default = "CentOS-7-64-bit-UG-Build-VM-Version-13"
}

variable "vcpus" {
  type    = string
  default = "4"
}

variable "vram" {
  type    = string
  default = "16384"
}

# variable "puppet_environment" {
#  type = "string"
#  default="seeLocalsSectionBelow"
# }

variable "puppet_role" {
  type    = string
  default = "iotelastic"
}

variable "team" {
  type    = string
  default = "MYTEAM"
}

locals {
  puppet_environment = "${var.team}_production"
}

// variable "backup_tag" {
//   type = "string"
//   default = "Linux - Terraform - 4 wk - Job 1"
// }
::::::::::::::
versions.tf
::::::::::::::

terraform {
  required_version = ">= 0.12"
}

### Debug Output

$ tf apply
2020/02/19 09:49:41 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
data.vsphere_datacenter.datacenter: Refreshing state...
data.vsphere_datastore_cluster.datastore_cluster: Refreshing state...
data.vsphere_virtual_machine.template: Refreshing state...
data.vsphere_compute_cluster.cluster: Refreshing state...
data.vsphere_network.network: Refreshing state...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be created
  + resource "vsphere_virtual_machine" "vm" {
      + boot_retry_delay                        = 10000
      + change_version                          = (known after apply)
      + cpu_hot_add_enabled                     = true
      + cpu_limit                               = -1
      + cpu_share_count                         = (known after apply)
      + cpu_share_level                         = "normal"
      + datastore_cluster_id                    = "group-p542647"
      + datastore_id                            = (known after apply)
      + default_ip_address                      = (known after apply)
      + ept_rvi_mode                            = "automatic"
      + firmware                                = "bios"
      + folder                                  = "MYOTHERPATH"
      + force_power_off                         = true
      + guest_id                                = "centos6_64Guest"
      + guest_ip_addresses                      = (known after apply)
      + host_system_id                          = (known after apply)
      + hv_mode                                 = "hvAuto"
      + id                                      = (known after apply)
      + imported                                = (known after apply)
      + latency_sensitivity                     = "normal"
      + memory                                  = 16384
      + memory_hot_add_enabled                  = true
      + memory_limit                            = -1
      + memory_share_count                      = (known after apply)
      + memory_share_level                      = "normal"
      + migrate_wait_timeout                    = 30
      + moid                                    = (known after apply)
      + name                                    = "MY.F.Q.D.N"
      + num_cores_per_socket                    = 1
      + num_cpus                                = 4
      + reboot_required                         = (known after apply)
      + resource_pool_id                        = "resgroup-46"
      + run_tools_scripts_after_power_on        = true
      + run_tools_scripts_after_resume          = true
      + run_tools_scripts_before_guest_shutdown = true
      + run_tools_scripts_before_guest_standby  = true
      + scsi_bus_sharing                        = "noSharing"
      + scsi_controller_count                   = 1
      + scsi_type                               = "pvscsi"
      + shutdown_wait_timeout                   = 3
      + swap_placement_policy                   = "inherit"
      + uuid                                    = (known after apply)
      + vapp_transport                          = (known after apply)
      + vmware_tools_status                     = (known after apply)
      + vmx_path                                = (known after apply)
      + wait_for_guest_ip_timeout               = 0
      + wait_for_guest_net_routable             = true
      + wait_for_guest_net_timeout              = 5

      + clone {
          + template_uuid = "4209a91e-4993-10a5-6476-a91c29abef92"
          + timeout       = 30

          + customize {
              + dns_server_list = [
                  + "MYDNS",
                ]
              + dns_suffix_list = [
                  + "MY.F.Q.D.N",
                ]
              + ipv4_gateway    = "MYGW"
              + timeout         = 10

              + linux_options {
                  + domain       = "MY.F.Q.D.N"
                  + host_name    = "MYHOST"
                  + hw_clock_utc = true
                }

              + network_interface {
                  + ipv4_address = "MYIP"
                  + ipv4_netmask = 24
                }
            }
        }

      + disk {
          + attach           = false
          + datastore_id     = "<computed>"
          + device_address   = (known after apply)
          + disk_mode        = "persistent"
          + disk_sharing     = "sharingNone"
          + eagerly_scrub    = false
          + io_limit         = -1
          + io_reservation   = 0
          + io_share_count   = 0
          + io_share_level   = "normal"
          + keep_on_remove   = false
          + key              = 0
          + label            = "disk0"
          + path             = (known after apply)
          + size             = 5000
          + thin_provisioned = false
          + unit_number      = 0
          + uuid             = (known after apply)
          + write_through    = false
        }

      + network_interface {
          + adapter_type          = "vmxnet3"
          + bandwidth_limit       = -1
          + bandwidth_reservation = 0
          + bandwidth_share_count = (known after apply)
          + bandwidth_share_level = "normal"
          + device_address        = (known after apply)
          + key                   = (known after apply)
          + mac_address           = (known after apply)
          + network_id            = "dvportgroup-460844"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vsphere_virtual_machine.vm: Creating...
vsphere_virtual_machine.vm: Still creating... [10s elapsed]
vsphere_virtual_machine.vm: Still creating... [20s elapsed]
vsphere_virtual_machine.vm: Still creating... [30s elapsed]
vsphere_virtual_machine.vm: Still creating... [40s elapsed]
vsphere_virtual_machine.vm: Still creating... [50s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [1m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [2m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [3m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m10s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m20s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m30s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m40s elapsed]
vsphere_virtual_machine.vm: Still creating... [4m50s elapsed]
vsphere_virtual_machine.vm: Still creating... [5m0s elapsed]
vsphere_virtual_machine.vm: Still creating... [5m10s elapsed]

Error:
WARNING:

▽
2020/02/19 09:49:31 [INFO] Terraform version: 0.12.20
2020/02/19 09:49:31 [INFO] Go runtime version: go1.12.13
2020/02/19 09:49:31 [INFO] CLI args: []string{"/home/terraform/bin/terraform", "init"}
2020/02/19 09:49:31 [DEBUG] Attempting to open CLI config file: /home/terraform/.terraformrc
2020/02/19 09:49:31 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/02/19 09:49:31 [INFO] CLI command args: []string{"init"}
2020/02/19 09:49:31 [DEBUG] New state was assigned lineage "11d5c4b7-d744-0d89-9328-b159cea596aa"
2020/02/19 09:49:31 [DEBUG] checking for provider in "."
2020/02/19 09:49:31 [DEBUG] checking for provider in "/home/terraform/bin"
2020/02/19 09:49:31 [DEBUG] checking for provisioner in "."
2020/02/19 09:49:31 [DEBUG] checking for provisioner in "/home/terraform/bin"
2020/02/19 09:49:31 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/02/19 09:49:31 [DEBUG] checking for provider in "."
2020/02/19 09:49:31 [DEBUG] checking for provider in "/home/terraform/bin"
2020/02/19 09:49:31 [DEBUG] plugin requirements: "vsphere"="< 1.16.0"
2020/02/19 09:49:31 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2020/02/19 09:49:32 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/vsphere/versions"
2020/02/19 09:49:32 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/hashicorp/vsphere/1.15.0/download/linux/amd64"
2020/02/19 09:49:32 [DEBUG] verified GPG signature with key from HashiCorp Security <security@hashicorp.com>
2020/02/19 09:49:32 [DEBUG] getting provider "vsphere" (hashicorp/vsphere) version "1.15.0"
2020/02/19 09:49:32 [DEBUG] plugin cache is disabled, so downloading vsphere 1.15.0 from https://releases.hashicorp.com/terraform-provider-vsphere/1.15.0/terraform-provider-vsphere_1.15.0_linux_amd64.zip?checksum=sha256:bda8b06b784955fee16c87880e1c36bc7f31fb091dded9092108bfb7658a4d0e
2020/02/19 09:49:33 [DEBUG] looking for the vsphere 1.15.0 plugin we just installed
2020/02/19 09:49:33 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/02/19 09:49:33 [DEBUG] found provider "terraform-provider-vsphere_v1.15.0_x4"
2020/02/19 09:49:33 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"vsphere", Version:"1.15.0", Path:"/home/terraform/gitlab.is.ed.ac.uk/terraform-vsphere/virtual.machines/ece02.vh.iot.ed.ac.uk/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.15.0_x4"}:struct {}{}}
2020/02/19 09:49:33 [DEBUG] filtered plugins discovery.PluginMetaSet{discovery.PluginMeta{Name:"vsphere", Version:"1.15.0", Path:"/home/terraform/gitlab.is.ed.ac.uk/terraform-vsphere/virtual.machines/ece02.vh.iot.ed.ac.uk/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.15.0_x4"}:struct {}{}}
2020/02/19 09:49:33 [DEBUG] checking for provider in "."
2020/02/19 09:49:33 [DEBUG] checking for provider in "/home/terraform/bin"
2020/02/19 09:49:33 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/02/19 09:49:33 [DEBUG] found provider "terraform-provider-vsphere_v1.15.0_x4"
2020/02/19 09:49:33 [DEBUG] found valid plugin: "vsphere", "1.15.0", "/home/terraform/gitlab.is.ed.ac.uk/terraform-vsphere/virtual.machines/ece02.vh.iot.ed.ac.uk/.terraform/plugins/linux_amd64/terraform-provider-vsphere_v1.15.0_x4"
2020/02/19 09:49:33 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/02/19 09:49:33 [DEBUG] found provider "terraform-provider-vsphere_v1.15.0_x4"
2020/02/19 09:49:35 [INFO] Terraform version: 0.12.20
2020/02/19 09:49:35 [INFO] Go runtime version: go1.12.13
2020/02/19 09:49:35 [INFO] CLI args: []string{"/home/terraform/bin/terraform", "plan"}
2020/02/19 09:49:35 [DEBUG] Attempting to open CLI config file: /home/terraform/.terraformrc
2020/02/19 09:49:35 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
/ERR
There was an error performing post-clone changes to virtual machine "/MYPATH/DCC Servers/MY.F.Q.D.N":
error reconfiguring virtual machine: Post https://MYVCSA/sdk: context deadline exceeded
Additionally, there was an error removing the cloned virtual machine:
error destroying virtual machine: ServerFaultCode: Permission to perform this operation was denied.

The virtual machine may still exist in Terraform state. If it does, the
resource will need to be tainted before trying again. For more information on
how to do this, see the following page:
https://www.terraform.io/docs/commands/taint.html

If the virtual machine does not exist in state, manually delete it to try again.

  on config.tf line 34, in resource "vsphere_virtual_machine" "vm":
  34: resource "vsphere_virtual_machine" "vm" {

I can provide full DEBUG but I'd rather post this in a Private repo than via Github Gist
Please provide provider maintainer Github username if you would like to have the full output

### Panic Output

N/A

### Expected Behavior

VM should be created

### Actual Behavior

VM creation fails with above error

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply (yes)

### Important Factoids

We have built about 150 VMs successfully using Terraform in recent months (Thanks for all the hard work on the provider - it makes a real difference to us).  This problem VM (& 2 other VMs which built successfully) are unusual because we are allocating 5TB storage to each.  The error above seems to suggest a timeout due to "an error performing post-clone changes" - Perhaps this is referring to guest customisation .. I am not sure.

I am using provider v1.15 due to ongoing reported issue with v1.16.1 - See #966 for details

I have tried this build several times

Occasionally when I try it, I get a Guest customistion already is progress error instead 

To address that problem I do the following which usually works but I might have seen one occasion when it did not work - 

1. Manipulate template and new_VM /vmfs/volumes/{datastore}/vm/ files to remove guest customisation binary from both dirs 
2. Remove the line referring to tools.deployPkg.filename in template vmtx in order to work-around that 

### References

N/A

**Comment by koikonom** [comment]
Hi @glenfiddich, I am part of the terraform vsphere provider team. Can you please share the debug log with me?

**Comment by aareet** [comment]
Closing since it has been 30 days since last response. Please reopen if this is still an issue.
