### ISSUE TITLE
Lack of support for OUPath field on AD join

### ISSUE THREAD

**Issue by rbprado** [terraform-providers/terraform-provider-vsphere#996]
Hi there,

I'm working on a provisioning with resource `vsphere_virtual_machine`.
With the `customize` - `windows_options` I'm able to add the new provisioned VM to the domain but as it lacks the `OU Path` argument it is getting into the wrong default OU at the domain.

As I can see from the Azure provider they are already supporting the `domain_ou` argument:
https://www.terraform.io/docs/providers/azure/r/instance.html

Please correct me if I'm wrong but from the current documentation I think the only possibility is adding the VM into the domain within `sysprep`:
https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#supplying-your-own-sysprep-file

Also in order to add more context, from the Windows documentation you can see the `Example 4` with the OUPath argument being given:
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/add-computer?view=powershell-5.1

Am I missing anything or the vSphere provider doesn't support OU Path?
If it doesn't support, is it on the road map?

**Comment by bill-rich** [comment]
Hi @rbprado!

Unfortunately, we are limited by the capabilities of vSphere's API and Go SDK. For most of the operations in the Terraform vSphere provider, we are using govmomi with the VIM client. To join the VM do a domain, we are using [CustomizationIdentification](https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.customization.Identification.html), but I don't believe there is a way to support `OU Path` at this time.
